Ensembles implementations in FEDOT
aimclub/FEDOT pull request #1005
Opened 2022-12-12 13:36 UTC by aPovidlo

Adding an ensemble (stacking and bagging) operations to FEDOT

2023-01-10 16:55 UTC, nicl-nno commented on test/unit/models/test_strategy.py
> +    assert predicted_labels.shape[0] == 240
Может тут (и ниже) проверять ещё и метрики?

2023-01-10 17:00 UTC, nicl-nno commented on fedot/core/operations/evaluation/bagging.py
> +class SkLearnBaggingStrategy(EvaluationStrategy):
Может лучше унаследоваться он SkLearnEvaluationStrategy? Вроде часть методов идентична.

2023-01-10 18:34 UTC, aPovidlo commented on test/unit/models/test_strategy.py
> +    assert predicted_labels.shape[0] == 240
@nicl-nno Хорошо, можно добавить

2023-01-10 18:42 UTC, aPovidlo commented on fedot/core/operations/evaluation/bagging.py
> +class SkLearnBaggingStrategy(EvaluationStrategy):
@nicl-nno думал об этом, но не смог найти приемуществ такой реализации. Как мне показалось, как сейчас лучше для читаймости и по логике, все же это отдельная независимая операция.

2023-01-10 18:53 UTC, aPovidlo commented on fedot/core/operations/evaluation/bagging.py
> +                # - ``bag_lgbm_xt`` -> Bagging of the LightGBM Extra Trees
> А есть ли вообще принципиальная разница в реализации бэггинга для разных моделей?

Разница в гиперпарамметрах базовых моделей (имею ввиду `'model_params'`). Для каждой из моделей они свои, их хотелось бы уметь передавать и тюнить.

> Нельзя ли, например, тип модели вынести в гиперпараметр операции бэггинга? Кажется, это сделает код более компактным.

Думаю, что этого не стоит делать. Для bag_dt количество базовых модлей `'numbers_of_learners'` по-умолчанию можно указать `100` (сейчас меньше для отладки) и он сможет обучить их за разумное время. А вот для другой модели такого количества может буть уже перебором. Это повлияет на работоспособность всего фреймворка, потому что запнется на их обучении. Поэтому мне показалось логичнее разделять их.

2023-01-10 21:56 UTC, nicl-nno commented on fedot/core/operations/evaluation/bagging.py
> +class SkLearnBaggingStrategy(EvaluationStrategy):
Преимущество в том что методы fit и predict можно будет взять из предка. Или там есть какая-то разница в реализации?

2023-01-11 09:30 UTC, nicl-nno commented on fedot/core/operations/evaluation/bagging.py
> +                # - ``bag_lgbm_xt`` -> Bagging of the LightGBM Extra Trees
Хм. Можно тогда идти от обратного - добавить в модель 'dt' параметры 'with_bagging' и 'number_of_learners'.

Ну лан, в первой версии давай оформим отдельной моделью, а потом подумаем.

2023-01-13 11:27 UTC, valer1435 requested changes

2023-01-13 11:28 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ensemble_implementations/bagging.py
> +            idx = np.random.choice(train_data.features.shape[0], train_data.features.shape[0], replace=True)
PS просмотрел пока не весь pr. Вижу, что многое поменялось - пробегусь еще раз полностью по новой версии позже

2023-01-17 09:51 UTC, valer1435 requested changes

2023-01-17 09:51 UTC, valer1435 commented on fedot/core/data/data_split.py
> +        return [[train_index, test_index] for train_index, test_index in
Кажется, такие вещи делаются с помощью  [генераторов](https://github.com/aimclub/FEDOT/blob/master/fedot/core/validation/split.py#L116), например.  И возможно стоит посмотреть на [это ](https://github.com/aimclub/FEDOT/blob/master/fedot/core/optimisers/objective/data_source_splitter.py)

2023-01-17 09:51 UTC, valer1435 commented on fedot/core/operations/evaluation/bagging.py
> +            return 'reg'
Почему бы не использовать уже существующие перечисления?

2023-01-17 09:51 UTC, valer1435 commented on fedot/core/repository/data/model_repository.json
> +      "meta": "bagging",
А можно как-то все эти общие теги убрать в тег bagging'a?

2023-01-17 14:38 UTC, aPovidlo commented on fedot/core/data/data_split.py
> +        return [[train_index, test_index] for train_index, test_index in
Забыл убрать этот файл, он скорее тоже неактуальный. В про существование реализованного DataSplitter не знал.

2023-01-17 14:39 UTC, aPovidlo commented on fedot/core/operations/evaluation/bagging.py
> +            return 'reg'
Не понял вопроса, какие перечисления?

2023-01-17 14:40 UTC, aPovidlo commented on fedot/core/repository/data/model_repository.json
> +      "meta": "bagging",
Что ты имеешь ввиду про >общие теги убрать?

2023-01-17 14:43 UTC, aPovidlo commented on fedot/core/data/data_split.py
> +        return [[train_index, test_index] for train_index, test_index in
Про генератор в курсе, не сделал этого, потому что мне нужно было брать элементы по индексам

2023-01-18 08:41 UTC, valer1435 commented on fedot/core/repository/data/model_repository.json
> +      "meta": "bagging",
![image](https://user-images.githubusercontent.com/32017472/213123400-82ddc84d-db1f-4da0-8eb1-8d4035dcef95.png)
`bagging `встречается в описании модели 3 (не считая приставку bag_ в названии) раза. И так у каждой бэггинг модели. Можно ли как-то сократить появление одинаковых тегов, перечислив их не отдельно у каждой модели, а в заголовке https://github.com/aimclub/FEDOT/pull/1005/files#diff-a5c1624bd36467920ea4aedc11707222e45cce478c7c6728bbdc08424c455621R119-R131

2023-01-18 09:09 UTC, valer1435 commented on fedot/core/repository/data/model_repository.json
> +      "meta": "bagging",
На крайний случай эти модели можно убрать в отдельный файл - уж очень они специфичными получаются. К тому же они повторяют уже существующие модели и это будет мешать при работе с репозиторием моделей. (Устанешь искать нужную тебе модель)

2023-01-18 09:11 UTC, aPovidlo commented on fedot/core/operations/evaluation/bagging.py
> +            return 'reg'
Понял. Да, действительно хотелось бы исправить этот метод на какой-нибудь вариант с использованием типов задачи. Там выше оставил для этого комментарий. Однако, пока не нашел откуда можно было бы их взять на этапе объявление класса. В других реализациях операций не было нужды в типе решаемой задачи, только если в `fit` можно было бы взять из `InputData`.

Поэтому буду рад если ты знаешь способ и можешь помочь в этом.

2023-01-18 09:14 UTC, aPovidlo commented on fedot/core/repository/data/model_repository.json
> +      "meta": "bagging",
Понял. Действительно разумно оставить их только в пресете, а из тэгов убрать.

2023-01-19 08:33 UTC, valer1435 commented on fedot/core/operations/evaluation/bagging.py
> +            return 'reg'
Думаю можно сделать так, как уже было сделано со sklearn'овскими моделями - разделить стратеги для [регрессии ](https://github.com/aimclub/FEDOT/blob/master/fedot/core/operations/evaluation/regression.py)и  [классификации](https://github.com/aimclub/FEDOT/blob/master/fedot/core/operations/evaluation/classification.py). И оставить базовый класс бэггинга (как и базовый класс [склерна](https://github.com/aimclub/FEDOT/blob/master/fedot/core/operations/evaluation/evaluation_interfaces.py#L136)).

При текущей реализации будет громоздко тащить в метод predict функциональность классификатора и регрессии

2023-01-24 09:18 UTC, valer1435 requested changes

2023-01-24 09:18 UTC, valer1435 commented on fedot/core/operations/evaluation/bagging.py
> +            params = OperationParameters.from_operation_type(operation_type, **params)
На этапе вызова этой функции у нас уже должны по идее инициализироваться параметры. Зачем из заново объявлять?

2023-01-24 09:18 UTC, valer1435 commented on fedot/core/operations/evaluation/bagging.py
> +    def fit(self, train_data: InputData):
Можно перенести в суперкласс

2023-01-24 09:18 UTC, valer1435 commented on fedot/core/operations/evaluation/bagging.py
> +    def predict(self, trained_operation, predict_data: InputData) -> OutputData:
Predict тоже совпадает у двух классов. Я так понимаю, что подхватка случаев предсказания вероятностей или меток заложена на уровне имплементации?

2023-01-24 09:18 UTC, valer1435 commented on test/unit/data_operations/test_data_operations_implementations.py
> +    bagging_models = OperationTypesRepository().suitable_operation(task_type=TaskTypesEnum.regression, tags=['bagging'])
По идее так должно быть лаконичнее 
`model_names = OperationTypesRepository().suitable_operation(task_type=TaskTypesEnum.regressionб forbidden_tags=['bagging']) `

2023-01-24 09:18 UTC, valer1435 commented on test/unit/models/test_strategy.py
> +def test_bagging_classification_operation(operation):
Как мне кажется лучше сделать аналог этих [тестов](https://github.com/aimclub/FEDOT/blob/master/test/unit/models/test_model.py#L162). Потом 100% забудешь при добавлении новой модели для бэггинга запихнуть ее в тест.

2023-01-24 10:54 UTC, aPovidlo commented on fedot/core/operations/evaluation/bagging.py
> +            params = OperationParameters.from_operation_type(operation_type, **params)
Для тестов, в которых вызывается необходимый класс бэггинга, и возможности передачи параметров.

2023-01-24 10:55 UTC, aPovidlo commented on fedot/core/operations/evaluation/bagging.py
> +    def predict(self, trained_operation, predict_data: InputData) -> OutputData:
Да

2023-01-24 10:55 UTC, aPovidlo commented on test/unit/data_operations/test_data_operations_implementations.py
> +    bagging_models = OperationTypesRepository().suitable_operation(task_type=TaskTypesEnum.regression, tags=['bagging'])
Согласен

2023-01-24 10:56 UTC, aPovidlo commented on test/unit/models/test_strategy.py
> +def test_bagging_classification_operation(operation):
Согласен

2023-01-24 10:58 UTC, aPovidlo commented on fedot/core/operations/evaluation/bagging.py
> +            params = OperationParameters.from_operation_type(operation_type, **params)
Думаю, все-таки перепишу тесты через `PipelineBuilder` и уберу этот метод

2023-01-24 11:31 UTC, aPovidlo commented on fedot/core/operations/evaluation/bagging.py
> +        self._bagging_params, self._model_params = self._set_operation_params(operation_type, params)
Не совсем тебя понял. bag_type() в классе предка, а вызывать его из класса родителя? А get_bag откдуа?

И в итоге, не вернулись ли туда, от куда начали разбитие на два класса? Уж лучше было когда все в одном

2023-01-24 11:53 UTC, aPovidlo commented on fedot/core/operations/evaluation/bagging.py
> +        self._bagging_params, self._model_params = self._set_operation_params(operation_type, params)
Думаю, что `_convert_to_operation` пока нужно оставить в каждом из классе

2023-01-24 12:37 UTC, aPovidlo commented on fedot/core/operations/evaluation/bagging.py
> +            params = OperationParameters.from_operation_type(operation_type, **params)
Вспомнил. У меня ранее падал тест `test_api_print_info_correct`. В других реализациях параметры использовались только на уровне `fit`, поэтому в них нужды в `__init__` не было. А так как сейчас есть необходимость, а в инициализацию `params` приходят равные `None` они и вызывают ошибку. Поэтому решил добавить функцию, которая их бы добавляла. Поэтому нет, на этапе вызоыва этой функции у нас еще нет иницилизированных параметров.

2023-01-24 21:35 UTC, valer1435 commented on fedot/core/operations/evaluation/bagging.py
> +        self._bagging_params, self._model_params = self._set_operation_params(operation_type, params)
```
class SkLearnBaggingStrategy(EvaluationStrategy, ABC):
.....
def __init__():
    ....
    self.bag_type = None
    ....

def _convert_to_operation(self, operation_type: str):
        if operation_type in self.__operations_by_types.keys():
            if self._model_params:
                self._bagging_params['base_estimator'] = self.__operations_by_types[operation_type](
                    **self._model_params)
            else:
                self._bagging_params['base_estimator'] = self.__operations_by_types[operation_type]()

            return self.bag_type(**self._bagging_params)


class SkLearnBaggingClassificationStrategy(SkLearnBaggingStrategy):
....
def __init__():
    ....
    self.bag_type = BaggingClassifier
    ....

```С регрессией также. Не уверен, что это лучшее решение, но сокращает код в 2 раза

2023-01-24 22:00 UTC, valer1435 requested changes

2023-01-24 22:00 UTC, valer1435 commented on fedot/core/operations/evaluation/bagging.py
> +            params = OperationParameters.from_operation_type(operation_type, **params)
Идею понял, но есть несколько идей: 
1) убрать @static и записывать  bagging_params, model_params в поля класса
2) Сделать вызов этого метода до инициализации конструктора базового класса и сделать так, чтобы метод возвращал params. params потом уже передавать в конструктор. Нужно, чтобы не было 2 разных объекта параметров. Сейчас именно так

2023-01-25 09:03 UTC, valer1435 requested changes

2023-01-25 11:10 UTC, aPovidlo commented on fedot/core/operations/evaluation/bagging.py
> +    def predict_proba(self, trained_operation, predict_data: InputData) -> OutputData:
Не понял, нужно сделать подобное методу `SkLearnClassificationStrategy`?

2023-01-25 11:13 UTC, aPovidlo commented on fedot/core/operations/evaluation/bagging.py
> +        return super().fit(train_data)
Да, в курсе, но, как по мне, так намного лучше читается сам код и легче будет потом разобраться что к чему

2023-01-25 11:23 UTC, aPovidlo commented on fedot/core/pipelines/tuning/search_space.py
> +                'bagging_params': {
С тюнингом пока все сложно в плане реализации. Про использование вложенных параметров для hyperopt пока еще не успел посмотреть, поэтому не знаю работает ли тюнинг, это сейчас и выясняю. Изначально у меня была немного другая идея по оптимизации базовых моделей в бэггинге. Из-за временной дороговизны операции, думаю, что будет более рационально использовать найденные на этапе композирования и тюнинг модели, которые после можно обернуть в бэггинг и посмотреть улучшает ли он результат.

Пример, во время композирования и тюнинга мы нашли, что пайплайн 'lgbm' {с найденными оптимальными параметрами} и в качестве базовой моделей бэггинга используем эту модель с найденными параметрами.

2023-01-25 11:25 UTC, aPovidlo commented on fedot/core/pipelines/tuning/search_space.py
> +                'bagging_params': {
Однако, пока все еще не понимаю, как их использовать если у нас какая-то более разветвленная структура пайплайна получилась

2023-01-25 11:26 UTC, aPovidlo commented on test/unit/models/test_strategy.py
> +        assert metric < 1000
Почему бы и нет

2023-01-25 16:11 UTC, nicl-nno commented on fedot/core/operations/evaluation/bagging.py
> +        return super().fit(train_data)
Дублировать так реализации методов базового класса действительно нет особого смысла, ето анти-паттерн.

2023-03-27 13:18 UTC, aPovidlo commented on fedot/core/operations/evaluation/bagging.py
> +        return super().fit(train_data)
@valer1435 @nicl-nno уберу в следующем коммите

2023-03-27 13:26 UTC, aPovidlo commented on fedot/core/operations/evaluation/bagging.py
> +    def predict_proba(self, trained_operation, predict_data: InputData) -> OutputData:
@valer1435 Убрал

2023-03-28 13:23 UTC, valer1435 requested changes
Вроде уже близко

2023-03-28 13:23 UTC, valer1435 commented on fedot/core/operations/evaluation/bagging.py
> +                params = OperationParameters.from_operation_type(operation_type, **(params.to_dict()))
Если и так приходит OperationParams, зачем его создавать заново?

2023-03-28 13:41 UTC, aPovidlo commented on fedot/core/composer/gp_composer/specific_operators.py
> +    bag_model = 'bag_' + mutable_node.name
Взять название модели без префикса `bag_`. Пока не придумал, как изящнее сделать

2023-03-28 13:41 UTC, aPovidlo commented on fedot/core/composer/gp_composer/specific_operators.py
> +    new_node = PipelineBuilder().add_node(bag_model, params=bag_params).build().nodes[0]
@valer1435 не работает так, потому что он параметры не принимает

2023-03-28 13:48 UTC, aPovidlo commented on fedot/core/operations/evaluation/bagging.py
> +                params = OperationParameters.from_operation_type(operation_type, **(params.to_dict()))
@valer1435 при мутации мы передаем параметры из ноды модели уже в `OperationParameters(...)`. Но в нем отсутствует `bagging_params`, поэтому необходимо подтянуть дефолтные

2023-03-28 13:56 UTC, aPovidlo commented on fedot/core/composer/gp_composer/specific_operators.py
> +    replaced_node = pipeline.nodes[replaced_node_index]
@valer1435 возможно, попробую тогда убрать

2023-03-28 13:59 UTC, aPovidlo commented on fedot/core/composer/gp_composer/specific_operators.py
> +def bagging_mutation(pipeline: Pipeline, requirements, params, **kwargs) -> Pipeline:
@valer1435 Да, думаю, что стоит добавить проверку на это

2023-04-01 15:51 UTC, aPovidlo commented on fedot/core/composer/gp_composer/specific_operators.py
> +def bagging_mutation(pipeline: Pipeline, requirements, params, **kwargs) -> Pipeline:
@valer1435 исправил [здесь](https://github.com/aimclub/FEDOT/pull/1005/commits/2a12f838fa2e460dd1ee02eaa9a6e848d9592395)

2023-04-03 08:22 UTC, valer1435 commented
1) Я мб пропустил, но где-то бэггинг мутация в процессе автоматической работы федота используется?

2) Для тестов стоит подобрать более простые модели или уменьшить значение параметров. Видимо долго работает

2023-04-03 11:16 UTC, aPovidlo commented
> 1. Я мб пропустил, но где-то бэггинг мутация в процессе автоматической работы федота используется?

1. Пока еще не добавлял ее в дефолтные мутации, или какие-либо параметры для запуска в автоматической режиме работы

> 2. Для тестов стоит подобрать более простые модели или уменьшить значение параметров. Видимо долго работает

2. Данная очевидность уже обсуждалась. Сейчас и так подобранны минимальные значения параметров. Хотелось бы проверять все модели, но возможно стоит ограничится только `'dt'`, т.к. раз на раз бывает превышения времени выполнения тестов

2023-04-04 09:00 UTC, valer1435 requested changes
Тогда можно перенести в интеграционники тест со всеми моделями, а в юнит оставить только dt

2023-04-04 12:40 UTC, aPovidlo commented on fedot/core/operations/evaluation/bagging.py
> +                params = OperationParameters.from_operation_type(operation_type, **(params.to_dict()))
Ну если где-то они будут отсутствовать или в `model_params`, или в `bagging_params`, или в обеих, то взять дефолтные

2023-04-04 12:42 UTC, aPovidlo commented on fedot/core/composer/gp_composer/specific_operators.py
> +    if mutable_candidates:
Кмк проще когда один return в функции

2023-04-08 07:36 UTC, valer1435 commented on fedot/core/operations/evaluation/bagging.py
> +                params = OperationParameters.from_operation_type(operation_type, **(params.to_dict()))
Поправь, если не прав, но тогда условие должно выглядеть так: if not (params.get('model_params') and params.get('bagging_params')): ?

2023-04-10 08:53 UTC, valer1435 commented on fedot/core/composer/gp_composer/specific_operators.py
> +    new_node = PipelineBuilder().add_node(bag_model, params=bag_params).build().nodes[0]
И правда. Но можно сделать так 
 new_node=PipelineNode('bag_node)
new_node.parameters = bag_params

Мне кажется выглядит логичнее и проще

2023-09-21 15:23 UTC, pep8speaks commented
Hello @aPovidlo! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









* In the file [`fedot/core/data/data_split.py`](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/data/data_split.py):

> [Line 31:15](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/data/data_split.py#L31): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'np'
> [Line 32:18](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/data/data_split.py#L32): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'np'
> [Line 33:20](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/data/data_split.py#L33): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'np'
> [Line 69:59](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/data/data_split.py#L69): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'np'
> [Line 70:58](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/data/data_split.py#L70): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'np'
> [Line 100:44](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/data/data_split.py#L100): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'np'
> [Line 124:19](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/data/data_split.py#L124): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'np'





* In the file [`fedot/core/operations/evaluation/bagging_kfold.py`](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/bagging_kfold.py):

> [Line 177:1](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/bagging_kfold.py#L177): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file







* In the file [`fedot/core/operations/evaluation/operation_implementations/models/bag_ensembles/bag_ensemble.py`](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/operation_implementations/models/bag_ensembles/bag_ensemble.py):

> [Line 1:1](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/operation_implementations/models/bag_ensembles/bag_ensemble.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) 'copy' imported but unused
> [Line 2:1](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/operation_implementations/models/bag_ensembles/bag_ensemble.py#L2): [F401](https://duckduckgo.com/?q=pep8%20F401) 'time' imported but unused
> [Line 15:121](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/operation_implementations/models/bag_ensembles/bag_ensemble.py#L15): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 135:121](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/operation_implementations/models/bag_ensembles/bag_ensemble.py#L135): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 120 characters)

* In the file [`fedot/core/operations/evaluation/operation_implementations/models/bag_ensembles/fold_fitting_strategy.py`](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/operation_implementations/models/bag_ensembles/fold_fitting_strategy.py):

> [Line 172:26](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/operation_implementations/models/bag_ensembles/fold_fitting_strategy.py#L172): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file



* In the file [`fedot/core/operations/evaluation/test_bagging_kfold.py`](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/test_bagging_kfold.py):

> [Line 3:1](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/test_bagging_kfold.py#L3): [F401](https://duckduckgo.com/?q=pep8%20F401) 'lightgbm.LGBMClassifier' imported but unused
> [Line 4:1](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/test_bagging_kfold.py#L4): [F401](https://duckduckgo.com/?q=pep8%20F401) 'catboost.CatBoostClassifier' imported but unused
> [Line 9:1](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/test_bagging_kfold.py#L9): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.operations.evaluation.bagging_kfold.KFoldBaggingClassifier' imported but unused
> [Line 10:1](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/test_bagging_kfold.py#L10): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.pipelines.pipeline.Pipeline' imported but unused
> [Line 13:1](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/test_bagging_kfold.py#L13): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.repository.operation_types_repository.OperationTypesRepository' imported but unused
> [Line 16:1](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/test_bagging_kfold.py#L16): [F401](https://duckduckgo.com/?q=pep8%20F401) 'test.unit.pipelines.test_decompose_pipelines.get_classification_data' imported but unused
> [Line 146:1](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/test_bagging_kfold.py#L146): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 156:48](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/test_bagging_kfold.py#L156): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 161:52](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/test_bagging_kfold.py#L161): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 166:48](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/test_bagging_kfold.py#L166): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 171:48](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/test_bagging_kfold.py#L171): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 176:50](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/test_bagging_kfold.py#L176): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 181:48](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/test_bagging_kfold.py#L181): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 223:5](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba279641e/fedot/core/operations/evaluation/test_bagging_kfold.py#L223): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'y_hat_m' is assigned to but never used
> [Line 225:121](https://github.com/aimclub/FEDOT/blob/405a3f54a1950fd886f45f005b29ff3ba2796 [...]

2024-05-07 14:33 UTC, nicl-nno commented
Closed as obsolete

2024-05-07 14:33 UTC, closed without merging