Update readme file and setup
aimclub/FEDOT pull request #1014
Opened 2022-12-23 12:25 UTC by Nunkyl

2022-12-23 12:56 UTC, nicl-nno commented on README.en.rst
> +   :target: /README.rst
![image](https://user-images.githubusercontent.com/5711814/209339518-f276b301-5738-46af-9a99-3c4f82f1d7a8.png)

А можно эту плашку загнать в таблицу ниже для единообразия?

2022-12-23 16:10 UTC, nicl-nno commented on README.rst
> +Мы благодарны контрибьютерам за их важный вклад, а участников многочисленных конференций и семинаров - за их ценные советы и предложения.
Несогласовано грамматически.

2022-12-23 16:10 UTC, nicl-nno commented on README.rst
> +Кроме того, мы работаем над рядом исследовательских задач, связанных с бенчмаркингом временных рядов AutoML и мультимодальным моделированием.
бенчмаркингом прогнозирования временных рядов с помощью AutoML

2022-12-23 16:11 UTC, nicl-nno commented on README.rst
> +Также можно посмотреть на `сравнительный анализ <https://github.com/ITMO-NSS-team/FEDOT-benchmarks>`__, это репозиторий, который был разработан для сравнения FEDOT с другими хорошо известными фреймво
Давай уберем эту ссылку и текст из обоих README.

2022-12-23 16:11 UTC, nicl-nno commented on README.rst
> +* В пакете `core <https://github.com/nccr-itmo/FEDOT/tree/master/fedot/core>`__  находятся основные классы и скрипты. Это *ядро* фреймворка FEDOT.
Во всех ссылках можно заменить https://github.com/nccr-itmo/FEDOT на https://github.com/aimclub/FEDOT

2022-12-23 16:13 UTC, nicl-nno commented on README.rst
> +Установка с дополнительными зависимостями для обработки изображений и текста, а также для DNNs:
>DNNs
>DNN

2022-12-23 16:14 UTC, nicl-nno approved these changes

2022-12-23 16:17 UTC, nicl-nno requested changes
Проблема ещё с pypi - как-то бы сделать, чтобы там оставился английский текст.

2022-12-23 16:34 UTC, Nunkyl commented on README.en.rst
> +   :target: /README.rst
Добавила в таблицу

2022-12-23 16:34 UTC, Nunkyl commented on README.rst
> +Мы благодарны контрибьютерам за их важный вклад, а участников многочисленных конференций и семинаров - за их ценные советы и предложения.
Исправила

2022-12-23 16:37 UTC, Nunkyl commented on README.rst
> +Кроме того, мы работаем над рядом исследовательских задач, связанных с бенчмаркингом временных рядов AutoML и мультимодальным моделированием.
Исправила

связанных с бенчмаркингом прогнозирования временных рядов с помощью AutoML и мультимодального моделирования

2022-12-23 16:38 UTC, Nunkyl commented on README.rst
> +Также можно посмотреть на `сравнительный анализ <https://github.com/ITMO-NSS-team/FEDOT-benchmarks>`__, это репозиторий, который был разработан для сравнения FEDOT с другими хорошо известными фреймво
Готово

2022-12-23 16:38 UTC, Nunkyl commented on README.rst
> +* В пакете `core <https://github.com/nccr-itmo/FEDOT/tree/master/fedot/core>`__  находятся основные классы и скрипты. Это *ядро* фреймворка FEDOT.
Готово

2022-12-23 16:38 UTC, Nunkyl commented on README.rst
> +Установка с дополнительными зависимостями для обработки изображений и текста, а также для DNNs:
Исправила

2022-12-24 11:12 UTC, nicl-nno commented on setup.py
> +README = Path(HERE, 'README.en.rst').read_text(encoding='utf-8')
Можно ещё для надежности поменять на README_en.rst - чтобы не было путаницы с расширениями.

2022-12-26 10:10 UTC, Nunkyl commented on setup.py
> +README = Path(HERE, 'README.en.rst').read_text(encoding='utf-8')
Готово

2022-12-26 12:40 UTC, nicl-nno approved these changes

2022-12-26 15:08 UTC, merged