Various fixes to work with large datasets in better way
aimclub/FEDOT pull request #1019
Opened 2023-01-11 17:01 UTC by nicl-nno

There are several mini-fixes are applied:

- Stopping if even one fold failed 
- Presets bug fixed
- More stable wor for short timeouts
- Various minor changes

2023-01-13 08:09 UTC, valer1435 commented on fedot/api/main.py
> +        if self.params.api_params['preset'] != 'auto':
Почему потребовалось добавать условие?

2023-01-13 09:04 UTC, nicl-nno commented on fedot/api/main.py
> +        if self.params.api_params['preset'] != 'auto':
Потому что сейчас если задать список available_operations вначале - то потом в варианте auto они уже не меняются. Не нашел блоее изящного решения, так кажется более масштабный рефакторинг нужен.

2023-01-13 11:24 UTC, valer1435 commented on fedot/api/main.py
> +        if self.params.api_params['preset'] != 'auto':
![image](https://user-images.githubusercontent.com/32017472/212309489-11a0c1a5-b9cb-4e5f-82af-17a3629a3acd.png)

2023-01-19 18:28 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +                                keep_history=True, history_dir=None, )
Поправил.

2023-01-20 09:21 UTC, valer1435 commented on fedot/core/pipelines/tuning/unified.py
> +            remaining_time = self.max_seconds - global_tuner_timer.minutes_from_start * 60
Почему нельзя считать секунды и надо округлять до минут?

2023-01-20 10:33 UTC, gkirgizov requested changes

2023-01-20 10:33 UTC, gkirgizov commented on fedot/api/main.py
> +                raise ValueError('No any models were found')
грамматика: достаточно "No models were found", c any масло масляное немного

2023-01-20 10:33 UTC, gkirgizov commented on fedot/core/optimisers/archive/individuals_containers.py
> +            return
сюда может придти  None?

2023-01-20 10:33 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/evaluation.py
> +class SequentialDispatcher(MultiprocessingDispatcher):
Может, выделить обеим диспетчерам общий суперкласс? А то выглядит не очень корректно, последовательный оценщик оказывется подклассом многопоточного. Какой-нибудь `isinstance(sequential, MultiprocessingDispatcher)` вернет True и вызовет небольшой WTF-эффект

2023-01-20 10:33 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/evaluation.py
> +class SequentialDispatcher(MultiprocessingDispatcher):
И он очень похож на SimpleDispatcher. Может, один из них оставить?

2023-01-20 10:33 UTC, gkirgizov commented on fedot/core/pipelines/tuning/unified.py
> +                    raise ex
Может, стоит добавить эту лоигку в LoggingAdapter, что-то вроде флага `raise_in_tests`. чтобы в одном месте единообразно выкидывать исключение на всех-всех warning-ах? И тем самым не загрязнять production-код лоигкой, связаннйо с тестами

2023-01-20 10:39 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/evaluation.py
> +class SequentialDispatcher(MultiprocessingDispatcher):
>И он очень похож на SimpleDispatcher. Может, один из них оставить?

Это так. Не стал его пока убирать, т.к. ты писал что он нужен для тестов:

![image](https://user-images.githubusercontent.com/5711814/213675699-a04d6355-bb18-45c2-8293-746b0a812102.png)

Если Sequential для это хватит, то да, давай уберем.

С суперклассом согласен.

2023-01-20 10:40 UTC, nicl-nno commented on fedot/core/optimisers/archive/individuals_containers.py
> +            return
Может прийти [], если ни один индивид в популяции не успел обработаться.

2023-01-20 19:07 UTC, nicl-nno commented on fedot/core/pipelines/tuning/unified.py
> +                    raise ex
Попробовал это сделать вот [так](https://github.com/aimclub/FEDOT/pull/1019/files#diff-702f1068708455144cc2ae7bceb96da8e1de4b0688343b793e3da2b806988ccfR175-R205)

2023-01-20 19:07 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/evaluation.py
> +class SequentialDispatcher(MultiprocessingDispatcher):
Убрал Simple и создал BasePipelineEvaluationDispatcher в том же файле.

2023-01-20 19:07 UTC, nicl-nno commented on fedot/api/main.py
> +                raise ValueError('No any models were found')
Поменял.

2023-01-20 19:07 UTC, nicl-nno commented on fedot/api/api_utils/assumptions/assumptions_handler.py
> +                                             n_jobs: int = -1) -> Pipeline:
Поменял.

2023-01-23 11:10 UTC, nicl-nno commented
Обновил до мастера.

2023-01-23 11:11 UTC, nicl-nno commented on fedot/api/main.py
> +                raise ValueError('No any models were found')
Поменял

2023-01-23 11:11 UTC, nicl-nno commented on fedot/core/pipelines/tuning/unified.py
> +            remaining_time = self.max_seconds - global_tuner_timer.minutes_from_start * 60
Поменял.

2023-01-23 11:18 UTC, nicl-nno commented
>Сейчас получается, что работа с available_operations происходит [тут](https://github.com/aimclub/FEDOT/pull/1019/files#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR101) и в этом куске кода. Так и должно быть?

Если они явно не заданы - то вроде да.

2023-01-23 17:11 UTC, valer1435 approved these changes

2023-01-24 09:11 UTC, YamLyubov approved these changes

2023-01-24 14:51 UTC, merged