Generalize PipelineBuilder
aimclub/FEDOT pull request #1020
Opened 2023-01-11 23:30 UTC by maypink

WIP

2023-01-12 00:08 UTC, nicl-nno commented on fedot/core/pipelines/pipeline_builder.py
> +class PipelineBuilder(OptGraphBuilder):
Вопрос общего характера: а не будет ли полезно свете этого рефакторинга избавиться от PrimaryNode и SecondaryNode вообще?

Изначально они вводились потому, что у них разных старатегии обучения в ходе fit. Но мб если отделить реализацию обучения от структуры, то будет проще? И тот же Secondary будет от OptGraphBuilder отличаться совсем незначительно.
 
Ещё разница в Primary/Secondary важна для выбора корректных замен - но это тоже можно реализовать иначе.

2023-01-17 10:24 UTC, maypink commented on fedot/core/pipelines/pipeline_builder.py
> +class PipelineBuilder(OptGraphBuilder):
Учитывая, что все, чем они по факту отличаются это `nodes_from`, то да, на первый взгляд отделить реализацию обучения от структуры выглядит несложно, можно попробовать.

2023-01-17 10:24 UTC, maypink commented
Со skip connections получается так: до и после соединения `knn` и `scaling`
![image](https://user-images.githubusercontent.com/57305249/212870205-d92b30ed-b99b-48be-86e9-15590c12745b.png)
![image](https://user-images.githubusercontent.com/57305249/212870257-384160a7-6683-48f3-a92d-100962c4cd56.png)

2023-01-20 09:56 UTC, gkirgizov requested changes

2023-01-20 09:56 UTC, gkirgizov commented on fedot/core/pipelines/pipeline_builder.py
> +class PipelineBuilder(OptGraphBuilder):
Согласен с этой идеей. Упростится логика обхода и создания пайплайнов. Тоже возникали мысли, что это разделение выглядит необязательным.

Только лучше это сделать в отдельном PR, скорее всего будет много небольших изменений по федоту.  Заведу issue

2023-01-20 09:56 UTC, gkirgizov commented on fedot/core/pipelines/pipeline_builder.py
> +        Can be used only in the very end of graph building but before 'join_branches'.
А почему только перед join_branches?
Что-то сломается, если использовать после?

2023-01-20 09:56 UTC, gkirgizov commented on fedot/core/optimisers/opt_graph_builder.py
> +class OptGraphBuilder:
Суть issue в том, чтобы создать рабочий билдер для графов, либо описать что этому препятствует.
На первый взгляд мне кажется, что ничего не мешает использовать этот билдер для того, чтобы создавать OptGraph, например в тестах: `OptGraphBuilder().add_node('a').add_branch('b', 'c').add_join('d').build() -> OptGraph` где на выходе мы получаем объект OptGraph, который можно использовать.

Может быть, для этого можно как-то параметризовать GraphBuilder типом конструируемого графа, вроде как (взял из головы для примера): `GraphBuilder(bulit_graph_cls=Pipeline).add_sequence(...).build()` -- и мы получаем Pipeline. Или передавать adapter необходимый. Что-то такое будет полезнее простого интерфейса. который придется однотипно реализовывать.

2023-01-23 23:42 UTC, maypink commented on fedot/core/pipelines/pipeline_builder.py
> +        Can be used only in the very end of graph building but before 'join_branches'.
экшели ничего, добавила проверок, чтобы избежать графа с циклом в таком случае

2023-01-23 23:52 UTC, maypink commented on fedot/core/optimisers/opt_graph_builder.py
> +class OptGraphBuilder:
сделала с адаптером, но оставила абстрактный класс `GraphBuilder`, чтобы была возможность для других типов графовых структур переопределить под себя

2023-01-24 05:52 UTC, gkirgizov approved these changes

2023-01-24 22:01 UTC, merged