Added tune method to API
aimclub/FEDOT pull request #1021
Opened 2023-01-13 17:35 UTC by aPovidlo

Solution to Issue #1018

2023-01-20 09:30 UTC, YamLyubov requested changes

2023-01-20 09:30 UTC, YamLyubov commented on fedot/api/main.py
> +             show_progress: bool = False) -> Pipeline:
Тут нужно добавить еще ``validation_blocks`` иначе тюнер будет расчитывать метрику для временных рядов не так, как до этого композер

2023-01-20 09:30 UTC, YamLyubov commented on test/unit/api/test_main_api.py
> +        train_data, test_data, _ = get_dataset(task_type, validation_blocks=1)
Если здесь ```validation_blocks=1``` тогда в тюнере они тоже должны быть равны единице. Сейчас в тюнере ``validation_blocks=None``, что не тоже самое

2023-01-20 09:30 UTC, YamLyubov commented on test/unit/api/test_main_api.py
> +    tuned_pipeline = deepcopy(model.tune(timeout=0.5))
Можно уменьшить таймаут до 0.1

2023-01-20 13:29 UTC, aPovidlo commented on fedot/api/main.py
> +            metric = self.params.metric_to_compose
@YamLyubov @nicl-nno А их как-то может починить или убрать забыли когда-то?

2023-01-20 13:34 UTC, aPovidlo commented on fedot/api/main.py
> +            pipeline_tuner = pipeline_tuner.with_timeout(timedelta(seconds=60 * timeout))
Да, это я почему-то подумал, что timedelta() не будет воспринимать float. Проверил и он все-таки будет, поэтому исправлю.

2023-01-20 13:35 UTC, aPovidlo commented on fedot/api/main.py
> +            pipeline_tuner = pipeline_tuner.with_timeout(timeout=None)
Это скорее было сделанно, потому что если не указывать время, то будет дефолтное значение при инициализации. Думаю, что может быть по умолчанию бесконечность ставить, а не в методе изменять?

2023-01-20 13:44 UTC, aPovidlo commented on fedot/api/main.py
> +        self.current_pipeline.fit(self.train_data)
А что значит > новые для тюнинга?

2023-01-20 13:44 UTC, aPovidlo commented on fedot/api/main.py
> +             show_progress: bool = False) -> Pipeline:
Спасибо, исправлю это

2023-01-20 13:45 UTC, aPovidlo commented on test/unit/api/test_main_api.py
> +    tuned_pipeline = deepcopy(model.tune(timeout=0.5))
Хорошо

2023-01-20 14:15 UTC, aPovidlo commented on fedot/api/main.py
> +             show_progress: bool = False) -> Pipeline:
@YamLyubov А он же обязательно должен быть одинаковым с тем, который был указан в композере, или не всегда?

2023-01-20 21:03 UTC, nicl-nno commented on fedot/api/main.py
> +            metric = self.params.metric_to_compose
Видимо забыли убрать - можно в рамках этого PR это и сделать (надо только проверит).

2023-01-24 09:14 UTC, YamLyubov commented on fedot/api/main.py
> +        self.current_pipeline.fit(self.train_data)
Ну то есть мы получили модель в рамках Fedot.fit на одних данных, а потом решили подобрать гиперпараметры через тюнинг на других данных.

2023-01-24 09:16 UTC, YamLyubov commented on fedot/api/main.py
> +             show_progress: bool = False) -> Pipeline:
От количества ```validation_blocks`` зависит то, как мы будем рассчитывать метрику.

2023-01-24 09:31 UTC, YamLyubov commented on fedot/api/main.py
> +             show_progress: bool = False) -> Pipeline:
Также get_metrics() тоже использует ```validation_blocks``` тоже, что и композер.

2023-01-24 09:34 UTC, YamLyubov commented on fedot/api/main.py
> +            pipeline_tuner = pipeline_tuner.with_timeout(timeout=None)
Тогда в TunerBuilder надо еще поменять ```self.iterations=DEFAULT_TUNING_ITERATIONS_NUMBER``` и ```self.timeout=None```. В hyperopt нельзя прям бесконечность поставить

2023-01-24 17:11 UTC, aPovidlo commented on test/unit/api/test_main_api.py
> +        train_data, test_data, _ = get_dataset(task_type, validation_blocks=1)
Исправил

2023-01-24 17:13 UTC, aPovidlo commented on fedot/api/main.py
> +             show_progress: bool = False) -> Pipeline:
Думаю, что у меня получилось это исправить, если обернуть метод в `api_composer` чтобы использовать информацию из `composer_requirements`

2023-01-24 17:14 UTC, aPovidlo commented on fedot/api/main.py
> +            pipeline_tuner = pipeline_tuner.with_timeout(timeout=None)
Исправил все это в `tuner_builder.py`

2023-01-24 17:15 UTC, aPovidlo commented on fedot/api/main.py
> +            metric = self.params.metric_to_compose
Убрал

2023-01-25 12:06 UTC, YamLyubov requested changes

2023-01-25 12:06 UTC, YamLyubov commented on fedot/api/api_utils/api_composer.py
> +    def tune_pipeline(self, pipeline: Pipeline,
Мне кажется, этот метод дублирует ```tune_final_pipeline```, было бы лучше этот метод все-таки в api вынести. Можно же просто тогда доставать ```composer_params = self.api_composer.composer_requirements```

2023-01-25 12:06 UTC, YamLyubov commented on fedot/api/main.py
> +        self.current_pipeline = ApiComposer.tune_pipeline(
Тут скорее всего имелось в виду ```self.api_composer```

2023-01-25 15:36 UTC, nicl-nno commented on fedot/api/main.py
> +        self.current_pipeline.fit(self.train_data)
Если реализовал - пусть будет, в теории может пригодится. Главное что их передача необязательна.

2023-01-25 15:37 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +                                keep_history=True, history_dir=None, )
Лишняя запятая?

2023-01-25 15:40 UTC, nicl-nno commented on fedot/api/main.py
> +            metric = self.metrics.get_metrics_mapping(self.metrics.get_problem_metrics()[0])
Кажется, можно часть metric = self.metrics.get_metrics_mapping вынести за if.

2023-01-25 17:39 UTC, aPovidlo commented on fedot/api/main.py
> +            show_progress: shows progress of tuning if true
В [тесте](https://github.com/aimclub/FEDOT/blob/9ea1b8c0fb7d38b7d677b203b1c6468e7a5805cd/test/unit/api/test_main_api.py#L173) можно увидеть, что передается только время на тюнинг. Из `fit` нам только необходимо знать параметр для метода `.with_requirements(...)`.

2023-01-25 17:40 UTC, aPovidlo commented on fedot/api/main.py
> +            show_progress: shows progress of tuning if true
Заметил, что `self.api_composer.tuner_requirements` и `cv_folds` и `n_jobs` перекрывают друг друга. Поэтому в следующем коммите исправлю этот момент

2023-01-25 17:42 UTC, aPovidlo commented on fedot/api/main.py
> +            metric = self.metrics.get_metrics_mapping(self.metrics.get_problem_metrics()[0])
И вправду, можно вынести

2023-01-26 09:57 UTC, YamLyubov requested changes

2023-01-26 09:57 UTC, YamLyubov commented on fedot/api/main.py
> +            input_data = self.train_data
Может в этой и аналогичных строчках лучше переформатировать ```input_data = input_data or self.train_data```

2023-01-26 09:57 UTC, YamLyubov commented on fedot/api/main.py
> +            n_jobs = self.api_composer.tuner_requirements.n_jobs
Эти строчки дублируют логику TunerBuilder. Если ты делаешь такую замену, то уже нет смысла в билдер и requirements, и cv_folds и n_jobs передавать. 

Было бы удобнее в самих ComposerRequirements заменить необходимые параметры и только их передавать

2023-01-26 09:57 UTC, YamLyubov commented on test/unit/api/test_main_api.py
> +def test_api_tune_correct(task_type, metric_name, pred_model):
У меня этот тест не проходит. Видимо модель переобучается на трейне.
![image](https://user-images.githubusercontent.com/43475193/214805032-2f2b80ae-2454-46e9-bc5a-ed21ddca0de1.png)

2023-01-26 10:25 UTC, aPovidlo commented on fedot/api/main.py
> +            input_data = self.train_data
Да, так будет лучше

2023-01-26 10:26 UTC, aPovidlo commented on fedot/api/main.py
> +            n_jobs = self.api_composer.tuner_requirements.n_jobs
Соглашусь

2023-01-26 18:21 UTC, nicl-nno approved these changes

2023-01-30 16:36 UTC, YamLyubov approved these changes

2023-01-30 16:40 UTC, merged