+ main API input preprocessing activation param
aimclub/FEDOT pull request #1025
Opened 2023-01-16 13:40 UTC by IIaKyJIuH

Adds main api parameter (named as `use_io_preprocessing`) that switches off preprocessing of passed input data.

* This behaviour relies on a fact that data is already preprocessed.
* Doesn't switch off preprocessing of the data while making "inner input" for further model's layers.

2023-01-16 13:40 UTC, IIaKyJIuH commented
Нужно будет изменить docstring, если всё остальное норм.

2023-01-19 14:45 UTC, MorrisNein requested changes
В целом всё хорошо, только есть небольшие предложения по структуре кода

2023-01-19 14:45 UTC, MorrisNein commented on fedot/core/pipelines/pipeline.py
> +
Предлагаю вынести в метод `_preprocess_for_fit(data)`, а условие превратить в "заглушку" в начале функции.
Аналогично с предиктом.

Возможно, дело во мне, но такой вариант кажется лаконичнее. На уровне фита-предикта слишком подробно расписан препроцессинг

2023-01-19 14:45 UTC, MorrisNein commented on fedot/core/pipelines/pipeline.py
>          return result
То же самое, можно понизить уровень вложенности, добавив заглушку

```
if self.preprocessor is not None:
    return result
```

2023-01-19 14:45 UTC, MorrisNein commented on fedot/api/main.py
> +        use_io_preprocessing: bool indicating whether to do preprocessing of further given data, enabled by default.
Уже проговорили, но продублирую тут на всякий случай: лучше убрать "io" из имени параметра

2023-01-19 14:45 UTC, MorrisNein commented on fedot/api/api_utils/api_data.py
>          return data
Тут тоже бы сделать заглушкой. Мне кажется, лучше 2 раза написать `return data`, чем добавить уровень вложенности нескольким строкам

2023-01-19 14:45 UTC, MorrisNein commented on fedot/api/api_utils/api_data.py
> +                                    'label_encoded': self.preprocessor.label_encoding_for_fit}
Мне кажется, не стоит делать атрибут объекта опциональным, это усложняет разработку. Пусть там хранится None или пустой словарь, если он не нужен.

2023-01-19 14:51 UTC, MorrisNein commented
Изначально можно бы сделать более лениво: создать DummyPreprocessor, который реализует все необходимые методы, но при этом возвращает то же, что в него передано, и не требует перестройки внешнего кода. 

Преимущества: - другим компонентам программы не нужно будет знать, используем ли мы хоть какой-то препроцессор, - следовательно, большинство добавленных проверок на None не будут нужны.

Недостатки:  
- немного усложнится дебаг,
- придётся сопровождать Dummy-класс, но это решается абстрактным интерфейсом + наследованием

С одной стороны упрощаем, с другой более сложно.

2023-01-24 07:17 UTC, IIaKyJIuH commented on fedot/api/api_utils/api_data.py
> +            self.preprocessor = None
Теперь тут всегда изначально [устанавливается DummyPreprocessor](https://github.com/aimclub/FEDOT/pull/1025/files#diff-650638a6c6857b24a2475786ce055e9486f5484462307146eba8d3219bb7344bR33)

2023-01-24 07:18 UTC, IIaKyJIuH commented on fedot/api/api_utils/api_data.py
> +                self._recommendations[name](input_data, *rec.values())
[Готово](https://github.com/aimclub/FEDOT/pull/1025/files#diff-650638a6c6857b24a2475786ce055e9486f5484462307146eba8d3219bb7344bR122-R125)

2023-01-24 07:19 UTC, IIaKyJIuH commented on fedot/core/operations/atomized_model.py
> +        self.atomized_preprocessor = DataPreprocessor() if pipeline.preprocessor is not None else None
Насчёт этого не знаю(
Но узнаю

2023-01-24 07:56 UTC, IIaKyJIuH commented on fedot/core/pipelines/pipeline.py
> +
Убрал такое странное условие, теперь всё гораздо приземлённее.
[Лишь упаковал метод](https://github.com/aimclub/FEDOT/pull/1025/files#diff-234d33139f2520fa65ffcb8d6bb7a6958e97b3aae2cd3def0ac8cfd37f4a8d7aR234) для ts в этот же класс (хотя он там и не используется), чтобы было семантичнее в смысле предобработчика

2023-01-24 07:57 UTC, IIaKyJIuH commented on fedot/core/pipelines/pipeline.py
>          return result
Теперь там такой же уровень вложенности, который был изначально

2023-01-24 07:57 UTC, IIaKyJIuH commented on fedot/api/api_utils/api_data.py
>          return data
Тут теперь тоже всё как и раньше

2023-01-24 07:58 UTC, IIaKyJIuH commented on fedot/api/api_utils/api_data.py
> +                                    'label_encoded': self.preprocessor.label_encoding_for_fit}
[Вот такие поля теперь будут по умолчанию](https://github.com/aimclub/FEDOT/pull/1025/files#diff-650638a6c6857b24a2475786ce055e9486f5484462307146eba8d3219bb7344bR32-R33)

2023-01-24 08:12 UTC, IIaKyJIuH commented on fedot/api/main.py
> +        use_io_preprocessing: bool indicating whether to do preprocessing of further given data, enabled by default.
[В этом коммите попробовал всё переименовать по уму](https://github.com/aimclub/FEDOT/pull/1025/commits/7309ed0ee09b0a821b3233fc48a73624d4f89f28)

2023-01-25 09:39 UTC, IIaKyJIuH commented on fedot/core/operations/atomized_model.py
> +        self.atomized_preprocessor = DataPreprocessor() if pipeline.preprocessor is not None else None
Уже пинганул @maypink, если я правильно понял, она может подсказать.

2023-01-26 08:55 UTC, IIaKyJIuH commented on fedot/core/operations/atomized_model.py
> +        self.atomized_preprocessor = DataPreprocessor() if pipeline.preprocessor is not None else None
Вообще, если чисто логически посмотреть и подумать, в двух местах используется этот препроцессор, и то только для непосредственно препроцессинга, выглядит максимально логичным использовать препроцессор от пайплайна. 

По идее, ничего не должно переназначаться или ломаться, поэтому не вижу смысла в проверке этого в тестах, что скажешь @MorrisNein?

![image](https://user-images.githubusercontent.com/38308131/214795082-8ae86acb-8e95-4df6-a3b9-43a6ffb1e3f0.png)

2023-01-26 14:30 UTC, MorrisNein commented on fedot/core/operations/atomized_model.py
> +        self.atomized_preprocessor = DataPreprocessor() if pipeline.preprocessor is not None else None
Выглядит надёжно, если препроцессор существенно не изменяет своего содержимого в процессе работы.

В таком формате можем вообще не хранить препроцессор в AtomizedModel, а использовать только препроцессор напрямик из пайплайна. Не уверен так сходу, насколько архитектурно это адекватно

2023-01-26 14:51 UTC, MorrisNein approved these changes
Хороший PR, одобряю!

2023-01-26 17:46 UTC, nicl-nno approved these changes

2023-01-27 18:33 UTC, nicl-nno commented
Ребейз ещё надо бы сделать - много накопилось конфиликтов.

2023-01-30 08:43 UTC, andreygetmanov requested changes

2023-01-30 08:43 UTC, andreygetmanov commented on fedot/core/pipelines/pipeline_builder.py
> +    def __init__(self, *initial_nodes: Optional[Node], use_input_preprocessing: bool = True):
А есть ли возможность положить куда-то `use_input_preprocessing`, при этом не уменьшая уровень абстракции PipelineBuilder?
И не будет ли проблем со скорым отделением Голема? PipelineBuilder не входит в классы, которые туда переносятся?

2023-02-06 10:02 UTC, gkirgizov requested changes

2023-02-06 10:02 UTC, gkirgizov commented on fedot/core/optimisers/opt_graph_builder.py
> +        return result_opt_graph
В целом ок. Но для более легкой поддержки в будущем этот параметр лучше вытащить куда-нибудь в init PipelineAdapter-а. Он и нужен для более точной и специфичной параметризации подклассов. Возможно ли это?

2023-02-06 11:15 UTC, IIaKyJIuH commented on fedot/core/composer/composer_builder.py
> +    def build(self) -> Composer:  # TODO: put kwargs here?
Думал, что сюда возможно пойдёт kwargs-параметром "`use_input_preprocessing`", но сделав парочку тестов, понимаю, что тут можно обойтись и без этого.

2023-02-06 11:18 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/evaluation.py
> +                # TODO: Is it even needed here?
Это необязательный параметр, который нужен только лишь для того, чтобы при `_restore`'инге индивида в пайплайн сохранялся параметр с необходимостью в препроцессинге, а именно, `use_input_preprocessing`.
Это же справедливо и для мест, где создаётся индивид из пайплайна, точное такое же обоснование.

Если этот ключ не передавать, ничего не сломается, просто по умолчанию препроцессинг будет включаться. Суть в том, что это не всегда же нужно.

2023-02-06 11:22 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/gp_optimizer.py
> +            for graph in initial_graphs]  # TODO: Is it legal?
Не понимаю, как связаны composer_params и параметры для создания индивида?

Я думал, что индивид создаётся в FEDOT'е, в основном, из пайплайна, поэтому нужно именно в пайплайне сохранять параметр использования препроцессинга -- `use_input_preprocessing`.

Тут же происходит попытка достать это поле из класса пайплайна, ничего не ломается. Не придумал, как можно сделать это безболезненнее и элегантнее

2023-02-06 14:55 UTC, IIaKyJIuH commented on fedot/core/optimisers/opt_graph_builder.py
> +        return result_opt_graph
Дело в том, что этот адаптер, по сути, создаётся [в этом месте](https://github.com/aimclub/FEDOT/blob/add-preprocessing-control/fedot/core/pipelines/pipeline_builder.py#L7). То есть этот адаптер создаётся на данный момент статично.

Можно перевести всё на динамичное создание путём ввода функции обёртки с `args` и `kwargs`, в целом, всё останется на тех же местах, проблема в том, что тогда параметр `use_input_preprocessing` будет храниться в ещё нескольких классах (вообще говоря у меня так было в ранних коммитах, но мы от этого отошли), думаешь, оно стоит того?

2023-02-06 15:24 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimizer.py
> +            for graph in initial_graphs]  # TODO: Is it legal?
Настройка препрцессинга задается при запуске AutoML, так? То есть это параметр, имеющий значение для всео фрейморвка, а не отдельного графа.
В текущем случае настройка призводится отдельно для каждого индивида. Каждый индивид несет свой параметр, который передается его потомкам и тд. Вопрос в том, а нужна ли такая детальность? Может, задать этот параметр в одном месте и оттуда его и брать?

2023-02-06 15:26 UTC, gkirgizov commented on fedot/core/optimisers/opt_graph_builder.py
> +        return result_opt_graph
Нет, пожалуй не стоит)

2023-02-07 09:43 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/operators/regularization.py
> +                                       metadata=ind.metadata)  # TODO: Is it legal
А тут же просто метадата от индивида сохраняется, разве это не норм? В противном случае, не понимаю, зачем она вообще тогда

2023-02-07 11:26 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/operators/crossover.py
> +                     for graph in new_graphs)
[Вроде оно](https://github.com/aimclub/FEDOT/pull/1025/commits/a4c83826f99261530636988c2c68e382796bbeb4)

Стало лучше?

2023-02-07 11:33 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/gp_optimizer.py
> +            for graph in initial_graphs]  # TODO: Is it legal?
Вообще этот параметр в метадате используется [тут](https://github.com/aimclub/FEDOT/blob/add-preprocessing-control/fedot/core/adapter/adapter.py#L96-L100).
Это снова отсылает нас к тому, что можно было бы прямо в `PipelineAdapter`'е использовать параметр `use_input_preprocessing`. Однако, как мы уже выяснили, это потребует дополнительно хранить этот же параметр в ещё некоторых классах.

Тем не менее, попробую что-нибудь в этом русле придумать, потому что если получится - это должно действительно решить поломку логики

2023-02-07 15:50 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/gp_optimizer.py
> +            for graph in initial_graphs]  # TODO: Is it legal?
Получилось в `PipelineAdapter`'е добавить это поле на препроцессинг, [упростилось всё](https://github.com/aimclub/FEDOT/pull/1025/commits/07e805fe98d0e384ff9a4aaea3cf786faf6a1f11)

Норм?

2023-02-08 04:00 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/crossover.py
> +                                # TODO: Is it still legal?
Примерно так, только можноеще лучше скрыть лишнее. Может, добавить в requirements сразу словарик вроде `static_individual_metadata`? и брать его сразу. Плюс такого решения в том, что операторам эволюции не нужно знать о каких-то полях индивида, которые их совершенно не интересуют.
Словарик этот можно собирть где-то на этапе настройки оптимизатора в начале запуска федота.

Добавлю также, что GOLEM в принипе не знает ни про какой препроцессинг, а эти классы уходят в голем. Поэтому нужно эти метаданные скрыть за непрозрачным словариком.

2023-02-08 04:00 UTC, gkirgizov commented on fedot/core/optimisers/opt_graph_builder.py
> +
Решение правда приводит к более приятнму коду. Но тут вознкает другая проблемка -- этот класс пойдет в ГОЛЕМ, а PipelineAdapter останется в FEDOT-е. Так что такая проверка там не сработает.

Но нужна ли вообще эта строчка? Если мы мерджим два PipelineBuilder, то они должны иметь одинаковый параметр use_input_preprocessing, так?

2023-02-08 04:00 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/regularization.py
> +                                       metadata=ind.metadata)  # TODO: Is it legal
да, ты прав, проглядел

2023-02-08 04:00 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/crossover.py
> +                     for graph in new_graphs)
лучше, но я еще оставил коммент ниже (новое ревью)

2023-02-08 08:31 UTC, IIaKyJIuH commented on fedot/core/optimisers/opt_graph_builder.py
> +
На самом деле, параметр `graph_adapter` у двух билдеров не мёржится.
Без моих изменений, единственное, что происходило - новый "смёрженный" билдер [брал адаптер от второго билдера](https://github.com/aimclub/FEDOT/blob/add-preprocessing-control/fedot/core/optimisers/opt_graph_builder.py#L216) и всё.
Поэтому тут точно надо что-то придумать

2023-02-08 10:58 UTC, IIaKyJIuH commented on fedot/core/optimisers/opt_graph_builder.py
> +
[Так](https://github.com/aimclub/FEDOT/pull/1025/commits/f8468ed18dd8cc022dd54479cce5a8ae27d88f39) норм?

2023-02-08 10:58 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/operators/crossover.py
> +                                # TODO: Is it still legal?
Вроде [получилось](https://github.com/aimclub/FEDOT/pull/1025/commits/1a2f43183fd6c06158be246e1e424bf759139b94). Лучше?

2023-02-08 11:13 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/evaluation.py
> +                # TODO: Is it even needed here?
Убрал вообще параметр с препроцессингом в поле `metadata` класса `GraphEvalResult`. Кажется, он действительно там не нужен.

2023-02-09 10:22 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/crossover.py
> +                                # TODO: Is it still legal?
А зачем нам в принципе тут указывать эту строку 'use_input_preprocessing'? Кажется, что данному классу эту строку необязательно знать. Что-то изменится, если ее убрать и просто передавать словарик из requirements как есть?

2023-02-09 11:27 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/operators/crossover.py
> +                                # TODO: Is it still legal?
Не понял тебя. [Я же теперь просто передаю статический объект со словарём в индивидов](https://github.com/aimclub/FEDOT/pull/1025/commits/1a2f43183fd6c06158be246e1e424bf759139b94#diff-2b5f3f03a740803202f4cd9b4bc5da3b6219f5f062ee654a7bc8812a894b3084R92), не указывая у них поле `use_input_preprocessing`.

Не понял, куда смотреть.

2023-02-09 11:30 UTC, IIaKyJIuH commented on fedot/core/optimisers/opt_graph_builder.py
> +
А так и происходит в случае, если [адаптеры разных типов](https://github.com/aimclub/FEDOT/pull/1025/commits/f8468ed18dd8cc022dd54479cce5a8ae27d88f39#diff-a8684b14bcbe08cebe194782dd827961ca623639e7a92c3224c9fbc68969acafR209-R210).
Я же кидаю ошибку, когда у них разные типы в значениях, показалось, что такое в теории возможно.

Мб эту проверку для адаптеров тоже уместить в одном методе, чтобы нагляднее было?

2023-02-10 02:56 UTC, gkirgizov commented on fedot/core/optimisers/opt_graph_builder.py
> +
понял. перемещать не обязаттельно, так хорошо

2023-02-10 02:57 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/crossover.py
> +                                # TODO: Is it still legal?
все, вижу. кажется, в ревью с телефона это я не туда посмотрел, извиняюсь

2023-02-10 02:58 UTC, gkirgizov approved these changes

2023-02-10 08:51 UTC, MorrisNein approved these changes

2023-02-10 08:51 UTC, MorrisNein commented on fedot/api/api_utils/api_composer.py
> +                if k in ['use_input_preprocessing']
Здесь список-фильтр выполняет неявную роль. Вынеси его в именованную переменную, пожалуйста.

2023-02-10 08:52 UTC, MorrisNein commented on fedot/api/api_utils/api_composer.py
> +                if k in ['use_input_preprocessing']
Можно даже от обратного идти и изначально итерироваться по этому списку, выхватывая нужные параметры при наличии?

2023-02-14 15:36 UTC, merged