Сlstm refactoring
aimclub/FEDOT pull request #1029
Opened 2023-01-25 11:51 UTC by valer1435

Some changes that can increase efficiency of clstm algorithm. Also bug with composer's inability to use model during composing was solved.

But using such heavy model in composing still questionable due to low performance compared with it's weight (maybe it can be useful on some types of data and with small horizon but I can't say exactly). Maybe we can refactor model structure, advices are welcome.

2023-01-25 11:55 UTC, nicl-nno commented on examples/simple/time_series_forecasting/clstm.py
> +    # pipeline_tuner.tune(pipeline)
Почисти сразу закомментированный код.

2023-01-25 11:58 UTC, valer1435 commented
Из основных изменений - убрал lagged преобразование из модели и заменил последовательное предсказание интервальным

2023-01-25 12:00 UTC, aPovidlo commented
А `'learning_rate': 0.0004,` при `'num_epochs': 50` не слишком ли мал?

2023-01-25 21:04 UTC, staeros approved these changes

2023-01-28 11:36 UTC, valer1435 commented on examples/simple/time_series_forecasting/clstm.py
> +    # pipeline_tuner.tune(pipeline)
[Убрал](https://github.com/aimclub/FEDOT/pull/1029/commits/351c92b935080224d2e4a1acfc0c27b3923ea45e#diff-98ab2e857d2a8be66f8beb3439f8604a919d6128b9122f2804ca1528ece87954R65-R66)

2023-02-06 09:31 UTC, nicl-nno commented on examples/simple/time_series_forecasting/api_forecasting.py
> +    #time_series['value'] = (time_series['value'] - np.mean(time_series['value'])) / np.std(time_series['value'])
Закомментированный код всё ещё остался.

2023-02-06 09:36 UTC, nicl-nno commented on fedot/core/pipelines/verification_rules.py
> +        print('cgru')
Не нужно?

2023-02-06 09:37 UTC, nicl-nno commented on examples/simple/time_series_forecasting/ts_pipelines.py
>                      'optimizer': 'adam', 'loss': 'mse'}
А всё это обязательно указывать? Если нет, то хорошо бы в одном из примеров продемонстировать вариант без явно заданных гиперпараметров.

2023-02-06 09:37 UTC, nicl-nno commented on test/unit/tasks/test_forecasting.py
>      predicted = pipeline.predict(test_data).predict[0]
А тут время выполнения теста норм, не слишком долго обучается cgru?

2023-02-06 09:39 UTC, nicl-nno commented
За рамками PR - надо будет проработать схему реализации таких тяжелых моделей на базе F.Ind. 
Потому что тут мы все равно в стандарные пресеты lstm-ы не включаем и о их существовании мало кто знает.

2023-02-06 10:53 UTC, aPovidlo requested changes
Не совсем понял, `clstm` остается в коде, но при это во многих местах о нем информация удалилась или была заменена на `cgru`. Может быть стоит восстановить везде про `lstm`?
Потенциально, в пайплайне их можно же обе использовать.

2023-02-06 10:53 UTC, aPovidlo commented on docs/source/basics/ts_forecasting.rst
> +* `Forecasting using cgru <https://github.com/nccr-itmo/FEDOT/blob/master/examples/simple/time_series_forecasting/cgru.py>`_
Доки может тоже изменить и прочие картинки, т.к. ты же все-равно оставил LSTM

2023-02-06 10:53 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/cgru.py
> +            'adam': torch.optim.AdamW(self.model.parameters(), lr=self.learning_rate),
`Adam` и `AdamW` это разные оптимизаторы. Чтобы не было путаницы у пользователей, лучше добавить в словарь отдельный ключ adamw.

2023-02-06 10:53 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/cgru.py
> +        data_loader = self._create_dataloader(train_data)
Еще можно было бы добавить для улучшения обучения динамическое изменение learning_rate от валидационных данных [lr_scheduler](https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate)

2023-02-06 10:53 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/cgru.py
> +        self.hidden_cell = torch.zeros(1, batch_size, self.hidden_size).to(device)
Вроде если какие-то случайные веса генерировать, то это может быть более профитнее, чем просто от нулей отталкиваться.

2023-02-06 10:53 UTC, aPovidlo commented on examples/simple/time_series_forecasting/cgru.py
> +    horizon = 2
А не слишком ли малый горизонт?

2023-02-06 18:55 UTC, valer1435 commented on examples/simple/time_series_forecasting/cgru.py
> +    horizon = 2
На маленьком горизонте он побеждает ридж

2023-02-07 10:31 UTC, valer1435 commented on examples/simple/time_series_forecasting/api_forecasting.py
> +    #time_series['value'] = (time_series['value'] - np.mean(time_series['value'])) / np.std(time_series['value'])
[Убрал](https://github.com/aimclub/FEDOT/pull/1029/commits/9d1430cf2a504fbb4c0073c722892ceba4dde8dd#diff-61d9c62b97ba3e153b9fb93d8340113be9aeebf42be709a8b91dc56fa2c04ab9R22-R23)

2023-02-07 10:31 UTC, valer1435 commented on fedot/core/pipelines/verification_rules.py
> +        print('cgru')
[Нет](https://github.com/aimclub/FEDOT/pull/1029/commits/9d1430cf2a504fbb4c0073c722892ceba4dde8dd#diff-626f6b72c51c57024482629cd3ec367c301efd52b2e8883b75c2c6ce394c74eaR107-R108)

2023-02-07 10:32 UTC, valer1435 commented on examples/simple/time_series_forecasting/ts_pipelines.py
>                      'optimizer': 'adam', 'loss': 'mse'}
[Убрал](https://github.com/aimclub/FEDOT/pull/1029/commits/9d1430cf2a504fbb4c0073c722892ceba4dde8dd#diff-98ab2e857d2a8be66f8beb3439f8604a919d6128b9122f2804ca1528ece87954R13-R16)

2023-02-07 10:33 UTC, valer1435 commented on test/unit/tasks/test_forecasting.py
>      predicted = pipeline.predict(test_data).predict[0]
Действительно, долго. 6-7 секунд на 2 теста. Раньше посчитали как-то не критичным. Убрал в [интеграционные](https://github.com/aimclub/FEDOT/pull/1029/commits/9d1430cf2a504fbb4c0073c722892ceba4dde8dd#diff-341077bd875805ca4266bfae2598d75c35ee5f0260ba3e473aef318e29818b16R7)

2023-02-07 10:33 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/cgru.py
> +            'adam': torch.optim.AdamW(self.model.parameters(), lr=self.learning_rate),
[Поменял](https://github.com/aimclub/FEDOT/pull/1029/commits/9d1430cf2a504fbb4c0073c722892ceba4dde8dd#diff-2e757189efed106001507ee9fb93df8a34d81ecec4728aaddf402c28b5c44ea7R166)

2023-02-07 10:34 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/cgru.py
> +        data_loader = self._create_dataloader(train_data)
Не помогло, даже хуже стало. А подбирать параметры еще и scheduler'a в автомле будет уже слишком.

2023-02-07 10:35 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/cgru.py
> +        self.hidden_cell = torch.zeros(1, batch_size, self.hidden_size).to(device)
Насчет профита не знаю, вроде и нулями норм заполнять. Но в доках торча, в примере они заполняют случайно, да.
[Обновил](https://github.com/aimclub/FEDOT/pull/1029/commits/9d1430cf2a504fbb4c0073c722892ceba4dde8dd#diff-4d20c87c08c249746ab5e12a4b89e271258cc14a133e37fe2125f623e55833a9R183)

2023-02-07 10:35 UTC, valer1435 commented on examples/simple/time_series_forecasting/cgru.py
> +    horizon = 2
[Теперь 12](https://github.com/aimclub/FEDOT/pull/1029/commits/9d1430cf2a504fbb4c0073c722892ceba4dde8dd#diff-98ab2e857d2a8be66f8beb3439f8604a919d6128b9122f2804ca1528ece87954R11). На самом деле не принципиально

2023-02-07 12:38 UTC, aPovidlo approved these changes

2023-02-13 18:56 UTC, nicl-nno approved these changes

2023-02-14 11:37 UTC, staeros approved these changes

2023-02-20 08:59 UTC, merged