1027 remove separation on primary secondary pipeline nodes
aimclub/FEDOT pull request #1031
Opened 2023-01-30 11:59 UTC by maypink

WIP

2023-02-07 19:51 UTC, andreygetmanov requested changes
Прекрасная работа!
Скажи, а как будет вести себя композер с нодами-источниками данных в мультимодальных пайплайнах?

2023-02-07 19:51 UTC, andreygetmanov commented on examples/advanced/gpu_example.py
> +from fedot.core.pipelines.node importPipelineNode
Пробел пропустила

2023-02-07 19:51 UTC, andreygetmanov commented on fedot/core/optimisers/gp_comp/pipeline_composer_requirements.py
> +    :param secondary: operation types for :class:`~fedot.core.pipelines.node.SecondaryNode`
Вместо SecondaryNode должен быть PipelineNode?

2023-02-07 19:51 UTC, andreygetmanov commented on fedot/core/pipelines/node.py
> +class PipelineNode(Node):
Сюда докстринг разве не нужен?

2023-02-07 19:51 UTC, andreygetmanov commented on fedot/core/pipelines/node.py
> +SecondaryNode = PipelineNode
Не совсем понимаю, зачем это здесь. Мб забыла убрать?

2023-02-07 19:51 UTC, andreygetmanov commented on fedot/preprocessing/structure.py
> +    all possible paths from primary Node (or primary Nodes) to root node. If at least
Мне кажется, если мы отказываемся от класса PrimaryNode, лучше указывать маленькими `primary node`

2023-02-07 19:51 UTC, andreygetmanov commented on test/unit/pipelines/test_pipeline_verification.py
> -def test_pipeline_without_primary_nodes_raise_exception():
Мне кажется, подобный тест будет актуален для мультимодальных пайплайнов, т.к. там есть смысл в primary node: через неё подаются данные в пайплайн (нода `data_source_table` и т.п.)
Мб его чуточку поменять?

2023-02-08 12:01 UTC, ChrisLisbon requested changes

2023-02-08 12:01 UTC, ChrisLisbon commented on test/unit/pipelines/test_pipeline_verification.py
> -def test_pipeline_without_primary_nodes_raise_exception():
Поменять определенно стоит, потому что для обычных пайплайнов отсутствие primary ноды тоже не норма, а этот тест это покрывал

2023-02-08 13:48 UTC, nicl-nno commented on test/unit/pipelines/test_pipeline_verification.py
> -def test_pipeline_without_primary_nodes_raise_exception():
Так вроде с новым подходом вроде вообще нет такой ситуации, как "отсутствие primary ноды". Можно только проверять, что конкретно находится в начальных PipelineNode

2023-02-08 13:49 UTC, nicl-nno commented on fedot/preprocessing/structure.py
> +    all possible paths from primary Node (or primary Nodes) to root node. If at least
Или "primary PipelineNode".

2023-02-08 14:29 UTC, maypink commented on test/unit/pipelines/test_pipeline_verification.py
> -def test_pipeline_without_primary_nodes_raise_exception():
кажется, что теперь отсутствие primary `PipelineNode` означает, что в пайплайне есть цикл, а это проверяется тестом ниже. убранный тест же покрывал именно проверку типов, а не по факту наличие/отсутствие чего-либо в `nodes_from`

2023-02-09 13:15 UTC, ChrisLisbon commented on test/unit/pipelines/test_pipeline_verification.py
> -def test_pipeline_without_primary_nodes_raise_exception():
Имела в виду наличие is_primary хотя бы в одной ноде, но как хотите

2023-02-09 13:45 UTC, maypink commented on fedot/core/pipelines/node.py
> +SecondaryNode = PipelineNode
это оставлено для обратной совместимости. в `data_preprocessor.pkl` файле сохранялись пути до `PrimaryNode` и `SecondaryNode`, так что теперь без этих строк старые пайплайны не подгрузятся. 
говоря про волшебный скрипт, чтобы пайплайны старого образца стали нового: pickle файлы напрямую изменить сложновасто ввиду того, что там все в байтах. у меня есть другая идея, как это можно сделать, но пока что без особого успеха. так что предлагаю этот пр влить с этими строками + сделать ишую об этом

2023-02-09 13:45 UTC, maypink commented on fedot/core/pipelines/node.py
> +SecondaryNode = PipelineNode
[ответ на такой же вопрос](https://github.com/aimclub/FEDOT/pull/1031#discussion_r1101481394)

2023-02-09 13:52 UTC, maypink commented on examples/advanced/gpu_example.py
> +from fedot.core.pipelines.node importPipelineNode
[done](https://github.com/aimclub/FEDOT/pull/1031/files#diff-de39eb7076a579e44b0bf9e4550c5970e7f877e4ea55a1cb250b303ebfa5ef57R9)

2023-02-09 13:53 UTC, maypink commented on fedot/core/optimisers/gp_comp/pipeline_composer_requirements.py
> +    :param secondary: operation types for :class:`~fedot.core.pipelines.node.SecondaryNode`
[done](https://github.com/aimclub/FEDOT/pull/1031/files#diff-cc8aec0af40b7cb1e8d8d6df242a3474802fcb114134e73326c33bb8d1690f3bR19-R20)

2023-02-09 13:53 UTC, maypink commented on fedot/core/pipelines/node.py
> +class PipelineNode(Node):
[done](https://github.com/aimclub/FEDOT/pull/1031/files#diff-f8b54747977d30964212d81746ebb50494c660385b62e2819bb23b83c156f20dR270-R277)

2023-02-09 13:54 UTC, maypink commented on fedot/preprocessing/structure.py
> +    all possible paths from primary Node (or primary Nodes) to root node. If at least
[done](https://github.com/aimclub/FEDOT/pull/1031/files#diff-15473f6ab00d30550c93d83bbbe620118b8d11c09bd0ffa5510c6804f8750796R15)

2023-02-09 13:58 UTC, nicl-nno commented on fedot/core/pipelines/node.py
> +SecondaryNode = PipelineNode
Стоит тогда в комменарии к этим строкам пояснить, зачем это и что это obsolete.
Как инструмент обратной совместимости вполне норм.

2023-02-09 14:35 UTC, maypink commented on fedot/core/pipelines/node.py
> +SecondaryNode = PipelineNode
[оки, done](https://github.com/aimclub/FEDOT/pull/1031/commits/48e4bcd7eb997b7b248d512ea5f91a0daf681024)

2023-02-10 03:29 UTC, gkirgizov commented on fedot/core/pipelines/node.py
> +class PipelineNode(Node):
Подумал я, а как теперь отличаются Node и PipelineNode, как между ними разделены обязанности?

2023-02-10 03:31 UTC, gkirgizov commented on fedot/core/pipelines/node.py
> +class PipelineNode(Node):
Подумал я, а как теперь отличаются Node и PipelineNode, как между ними разделены обязанности?

2023-02-13 16:55 UTC, maypink commented on fedot/core/pipelines/node.py
> +class PipelineNode(Node):
ага, и правда нелогичное деление, показалось, что в `Node` будет черновик, а в `PipelineNode` чистовик, так сказать. [done](https://github.com/aimclub/FEDOT/pull/1031/commits/5d1f44599fb90651ca121c1c781fefd136b496be)

2023-02-13 19:23 UTC, andreygetmanov approved these changes

2023-02-14 05:20 UTC, gkirgizov approved these changes

2023-02-14 05:21 UTC, gkirgizov commented on fedot/core/pipelines/node.py
> +class PipelineNode(Node):
меньше сущностей -- счастливее Оккам

2023-02-15 10:13 UTC, ChrisLisbon approved these changes

2023-02-16 08:00 UTC, merged