Refactorштп of ApiParams and ApiMetrics
aimclub/FEDOT pull request #1041
Opened 2023-02-09 08:21 UTC by YamLyubov

WIP

2023-03-03 04:52 UTC, gkirgizov requested changes

2023-03-03 04:52 UTC, gkirgizov commented on test/unit/api/test_api_params.py
> +default_int_value = 2
Что такое `default_int_value`, чем оно обосновано? Какая связь между разными параметрами, так, что они обязательно одно значение имеют?

2023-03-03 04:52 UTC, gkirgizov commented on test/unit/api/test_api_params.py
> +                         'keep_history', 'history_dir', 'cv_folds', 'validation_blocks']
Напрягает то, что список этих ключей повторяется минимум трижды. Здесь, выше в словарие в качестве ключей, и в поле COMPOSER_REQUIREMENTS_KEYS. Можно где-то в одном месте эти ключи прописать? Это сильно упростит изменения в API

2023-03-03 04:52 UTC, gkirgizov commented on test/unit/api/test_api_params.py
> +correct_gp_algorithm_keys = ['mutation_types', 'genetic_scheme_type', 'pop_size']
Тот же коммент выше -- повтор

2023-03-03 04:52 UTC, gkirgizov commented on test/unit/api/test_api_params.py
> +                         'keep_history', 'history_dir', 'cv_folds', 'validation_blocks']
Увидел, что это тесты. В любом случае, тесты очень быстро отстанут от реальности, легко забыть их поправить.

2023-03-03 08:30 UTC, YamLyubov commented on test/unit/api/test_api_params.py
> +default_int_value = 2
default_int_value не имеет какого-то обоснованного значения. Смысл в том, чтобы заполнить все возможные значения, которые можно передать через Api. Параметры не должны быть одинаковыми. Можно заполнить их разными, более осмысленными числами, так наверное будет более понятно

2023-03-03 09:34 UTC, YamLyubov commented on test/unit/api/test_api_params.py
> +default_int_value = 2
[Убрала ](https://github.com/aimclub/FEDOT/pull/1041/files#diff-45cf3b8c5bd3644b4a5de95d9bcc12f254a6dc387523dc6498b7d3e9091c3c89R17-R20) ```default_int_value```.

2023-03-03 09:35 UTC, YamLyubov commented on test/unit/api/test_api_params.py
> +                         'keep_history', 'history_dir', 'cv_folds', 'validation_blocks']
[Убрала немного повторов](https://github.com/aimclub/FEDOT/pull/1041/files#diff-45cf3b8c5bd3644b4a5de95d9bcc12f254a6dc387523dc6498b7d3e9091c3c89R58-R60). Смысл теста как раз в том, что возвращаются корректные атрибуты этих классов.

2023-03-03 12:42 UTC, gkirgizov commented on test/unit/api/test_api_params.py
> +                         'keep_history', 'history_dir', 'cv_folds', 'validation_blocks']
Понял, тогда звучит вполне приемлемо

2023-03-06 08:53 UTC, maypink approved these changes

2023-03-06 14:15 UTC, YamLyubov commented on fedot/api/api_utils/api_params_repository.py
> +                    params[k] = v
Можешь, пожалуйста, расписать как ты это видишь, а то не могу разобраться?)

2023-03-06 14:30 UTC, IIaKyJIuH commented on fedot/api/api_utils/api_params_repository.py
> +                    params[k] = v
Да, без проблем, я ошибся вообще говоря, не исключающее или, а обычное вычитание множеств)

```
for k in self.default_params.keys() - params.keys():
    if (v := self.default_params[k]) is not None:
        params[k] = v
```

2023-03-06 15:36 UTC, YamLyubov commented on examples/simple/regression/api_regression.py
> +    composer_params = {'history_dir': 'custom_history_folder', 'preset': 'auto'}
В api поменяла cache_folder на cache_dir

2023-03-06 15:37 UTC, YamLyubov commented on fedot/api/api_utils/api_params_repository.py
> +        invalid_keys = set(params.keys()) - allowed_keys
[Изменила](https://github.com/aimclub/FEDOT/pull/1041/files#diff-756a39d6d95b402e1270d3e661dd270202f55c238132e05efd915cf2062a0202R79-R80)

2023-03-06 15:37 UTC, YamLyubov commented on fedot/api/api_utils/api_params_repository.py
> +                    params[k] = v
[Изменила](https://github.com/aimclub/FEDOT/pull/1041/files#diff-756a39d6d95b402e1270d3e661dd270202f55c238132e05efd915cf2062a0202R85-R88)

2023-03-06 15:38 UTC, YamLyubov commented on fedot/api/api_utils/api_params_repository.py
> +                                        if k in ApiParamsRepository.COMPOSER_REQUIREMENTS_KEYS}
[Тут](https://github.com/aimclub/FEDOT/pull/1041/files#diff-756a39d6d95b402e1270d3e661dd270202f55c238132e05efd915cf2062a0202R94-R95) и [тут](https://github.com/aimclub/FEDOT/pull/1041/files#diff-756a39d6d95b402e1270d3e661dd270202f55c238132e05efd915cf2062a0202R108-R110) поменяла

2023-03-06 15:39 UTC, YamLyubov commented on fedot/api/api_utils/api_composer.py
>              .build()
Согласна, поменяла в основных файлах, которые в этом pr затрагивались

2023-03-06 15:40 UTC, YamLyubov commented on fedot/api/api_utils/api_params_repository.py
> +    STATIC_INDIVIDUAL_METADATA_KEYS = ['use_input_preprocessing']
[Готово](https://github.com/aimclub/FEDOT/pull/1041/files?diff=unified&w=0#diff-756a39d6d95b402e1270d3e661dd270202f55c238132e05efd915cf2062a0202R19-R25)

2023-03-06 15:40 UTC, YamLyubov commented on fedot/api/api_utils/metrics.py
> +            if isinstance(specific_metric, str) or isinstance(specific_metric, Callable):
[Готово](https://github.com/aimclub/FEDOT/pull/1041/files?diff=unified&w=0#diff-fa6bac620e570ee78b5f7df93b972d710f8f742fad71f1f970d36c0c7eabbbd7R63)

2023-03-06 15:41 UTC, YamLyubov commented on fedot/api/api_utils/params.py
> +            del self._parameters['available_operations']
[Готово](https://github.com/aimclub/FEDOT/pull/1041/files?diff=unified&w=0#diff-35c9039b23102036436d1536f49036a1cdfa7214c697fbd184e84071246dead8R77)

2023-03-06 15:42 UTC, YamLyubov commented on fedot/api/api_utils/params.py
> +            if requirements else None
Теперь [так](https://github.com/aimclub/FEDOT/pull/1041/files?diff=unified&w=0#diff-35c9039b23102036436d1536f49036a1cdfa7214c697fbd184e84071246dead8R151-R152)

2023-03-06 15:44 UTC, YamLyubov commented on fedot/api/api_utils/params.py
> +        return self._parameters
Да, дествительно [унаследовала](https://github.com/aimclub/FEDOT/pull/1041/files?diff=unified&w=0#diff-35c9039b23102036436d1536f49036a1cdfa7214c697fbd184e84071246dead8R25) от UserDict и удалила методы

2023-03-06 15:45 UTC, YamLyubov commented on test/unit/api/test_main_api.py
> +    assert all(value > 0 for value in list(metric.values()))
[Не обязательно)](https://github.com/aimclub/FEDOT/pull/1041/files?diff=unified&w=0#diff-3024e99987ea3223b4f92729b426eabaf4b75077e6d3c3a550fde20d3a4e23fbR166)

2023-03-06 15:45 UTC, YamLyubov commented on test/unit/api/test_api_params.py
> +        assert k in default_params
[Исправила](https://github.com/aimclub/FEDOT/pull/1041/files?diff=unified&w=0#diff-45cf3b8c5bd3644b4a5de95d9bcc12f254a6dc387523dc6498b7d3e9091c3c89R74)

2023-03-06 15:46 UTC, YamLyubov commented on test/unit/api/test_api_params.py
> +    assert all(key in correct_keys for key in output_params.keys())
[Тоже исправила ](https://github.com/aimclub/FEDOT/pull/1041/files?diff=unified&w=0#diff-45cf3b8c5bd3644b4a5de95d9bcc12f254a6dc387523dc6498b7d3e9091c3c89R94)

2023-03-06 15:47 UTC, YamLyubov commented on test/unit/api/test_api_params.py
> +    assert not any(key in correct_keys and key not in output_params.keys() for key in input_params)
Получилось даже еще [упростить](https://github.com/aimclub/FEDOT/pull/1041/files?diff=unified&w=0#diff-45cf3b8c5bd3644b4a5de95d9bcc12f254a6dc387523dc6498b7d3e9091c3c89R95-R96)

2023-03-06 16:38 UTC, IIaKyJIuH commented on fedot/api/api_utils/params.py
> +            if requirements else None
Супер!

2023-03-06 16:44 UTC, IIaKyJIuH commented on fedot/api/api_utils/params.py
> +        return self._parameters
Молодец, отлично разобралась в этом! Круто выглядит

2023-03-06 16:45 UTC, IIaKyJIuH commented on test/unit/api/test_main_api.py
> +    assert all(value > 0 for value in list(metric.values()))
Можешь [тут ещё также сделать](https://github.com/aimclub/FEDOT/pull/1041/files?diff=unified&w=0#diff-33b3da5de920cc340bbc6820f766f3d73a87d0545f26ca587bd630cd5cc8a8d3R44), плз))

2023-03-06 18:51 UTC, IIaKyJIuH commented on test/unit/api/test_api_params.py
> +    assert not any(key in correct_keys and key not in output_params.keys() for key in input_params)
Гениально, кст
Но с другой стороны я думал долго и мысли назрели вот, а эта проверка не аналогична ли проверке выше?

То есть выше убеждались, что все ключи `output_params` "корректные"
Тут же убеждаемся, что все "корректные" ключи `input_params` находятся и в `output_params`, но потенциально это может быть проверка на то, что все "корректные" ключи находятся в `output_params`, правильно понял?

2023-03-07 06:31 UTC, IIaKyJIuH commented on fedot/api/api_utils/api_composer.py
>              .build()
Замени ещё [тут](https://github.com/aimclub/FEDOT/pull/1041/files?diff=unified&w=0#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR259-R267) тогда, плиз

2023-03-07 06:57 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
>              .build()
@IIaKyJIuH в целом предложение хорошее - а можно это мониторить (или даже править) с помощью линтера (текущего или какого-то иного)?

2023-03-07 07:13 UTC, IIaKyJIuH commented on fedot/api/api_utils/api_composer.py
>              .build()
@nicl-nno 

Кажется, можно установить [плагин для текущего линтера](https://github.com/wemake-services/flake8-broken-line), но я ещё не проверял.

Преттиров на такое не находил ещё

2023-03-07 11:33 UTC, YamLyubov commented on fedot/api/api_utils/api_params_repository.py
> +                                        if k in ApiParamsRepository.COMPOSER_REQUIREMENTS_KEYS}
Подумала-подумала и откатила обратно, все-таки до этого читаемость была лучше

2023-03-07 11:34 UTC, YamLyubov commented on fedot/api/api_utils/api_composer.py
>              .build()
[Готово](https://github.com/aimclub/FEDOT/pull/1041/files#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR259-R267)

2023-03-07 11:35 UTC, YamLyubov commented on test/unit/api/test_main_api.py
> +    assert all(value > 0 for value in list(metric.values()))
[Готово](https://github.com/aimclub/FEDOT/pull/1041/files#diff-33b3da5de920cc340bbc6820f766f3d73a87d0545f26ca587bd630cd5cc8a8d3R44)

2023-03-07 11:39 UTC, IIaKyJIuH commented on fedot/api/api_utils/api_params_repository.py
> +                                        if k in ApiParamsRepository.COMPOSER_REQUIREMENTS_KEYS}
Вообще согласен, не тот случай, получается

2023-03-07 11:41 UTC, IIaKyJIuH commented on fedot/api/api_utils/api_composer.py
>              .build()
Топич!

2023-03-07 11:46 UTC, YamLyubov commented on test/unit/api/test_api_params.py
> +    assert not any(key in correct_keys and key not in output_params.keys() for key in input_params)
```outpu_params``` необязательно содержит все корректные ключи. Смысл в том, что все корректные ключи из ```input_params``` переносятся в ```output_params```. Однако, ```output_params``` могут содержать ключи, котjрых изначально не было в ```input_params```

2023-03-07 11:52 UTC, IIaKyJIuH commented on test/unit/api/test_api_params.py
> +    assert not any(key in correct_keys and key not in output_params.keys() for key in input_params)
Хорошо

2023-03-07 11:52 UTC, IIaKyJIuH approved these changes

2023-03-07 12:10 UTC, merged