confidence intervals added
aimclub/FEDOT pull request #1063
Opened 2023-03-07 14:13 UTC by GrigoriJasnovidov

ConfidenceIntervals class for predicting confidence intervals is created. 
The instance of ConfidenceInterval class takes pipelines from the last generation, fit these pipelines in order to minimize quantile_loss metric and creates confidence intervals in this way. 

ConfidenceIntervals(model, train_input)
Arguments: 
        model  - a fitted fedot model for ts_forecasting. 
        train_input – a train input used for building the model.
Methods: 
        .fit(up_quantile, low_quantile,horizon=None,low_tuner=None,up_tuner=None,number_models=10,pipelines_show = 
          True)
       This method outputs several confidence intervals allowing us to build a final confidence interval using method forecast.
        Arguments:
                     up_quantile/low_quantile – quantiles for upper/low confidence intervals. 
                      horizon – length of time horizon for predicting confidence intervals. If None then it is the same as in                           
                                    model.task.params; if natural number this number of steps is used for forecasting.
                      number_models – number models used for forecasting confidence intervals. Can be natural number or ‘max’, in 
                                   this case all avaliable models used. If number_models > number of avaliable models then all avaliable 
                                  models used.
       		     pipelines_show – boolean parameters whether to show pipelines during fitting.  
   .forecast(regim = ‘quantile’) forecasts confidence intervals given ConfidenceIntervals fitted. Possible values of regime:
		‘quantile’,’median’, etc. In each regime intervals obtained after fitting are used to build confidence intervals 
   .plot() plot the confidence intervals, forecast and (if given) actual test time series

2023-03-07 19:38 UTC, nicl-nno commented
Прежде чем буду содержательно смотреть:

1. Убрать лишние файлы
2. Пояснить как собственно это все использовать - где точка входа.

Добавить к одному из имеющихся примеров прогнозирования Fedot-ом интервальную оценку.

2023-03-15 18:12 UTC, nicl-nno commented on fedot/confidence_intervals/utils.py
> +    for i in range(l):
Такого рода циклы тут и ниже выглядят очень ресурсоемко. Нельзя ли их векторизовать?

2023-03-15 18:13 UTC, nicl-nno commented on fedot/confidence_intervals/main.py
> +        for ind in self.model.history.individuals[-2]:
Завязка на [-2] выглядит сложно понимаемо.

2023-03-15 18:16 UTC, nicl-nno commented on fedot/confidence_intervals/tuners.py
> +    return {'low_tuner':low_tuner, 'up_tuner':up_tuner}
Для практических задач захардкоженное ограничение по времени выглядит малоприменимо.

2023-03-15 18:17 UTC, nicl-nno commented on fedot/confidence_intervals/main.py
> +                        preds = self.model.forecast(horizon=horizon)
Точно ли это условие нужно? По умолчанию horizon вероятно и есть None

2023-03-15 18:17 UTC, nicl-nno commented on fedot/confidence_intervals/main.py
> +            print('Error! Confidence intervals are not computed!')
Вместо всех print-ов лучше использовать logger.

2023-03-15 18:19 UTC, nicl-nno commented on fedot/confidence_intervals/main.py
> +            low_res = truncated_mean_array(arrays = self.low_predictions)
В большинстве вариантов меняется только функция, нет смысла дублировать код. Да и up и low можно возвращать за раз, сделав функции более специализированными.

2023-03-15 18:19 UTC, nicl-nno commented on fedot/confidence_intervals/visualization.py
> +def plot_confidence_intervals(horizon,
Кажется, лучше вынести это в стандартный визуализатор?

2023-03-15 18:20 UTC, nicl-nno commented on fedot/confidence_intervals/main.py
> +                    tuned_pipeline = low_tuner.tune(pipeline)
Это конечно выглядит очень ресурсоемко.

Не пробовал ту схему, которую мы обсуждали - когда разнообразие создается за счет мутации финального пайплайна?

2023-03-15 18:23 UTC, nicl-nno commented on fedot/confidence_intervals/main.py
> +    def fit(self, up_quantile,low_quantile, horizon = None,
Этот метод явно слишком сложный, его нужно разбить на несколько.

2023-03-15 18:27 UTC, nicl-nno commented on fedot/confidence_intervals/main.py
> +        return {'up_predictions':up_predictions, 'low_predictions':low_predictions}
Может лучше возвращать экземпляр класса, унаследованного от OutputData?

2023-03-15 18:27 UTC, nicl-nno commented
1) По примерам - с самом FEDOT-е такое количество ноутбуков не нужно, добавь хватит одного примера в формате .py. 
На каком-то наиболее показательном датасете.

2) Нужен хотя бы базовый unit-тест, показывающий что всё  это работает.

3) Много отступлений от PEP8 - проверь плз.

2023-03-15 18:28 UTC, nicl-nno commented on fedot/confidence_intervals/main.py
> +                    self.model.current_pipeline.show()
Видимо это можно убрать?

2023-03-15 18:29 UTC, nicl-nno commented on fedot/confidence_intervals/main.py
> +                        pipeline.show()
Не уверен что это особо нужно. Лучше в детальный лог выводить.

2023-03-15 18:31 UTC, nicl-nno commented on fedot/confidence_intervals/metrics.py
> +def quantile_loss(y_true, y_pred, quantile=0.5):
А в ходе непосредственно оптимизации структуры модели этот loss не пригодится?

2023-03-15 18:33 UTC, nicl-nno commented on fedot/confidence_intervals/metrics.py
> +    lv = len(values)
Названия лучше более читаемыми делать, тут и далее.

2023-03-15 18:35 UTC, nicl-nno commented on fedot/confidence_intervals/utils.py
> +    return median
Кажется этот код различается одним вызовом функции. Да и у остальных разница минимальная.

2023-03-15 18:38 UTC, nicl-nno commented on fedot/confidence_intervals/main.py
> +            if pipeline not in pipeline_dicts:
Если это способ проверить, был ли уже в точности такой пайплайн - то выглядит не очень изящно. Можно просто сравнить descriptive_id, а если хочется проигнорировать гиперпараметры - то graph_description.

2023-03-15 18:39 UTC, nicl-nno commented on fedot/confidence_intervals/tuners.py
> +            return value
Если есть модуль metrics - то можно их туда и отправить.

2023-03-15 18:41 UTC, nicl-nno commented on fedot/confidence_intervals/main.py
> +class ConfidenceIntervals:
Логика класса в целом понятна, но нужно его доработать, причем больше в сторону упрощения. Сейчас он делает очень много всего за раз.

При этом класс жестко реализует только один способ построение интервалов - хотя явно нужна вариативность, чтобы реализовать и другие методы.

Cтруктурно класс и другие связанные с ним стоит положить в fedot/fedot/core/pipelines/ts/confidence_interval, например - не в корень FEDOT-а.

2023-03-16 21:51 UTC, nicl-nno commented on fedot/confidence_intervals/metrics.py
> +            metrics = np.append(metrics,(quantile-1)*x)
С этим разобрались, но остался вопрос про mean.

2023-04-14 14:34 UTC, nicl-nno commented on fedot/prediction_intervals/logger.py
> +def logger_prediction_intervals():
А это точно нужно? В проекте есть свой логгер.

2023-04-14 14:34 UTC, nicl-nno commented on fedot/prediction_intervals/main.py
> +        if method == 'best_pipelines_quantiles':
elif?

2023-04-17 14:16 UTC, GrigoriJasnovidov commented on fedot/confidence_intervals/utils.py
> +    for i in range(l):
Сделано

2023-04-17 14:16 UTC, GrigoriJasnovidov commented on fedot/confidence_intervals/main.py
> +        for ind in self.model.history.individuals[-2]:
добавлен комментарий, что это последнее поколение

2023-04-17 14:17 UTC, GrigoriJasnovidov commented on fedot/confidence_intervals/tuners.py
> +    return {'low_tuner':low_tuner, 'up_tuner':up_tuner}
ограничение по времени теперь можно установить напрямую

2023-04-17 14:17 UTC, GrigoriJasnovidov commented on fedot/confidence_intervals/main.py
> +                        preds = self.model.forecast(horizon=horizon)
Условие ненужно, я удалил лишнее

2023-04-17 14:18 UTC, GrigoriJasnovidov commented on fedot/confidence_intervals/main.py
> +            low_res = truncated_mean_array(arrays = self.low_predictions)
сделано

2023-04-17 14:18 UTC, GrigoriJasnovidov commented on fedot/confidence_intervals/main.py
> +            print('Error! Confidence intervals are not computed!')
Я добавил логгер.

2023-04-17 14:20 UTC, GrigoriJasnovidov commented on fedot/confidence_intervals/main.py
> +                    self.model.current_pipeline.show()
Я убрал лишнее

2023-04-17 14:21 UTC, GrigoriJasnovidov commented on fedot/confidence_intervals/main.py
> +                    self.model.current_pipeline = tuned_pipeline
Я теперь работаю только с копией модели. Это стало ненужно, я убрал.

2023-04-17 14:21 UTC, GrigoriJasnovidov commented on fedot/confidence_intervals/main.py
> +                    pipeline = PipelineAdapter().restore(ind.graph)
я убрал лишнее

2023-04-17 14:32 UTC, GrigoriJasnovidov commented on fedot/prediction_intervals/main.py
> +        if method == 'best_pipelines_quantiles':
в будущем планируются еще методы, в итоге будет if +elif+elif + else.

2023-04-17 16:40 UTC, nicl-nno commented on fedot/prediction_intervals/main.py
> +        if method == 'best_pipelines_quantiles':
Ну проверка-то в любом случае взаимоисключающая.

2023-05-09 07:49 UTC, valer1435 requested changes
Сильно не хватает Docstring и TypeHint

2023-05-09 07:49 UTC, valer1435 commented on fedot/prediction_intervals/main.py
> +    def fit(self,
Думаю, что стоит перенести передачу данных в метод fit, тк это больше подходит под интерфейс sklearn и fedot.

2023-05-09 07:49 UTC, valer1435 commented on fedot/prediction_intervals/main.py
> +            self.method = 'last_generation_ql'
А все параметры передавать в `__init__`

2023-05-09 07:49 UTC, valer1435 commented on fedot/prediction_intervals/main.py
> +        self.is_fitted = True
Предполагается, что в этот класс модель должна прийти необученной? В таком случае можно было бы обойтись self.model.current_pipeline.is_fitted()

Кстати, почему сюда прокидывается именно объект API? По-идее мы же можем прокинуть просто пайплайн

2023-05-09 07:49 UTC, valer1435 commented on fedot/prediction_intervals/main.py
> +            if regime == 'quantile':
Напрашивается подобие case в виде словаря, например: {'quantile': ('quantile_up', 'quantile_low')}

2023-05-09 07:49 UTC, valer1435 commented on fedot/prediction_intervals/metrics.py
> +    res = np.array(y_true) - np.array(y_pred)
Мы вроде внутри никогда не работаем с листами, поэтому дополнительное преобразование в array можно убрать

2023-05-12 12:45 UTC, GrigoriJasnovidov commented on fedot/prediction_intervals/main.py
> +    def fit(self,
да, хорошая идея

2023-05-12 12:47 UTC, GrigoriJasnovidov commented on fedot/prediction_intervals/metrics.py
> +    res = np.array(y_true) - np.array(y_pred)
окей

2023-06-13 13:13 UTC, GrigoriJasnovidov commented on fedot/prediction_intervals/metrics.py
> +    res = np.array(y_true) - np.array(y_pred)
сделано

2023-06-13 13:13 UTC, GrigoriJasnovidov commented on fedot/prediction_intervals/main.py
> +            self.method = 'last_generation_ql'
сделано

2023-06-13 13:14 UTC, GrigoriJasnovidov commented on fedot/prediction_intervals/main.py
> +    def fit(self,
сделано, теперь в fit подается только train_input

2023-06-13 13:16 UTC, GrigoriJasnovidov commented on fedot/prediction_intervals/logger.py
> +def logger_prediction_intervals():
теперь везде используется дефолтный логгер

2023-06-14 10:13 UTC, valer1435 requested changes
Нужно обновить примеры под новый интерфейс + стоит добавить пример в .py формате, по аналогии с api_forecasting, например

2023-06-14 10:13 UTC, valer1435 commented on fedot/prediction_intervals/main.py
> +           model: a fitted Fedot model for times series forecasting task
Тут мне кажется уместней будет написать что-то вроде Fedot class object, чтобы избежать недопонимания

2023-06-14 10:13 UTC, valer1435 commented on fedot/prediction_intervals/main.py
> +            self.all_predictions = solver_mutation_of_best_pipeline(
Поместив солверы в класс, можно избежать постоянной передачи аргументов в стиле model=self.model

2023-06-14 10:13 UTC, valer1435 commented on fedot/prediction_intervals/main.py
> +            regime_up = {'quantile': 'quantile_up', 'mean': 'mean', 'median': 'median', 'absolute_bounds': 'max'}
Это следует занести в поля класса

2023-06-14 10:17 UTC, valer1435 commented
Еще по поводу ноутбуков: я не то, чтобы с интервалами много работал, но то, что я видел, обычно визуализируется заливкой в плотлибе. Делается это не очень просто (когда-то сам делал), но так понятнее, чем смотреть на n графиков, которые сливаются в единое целое. Тот вариант, что сейчас точно нужно оставить, но вариант с заливкой кмк приятнее глазу и не нагружает (пример ниже).
![image](https://github.com/aimclub/FEDOT/assets/32017472/5b8c5d66-cc47-4d61-80d5-38e9a303d549)

![image](https://github.com/aimclub/FEDOT/assets/32017472/dafca18a-4945-46bb-bd3f-5d1f5f8e8a6b)
И еще в ноутбуках очень много как будто лишнего вывода (нужно долго скроллить)

2023-06-15 10:51 UTC, nicl-nno commented
Перед вливанием ветки причесанные ноутбуки можно будет перенести сюда как один из примеров: https://github.com/ITMO-NSS-team/fedot-examples

2023-06-15 13:45 UTC, GrigoriJasnovidov commented on fedot/prediction_intervals/main.py
> +           model: a fitted Fedot model for times series forecasting task
сделано

2023-06-15 13:45 UTC, GrigoriJasnovidov commented on fedot/prediction_intervals/main.py
> +            regime_up = {'quantile': 'quantile_up', 'mean': 'mean', 'median': 'median', 'absolute_bounds': 'max'}
сделано

2023-06-22 12:20 UTC, valer1435 requested changes
Пример в .py файле и переработка ноутбуков еще не готовы? Кстати примеры можно перенести в папку examples/simple/ts/confidence_intervals

PS можно делать ссылки на код, где делаешь исправления, например, [так](https://github.com/aimclub/FEDOT/pull/1063/commits/9661dd88c62157d6372ce12a23d362edd1eef18f#diff-d1d9cbd70ea8e57b65027d9982397838d0e627f7ea4005a556ef49135495ee51R69):

2023-06-22 12:20 UTC, valer1435 commented on fedot/prediction_intervals/solvers/solver.py
> +def solver_prediction_intervals(model,
Можно ли это сделать через partial? С первого взгляда выглядит, что да

2023-06-26 04:58 UTC, valer1435 reviewed
Уезжаю на сборы, поменял вердикт, чтобы смог влить

2023-06-26 15:08 UTC, GrigoriJasnovidov commented on fedot/prediction_intervals/solvers/solver.py
> +def solver_prediction_intervals(model,
сделано

2023-06-27 10:32 UTC, GrigoriJasnovidov commented on fedot/prediction_intervals/solvers/solver.py
> +def solver_prediction_intervals(model,
добавил примеры

2023-06-30 15:45 UTC, nicl-nno commented on test/unit/pipelines/prediction_intervals/test_solver_mutations.py
> +                                     keep_percentage=0.8), " solver_mutation_of_best_pipeline with replacement failed"
Такие однотипные тесты можно через xixture унифицировать. 

Правда не очень понятно, что конкретно они тестируют. Просто сам факт что функция solver_mutation_of_best_pipeline отработала успешно?

2023-06-30 16:00 UTC, nicl-nno commented on fedot/core/pipelines/prediction_intervals/pipeline_api.py
> +class PredictionIntervalsPipeline:
А в PredictionIntervalsPipeline нужно уточнение про Pipeline? А ты выглядит как будто это разновидность пайплайна, хотя это не так.

2023-06-30 16:02 UTC, nicl-nno commented on fedot/core/pipelines/prediction_intervals/solvers/last_generation_quantile_loss.py
> +"""
Лучше докстринги к функциям дать в google-нотации (cм пункт 5 тут [Google-Style](https://aimclub.github.io/open-source-ops/tutorials/documentation.html))

2023-06-30 16:04 UTC, nicl-nno commented on fedot/core/pipelines/prediction_intervals/solvers/solver.py
> +def solver_prediction_intervals(model,
Везде стоит расставить type-hint. Ну и конечно такое большое количество параметров у функции - плохой признак. Может часть из них обернуть в датакласс?

2023-06-30 16:05 UTC, nicl-nno commented on fedot/core/pipelines/prediction_intervals/utils.py
> +        return (pickle.load(f))
А зачем это нужно? Как минимум возможно ошибка с правами записи. Да и выглядит как замена deepcopy.

2023-06-30 16:06 UTC, nicl-nno commented on fedot/core/pipelines/prediction_intervals/utils.py
> +# compute maximal jumps of a ts
А кто такие jumps? Выходы за пределы интервала?

2023-06-30 16:08 UTC, nicl-nno commented on fedot/core/pipelines/prediction_intervals/pipeline_api.py
> +        pass
А этим методы нужны?

2023-07-03 10:38 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/pipeline_api.py
> +class PredictionIntervalsPipeline:
pipeline_api.py это неготовый файл. Его идея в том, что для подхода с мутациями нам достаточно только иметь какой-нибудь пайплайн. В будущем класс PredictionIntervalsPipeline будет инизиализироваться пайплайном и параметрами для мутаций.

2023-07-03 10:41 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/utils.py
> +        return (pickle.load(f))
если я не ошибаюсь, deepcopy не работает с объектом Fedot. Я копирую объект, так как он может немного изменится в процессе построения предсказательных интервалов.
Можно сделать режим в котором модель не копируется чтобы избежать таких проблем.

2023-07-03 10:45 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/utils.py
> +# compute maximal jumps of a ts
jumps - это максимальные скачки временного ряда вверх и вниз за один шаг. Они нужны для того, чтобы отсеивать заведомо плохие мутации по следующему принципу: если первое значение отличается от прогноза более чем на jumps['up'] то мы выкидываем такую мутацию. То же самое с jumps['low']

2023-07-03 10:47 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/pipeline_api.py
> +        pass
пока временно удалю pipeline_api.py из этого репозитория

2023-07-07 14:14 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/utils.py
> +        return (pickle.load(f))
добавил опцию что модель можно не копировать

2023-07-07 15:46 UTC, GrigoriJasnovidov commented on test/unit/pipelines/prediction_intervals/test_solver_mutations.py
> +                                     keep_percentage=0.8), " solver_mutation_of_best_pipeline with replacement failed"
добавил тест который оценивает picp и interval_score для каждого метода на синтетическом ряду.

2023-07-07 15:47 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/solvers/last_generation_quantile_loss.py
> +"""
сделано

2023-07-07 15:49 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/solvers/solver.py
> +def solver_prediction_intervals(model,
упростил это место. Теперь при инициализации PredictionIntervals self.solver напрямую вызывается из вспомогательных файлов.

2023-07-07 16:44 UTC, nicl-nno commented on fedot/core/pipelines/prediction_intervals/utils.py
> +        return (pickle.load(f))
![image](https://github.com/aimclub/FEDOT/assets/5711814/cb8e3360-660a-42a7-9427-fab2742d5f52)

Но вроде она все равно копируется.

2023-07-07 16:45 UTC, nicl-nno commented on test/unit/pipelines/prediction_intervals/test_prediction_intervals.py
> +        model = pickle.load(f)
picle-файлам лучше дать более говорящие название и переместить в папку data.

2023-07-07 16:48 UTC, nicl-nno commented on fedot/core/pipelines/prediction_intervals/solvers/solver.py
> +def solver_prediction_intervals(model,
Ок, но параметры все равно лучше завернуть в датакласс.

![image](https://github.com/aimclub/FEDOT/assets/5711814/b2962480-f081-420e-8a46-283269f216e2)

Как пример такой структуры: https://github.com/aimclub/GOLEM/blob/master/golem/core/optimisers/optimizer.py#L51

2023-07-07 16:50 UTC, nicl-nno commented on test/unit/pipelines/prediction_intervals/test_mutation.py
> +def check_uniqueness(l: list):
Если это просто проверка на уникальность элементов, то можно что-то вроде так:

`len(set(l)) == len(l)`

2023-07-07 16:51 UTC, GrigoriJasnovidov commented on test/unit/pipelines/prediction_intervals/test_mutation.py
> +def check_uniqueness(l: list):
здесь это не работает, так как set нельзя вызвать от списка списков

2023-07-07 16:54 UTC, nicl-nno commented on test/unit/pipelines/prediction_intervals/test_mutation.py
> +        assert type(get_ts_mutation(get_individual)) == type(get_individual), f"mutation {i + 1} of failed"
Не очень понял суть проверки. 

Вроде get_individual - это функция, что должен вернуть type(get_individual)?

2023-07-07 16:58 UTC, GrigoriJasnovidov commented on test/unit/pipelines/prediction_intervals/test_mutation.py
> +        assert type(get_ts_mutation(get_individual)) == type(get_individual), f"mutation {i + 1} of failed"
здесь же вроде get_individual это не функция, а то что она возвращает. По сути, мы проверяем что мутация случилась, то есть получился объект класса Individual.

2023-07-07 17:01 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/utils.py
> +        return (pickle.load(f))
Вроде бы в текущей версии это исправлено: https://github.com/GrigoriJasnovidov/FEDOT/blob/master/fedot/core/pipelines/prediction_intervals/main.py

2023-07-10 14:13 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/solvers/solver.py
> +def solver_prediction_intervals(model,
добавил все параметры кроме самых основных в отдельный класс PredictionIntervalsParams

2023-07-14 16:21 UTC, GrigoriJasnovidov commented on test/unit/pipelines/prediction_intervals/test_prediction_intervals.py
> +        model = pickle.load(f)
сделано

2023-07-16 09:17 UTC, nicl-nno commented on test/unit/pipelines/prediction_intervals/test_solver_mutations.py
> +        assert solver_mutation_of_best_pipeline(train_input=params['train_input'],
Все ещё не очень понятно, что тут тестируется (кроме самого факта, что функция отработала).

2023-07-17 14:45 UTC, GrigoriJasnovidov commented on test/unit/pipelines/prediction_intervals/test_solver_mutations.py
> +        assert solver_mutation_of_best_pipeline(train_input=params['train_input'],
Да, здесь тестируется что функция просто отработала. Качество всех методов тестируется здесь: https://github.com/GrigoriJasnovidov/FEDOT/blob/master/test/unit/pipelines/prediction_intervals/test_prediction_intervals.py

2023-08-02 18:20 UTC, GrigoriJasnovidov commented on test/unit/pipelines/prediction_intervals/test_solver_mutations.py
> +        assert solver_mutation_of_best_pipeline(train_input=params['train_input'],
Сделал минимальные проверки на то, что каждый раз мы получаем предсказание нужной длины + проверка на то, что в дефолтном случае худшие пайплайны удаляются.

2023-08-16 09:09 UTC, nicl-nno commented
Замечания позакрывал, осталось синхронизировать с мастером.

2023-08-22 11:48 UTC, nicl-nno commented
Replaced with #1149

2023-08-22 11:48 UTC, closed without merging