1059 timestamp bug
aimclub/FEDOT pull request #1065
Opened 2023-03-13 09:37 UTC by IIaKyJIuH

Comparison of different approaches:
![image](https://user-images.githubusercontent.com/38308131/224662591-ba937643-6482-4b03-8116-0b4b635ca74c.png)

2023-03-13 09:39 UTC, IIaKyJIuH commented
В Numpy-стратегии предполагается, что временной 'unit' - это наносекунды, в моём решении тоже так предполагается, то есть сохраняется поведение.

Вопрос такой: нормально ли вообще использовать такой юнит, или это должны быть хотя бы миллисекунды или просто секунды?

2023-03-13 10:29 UTC, aPovidlo commented on fedot/api/api_utils/data_definition.py
> +        features[datetime_features.columns] = datetime_features.to_numpy().astype(float)  # 'ns' unit always
А почему `float`?

2023-03-13 10:38 UTC, IIaKyJIuH commented on fedot/api/api_utils/data_definition.py
> +        features[datetime_features.columns] = datetime_features.to_numpy().astype(float)  # 'ns' unit always
Может я что-то не учёл, но кажется модели работают именно с числами.
В препроцессинге данных точно происходит каст к числам, так что выглядит логично.

2023-03-13 10:41 UTC, IIaKyJIuH commented on fedot/api/api_utils/data_definition.py
> +        features[datetime_features.columns] = datetime_features.to_numpy().astype(float)  # 'ns' unit always
@MorrisNein Собственно поэтому препроцессинг и не запомнит выбранное преобразование шага, он просто работает с числами, а обычный каст к float преобразует timestamp по наносекундам.

2023-03-13 10:42 UTC, IIaKyJIuH commented on fedot/api/api_utils/data_definition.py
> +        features[datetime_features.columns] = datetime_features.to_numpy().astype(float)  # 'ns' unit always
Таким образом, в этом месте программы можно задавать сразу способ преобразования дат к числам. Можно параметр API для этого ввести, по умолчанию будет также к 'ns' приводить.

2023-03-13 11:00 UTC, aPovidlo commented on fedot/api/api_utils/data_definition.py
> +        features[datetime_features.columns] = datetime_features.to_numpy().astype(float)  # 'ns' unit always
@IIaKyJIuH Думал, что более логичнее было бы преобразовывать время в секунды и далее в `int`.

 А для задачи ts вроде же тоже можно время использовать, а как там преобразовывается?

2023-03-13 11:35 UTC, IIaKyJIuH commented on fedot/api/api_utils/data_definition.py
> +        features[datetime_features.columns] = datetime_features.to_numpy().astype(float)  # 'ns' unit always
Если кастовать всё в секунды, то можно потерять драгоценную информацию из даты. Там же даже есть ключ специальный `%f`, который означает микросекунды.

Вообще если задавать наносекунды в качестве временной единицы, то кажется можно обойтись и типом int, правда.
По поводу преоразований в задачах ts хз.

2023-03-13 12:20 UTC, IIaKyJIuH commented
> Может сразу снабдить тестом, воспроизврдящим проблему?

[Примерно такого вида тесты напрашиваются](https://github.com/aimclub/FEDOT/pull/1065/commits/8cced902df2a8533509ca5b493ba1d4e87a0f4c5). Допилю ещё кейсов, надо подумать.

Думаю, может быть стоит поместить тесты в integration?
Стоит ли ещё добавить проверку в [NumpyStrategy](https://github.com/aimclub/FEDOT/blob/1059-timestamp-bug/fedot/api/api_utils/data_definition.py#L102-L122) случай, когда в np.ndarray попадают `pd.Timestamp` объекты, или это уже совсем нереальный кейс? Обработки такого случая в NumpyStrategy нет, кстати говоря. 
Возможно, этот случай в препроцессоре уже обрабатывается, надо будет уточнить.

2023-03-13 19:55 UTC, nicl-nno commented
>Думаю, может быть стоит поместить тесты в integration?

Думаю лучше пусть будут в модульных. Можно их проводить, без эволюции, с predefined model.

2023-03-14 16:04 UTC, MorrisNein requested changes

2023-03-14 16:04 UTC, MorrisNein commented on test/unit/data_operations/test_data_definition.py
> +        assert False, te
Для такого можно использовать [pytest.raises()](https://docs.pytest.org/en/stable/reference/reference.html#pytest.raises)

2023-03-14 16:10 UTC, MorrisNein commented on test/unit/data_operations/test_data_definition.py
> +        assert False, te
Вижу, тут как раз обратная проверка. Тогда нужен ли вообще блок try/except?

2023-03-15 07:13 UTC, IIaKyJIuH commented on test/unit/data_operations/test_data_definition.py
> +        assert False, te
Кажется, так выглядит чётче, что проверяется именно отсутствие TypeError.

Если убрать блок, то даже не понятно толком, что и проверяется)

2023-03-15 07:14 UTC, IIaKyJIuH commented on test/unit/data_operations/test_data_definition.py
> +        assert False, te
Прокомментируй лучше TODO'шку внизу, плз

2023-03-15 07:21 UTC, IIaKyJIuH commented on test/unit/data_operations/test_data_definition.py
> +        assert False, te
Можно, кстати, поместить первый блок assert из try в else, тогда будет яснее всего?

2023-03-15 14:04 UTC, MorrisNein commented on test/unit/data_operations/test_data_definition.py
> +#         assert False, te
Если поведение `NumpyStrategy.define_data` уже где-то проверяется, то можно без этого обойтись

В обратном случае предлагаю добавить параметр "strategy" в первый тест, чтобы указывать и проверяемую стратегию, и входные данные

2023-03-15 14:09 UTC, MorrisNein commented on test/unit/data_operations/test_data_definition.py
> +#         assert False, te
Можно перекрёстно проверить все стратегии на одном наборе данных, просто использовав parametrize дважды

Как вариант, одним параметром передавать списком сами данные, а вторым передавать и стратегию, и функцию-предобработку, чтобы обернуть данные в dataframe или array

2023-03-16 08:24 UTC, IIaKyJIuH commented
@MorrisNein натолкнул меня на мысль, что нужно вообще изменить подход к обработке datetime фичей.
Оставлять их как есть в виде даты плохо, но и переводить во float тоже неинформативно и как будто сложнее. Особенно когда речь про ts задачи.

Вижу смысл покомпонентно отделять дату на часы, дни, месяцы, года...
Вопрос, есть ли смысл добавлять ключ API какой-то для обработки datetime-фичей? Ключ будет означать тип кодирования: просто во float, покомпонентно, или же ещё как-то. Или всегда лучше их отделять на компоненты и кодировать уже категориально?

2023-03-16 12:37 UTC, aPovidlo commented
> @MorrisNein натолкнул меня на мысль, что нужно вообще изменить подход к обработке datetime фичей. Оставлять их как есть в виде даты плохо, но и переводить во float тоже неинформативно и как будто сложнее. Особенно когда речь про ts задачи.

Может для разных задач, по разному предобработать данные?

> Вижу смысл покомпонентно отделять дату на часы, дни, месяцы, года... Вопрос, есть ли смысл добавлять ключ API какой-то для обработки datetime-фичей? Ключ будет означать тип кодирования: просто во float, покомпонентно, или же ещё как-то. Или всегда лучше их отделять на компоненты и кодировать уже категориально?

Покомпонентное разделение вполне разумный шаг, но почему категориально? Это же может сказаться на эффективности моделей. Им же с числами легче работать, чем с категориями (если это не катбуст).

2023-04-11 13:23 UTC, IIaKyJIuH commented on test/unit/data_operations/test_data_definition.py
> +        assert False, te
Я исправил весь файл, дополнив тесты для numpy:
[коммит](https://github.com/aimclub/FEDOT/blob/98aba06c66ed6f9d9fea0aa9e615abee4078bbe2/test/unit/data_operations/test_data_definition.py)

2023-04-11 13:24 UTC, IIaKyJIuH commented on test/unit/data_operations/test_data_definition.py
> +#         assert False, te
Так и сделал, ссылка в предыдущем комментарии

2023-04-11 13:30 UTC, IIaKyJIuH commented
Провёл тесты качества на проблемном датасете из issue. Использовал catboost в качестве модели. В 2 из 3 случаев наносекунды по качеству совпадают с миллисекундами (скрин):
![image](https://user-images.githubusercontent.com/38308131/231177603-990a808c-08ab-4426-aa7f-1d0dbf0d58c9.png)

Почему так - неизвестно. В остальном количестве случаев качество между всеми моделями идентичное. Получается, миллисекунды можно ставить, хуже не будет.

2023-04-12 19:42 UTC, MorrisNein commented on test/unit/data_operations/test_data_definition.py
> +#         assert False, te
Супер! А оправдано для стратегий проверять разные данные? Или можем сделать что-то вроде такого:

https://github.com/aimclub/FEDOT/blob/0a20a0da79e7f16a93ec973b86a7933d7e083852/test/unit/api/test_api_params.py#L82-L84

Если адаптировать под текущий случай:

```
@pytest.mark.parametrize('strategy, features_type', [(PandasStrategy, pd.DataFrame),
                                                     (NumpyStrategy, np.array)])
@pytest.mark.parametrize('features', [list_of_features_1,
                                      list_of_features_2])
def test_strategy(strategy: Type[StrategyDefineData], features_type: Any, features: FeaturesType, monkeypatch):
    features = features_type(features)
    ...
```

Вижу, там используется dtype. Если он критичен для тестов, можем оставить как есть и не усложнять параметризацию.

Либо пойти во все тяжкие 😈 :

```
@pytest.mark.parametrize('strategy, features_type', [(PandasStrategy, pd.DataFrame),
                                                     (NumpyStrategy, np.array)])
@pytest.mark.parametrize('dtype', [object, np.datetime64, None])
@pytest.mark.parametrize('features', [list_of_features_1,
                                      list_of_features_2])
def test_strategy(strategy: Type[StrategyDefineData], features_type: Any, dtype: Any, features: FeaturesType, monkeypatch):
    features = features_type(features, dtype=dtype)
    ...
```

2023-04-16 09:11 UTC, aPovidlo commented
> Почему так - неизвестно. В остальном количестве случаев качество между всеми моделями идентичное. Получается, миллисекунды можно ставить, хуже не будет.

Предположу, что возможно это связанно с фиксированием в `RandomStateHandler` у кб или подтягиванием одной и той же модели из кеша

2023-04-17 10:28 UTC, IIaKyJIuH commented on test/unit/data_operations/test_data_definition.py
> +#         assert False, te
Решил в итоге вообще не проверять стратегии, потому что получался не тру юнит-тест в таком случае. Сейчас проверяю просто [конвертацию дат в разных типах данных в число](https://github.com/aimclub/FEDOT/blob/15a39b84c336f2f7fd13d8f8df722e66ff6f6dcc/test/unit/data_operations/test_data_definition.py).

2023-04-17 10:30 UTC, IIaKyJIuH commented
> > Почему так - неизвестно. В остальном количестве случаев качество между всеми моделями идентичное. Получается, миллисекунды можно ставить, хуже не будет.
> 
> Предположу, что возможно это связанно с фиксированием в `RandomStateHandler` у кб или подтягиванием одной и той же модели из кеша

Сид передаю определённый, т.е. он устанавливается воспроизводимый и одинаковый всегда.
Кеш я вообще отключил, так что тут сложнее)

2023-04-20 14:27 UTC, aPovidlo approved these changes

2023-04-20 14:53 UTC, IIaKyJIuH commented
Уже намеревался смёрджить ветку, как вдруг задумался и понял, что контракт на `use_input_preprocessing` в моих текущих правках не выполняется.
Передавать его глубоко в `DataDefiner`'ы выглядит неэстетично (уже попробовал), нужно засунуть эту конвертацию в "обязательную предобработку", которая как раз подвязана на тот параметр.

2023-04-21 14:49 UTC, aPovidlo approved these changes

2023-04-21 14:49 UTC, aPovidlo commented on fedot/preprocessing/preprocessing.py
> +            data.target = np_datetime_to_numeric(data.target)  # TODO: А нужно ли конвертировать таргет из даты в число?
А этот вопрос не относится к этому PR?

2023-04-21 15:01 UTC, IIaKyJIuH commented on fedot/preprocessing/preprocessing.py
> +            data.target = np_datetime_to_numeric(data.target)  # TODO: А нужно ли конвертировать таргет из даты в число?
Вопрос относится к этому PR.
Кажется, что кейс с датами в таргете редкий, но вероятен же?

2023-04-21 17:36 UTC, MorrisNein approved these changes

2023-04-21 17:36 UTC, MorrisNein commented on test/unit/data_operations/test_text_preprocessing.py
> +                           target=np.array([0, 1, 1, 0]),
А на что это влияет?

2023-04-21 17:36 UTC, MorrisNein commented on fedot/core/data/data.py
> +    converted_cols = date_cols.to_numpy(np.int64) // 10 ** 6  # to 'ms' unit from 'ns'
Тут можно обойтись без лишнего действия, написав 1e6

2023-04-21 18:01 UTC, IIaKyJIuH commented on test/unit/data_operations/test_text_preprocessing.py
> +                           target=np.array([0, 1, 1, 0]),
Тест не выполнялся.
Тут была ошибка, потому что InputData предполагает ndarray, а не другие массиво-списки.

2023-04-21 18:03 UTC, IIaKyJIuH commented on fedot/core/data/data.py
> +    converted_cols = date_cols.to_numpy(np.int64) // 10 ** 6  # to 'ms' unit from 'ns'
[Действительно](https://github.com/aimclub/FEDOT/pull/1065/commits/378b2a0f4364e6cf74d9bdc5b496fee9940a9ecd)

2023-04-24 10:18 UTC, merged