879 FEDOT features
aimclub/FEDOT pull request #1075
Opened 2023-03-29 12:46 UTC by IIaKyJIuH

Solves issue #879

2023-03-29 12:50 UTC, IIaKyJIuH commented
Вот ссылки на основные страницы в обновлённой документации, которые были затронуты:

[Сами фичи](https://fedot.readthedocs.io/en/879_doc_features/introduction/fedot_features/index.html)

[Перенесённые и доработанные концепции фреймворка](https://fedot.readthedocs.io/en/879_doc_features/basics/concepts.html)

2023-03-30 12:50 UTC, nicl-nno commented on docs/source/introduction/fedot_features/automation/dimensionality_reduction.rst
> +    [А что по ITMO_FS у нас, кстати? Вроде нигде не используется на 28.03.2023]
Не используется. А он где-то упомянут?

2023-03-30 12:50 UTC, nicl-nno commented on docs/source/introduction/fedot_features/automation/data_nature.rst
> +    Стоит ли тут написать, что datetime будет конвертиться в число?
В целом да.

2023-03-30 12:51 UTC, nicl-nno commented on docs/source/introduction/fedot_features/tasks.rst
> +* Time-series problems ([uni/multi]variate)
Cтоит упомянуть, что речь именно о прогнозировании.

2023-03-30 12:52 UTC, nicl-nno commented on docs/source/introduction/fedot_features/tasks.rst
> +The last is not true to many other frameworks and also that versatility is not true either.
Не очень понятная формулировка, особенно в части про versatility. Да и true в этом контексте выглядит не оч.

2023-03-30 12:54 UTC, nicl-nno commented on docs/source/introduction/fedot_features/automation/dimensionality_reduction.rst
> +Currently FEDOT supports only feature selection algorithms provided by scikit-learn, but there aren't extraction ones.
Не эксперт в грамматике, но "there aren’t extraction ones" звучит как-то странно. Ну и feature generation тоже реализован вроде как.

2023-03-30 12:56 UTC, nicl-nno commented on docs/source/introduction/fedot_features/automation/dimensionality_reduction.rst
> +Dimensionality reduction
Вроде ниже речь о feature selection. Методы снижения размерности у нас тоже есть, но они не упомянуты.

2023-03-30 12:57 UTC, nicl-nno commented on docs/source/introduction/fedot_features/automation/used_models.rst
> +That option thereby influences:
Ну вот не пишут так:

![image](https://user-images.githubusercontent.com/5711814/228842902-a36b02c0-a2f5-425a-9e48-c84551e1dc78.png)


И явно подробностей не хватает в этом разделе.

2023-03-30 12:58 UTC, nicl-nno commented on docs/source/introduction/fedot_features/data_preprocessing.rst
> +Data preprocessing
Кажется нужны какие-то отсылки к https://fedot.readthedocs.io/en/879_doc_features/advanced/data_preprocessing.html

2023-03-30 12:59 UTC, nicl-nno commented on docs/source/introduction/fedot_features/composition_method.rst
> +Composition method
Composition - не очень понятный термин, без пояснений выносить в заголовок его не стоит.

2023-03-30 22:32 UTC, nicl-nno commented on docs/source/introduction/fedot_features/automation/dimensionality_reduction.rst
> +    [А что по ITMO_FS у нас, кстати? Вроде нигде не используется на 28.03.2023]
Пока вряд ли - т.к. кажется создатели его не особо развивают.

2023-03-31 13:12 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/automation/data_nature.rst
> +Data nature
Поместил в этот раздел, чтобы подчеркнуть автоматическое определение и преобразование типов данных (того же datetime или вычленение таргета).

2023-03-31 13:19 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/automation/dimensionality_reduction.rst
> +Currently FEDOT supports only feature selection algorithms provided by scikit-learn, but there aren't extraction ones.
Нашёл только извлечение признаков из текста. Где есть извлечение из других типов данных?

2023-03-31 14:14 UTC, DenisSidoren requested changes

2023-03-31 14:14 UTC, DenisSidoren commented on docs/source/introduction/fedot_features/index.rst
> +   automation/index
У меня предложение переделать этот раздел концептуально.

Внутри FEDOT Features должно быть 2 файла:
    1. **Distinctive characteristics** (или как угодно можно назвать этот раздел), в него войдет вся информация         из файлов **tasks, composition_method, data_preprocessing**. Разделение блоков информации через разные уровни Headings. Причина: в каждом из файлов нет достаточного объема информации, чтобы он занимал целую страницу в документации, как [тут](https://fedot.readthedocs.io/en/879_doc_features/introduction/fedot_features/tasks.html) и [тут](https://fedot.readthedocs.io/en/879_doc_features/introduction/fedot_features/composition_method.html)
    2. **AutoML capapilities**, который содержит в себе информацию из файлов **learning, data_nature, dimensionality_reduction, used_models**. Разделы так же делятся через иерархию Headings. Причина: сейчас через дополнительный[ index.rst](https://github.com/aimclub/FEDOT/blob/3758626f352b504758e363d193e5995359949499/docs/source/introduction/fedot_features/automation/index.rst) в директории **automation** создается бесполезная [страница доки](https://fedot.readthedocs.io/en/879_doc_features/introduction/fedot_features/automation/index.html), в которой, как и в примере выше, находится много отдельных страниц ([один](https://fedot.readthedocs.io/en/879_doc_features/introduction/fedot_features/automation/learning.html), [два](https://fedot.readthedocs.io/en/879_doc_features/introduction/fedot_features/automation/data_nature.html), [три](https://fedot.readthedocs.io/en/879_doc_features/introduction/fedot_features/automation/dimensionality_reduction.html), [четыре](https://fedot.readthedocs.io/en/879_doc_features/introduction/fedot_features/automation/used_models.html)) с малым количеством информации

2023-03-31 14:14 UTC, DenisSidoren commented on docs/source/introduction/what_is_fedot.rst
> +There is a :doc:`quickstart guide for begginers <tutorial/quickstart>`.
опечатка в beginners

2023-03-31 14:14 UTC, DenisSidoren commented on docs/source/introduction/tutorial/quickstart.rst
> +or Linux distributions.
Fedot has been perfectly supported on Windows, Linux, and MacOS systems.

(как альтернатива)

2023-03-31 14:39 UTC, MorrisNein requested changes

2023-03-31 14:39 UTC, MorrisNein commented on docs/source/introduction/tutorial/quickstart.rst
> +or Linux distributions.
`works fine` - можем быть скормнее 😆 

Но не обязательно)

2023-03-31 14:39 UTC, MorrisNein commented on docs/source/introduction/fedot_features/data_preprocessing.rst
> +    Both of the technics applied only once.
На мой взгляд, лучше написать вот так:

`Both obligatory and optional preprocessing are applied only once.` 

И ещё напрашивается вопрос: "when are they applied?"

2023-03-31 14:39 UTC, MorrisNein commented on docs/source/introduction/fedot_features/data_preprocessing.rst
> +your program, these are:
Лучше писать как есть: `Obligatory preprocessing` вместо `The first one`, чтобы при чтении не держать в памяти, какие там этапы, и какой у них порядок. 

Cares кажется неподходящим словом.

Предлагаю что-то вроде:

`**Obligatory preprocessing**, as you might guess, solves important problems that can disrupt or complicate data processing, such as:`

2023-03-31 14:39 UTC, MorrisNein commented on docs/source/introduction/fedot_features/data_preprocessing.rst
> +it is necessary for the next model from a processing queue to work.
Тут тоже лучше указать тип препроцессинга вместо номера.

Уместен будет артикль `the` перед `composed pipeline` и `processing queue`.

2023-03-31 14:39 UTC, MorrisNein commented on docs/source/introduction/fedot_features/automation/used_models.rst
> +* reasonability of the selected models according to the task field.
- `its` вместо `it's`
- `reasonability` - тоже как будто не оч подходит.
Возможно, так сочтёшь более подходящим: `suitability of the candidate models for the task's field`.

2023-04-04 10:32 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/automation/used_models.rst
> +That option thereby influences:
Окей, будет `it thereby influences`.

Подробности кажутся излишними, потому что я дал на них ссылку в API.
Можно только обратить внимание на дефолтное `auto` и влияние этих параметров, что и было изначально)

2023-04-04 10:54 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/composition_method.rst
> +but you are free to use any other approach, for example, bayesian optimization or even random search.
В этом PR не планирую расширять. Не знаю, чем можно дополнить, убрать страницу?

2023-04-04 12:29 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/automation/dimensionality_reduction.rst
> +    [А что по ITMO_FS у нас, кстати? Вроде нигде не используется на 28.03.2023]
Убрал комментарий
[Коммит](https://github.com/aimclub/FEDOT/pull/1075/commits/345ff5cd54085b4601cf2921a1e29878360841c3)

2023-04-04 12:30 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/tasks.rst
> +* Time-series problems ([uni/multi]variate)
[Готово](https://github.com/aimclub/FEDOT/pull/1075/commits/345ff5cd54085b4601cf2921a1e29878360841c3#diff-a9cd02ffc5ac36153a77d31cb7131e06ccafb6302e78a54baa532c4d358397abR8)

2023-04-04 13:04 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/tasks.rst
> +* Clustering (but not as the main one yet)
[Оставил только главные](https://github.com/aimclub/FEDOT/blob/345ff5cd54085b4601cf2921a1e29878360841c3/docs/source/introduction/fedot_features/tasks.rst)

2023-04-04 13:04 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/tasks.rst
> +The last is not true to many other frameworks and also that versatility is not true either.
Это просто убрал)

2023-04-04 13:05 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/automation/dimensionality_reduction.rst
> +Currently FEDOT supports only feature selection algorithms provided by scikit-learn, but there aren't extraction ones.
Изменил вообще, теперь файл выглядит [так](https://github.com/aimclub/FEDOT/blob/345ff5cd54085b4601cf2921a1e29878360841c3/docs/source/introduction/fedot_features/automation/dimensionality_reduction.rst)

2023-04-04 13:06 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/automation/dimensionality_reduction.rst
> +Dimensionality reduction
Переименовал на `Dimensionality operations`, а ещё явно [отделил](https://github.com/aimclub/FEDOT/blob/345ff5cd54085b4601cf2921a1e29878360841c3/docs/source/introduction/fedot_features/automation/dimensionality_reduction.rst) два разных подхода к выборке фич

2023-04-04 13:08 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/automation/used_models.rst
> +That option thereby influences:
Подробностей не добавил, но изменил формулировки и пункты списка на более простые
[Коммит](https://github.com/aimclub/FEDOT/blob/345ff5cd54085b4601cf2921a1e29878360841c3/docs/source/introduction/fedot_features/automation/models_used.rst)

2023-04-04 16:24 UTC, IIaKyJIuH commented on docs/source/introduction/what_is_fedot.rst
> +There is a :doc:`quickstart guide for begginers <tutorial/quickstart>`.
[Исправил](https://github.com/aimclub/FEDOT/pull/1075/commits/345ff5cd54085b4601cf2921a1e29878360841c3#diff-711be8321824cbcee05dbb53f14e4f094187886f5991eb03a9a46b08814a87bbR38)

2023-04-04 16:24 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/quickstart.rst
> +or Linux distributions.
[Норм](https://github.com/aimclub/FEDOT/pull/1075/commits/345ff5cd54085b4601cf2921a1e29878360841c3#diff-b50e20ad116bd2c04aa8945e319418d0755cc2788237f1ffe244fcd703dd8e00R6)

2023-04-04 16:25 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/automation/used_models.rst
> +Using ``preset`` :doc:`main API parameter </api/api>` you can specify
[Окей](https://github.com/aimclub/FEDOT/pull/1075/commits/345ff5cd54085b4601cf2921a1e29878360841c3#diff-2ad4bde84f63d1256c0fff8bd3d7b18f5c1f5f7977311af51603c98a94990b03R4)

2023-04-04 16:28 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/automation/learning.rst
> +see :doc:`manual composing <../../tutorial/composing_pipelines/manual_creation>`
Поправил в этом [коммите](https://github.com/aimclub/FEDOT/pull/1075/commits/345ff5cd54085b4601cf2921a1e29878360841c3) парочку файлов:

* [what_is_fedot.rst](https://github.com/aimclub/FEDOT/pull/1075/commits/345ff5cd54085b4601cf2921a1e29878360841c3#diff-711be8321824cbcee05dbb53f14e4f094187886f5991eb03a9a46b08814a87bbR30)
* [learning.rst](https://github.com/aimclub/FEDOT/pull/1075/commits/345ff5cd54085b4601cf2921a1e29878360841c3#diff-c318cc57efa0d66ded2e46674734acaa298e55f69f37b00f027185e1c877c82dR10)

2023-04-04 16:29 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/automation/used_models.rst
[Сделано](https://github.com/aimclub/FEDOT/pull/1075/commits/345ff5cd54085b4601cf2921a1e29878360841c3#diff-2ad4bde84f63d1256c0fff8bd3d7b18f5c1f5f7977311af51603c98a94990b03R1)

2023-04-04 16:32 UTC, IIaKyJIuH commented on docs/source/introduction/what_is_fedot.rst
> +You can investigate more FEDOT's concepts :doc:`here <../basics/concepts>`.
С 1-ым согласен, а со вторым [не очень](https://style.mla.org/the-possessive-form-of-acronyms/#:~:text=To%20form%20the%20possessive%20of,acronyms%20in%20formal%20academic%20prose.).

Но на всякий случай упрощу.

2023-04-04 16:49 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/data_preprocessing.rst
> +it is necessary for the next model from a processing queue to work.
Насчёт номера согласен.

Почему определённый артикль? Я на это смотрю как на ввод понятий впервые, поэтому логичнее `a` выглядит.

2023-04-04 16:50 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/automation/used_models.rst
> +* reasonability of the selected models according to the task field.
[Исправил](https://github.com/aimclub/FEDOT/pull/1075/commits/345ff5cd54085b4601cf2921a1e29878360841c3#diff-2ad4bde84f63d1256c0fff8bd3d7b18f5c1f5f7977311af51603c98a94990b03R9-R11), укоротив эти пункты.
Но спасибо)

2023-04-04 16:52 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/composition_method.rst
> +Composition method
[Такое](https://github.com/aimclub/FEDOT/pull/1075/commits/5fec770becac562db461eecae34583479c7679a1#diff-a8c217770508bdb9e92ba6d83a8f23c9b777681bbbf5a65903a2f571a23e9800R1) название норм?

2023-04-04 16:53 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/data_preprocessing.rst
> +Data preprocessing
Что скажешь об [этом](https://github.com/aimclub/FEDOT/pull/1075/commits/5fec770becac562db461eecae34583479c7679a1#diff-3a59eda1dd146a9f62037d3bdc8d304055210365bb49046f30c5a141877bba13R49-R51)?
Выглядит элегантно)

2023-04-04 16:54 UTC, IIaKyJIuH commented on docs/source/introduction/what_is_fedot.rst
> +You can investigate more FEDOT's concepts :doc:`here <../basics/concepts>`.
[Вот так будет](https://github.com/aimclub/FEDOT/pull/1075/commits/5fec770becac562db461eecae34583479c7679a1#diff-711be8321824cbcee05dbb53f14e4f094187886f5991eb03a9a46b08814a87bbR36). Что скажешь?

2023-04-04 17:00 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/data_preprocessing.rst
> +    so you can save some time if you have already preprocessed dataset.
[Так лучше](https://github.com/aimclub/FEDOT/pull/1075/commits/5fec770becac562db461eecae34583479c7679a1#diff-3a59eda1dd146a9f62037d3bdc8d304055210365bb49046f30c5a141877bba13R9)?

2023-04-04 17:01 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/data_preprocessing.rst
> +    Both of the technics applied only once.
[Исправил](https://github.com/aimclub/FEDOT/pull/1075/commits/5fec770becac562db461eecae34583479c7679a1#diff-3a59eda1dd146a9f62037d3bdc8d304055210365bb49046f30c5a141877bba13R54) по твоему совету. А ответ на вопрос разрешил ссылкой "see also"))

2023-04-04 17:02 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/data_preprocessing.rst
> +your program, these are:
[Сделал чуть видоизменив](https://github.com/aimclub/FEDOT/pull/1075/commits/5fec770becac562db461eecae34583479c7679a1#diff-3a59eda1dd146a9f62037d3bdc8d304055210365bb49046f30c5a141877bba13R11-R12)

2023-04-04 21:41 UTC, nicl-nno commented on docs/source/introduction/fedot_features/composition_method.rst
> +Composition method
Тогда pipeline building

2023-04-04 21:42 UTC, nicl-nno commented on docs/source/introduction/fedot_features/data_preprocessing.rst
> +Data preprocessing
Пусть будет.

2023-04-04 21:42 UTC, nicl-nno commented on docs/source/introduction/fedot_features/composition_method.rst
> +but you are free to use any other approach, for example, bayesian optimization or even random search.
Добавь хотя бы отсылку на GOLEM-у.

2023-04-04 21:45 UTC, nicl-nno commented on docs/source/introduction/fedot_features/automation/used_models.rst
> +That option thereby influences:
Из страницы всё ещё неочевидно, что где-то можно почитать про перечень моделей в пресетах.

Стоит хотя бы разницу между основными best_quality и fast_train разобрать

2023-04-04 21:47 UTC, nicl-nno commented on docs/source/introduction/fedot_features/automation/dimensionality_reduction.rst
> +Dimensionality reduction
Стоит наверное перечислить конкретные названия операций, которые можно использовать при создании Node. Можно таблицей "название - расшифровка".

2023-04-05 15:22 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/composition_method.rst
> +Composition method
[Готово](https://github.com/aimclub/FEDOT/pull/1075/commits/a70587975d4444bae269e661eb409b0e1c3fdace)

2023-04-10 09:16 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/tasks.rst
> +* Time-series problems ([uni/multi]variate)
[Такие](https://github.com/aimclub/FEDOT/pull/1075/commits/19c34b5be4720243f11cef98342a85dc0909caaa#diff-a172f386b154fce91feb03be2ab2525cfc2075dc5f759626f7e5a85f259939d5R6-R8) подойдут?

2023-04-10 09:17 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/tasks.rst
> +* Time-series problems ([uni/multi]variate)
Смущает, что они на русском будут, когда вся документация английская)

2023-04-10 14:30 UTC, IIaKyJIuH commented on README.rst
> +- **Кастомизируемость.** FEDOT позволяет настраивать сложность моделей и, тем самым, получать необходимое качество моделей;
Не я это писал, но полагаю, что под "специальными шаблонами" понимается выбор: опции `preset`, доступных моделей в FEDOT и [стратегии из FEDOT'а](https://fedot.readthedocs.io/en/master/api/eval_strategy.html). Вообще, если это так, тогда пункт связан со следующим.

Если назвать пункт "Адаптируемость", будет ли понятнее, что это про задачи и данные?

2023-04-10 16:19 UTC, MorrisNein commented on README.rst
> +- **Кастомизируемость.** FEDOT позволяет настраивать сложность моделей и, тем самым, получать необходимое качество моделей;
> Если назвать пункт "Адаптируемость", будет ли понятнее, что это про задачи и данные?

В целом, и так понятно, просто глаз цепляется за неопределённую сущность "шаблон". Можно её тогда назвать пресетом для единообразия, либо "пресет и стратегия оценки"

2023-04-11 08:29 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/data_preprocessing.rst
> +it is necessary for the next model from a processing queue to work.
Понял тебя.
Если не конкретизировать `the next model`, можно ли будет писать с неопределённым артиклем (`a composed pipeline structure` & `a next model` & `a processing queue`)?

2023-04-11 08:30 UTC, IIaKyJIuH commented on README.rst
> +- **Кастомизируемость.** FEDOT позволяет настраивать сложность моделей и, тем самым, получать необходимое качество моделей;
Классная мысль, можно будет тогда заодно ссылки соответствующие навесить на эти слова

2023-04-11 12:44 UTC, IIaKyJIuH commented on README.rst
> +- **Кастомизируемость.** FEDOT позволяет настраивать сложность моделей и, тем самым, получать необходимое качество моделей;
Написал [текст концептов для README](https://github.com/aimclub/FEDOT/pull/1075/commits/c5971063a857cc77c9af27e895b8ff199e359364).

В README указал ссылки на ещё не существующие файлы master-ветки, они будут доступны после закрытия PR. Чтобы оценить общий вид, нужно зайти на страницу с концептами (Basics/Main concepts) в RTD.

2023-04-12 19:15 UTC, MorrisNein commented on docs/source/introduction/fedot_features/data_preprocessing.rst
> +it is necessary for the next model from a processing queue to work.
Да, так кажется вполне норм

2023-04-17 15:06 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/data_preprocessing.rst
> +it is necessary for the next model from a processing queue to work.
В таком случае заголовок будет выглядеть [так](https://github.com/aimclub/FEDOT/pull/1075/commits/f6690d2dddf4dc66101df63c427db06cf66541d0)

2023-04-17 15:06 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/composition_method.rst
> +but you are free to use any other approach, for example, bayesian optimization or even random search.
Коротко + отсылка на advanced страницу
[Коммит](https://github.com/aimclub/FEDOT/pull/1075/commits/d8e6b5c9403c37f572510d4e21e584df9cc429f7)

2023-04-17 15:13 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/data_preprocessing.rst
> +it is necessary for the next model from a processing queue to work.
Взгляни, пожалуйста, на скрытые замечания, там тоже комментарии висят.

2023-04-17 16:32 UTC, nicl-nno approved these changes

2023-04-18 10:11 UTC, IIaKyJIuH commented on docs/source/introduction/fedot_features/index.rst
> +   automation/index
Попробовал воплотить твою идею в реальность в [этом коммите](https://github.com/aimclub/FEDOT/pull/1075/commits/25d7e873d3e42ca3b12aecb1411974773ba803b2).

Поскольку расширил документацию за время твоего комментария, оставил некоторые "полные" страницы в качестве отдельных.
Страницу из раздела `AutoML capabilities` поместил просто в его индекс, там достаточно общая информация. 

Маленькие же страницы объединил в `main.rst`, не путает ли такое название?

2023-04-20 14:30 UTC, MorrisNein approved these changes

2023-04-25 11:11 UTC, DenisSidoren approved these changes

2023-04-25 11:12 UTC, merged