Add documented API params setters
aimclub/FEDOT pull request #1077
Opened 2023-03-31 18:48 UTC by MorrisNein

The main motivation is to improve API parameters usage:

- make them easier to document for us;
- make them easier to understand and set for users.

Existing documented parameters are divided in logical blocks, each of them got their separate setter:

- **with_composer_params**
    - `show_progress`
    - `preset`
    - `with_tuning`
    - `use_meta_rules`
    - `cache_dir`
    - `history_dir`
- **with_evolution_params**
    - `initial_assumption`
    - `num_of_generations`
    - `early_stopping_iterations`
    - `early_stopping_timeout`
    - `max_pipeline_fit_time`
    - `pop_size`
    - `keep_n_best`
    - `genetic_scheme`
    - `use_pipelines_cache`
    - `optimizer`
    - `optimizer_external_params`
- **with_pipeline_structure_params**
    - `available_operations`
    - `max_depth`
    - `max_arity`
- **with_pipeline_evaluation_params**
    - `metric`
    - `collect_intermediate_metric`
    - `cv_folds`
    - `validation_blocks`
- **with_data_processing_params**
    - `safe_mode`
    - `use_input_preprocessing`
    - `use_preprocessing_cache`

For now, I'm going to make API parameters created once they are used the first time, so subsequent calls of the setters could accumulate the values. After the parameters object is created, the `ValueError` to be raised.

2023-04-11 08:15 UTC, gkirgizov reviewed
Будет ли пользователю удобно искать, какой параметр к какому блоку относится? Например, мне нужно задать только метрику оптимизации -- как понять, какой `with_...` написать?

2023-04-11 14:08 UTC, IIaKyJIuH requested changes

2023-04-11 14:08 UTC, IIaKyJIuH commented on docs/source/advanced/sensitivity_analysis.rst
> +Conduct only composite model structure analysis via :class:`fedot.sensitivity.nodes_sensitivity.NodesAnalysis`,
Тут тоже лучше укоротить ссылку, м?

2023-04-11 14:08 UTC, IIaKyJIuH commented on docs/source/api/sensitivity.rst
>  Pipeline Complete Analysis
А если поставить [такое расширение](https://www.sphinx-doc.org/en/master/usage/extensions/autosectionlabel.html), можно будет избежать создание подобных ссылок?

2023-04-12 18:39 UTC, MorrisNein commented on fedot/api/main.py
> +    ):
Пока что работаю над этим, чуть поспешили с запросом на ревью. Запрошу повторный ревью, как допилю функционал

2023-04-12 18:42 UTC, MorrisNein commented
> Будет ли пользователю удобно искать, какой параметр к какому блоку относится? Например, мне нужно задать только метрику оптимизации -- как понять, какой `with_...` написать?

Я надеюсь, что из названия методов должно быть понятно. Например, вызываешь `with_...` и смотришь контекстные подсказки. Метрика относится к оценке пайплайнов -> наверняка нужно выбрать `with_pipeline_evaluation_params`. Можно сделать наборы параметров пересекающимися, если они подходят по контексту в несколько групп.

2023-04-12 18:43 UTC, MorrisNein commented on fedot/api/api_utils/assumptions/assumptions_handler.py
> +            data: data for pipelines.
Можно, конечно. Я просто обновил стиль докстринги, содержание не трогал. Поменяю

2023-04-12 18:57 UTC, MorrisNein commented on docs/source/api/sensitivity.rst
>  Pipeline Complete Analysis
Тут случилас неприятность с гитхабом - эти правки вообще не должны быть в данном PR. И секция с SA в документации безнадёжно устарела, её нужно написать заново, а не править

2023-04-12 18:58 UTC, MorrisNein commented on docs/source/advanced/sensitivity_analysis.rst
> +Conduct only composite model structure analysis via :class:`fedot.sensitivity.nodes_sensitivity.NodesAnalysis`,
То же самое - не актуальные правки по SA

2023-09-29 14:41 UTC, pep8speaks commented
Hello @MorrisNein! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`fedot/__init__.py`](https://github.com/aimclub/FEDOT/blob/cc90eeda39aef16c0f83a5b7b1763a673bd828b1/fedot/__init__.py):

> [Line 3:1](https://github.com/aimclub/FEDOT/blob/cc90eeda39aef16c0f83a5b7b1763a673bd828b1/fedot/__init__.py#L3): [F403](https://duckduckgo.com/?q=pep8%20F403) 'from fedot import *' used; unable to detect undefined names
> [Line 3:1](https://github.com/aimclub/FEDOT/blob/cc90eeda39aef16c0f83a5b7b1763a673bd828b1/fedot/__init__.py#L3): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.*' imported but unused
> [Line 4:1](https://github.com/aimclub/FEDOT/blob/cc90eeda39aef16c0f83a5b7b1763a673bd828b1/fedot/__init__.py#L4): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.api.Fedot' imported but unused
> [Line 4:1](https://github.com/aimclub/FEDOT/blob/cc90eeda39aef16c0f83a5b7b1763a673bd828b1/fedot/__init__.py#L4): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.api.FedotBuilder' imported but unused
> [Line 5:1](https://github.com/aimclub/FEDOT/blob/cc90eeda39aef16c0f83a5b7b1763a673bd828b1/fedot/__init__.py#L5): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.version.__version__' imported but unused

* In the file [`fedot/api/__init__.py`](https://github.com/aimclub/FEDOT/blob/cc90eeda39aef16c0f83a5b7b1763a673bd828b1/fedot/api/__init__.py):

> [Line 1:1](https://github.com/aimclub/FEDOT/blob/cc90eeda39aef16c0f83a5b7b1763a673bd828b1/fedot/api/__init__.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.api.main.Fedot' imported but unused
> [Line 2:1](https://github.com/aimclub/FEDOT/blob/cc90eeda39aef16c0f83a5b7b1763a673bd828b1/fedot/api/__init__.py#L2): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.api.builder.FedotBuilder' imported but unused

* In the file [`fedot/api/builder.py`](https://github.com/aimclub/FEDOT/blob/cc90eeda39aef16c0f83a5b7b1763a673bd828b1/fedot/api/builder.py):

> [Line 118:121](https://github.com/aimclub/FEDOT/blob/cc90eeda39aef16c0f83a5b7b1763a673bd828b1/fedot/api/builder.py#L118): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)

2023-09-29 15:01 UTC, MorrisNein commented on fedot/api/main.py
> +            instead of OneHot encoder if summary cardinality of categorical features is high.
Исправил

2023-09-29 15:01 UTC, MorrisNein commented on fedot/api/main.py
> +            ``'sequential'``). Default value is ``'populational'``.
Исправлено

2023-09-29 15:02 UTC, MorrisNein commented on fedot/api/main.py
> +            The array with prediction values.
Везде, где увидел, поправил

2023-09-29 15:02 UTC, MorrisNein commented on docs/source/advanced/hyperparameters_tuning.rst
>  ~~~~~~~~~~~~~~
Это больше не входит в данный PR

2023-09-29 15:20 UTC, MorrisNein commented
Переделал состав параметров в группах. Насколько удобно получилось -- посмотрите, пожалуйста.

Есть альтернативная идея сделать отдельные сеттеры для каждого из параметров API на этапе установки библиотеки. Наподобие того, как это реализовано в matplotlib.

Что-то вроде `FedotBuilder.pop_size(pop_size)`.

Но эта реализация несколько более муторная, возможно, даже есть смысл посмотреть в сторону программной генерации кода.

2023-09-29 15:42 UTC, MorrisNein commented on fedot/api/main.py
> +    ):
Теперь попадают через основной апи)
Сеттеры добавил в отдельную сущность

2023-10-12 14:12 UTC, gkirgizov commented
> Что-то вроде `FedotBuilder.pop_size(pop_size)`.
> 
> Но эта реализация несколько более муторная, возможно, даже есть смысл посмотреть в сторону программной генерации кода.

Данное решение уже достаточно хорошо. Думаю, пока не возникнут новые неудобства, можно на этом остановиться. Класс

2023-10-13 07:18 UTC, IIaKyJIuH approved these changes

2023-10-18 06:16 UTC, merged

2023-10-18 06:18 UTC, MorrisNein commented
Благодаря написанным тестам нашёл пропущенный параметр keep_history. Он был не задокументирован в основном API, и поэтому изначально не попал в FedotBuilder. 

Так что буду считать покрытие нового функционала тестами вполне достаточным для начала.