add example for surrogate optimizer
aimclub/FEDOT pull request #1085
Opened 2023-04-15 15:50 UTC by valer1435

Example with surrogate optimizer was added. External parameters field was removed from api (now we should use partial)

related pull request in GOLEM https://github.com/aimclub/GOLEM/pull/82

For using you should remove your golem installation and install golem from specified branch
pip install git+https://github.com/aimclub/GOLEM@surrogate-model#egg=thegolem

2023-04-15 15:54 UTC, valer1435 commented
Ссылка на связаный pr в FEDOT'е https://github.com/aimclub/GOLEM/pull/82

2023-04-16 09:48 UTC, nicl-nno commented on examples/advanced/surrogate_optimization.py
> +        return [0]
Сделай в примере оценку зависящей от какого-то свойства графа (глубины, например) - для наглядности.

2023-04-17 09:21 UTC, YamLyubov commented on test/unit/optimizer/test_external.py
> -def test_external_static_optimizer(data_fixture, request):
Не совсем поняла, зачем убирать тест (он же тестирует использование переданного оптимизатора)?

2023-04-17 12:59 UTC, ShikovEgor approved these changes

2023-04-18 07:27 UTC, maypink requested changes

2023-04-18 07:27 UTC, maypink commented on examples/advanced/surrogate_optimization.py
> +        input_data = kwargs.get('objective').__self__._data_producer.args[0]
кажется не должно возникать ситуаций, когда придется настолько лезть в кишки ради данных

2023-04-18 10:57 UTC, ShikovEgor approved these changes

2023-04-18 10:58 UTC, ShikovEgor approved these changes

2023-04-19 10:47 UTC, valer1435 commented on examples/advanced/surrogate_optimization.py
> +        return [0]
[done](https://github.com/aimclub/FEDOT/pull/1085/files#diff-a23dda50d6acd75b48bbf0f8b7f3d95d90fdcb9a69a9a61bd3040062e54665b4R12)

2023-04-19 10:48 UTC, valer1435 commented on test/unit/optimizer/test_external.py
> -def test_external_static_optimizer(data_fixture, request):
да, поторопился, [убрал ](https://github.com/aimclub/FEDOT/pull/1085/files#diff-d8c13f6fedf419a3219d4c7e63e79d37af2def69c2b57aa8a73ba8280dc2e8bcR36)только external_params

2023-04-19 10:48 UTC, valer1435 commented on examples/advanced/surrogate_optimization.py
> +        input_data = kwargs.get('objective').__self__._data_producer.args[0]
Это нормально при нашем подходе с objective. Но [упростил ](https://github.com/aimclub/FEDOT/pull/1085/files#diff-b74209f31e96829d85a9081c7c984c03dc210033b10faed484b809278e33961bR151)получение данных через поле

2023-04-19 14:14 UTC, ShikovEgor approved these changes

2023-04-19 14:16 UTC, ShikovEgor approved these changes

2023-04-20 16:54 UTC, nicl-nno approved these changes

2023-04-21 08:22 UTC, maypink approved these changes
гуд джоб коллега

2023-04-27 05:31 UTC, merged