358 Reduce execution time for unit tests
aimclub/FEDOT pull request #1098
Opened 2023-05-12 11:41 UTC by IIaKyJIuH

Closes #358

2023-05-12 12:12 UTC, gkirgizov requested changes
Вижу, что зависимости долго устанавливаются (4-5 минут), в духе torch, tensorflow, nltk (maybe) и мб еще какие-то. Может, их тоже вынести в интеграцию? Всего несколько тестов от них завияст, ниже на картинке у меня тесты падают как раз из-за отсутсвия таких зависимостей.

![изображение](https://github.com/aimclub/FEDOT/assets/10994117/15312ce2-b4d6-4929-8a63-50dbe53ef9d8)

Еще `test_table_cv.py` довольно долго крутится (локально 2-3 минуты), не пойму, из-за чего именно. Посмотришь тоже?

2023-05-12 12:15 UTC, IIaKyJIuH commented on test/unit/tasks/test_forecasting.py
>  from copy import deepcopy
Ага, это с линтингом была проблема.
[Исправил](https://github.com/aimclub/FEDOT/pull/1098/commits/840c4bef9157cb243747049b45d1f557a31f8a3b#diff-6d41b63f94e61d0658f76ccecf8d4c053f40c46a52e168b51bc112381926e0bdL2)

2023-05-15 13:41 UTC, IIaKyJIuH commented
> Вижу, что зависимости долго устанавливаются (4-5 минут), в духе torch, tensorflow, nltk (maybe) и мб еще какие-то. Может, их тоже вынести в интеграцию? Всего несколько тестов от них завияст, ниже на картинке у меня тесты падают как раз из-за отсутсвия таких зависимостей -- их тогда тоже нужно перенести.
> 
> ![изображение](https://user-images.githubusercontent.com/10994117/237966466-15312ce2-b4d6-4929-8a63-50dbe53ef9d8.png)
> 
> Еще `test_table_cv.py` довольно долго крутится (локально 2-3 минуты), не пойму, из-за чего именно. Посмотришь тоже?

С [такими правками](https://github.com/aimclub/FEDOT/pull/1098/commits/2b693348bf6908e0c66b0605e521bfb8c1d4af3d) по комментарию удалось сократить время исполнения тестов до 5 минут.

2023-05-22 11:37 UTC, gkirgizov approved these changes

2023-05-22 12:00 UTC, nicl-nno commented
А нет способа заставить codecov учитывать и интеграционные тесты тоже?

2023-05-22 12:03 UTC, IIaKyJIuH commented
> А нет способа заставить codecov учитывать и интеграционные тесты тоже?

Вот я думал об этом, но, кажется, что привязка покрытия идёт к запущенным тестам. Попробую ещё покопать.

2023-05-22 12:56 UTC, merged