Debug mode and modified fitness evaluation for for time series
aimclub/FEDOT pull request #1116
Opened 2023-07-04 19:52 UTC by nicl-nno

FEDOT_ANALYTIC_MODE=True param is added

Output path for degub is C:\Users\user\AppData\Local\Temp\FEDOT\ts_forecasting_debug

2023-07-24 14:09 UTC, kasyanovse approved these changes

2023-07-25 13:10 UTC, YamLyubov requested changes

2023-07-25 13:46 UTC, ChrisLisbon requested changes

2023-07-26 11:57 UTC, kasyanovse commented on fedot/api/api_utils/api_params_repository.py
> -            validation_blocks = 2
Исправлено.

2023-07-26 11:57 UTC, kasyanovse commented on fedot/api/api_utils/api_params_repository.py
> -            validation_blocks = 2
Скорректировано.

2023-07-26 11:58 UTC, kasyanovse commented on fedot/core/optimisers/objective/data_source_splitter.py
> +                                                  data.task.task_params.forecast_length)
Так действительно лучше, логика перенесена в InputAnalyser.give_recommendations.

2023-07-26 11:59 UTC, kasyanovse commented on fedot/core/optimisers/objective/data_source_splitter.py
> +                split_ratio = self.split_ratio or default_data_split_ratio_by_task[data.task.task_type]
После правок стало неактуально.

2023-07-31 11:27 UTC, kasyanovse commented on fedot/core/optimisers/objective/data_source_splitter.py
> +                                                  data.task.task_params.forecast_length)
А потом эта логика была удалена)
Теперь validation_blocks определяются автоматически внутри DataSourceSplitter, задать в Fedot больше нет возможности.

2023-07-31 11:28 UTC, kasyanovse commented on fedot/api/api_utils/api_params_repository.py
> -            validation_blocks = 2
Больше неактуально.

2023-07-31 11:28 UTC, kasyanovse commented on fedot/api/api_utils/api_params_repository.py
> -            validation_blocks = 2
Неактуально.

2023-07-31 14:06 UTC, YamLyubov requested changes
Правильно ли я поняла, что идея в том, чтобы пользователь сам не устанавливал `validation_blocks`? Ниже расписала проблему, которую вижу с этим. Логика, конечно, не самая очевидная, но надеюсь я более-менее объяснила. Надо бы пройтись по коду и по примерам - проверить, что с этим все нормально.

2023-07-31 14:16 UTC, kasyanovse commented on fedot/api/main.py
> +            Defaults to ``False``.
Просто привел в соответствие с дефолтным значением.

2023-07-31 14:17 UTC, kasyanovse commented on test/unit/data/test_data_split.py
> +                          # (DataSourceSplitter(cv_folds=3, shuffle=True), get_balanced_data_to_test_mismatch()),
Тест из-за бага не проходит #1119. Пока закомментил, в другой ветке чиню.

2023-07-31 14:33 UTC, kasyanovse commented on examples/simple/time_series_forecasting/api_forecasting.py
> +    train_data, test_data = train_test_data_setup(train_input)
Спасибо за такое подробное замечание))

Вообще, звучит как баг, нет?

2023-07-31 14:40 UTC, kasyanovse commented on fedot/api/main.py
> -        in_sample = in_sample if in_sample is not None else self._is_in_sample_prediction
Точно, пропустил вариант предсказания out-of-sample. Исправил.

2023-08-07 11:13 UTC, YamLyubov requested changes
Стоит еще обновить документацию для time series forecasing в этом или следующем pr. https://fedot.readthedocs.io/en/latest/basics/ts_forecasting.html

2023-08-07 11:13 UTC, YamLyubov commented on fedot/core/pipelines/tuning/tuner_builder.py
> -                                                       validation_blocks=self.validation_blocks,
Я так пониаю, что здесь по аналогии с `GPComposer` в `PipelineObjectiveEvaluate` надо передать количество валидационных блоков, определенных в `DataSourceSplitter`

2023-08-07 11:13 UTC, YamLyubov commented on fedot/core/pipelines/tuning/tuner_builder.py
> -    def with_validation_blocks(self, validation_blocks: int):
Подумала, что может стоит оставить возможность задавать количество валидационных блоков для тюнера? Это убобно при ручном запуске тюнинга

2023-08-08 06:58 UTC, kasyanovse commented on examples/simple/time_series_forecasting/api_forecasting.py
>      in_sample_forecast = model.predict(test_data)
Исправлено.

2023-08-08 06:58 UTC, kasyanovse commented on examples/advanced/surrogate_optimization.py
> +                            validation_blocks=2))
Исправлено.

2023-08-08 06:59 UTC, kasyanovse commented on fedot/core/pipelines/tuning/tuner_builder.py
> -                                                       validation_blocks=self.validation_blocks,
Исправлено.

2023-08-08 06:59 UTC, kasyanovse commented on fedot/core/pipelines/tuning/tuner_builder.py
> -    def with_validation_blocks(self, validation_blocks: int):
Вернул валидационные блоки обратно.

2023-08-08 07:43 UTC, YamLyubov approved these changes

2023-08-08 09:53 UTC, ChrisLisbon approved these changes

2023-08-08 09:53 UTC, ChrisLisbon commented on fedot/core/optimisers/objective/data_source_splitter.py
> +                                   f" Cross validation folds is set to {proposed_cv_folds_count}"))
Так блоков же достаточное количество, cannot be provided - опечатка или я чего-то не понимаю?

2023-08-08 10:04 UTC, kasyanovse commented on docs/source/basics/ts_forecasting.rst
> -to forecast next 10 values.
Логично. Перенес в раздел `Prediction`.

2023-08-08 10:07 UTC, kasyanovse commented on fedot/core/optimisers/objective/data_source_splitter.py
> +                                   f" Cross validation folds is set to {proposed_cv_folds_count}"))
cannot be provided - это для старого количества блоков `self.cv_folds`.
Новое, достаточное, - `proposed_cv_folds_count`.

2023-08-08 10:35 UTC, merged