Version variable added
aimclub/FEDOT pull request #1118
Opened 2023-07-06 16:21 UTC by nicl-nno

Version variable is added to support the following snippet:

from fedot import __version__
print(__version__)

2023-07-07 15:32 UTC, MorrisNein requested changes
[Вот тут](https://packaging.python.org/en/latest/guides/single-sourcing-package-version/) есть рекомендации, как сохранить версию фреймворка только в одном месте (она дублируется в setup.py)

Думаю, стоит воспользоваться

2023-07-07 15:41 UTC, MorrisNein commented
Можно создать version.py, в котором ничего не импортировать. Там задать переменную `__version__`. После этого импортировать эту переменную и в init, и в setup. 

Насколько я понимаю, в setup нужно, чтобы никакие компоненты фреймворка не импортировались. Поэтому нужен отдельный модуль, где ничего не импортируется, либо вообще текстовый файл.

2023-07-12 21:49 UTC, nicl-nno commented
Вынес как ты предложил. Надеюсь это в pypi сработает.

2023-07-13 12:05 UTC, MorrisNein requested changes
Попробовал сделать локальный build, получилось.

Попробовал загрузить на test.pypi.org - не получилось с вот такой ошибкой:

```
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
         Invalid value for requires_dist. Error: Can't have direct dependency: 'thegolem @ git+https://github.com/aimclub/GOLEM.git@stable#egg=thegolem'```

С реальным PyPI не возникает такой проблемы?

2023-07-13 12:05 UTC, MorrisNein commented on fedot/__init__.py
Теперь сюда нужно добавить строку, чтобы удовлетворить цели PR 

`from fedot.version import __version__`

2023-07-13 12:42 UTC, gkirgizov commented on fedot/__init__.py
да, в PyPi нельзя иметь завиимости такого вида. Поэтому для релизов зависимость отт ГОЛЕМа ставится на конкреттную версию

2023-07-13 12:44 UTC, gkirgizov approved these changes

2023-07-13 13:43 UTC, MorrisNein approved these changes

2023-07-13 13:55 UTC, merged