fix pos_label
aimclub/FEDOT pull request #1131
Opened 2023-08-02 11:12 UTC by valer1435

Error with pos_label when passing binary string target was fixed

2023-08-08 10:40 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +                         if not node.nodes_from]
Вроде у node есть метод is_primary.

2023-08-08 10:41 UTC, nicl-nno commented on fedot/core/pipelines/random_pipeline_factory.py
> +        is_primary_node_selected = height < max_depth - 1 and random.random() > 0.3
0.3 бы вынести в константу куда-то.

2023-08-08 10:42 UTC, nicl-nno commented on fedot/core/pipelines/verification_rules.py
> +        if not node.nodes_from:
Тут тоже можно на node.is_primary проверять

2023-08-08 11:42 UTC, aPovidlo requested changes

2023-08-08 11:42 UTC, aPovidlo commented on fedot/core/composer/gp_composer/specific_operators.py
> +def add_resample_mutation(pipeline: Pipeline, **kwargs):
Как-то без описания мутации и примера не совсем понятно что происходит

2023-08-08 11:42 UTC, aPovidlo commented on fedot/core/composer/metrics.py
>          return f1_score(y_true=reference.target, y_pred=predicted.predict,
Не понимаю немного. Если ошибка в том, что значения таргета и предикта принимают строковый тип, то разве это не лечится тем, что мы переводим значения в массивах в `int` при подсчете метрики? В этом случае `pos_label` совсем не нужен же.

2023-08-08 11:42 UTC, aPovidlo commented on fedot/core/operations/operation.py
> +        data = deepcopy(data)
А зачем?

2023-08-09 07:49 UTC, valer1435 commented on fedot/core/composer/metrics.py
>          return f1_score(y_true=reference.target, y_pred=predicted.predict,
Pos_label нужен для указания минорного класса в данных. Существуют данные, в которых нулевой класс представлен как минорный. А так как pos_label по умолчанию=1, ты будешь считать f1 по мажоритарному классу. Простым перегоном в инты это не решить

2023-08-09 07:51 UTC, valer1435 commented on fedot/core/operations/operation.py
> +        data = deepcopy(data)
В fit не уверен нужно ли это сейчас, добавил для избежания проблем в будущем. 

А в методе predict происходит неочевидное изменение полей у объекта входных данных
![image](https://github.com/aimclub/FEDOT/assets/32017472/13714616-3b7d-4732-9f74-4cab55c0f9dc)

2023-08-09 07:52 UTC, valer1435 commented on fedot/core/operations/operation.py
> +        data = deepcopy(data)
Из-за этого у тебя данные, прогнанные не через pipeline.predict, а через root_node.predict получают метку о том, что они предобработанны

2023-08-09 14:29 UTC, valer1435 commented on fedot/core/operations/operation.py
> +        data = deepcopy(data)
Если есть идеи, как это можно пофиксить без потери в скорости - буду рад услышать

2023-08-09 14:48 UTC, valer1435 commented on fedot/core/operations/operation.py
> +        data = deepcopy(data)
[Добавил ](https://github.com/aimclub/FEDOT/pull/1131/commits/544c5f6a6a0c8e1d7afb99b4854733372d3ffba2#diff-059ec354537ba96e9848bd54fe1320f3fefcb434caedb0a5e111a03c9d62428dR95)докстринг.

А в целом идея проста - в начало пайплайна добавляется resample. То есть он подцепляется ко всем primary_nodes

2023-08-09 14:53 UTC, valer1435 commented on fedot/core/composer/gp_composer/specific_operators.py
> +def add_resample_mutation(pipeline: Pipeline, **kwargs):
[Добавил ](https://github.com/aimclub/FEDOT/pull/1131/commits/544c5f6a6a0c8e1d7afb99b4854733372d3ffba2#diff-059ec354537ba96e9848bd54fe1320f3fefcb434caedb0a5e111a03c9d62428dR95)докстринг.

А в целом идея проста - в начало пайплайна добавляется resample. То есть он подцепляется ко всем primary_nodes

2023-08-09 14:53 UTC, valer1435 commented on fedot/core/pipelines/random_pipeline_factory.py
> +        is_primary_node_selected = height < max_depth - 1 and random.random() > 0.3
[Вынес](https://github.com/aimclub/FEDOT/pull/1131/commits/544c5f6a6a0c8e1d7afb99b4854733372d3ffba2#diff-93bdf18de5e4e89f2bb6558e4c6aed4bf6334b3900916496d6e3714df6d87b9fR18)

2023-08-09 14:54 UTC, valer1435 commented on fedot/core/pipelines/pipeline.py
> +                         if not node.nodes_from]
[Поменял](https://github.com/aimclub/FEDOT/pull/1131/commits/544c5f6a6a0c8e1d7afb99b4854733372d3ffba2#diff-234d33139f2520fa65ffcb8d6bb7a6958e97b3aae2cd3def0ac8cfd37f4a8d7aR340)

2023-08-09 15:05 UTC, nicl-nno commented on fedot/core/operations/operation.py
> +        data = deepcopy(data)
А это точно нужно именно в operation? Это действительно очень дорого делать deepcopy всех данных для каждого узла в пайплайне.

Кстати не очень понял почему тут вообще ставится флаг obligatorily_preprocessed. Вроде код выше за это не отвечает.

2023-08-09 15:06 UTC, aPovidlo commented on fedot/core/operations/operation.py
> +        data = deepcopy(data)
@valer1435 Думаю, что пока не критично. В целом, это проблема для PR по оптимизации используемой памяти

2023-08-11 07:57 UTC, valer1435 commented on fedot/core/operations/operation.py
> +        data = deepcopy(data)
> А это точно нужно именно в operation? Это действительно очень дорого делать deepcopy всех данных для каждого узла в пайплайне.
> 
> Кстати не очень понял почему тут вообще ставится флаг obligatorily_preprocessed. Вроде код выше за это не отвечает.

Да, это дорого, поэтому хотелось бы найти обходной путь. obligatory_preprocessed ставится в predict. Подумаю, может это и не нужно

2023-08-14 09:05 UTC, valer1435 commented on fedot/core/operations/operation.py
> +        data = deepcopy(data)
Удалил deepcopy и убрал присвоение флага препроцессинга

2023-08-14 09:35 UTC, merged