Refactor of data splitters
aimclub/FEDOT pull request #1138
Opened 2023-08-09 13:34 UTC by kasyanovse

1. Add support of multimodal data to cross validation
2. Add stratification for classification by default (#1119)
3. All data splitter function parameters are unified (shuffle_flag in `train_test_data_setup` was retained for backward compatibility)
4. Many checks added in `DataSourceSplitter` and `train_test_data_setup`
5. `core.validation.split.py` module is moved to `core.data.cv_folds.py`
6. New tests are added
7. `DataObjectiveAdvisor` is deleted because stratification if enable by default
8. `OneFoldInputDataSplit` is deleted because `cv_generator` get checked parameters from `DataSourceSplitter`. Cross validation always may be done.
9. Some old tests relay on unstratified samples. `DataSourceSplitter` and `train_test_data_setup` are call 
 with `stratify=False` in that cases.

2023-08-10 14:11 UTC, aPovidlo approved these changes

2023-08-14 09:42 UTC, andreygetmanov requested changes

2023-08-14 09:42 UTC, andreygetmanov commented on fedot/core/data/cv_folds.py
> +    :param data: InputData for train and test splitting
Если `data` может быть и `InputData`, и `MultiModalData`, лучше определить обобщённее: `data for train and test splitting`

2023-08-14 09:42 UTC, andreygetmanov commented on fedot/core/optimisers/objective/data_source_splitter.py
> +    :param log: Log for logging.
Порядок переменных в докстринге не совпадает с порядком переменных в классе. Так и должно быть?

2023-08-14 10:05 UTC, kasyanovse commented on fedot/core/data/cv_folds.py
> +    :param data: InputData for train and test splitting
Исправлено.

2023-08-14 10:05 UTC, kasyanovse commented on fedot/core/optimisers/objective/data_source_splitter.py
> +    :param log: Log for logging.
Исправлено.

2023-08-14 12:05 UTC, andreygetmanov approved these changes

2023-08-14 13:01 UTC, nicl-nno commented
Не забудь только pep8-замечания поправить.

2023-08-14 13:02 UTC, nicl-nno commented on fedot/core/optimisers/objective/data_source_splitter.py
> +                if self.cv_folds % 1 != 0:
Думаю более pythonic-вариант - попробовать привести к int и обработать исключение.

2023-08-14 13:20 UTC, kasyanovse commented
> Не забудь только pep8-замечания поправить.

Поправил. Осталось два замечания, но с кодом в указанных местах все нормально.

2023-08-14 13:23 UTC, merged