Add agent type
aimclub/FEDOT pull request #1142
Opened 2023-08-14 09:38 UTC by maypink

WIP

2023-08-22 13:49 UTC, gkirgizov requested changes

2023-08-22 13:49 UTC, gkirgizov commented on fedot/api/main.py
> +        The full range of context agents can be obtained here: golem.core.optimizers.adaptive.context_agents
Вряд ли этот комментарий кому-то пригодиться. Его с разбегу поймешь только ты, мне пришлось 5 раз вчитаться, Люба еще поймет. А те кто не знает -- им это не поможет. Предлагаю написать что-нибудь краткое, что поймет потенциальный рядовой пользователь и без технических деталей. Мол, "экспериментальная функциональность для адаптивной эволюции.... За деталями -- туда-то"

2023-09-04 11:48 UTC, maypink commented on fedot/api/main.py
> +        The full range of context agents can be obtained here: golem.core.optimizers.adaptive.context_agents
[done](https://github.com/aimclub/FEDOT/pull/1142/files#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR164)

2023-09-05 09:20 UTC, YamLyubov approved these changes

2023-09-05 09:20 UTC, YamLyubov commented on fedot/core/pipelines/pipeline_node_factory.py
> +        return available_operations
Можешь рассказать, для чего этот метод потенциально нужен?

2023-09-05 09:20 UTC, YamLyubov commented on fedot/api/main.py
> +        Both these params are a part of experimental functionality for adaptive evolution.
Может быть все-таки добавить что-то типа: "...Both these params are a part of experimental functionality for adaptive evolution. Adaptive evolution uses multi-armed bandits to choose most promising mutation at each iteration...."?

2023-09-05 14:30 UTC, maypink commented on fedot/core/pipelines/pipeline_node_factory.py
> +        return available_operations
там чтобы получать ембеддинги графов нужно либо иметь выбранный контекстнуальный агент как синглтон (чтобы он помнил все операции/модели в графах, что через него проходили), либо изначально подавать ему список всех доступных операций

2023-09-05 14:33 UTC, maypink commented on fedot/api/main.py
> +        Both these params are a part of experimental functionality for adaptive evolution.
как скажете

2025-05-13 12:52 UTC, closed without merging