Prediction Intervals
aimclub/FEDOT pull request #1149
Opened 2023-08-18 13:59 UTC by GrigoriJasnovidov

Prediction intervals for time series forecasting task functionality, unit tests and examples.

2023-08-18 14:15 UTC, nicl-nno requested changes
Оставил несколько небольших комментариев.

2023-08-18 14:15 UTC, nicl-nno commented on fedot/core/pipelines/prediction_intervals/solvers/mutation_of_best_pipeline.py
> +        show_progress (bool): flag to show progress
Убери типы данных из докстрингов (тут и в других аналогичных местах), они дублируют type hint что выше.

2023-08-18 14:15 UTC, nicl-nno commented on fedot/core/pipelines/prediction_intervals/solvers/mutation_of_best_pipeline.py
> +
Лишние пустые строки тут и ниже.

2023-08-18 14:15 UTC, nicl-nno commented on test/unit/pipelines/prediction_intervals/test_solver_mutations.py
> +        if x == params_different:
Тут видимо нужен elif. Ну и есть вариант params_with_replacement - для него вроде вообще никакой проверки не происходит.

2023-08-18 14:15 UTC, nicl-nno commented on test/unit/pipelines/prediction_intervals/test_solver_mutations.py
> +        model = pickle.load(f)
Выше есть очень похожая часть кода, их нельзя совместить?

2023-08-18 14:15 UTC, nicl-nno commented on test/unit/pipelines/prediction_intervals/test_prediction_intervals.py
> +    input_name = f'{fedot_project_root()}/test/unit/data/pred_ints_train_input_test.pickle'
А что в этом файле, временной ряд? Лучше ряд сохранить в csv, иначе при изменении архитектуры будут проблемы с тем, что pickle нужно генерировать заново.

model - это видимо API fedot? Скинь тогда отдельно куда-то скрипт, которым этот файл можно сгенерировать.

2023-08-18 14:59 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/solvers/mutation_of_best_pipeline.py
> +        show_progress (bool): flag to show progress
сделал

2023-08-18 15:13 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/solvers/mutation_of_best_pipeline.py
> +
удалил пустые строчки

2023-08-18 15:32 UTC, GrigoriJasnovidov commented on test/unit/pipelines/prediction_intervals/test_solver_mutations.py
> +        if x == params_different:
поставил elif и сделал проверку для params_with_replacement

2023-08-18 15:47 UTC, GrigoriJasnovidov commented on test/unit/pipelines/prediction_intervals/test_solver_mutations.py
> +        model = pickle.load(f)
Убрал model_name и input_name

2023-08-18 15:58 UTC, nicl-nno commented on examples/advanced/time_series_forecasting/prediction_intervals.py
> +    pred_ints.plot(ts_test=ts_test)
Запустил пример - что-то он какой-то невыразительный график дает. Так и должно быть?

![image](https://github.com/aimclub/FEDOT/assets/5711814/4ebc2f20-befc-4e6f-9667-97b3bfb62382)

В любом случае непонятно, что значит оранжевая линия.

2023-08-18 16:01 UTC, GrigoriJasnovidov commented on examples/advanced/time_series_forecasting/prediction_intervals.py
> +    pred_ints.plot(ts_test=ts_test)
вероятно, это древняя версия примера. Буду его обновлять

2023-08-18 20:46 UTC, nicl-nno commented on test/unit/pipelines/prediction_intervals/test_prediction_intervals.py
> +    input_name = f'{fedot_project_root()}/test/unit/data/pred_ints_train_input_test.pickle'
Если inputdata получается из CSV одной строчкой - то лучше сохранить csv.

2023-08-21 10:26 UTC, kasyanovse requested changes

2023-08-21 10:26 UTC, kasyanovse commented on fedot/core/pipelines/prediction_intervals/utils.py
> +        raise TypeError("Argument 'method' is incorrect.")
Здесь правильней применять `ValueError`.

2023-08-21 10:26 UTC, kasyanovse commented on fedot/core/pipelines/prediction_intervals/visualization.py
> +    fig.set(figwidth=15, figheight=7)
Не лучше будет вынести в аргументы?

2023-08-21 10:26 UTC, kasyanovse commented on fedot/core/pipelines/prediction_intervals/visualization.py
> +        label = 'Base quantiles'
А если ни одно условие не окажется истинным?

2023-08-21 10:26 UTC, kasyanovse commented on test/unit/pipelines/prediction_intervals/test_mutation.py
> +    return model.history.individuals[-1][0]
А не проще собрать новый объект `Individual` внутри функции с помощью кода, чем хранить целого Федота в .pickle?

2023-08-21 10:34 UTC, kasyanovse commented on fedot/core/pipelines/prediction_intervals/utils.py
> +        raise TypeError("Argument 'method' is incorrect.")
И можно в ошибку сразу вывести все возможные значения для `method`.

2023-08-21 10:48 UTC, nicl-nno commented on fedot/core/pipelines/prediction_intervals/main.py
> +                 params: PredictionIntervalsParams = PredictionIntervalsParams()):
Тогда аргументов будет слишком много.

2023-08-21 11:05 UTC, kasyanovse commented on fedot/core/pipelines/prediction_intervals/main.py
> +                 params: PredictionIntervalsParams = PredictionIntervalsParams()):
Сейчас всего 18 аргументов. Штук 5 можно упростить, останется 13 - это будет меньше, чем сейчас в `PredictionIntervalsParams`. Столько можно будет завести в один метод?

Можно упростить:
1. `show_progress`. Просто выводить все в лог.
2. `copy_model`. Я по коду писал, возможно, что можно отказаться от копирования модели в принципе.
3. `ql_number_models` и `bpq_number_models` слить в один параметр `number_models`.
4. `ql_tuner_validation_blocks`. Не актуальный параметр из-за последних пулреквестов.
5. `params`. Уйдет если отказаться от `PredictionIntervalsParams`.

2023-08-21 12:28 UTC, GrigoriJasnovidov commented on test/unit/pipelines/prediction_intervals/test_prediction_intervals.py
> +    input_name = f'{fedot_project_root()}/test/unit/data/pred_ints_train_input_test.pickle'
Добавил отдельно скрипт и дату в формате csv. 

Здесь модель обучается минуты 3, это не критично. Но может быть зависание с ее обучением которое приведет к тому что тестироваться все будет больше 15 минут.

2023-08-21 12:48 UTC, nicl-nno commented on fedot/core/pipelines/prediction_intervals/main.py
> +                 params: PredictionIntervalsParams = PredictionIntervalsParams()):
Больше семи аргументов все-таки иметь не стоит. Особенно если они объединяются в логическую группу.

В аналогичный местах для оптимизатора и проч. тоже выносили в датакласс.

2023-08-21 14:16 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/utils.py
> +        return (pickle.load(f))
В принципе, да реализовать model_copy в рамках - хорошая идея. Лучше копировать модель федота, так как мы меняем model.current_pipeline, и вроде model.forecast. Теоретически эти изменения могут повлиять на что-то при повторном использовании модели. Поэтому безопаснее работать с копией модели.

Вроде мы говорили с Колей, что уметь правильно копировать модель Fedot - это отдельный пул реквест, так как
текущий способ не оптимальный.

2023-08-21 14:23 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/main.py
> +        return {'up_int': up_int, 'low_int': low_int}
Поправил, действительно должно возвращаться self.up_int и self.low_int

2023-08-21 14:26 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/main.py
> +           nominal_error: nominal error for prediction intervals task
Это называется интервал прогнозирования (prediction interval), в принципе это похожие вещи. 
https://en.wikipedia.org/wiki/Prediction_interval

2023-08-21 14:26 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/metrics.py
> +    return np.mean(metrics)
Да, я только за)

2023-08-21 14:34 UTC, kasyanovse commented on fedot/core/pipelines/prediction_intervals/main.py
> +           nominal_error: nominal error for prediction intervals task
Я про `nominal_error`. По умолчанию параметр задается в 0,1. Это значит, что строится интервал, в котором ожидается реальное значение с вероятностью 0,9?

2023-08-21 14:34 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/metrics.py
> +    return s / length
Давай я только за)

2023-08-21 14:36 UTC, kasyanovse commented on fedot/core/pipelines/prediction_intervals/utils.py
> +        return (pickle.load(f))
Как я понял, в федоте меняется текущий пайплайн, чтобы сделать предсказание.
Можно отказаться от использования федота, заменив его функцией [out_of_sample_ts_forecast](https://github.com/aimclub/FEDOT/blob/500d91c89af5cc1c73b2a3ee208022d916227601/fedot/core/pipelines/ts_wrappers.py#L15). Тогда не надо будет его копировать, можно будет работать напрямую с пайплайном.

2023-08-21 14:37 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/metrics.py
> +def cwc(true: np.array, low: np.array, up: np.array, mu: float = 0.9, eta: float = 1, normalize_aiw=False):
Эта метрика вообще весьма своебразная. 
Она используется только для оценки результатов, для построения интервалов прогнозирования она не нужна. 

Я думаю ее лучше удалить, она имеет следующий дефект - для огромных интервалов прогнозирования покрывающих большую область около прогноза она 0.

2023-08-21 14:38 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/main.py
> +           nominal_error: nominal error for prediction intervals task
Да

2023-08-21 14:43 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/metrics.py
> +    up = np.array(up)
Убрал это преобразование

2023-08-21 14:43 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/metrics.py
> +    up = np.array(up)
Убрал это преобразование

2023-08-21 14:48 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/metrics.py
> +def interval_score(true: np.array, low: np.array, up: np.array, alpha: float = 0.1, weight: float = 2):
Здесь я думаю что да. Эта метрика используется только для оценки результатов, так что никаких проблем с дефолтными значениями не должно возникать.

Эта метрика - небольшое обобщение более или менее известной метрики interval score https://arxiv.org/pdf/2007.05709.pdf 
У них параметр weight всегда равен 2, если я не ошибаюсь. Параметр alpha в таких задачах тоже очень 
часто равен 0.1 иногда бывает 0.05. 

Так что здесь дефолтные значения - немного уменьшают длину кода при использовании.

2023-08-21 14:48 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/metrics.py
> +            array = np.append(array, 0)
Давай)

2023-08-21 14:50 UTC, GrigoriJasnovidov commented on examples/advanced/time_series_forecasting/prediction_intervals.py
> +    idx = np.array(range(len(np.array(ts))))
сделал

2023-08-21 15:04 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/solvers/best_pipelines_quantiles.py
> +        preds = model.forecast(horizon=horizon)
У нас PredictionIntervals очень сильно полагается на обученную модель федота, поэтому он всегда работает на тех же данных, на которых обучалась модель федота.

Механизм работы всего процесса следующий: 
1) сначала инициализируется PredictionIntervals при помощи модели федота. 
2) Далее идет метод PredictionIntervals.fit(train_input), который собственно и вычисляет 
набор предсказаний нескольких моделей, на основании которых будут строиться интервалы прогнозирования. Здесь аргумент train_input - это ровно тот же train_input который подавали модели федота 
modet.fit(train_input). Соответственно, model.train_data или что-то то подобное не используется никак (оно немного отличается от train_input, по крайней мере в старой версии). 
3) Вызывается метод forecast(), который строит интервалы прогнозирования на основе self.up_int и self.low_int.
Если при построении интервалов предсказания строились при помощи метода ''last_generation_ql'' то этот метод имеет несколько разных способ построения интервалов

2023-08-21 15:09 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/solvers/mutation_of_best_pipeline.py
> +            metric_value = RMSE.get_value(pipeline=pipeline, reference_data=train_input, validation_blocks=2)
Здесь суть в следующем. Когда мы считаем metric_value, наша цель отсеять потенциально очень плохие пайплайны - то есть те, которые имеют очень большое значение metric_value. Поэтому нам не сильно важно значение validation_blocks, будь то 1, 2 или 5.

2023-08-21 15:10 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/solvers/mutation_of_best_pipeline.py
> +    return predictions
На самом деле, такое теоретически возможно, но на практике не встречалось ни разу. 
Я думаю, что добавлю исключение с предложением использовать больше мутаций.

2023-08-21 15:12 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/ts_mutation.py
> +                  'lasso', 'ts_naive_average', 'locf', 'pca', 'linear', 'smoothing']
Наверное нет. Просто на момент разработки это места, некоторые мутации вызывали странные ошибки, поэтому я взял такой список. Наверное надо бы увеличить список мутаций.

2023-08-21 15:16 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/utils.py
> +           'up': np.quantile(resids, 1 - nominal_error / 2, method='median_unbiased')}
Вроде бы я только для одномерных данных это делал. Про многомерные - я не знаю будет ли работать.

Но вопрос интересный.

2023-08-21 16:52 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/utils.py
> +        raise TypeError("Argument 'method' is incorrect.")
Поправил ошибку и добавил значения метода.

2023-08-21 17:01 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/visualization.py
> +        label = 'Base quantiles'
Это внутренний параметр, отвечающий за подписи к графику. При вызове метода plot() у PredictionIntervals автоматически вызывается plot_prediction_intervals() с параметром labels='pred_ints', a если вызывается plot_base_quantiles() то автоматически вызывается plot_prediction_intervals() с параметром labels='base_quantiles'.

Так что здесь не нужно проверять значения labels.

2023-08-21 17:21 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/solvers/mutation_of_best_pipeline.py
> +    return predictions
Сделал

2023-08-21 17:25 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/ts_mutation.py
> +    return mutation._mutation(individual)[0]
Мне кажется так было до некоторого момента. Ошибка здесь должна влечь поломку всех тестов, так что здесь все должно быть в порядке. Сейчас возвращается tuple. https://github.com/aimclub/GOLEM/blob/main/golem/core/optimisers/genetic/operators/mutation.py

2023-08-21 17:41 UTC, nicl-nno commented on examples/advanced/time_series_forecasting/prediction_intervals.py
> +    pred_ints.plot(ts_test=ts_test)
Так а как на интервалы-то посмотреть?

2023-08-21 20:08 UTC, nicl-nno commented on fedot/core/pipelines/prediction_intervals/utils.py
> +           'up': np.quantile(resids, 1 - nominal_error / 2, method='median_unbiased')}
Предлагаю в этом PR-е ограничиться одномерными. Но надо конечно проверить чтобы поведение для многомерных было понятным (явный exception, например).

2023-08-22 09:06 UTC, kasyanovse commented on fedot/core/pipelines/prediction_intervals/solvers/mutation_of_best_pipeline.py
> +        metric_value = RMSE.get_value(pipeline=pipeline, reference_data=train_input, validation_blocks=2)
Я сейчас посмотрел внутрь get_value. А можно ли в данном случае использовать validation_blocks=None?

2023-08-22 09:14 UTC, kasyanovse commented on fedot/core/pipelines/prediction_intervals/solvers/mutation_of_best_pipeline.py
> +    return predictions
> такое теоретически возможно

Это уже достаточно для обработки.

Я бы сюда докинул еще обработку варианта когда получается всего 1-2 пайплайна. Такое малое количество пайплайнов не могут повлиять на точность оценки?

2023-08-24 15:02 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/utils.py
> +        return (pickle.load(f))
Избавился от копирования всего федота. В файле utils есть теперь функция get_last_generations, которая из модели федота вытаскивает финальный пайплайн и последнее поколение.

2023-08-24 15:27 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/visualization.py
> +    fig.set(figwidth=15, figheight=7)
сделал

2023-08-24 18:01 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/solvers/best_pipelines_quantiles.py
> +    elif number_models > number_avaliable_pipelines:
Добавил проверку всех подобных условий в функцию check_init_params https://github.com/aimclub/FEDOT/blob/prediction_intervals/fedot/core/pipelines/prediction_intervals/utils.py

Этот параметр можно задавать только через класс PredictionIntervalsParams, а при запуске PredictionIntervals есть автоматическая проверка что все параметры такие, какие нужно.

2023-08-24 18:02 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/solvers/mutation_of_best_pipeline.py
> +    best_pipeline = model.history.individuals[-1][0]
везде теперь model.history.generations

2023-08-25 13:35 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/ts_mutation.py
> +    return mutations
Сделал

2023-08-25 13:49 UTC, nicl-nno commented on examples/advanced/time_series_forecasting/prediction_intervals.py
> +    pred_ints.plot(ts_test=ts_test)
![image](https://github.com/aimclub/FEDOT/assets/5711814/61f01f1f-74ab-4430-afbe-f1494098f02e)

Теперь нарисовалось - но только после того как я plt.show() в plot_prediction_intervals добавил.

2023-08-25 13:57 UTC, GrigoriJasnovidov commented on examples/advanced/time_series_forecasting/prediction_intervals.py
> +    pred_ints.plot(ts_test=ts_test)
Да, видимо дело в этом. Добавил plt.show() в visualization/plot_prediction_intervals().

2023-08-25 15:25 UTC, nicl-nno commented on examples/advanced/time_series_forecasting/prediction_intervals.py
> +    # init_series = d[d['label'] =='temp']['value'].to_numpy()
Но не удалил же.

2023-08-25 15:51 UTC, nicl-nno commented on fedot/core/pipelines/prediction_intervals/utils.py
> +    l_inds = [(ind.fitness.value, pipeline_simple_structure(ind), ind.uid) for ind in unique_inds]
Функция выше закомментирована.

2023-08-28 15:06 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/ts_mutation.py
> +        new_pipeline = pipeline_simple_structure(new_ind)
Реализовал сравнение более правильным способом. При генерации мутаций сравнение идет через метод __eq__ реализованный в классе Graph. В функции get_different_pipelines из utils.py сравнение сделано через расширение функции get_distance_between из golem.core.dag.linked_graph. Причина здесь следующая: метод __eq__ сравнивает не толкьо структуру графа, но и внутренние параметры  и гиперпараметры узлов графа, то есть, два графа с одинаковой структурой будут показаны им как разные.

2023-08-28 15:18 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/ts_mutation.py
> +            number_pipelines += 1
сделал нечто подобное

2023-08-28 15:18 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/utils.py
> +    return list(map(lambda x: x.name, ind.graph.graph_description['nodes']))
ответил выше

2023-08-28 15:36 UTC, nicl-nno approved these changes

2023-08-29 15:29 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/ts_mutation.py
> +                  'lasso', 'ts_naive_average', 'locf', 'pca', 'linear', 'smoothing']
Теперь используются все достуные мутации для предсказания временных рядов.

2023-08-30 11:31 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/ts_mutation.py
> +        new_pipeline = pipeline_simple_structure(new_ind)
В итоге сделал все через метод get_distance_between, потомучто __eq__ иногда говорит что графы разные если они отличаются только гиперпараметрами.

2023-08-30 14:50 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/ts_mutation.py
> +                  'lasso', 'ts_naive_average', 'locf', 'pca', 'linear', 'smoothing']
Используются только стабильно работающие мутации. Удалил ариму из списка мутаций.

2023-08-30 15:54 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/ts_mutation.py
> +                  'lasso', 'ts_naive_average', 'locf', 'pca', 'linear', 'smoothing']
Я счас протестировал, проблемы возникают только при участи 'cgru', 'scaling' и 'normalization', с остальными моделями и дата-операциями все работает.

2023-08-31 12:46 UTC, kasyanovse requested changes

2023-08-31 12:46 UTC, kasyanovse commented on fedot/core/pipelines/prediction_intervals/solvers/mutation_of_best_pipeline.py
> +        raise ValueError('Variable predictions is empty list. Try to increase number_mutations to solve this problem.')
Не пробовал сделать ограничение на определенное количество пайплайнов, как мы обсуждали?

2023-08-31 12:46 UTC, kasyanovse commented on fedot/core/pipelines/prediction_intervals/ts_mutation.py
> +            mutations.append(new_ind)
В цикле while всегда следует делать остановку по превышению количества циклов. На всякий случай. Предельное количество циклов можно взять как 2-3-n * number_mutations.

2023-08-31 12:46 UTC, kasyanovse commented on fedot/core/pipelines/prediction_intervals/utils.py
> +        if np.array([get_distance_between(s.graph, x, compare_node_params=False) > 0 for x in graph_list]).all():
В `get_distance_between` результат функции преобразуется кодом: `int(distance)`. Получается, что при `distance = .1` два графа считаются одинаковыми?

2023-08-31 12:46 UTC, kasyanovse commented on fedot/core/pipelines/prediction_intervals/utils.py
> +    return {'final_choice': generations[-1][0], 'last_generation': generations[-2]}
`final_choice` лучше вытащить через `fedot.current_pipeline`, потому что, если не ошибаюсь, в последнем поколении может быть больше 1 пайплайна и не факт, что в порядке роста фитнеса.

2023-08-31 15:58 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/utils.py
> +    return {'final_choice': generations[-1][0], 'last_generation': generations[-2]}
final_choice должен иметь тип Individual. Можно отсортировать списко последнего поколения по фитнесу и брать индивид с лучшим фитнесом.

2023-08-31 15:59 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/ts_mutation.py
> +            mutations.append(new_ind)
Сделал + добавил логгер, чтобы он сообщал, если мутации кончились

2023-08-31 16:00 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/main.py
> +                 horizon: int = None,
сделал

2023-08-31 16:14 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/main.py
> +            self.horizon = horizon
сделал

2023-08-31 16:17 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/solvers/mutation_of_best_pipeline.py
> +        raise ValueError('Variable predictions is empty list. Try to increase number_mutations to solve this problem.')
Если у нас лист не пустой, то может просто мы будем ругаться через логгер?
В принципе это не наша ошибка, такое может взяться если юзер взял очень мало мутаций. 
Теоретически, может быть даже интересно смотреть на 1,2,3 мутации и видеть что произойдет.

2023-09-01 06:41 UTC, kasyanovse commented on fedot/core/pipelines/prediction_intervals/utils.py
> +        if np.array([get_distance_between(s.graph, x, compare_node_params=False) > 0 for x in graph_list]).all():
А не наоборот? Не получится ли что при distance = 0.1 два графа будут восприняты как одинаковые?

2023-09-01 06:53 UTC, kasyanovse commented on fedot/core/pipelines/prediction_intervals/solvers/mutation_of_best_pipeline.py
> +        raise ValueError('Variable predictions is empty list. Try to increase number_mutations to solve this problem.')
Другой вопрос, как это скажется на работоспособности по умолчанию. Мне кажется, что по умолчанию все должно работать надежно и только при желании можно начинать копаться в параметрах. А тут получается, что иногда может случиться так, что интервалы будут неточными и виноват в этом пользователь, что не знал что и где задать и что на что может повлиять и не читал при этом логгер на уровне INFO.

Я бы сделал ограничение минимального количества на уровне в несколько предсказаний (тут нужна экспертная оценка). Пусть выпадет ошибка, где будет четко сказано что сделать, чтобы все заработало, и пользователь, выполнив указания, получит хороший результат.

Делай на свой вкус)

2023-09-01 12:53 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/utils.py
> +    return {'final_choice': generations[-1][0], 'last_generation': generations[-2]}
сделал

2023-09-01 12:59 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/solvers/mutation_of_best_pipeline.py
> +        raise ValueError('Variable predictions is empty list. Try to increase number_mutations to solve this problem.')
В настройках по умолчанию будет стоять 30*0.66 = 19 мутаций, так что шанс что будет совсем мало мутаций достаточно маленький. Я в общем все же думаю что с логгером будет лучше.

2023-09-04 10:54 UTC, GrigoriJasnovidov commented on fedot/core/pipelines/prediction_intervals/utils.py
> +        if np.array([get_distance_between(s.graph, x, compare_node_params=False) > 0 for x in graph_list]).all():
Я немного посмотрел код + поэксперементировал, результат get_distance_between всегда получается целочисленным. Это видимо объясняется тем, что вершины в графах имеют имена а не дробные числа.

2023-09-04 11:49 UTC, kasyanovse approved these changes

2023-09-04 12:24 UTC, merged