Bugfix #1151
aimclub/FEDOT pull request #1153
Opened 2023-08-22 08:54 UTC by kasyanovse

2023-08-23 14:01 UTC, kasyanovse commented
Code for testing single core use in boosting models:

```
import numpy as np

from fedot.core.data.data import InputData
from fedot.core.pipelines.node import PipelineNode
from fedot.core.pipelines.pipeline import Pipeline
from fedot.core.repository.dataset_types import DataTypesEnum
from fedot.core.repository.tasks import Task, TaskTypesEnum

length = 1000
width = 10

data_class = InputData(idx=np.arange(length),
                       features=np.random.rand(length, width),
                       target=(np.random.rand(length) > 0.5).astype(int),
                       task=Task(TaskTypesEnum.classification),
                       data_type=DataTypesEnum.table)

data_reg = InputData(idx=np.arange(length),
                     features=np.random.rand(length, width),
                     target=np.random.rand(length),
                     task=Task(TaskTypesEnum.regression),
                     data_type=DataTypesEnum.table)

for data, models in zip([data_class, data_reg], [['xgboost', 'catboost', 'lgbm'], ['catboostreg', 'lgbmreg']]):
    for model in models:
        pipeline = Pipeline(PipelineNode(model))
        pipeline.fit(data)

```

2023-08-23 14:02 UTC, kasyanovse commented
Speed test for AR and ARIMA (for IPython):

```
import numpy as np

from fedot.core.data.data import InputData
from fedot.core.optimisers.objective import PipelineObjectiveEvaluate, MetricsObjective
from fedot.core.optimisers.objective.data_source_splitter import DataSourceSplitter
from fedot.core.pipelines.node import PipelineNode
from fedot.core.pipelines.pipeline import Pipeline
from fedot.core.repository.dataset_types import DataTypesEnum
from fedot.core.repository.quality_metrics_repository import RegressionMetricsEnum
from fedot.core.repository.tasks import Task, TaskTypesEnum, TsForecastingParams

length = 1000
data = np.random.rand(length)

data = InputData(idx=np.arange(len(data)),
                 features=data,
                 target=data,
                 data_type=DataTypesEnum.ts,
                 task=Task(TaskTypesEnum.ts_forecasting,
                           TsForecastingParams(forecast_length=2)))

data_splitter = DataSourceSplitter()
data_split = data_splitter.build(data)
objective_eval = PipelineObjectiveEvaluate(MetricsObjective(RegressionMetricsEnum.RMSE), data_split,
                                           validation_blocks=data_splitter.validation_blocks)

pipeline = Pipeline(PipelineNode('arima'))
%timeit pipeline.fit(data)
%timeit objective_eval.evaluate(pipeline)

pipeline = Pipeline(PipelineNode('ar'))
%timeit pipeline.fit(data)
%timeit objective_eval.evaluate(pipeline)

```

2023-08-29 16:52 UTC, valer1435 requested changes

2023-08-29 16:52 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/cgru.py
> +        if self.std != 0:
мб будет короче` return (array - self.mu) / (self.std + 1e-6)`?

2023-08-29 16:52 UTC, valer1435 commented on fedot/core/repository/data/model_repository.json
> +      "input_type": "[DataTypesEnum.table]",
Можешь пояснить, почему убрал multi_ts? Вроде для него как раз модели из sklearn_regr использовались? Или там неочевидно?

2023-08-29 16:52 UTC, valer1435 commented on test/integration/models/test_model.py
> +            target = np.zeros(length) + value
Может придумать что-то более реальное, чем константы? Или идея как раз в этом?

2023-08-29 16:52 UTC, valer1435 commented on test/integration/models/test_model.py
> +    to_skip = ['custom', 'arima', 'catboost', 'catboostreg',
Можно ли как-то эти модели найти по тегам? Так не будет проблем, когда будет добавлена новая модель, не подходящая под критерии теста

2023-08-30 13:12 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/cgru.py
> +        if self.std != 0:
Согласен. Скорректировал.

2023-08-30 13:13 UTC, kasyanovse commented on test/integration/models/test_model.py
> +    to_skip = ['custom', 'arima', 'catboost', 'catboostreg',
Эти модели внутри себя обрабатывают такое поведение, поэтому по тегам их выявить не получится.

2023-08-30 13:14 UTC, kasyanovse commented on fedot/core/repository/data/model_repository.json
> +      "input_type": "[DataTypesEnum.table]",
Модели из sklearn могут обрабатывать multi_ts аналогично тому, как он обрабатывается узлом lagged?

2023-08-30 13:17 UTC, kasyanovse commented on fedot/core/repository/data/model_repository.json
> +      "input_type": "[DataTypesEnum.table]",
Я посмотрел, у catboostregressor задан тип sklearn_regr. Вроде бы он воспринимает 2D массив в InputData.features как таблицу признаков, а не как набор данных с размерностью 1D.

2023-08-30 13:17 UTC, kasyanovse commented on fedot/core/repository/data/model_repository.json
> +      "input_type": "[DataTypesEnum.table]",
Или я чего-то не понимаю?

2023-08-31 09:01 UTC, valer1435 commented on fedot/core/repository/data/model_repository.json
> +      "input_type": "[DataTypesEnum.table]",
Понял, что имеется ввиду. Тогда да, все правильно, тут этого значения не должно быть

2023-08-31 10:48 UTC, valer1435 commented on test/integration/models/test_model.py
> +    to_skip = ['custom', 'arima', 'catboost', 'catboostreg',
Можешь проверить еще и glm?

2023-08-31 11:22 UTC, valer1435 reviewed
GLM стоит проверить

2023-08-31 11:23 UTC, valer1435 commented on test/integration/models/test_model.py
> +            target = np.zeros(length) + value
Тогда может вставить в название функции упоминание о том, что она выдает константные данные?

2023-08-31 12:59 UTC, kasyanovse commented on test/integration/models/test_model.py
> +            target = np.zeros(length) + value
А зачем?

2023-09-01 09:19 UTC, kasyanovse commented on test/integration/models/test_model.py
> +            target = np.zeros(length) + value
А, я понял.
Эта функция не только константные данные выдает. Она еще может случайные данные выдавать.

2023-09-03 06:36 UTC, valer1435 approved these changes

2023-09-03 17:20 UTC, merged