Boosting method implementation (Catboost)
aimclub/FEDOT pull request #1155
Opened 2023-08-22 16:42 UTC by aPovidlo

WIP

2023-08-22 16:58 UTC, nicl-nno commented on fedot/core/data/data.py
> +            features_names = df.drop(target_columns, axis=1).columns.to_nunpy()
nunpy

2023-08-22 17:01 UTC, nicl-nno commented on fedot/core/operations/evaluation/boostings.py
> +        return self._convert_to_output(prediction, predict_data)
А это всё нельзя откуда-то унаследовать?

2023-08-22 17:44 UTC, aPovidlo commented on fedot/core/operations/evaluation/boostings.py
> +        return self._convert_to_output(prediction, predict_data)
Думал над тем, чтобы заменить вызываемые классы бустингов в SklearnEvaluationStrategy, но там проблема с тем, что далее в fit не передается InputData, а np.ndarray массивы (x, y), также с параметрами params_for_fit. Этим отличаются конструкции и поэтому наследоваться не откуда

2023-09-04 09:18 UTC, valer1435 requested changes

2023-09-04 09:18 UTC, valer1435 commented on fedot/core/data/data.py
> +        if target_columns == '':
По идее могут прокинуть None? Тогда мб лучше сделать более общую проверку if not target_columns

2023-09-04 09:18 UTC, valer1435 commented on fedot/core/operations/evaluation/boostings.py
> +        operation_implementation = self.operation_impl(self.params_for_fit)
Можно ли перенести эту строчку в init?

2023-09-04 09:18 UTC, valer1435 commented on fedot/core/operations/evaluation/boostings.py
> +        return self._convert_to_output(prediction, predict_data)
![image](https://github.com/aimclub/FEDOT/assets/32017472/05e881ce-4689-46b6-b251-f478894f08e9)
 Кажется там передается InputData, можно метод фит просто переопределить

2023-09-04 09:18 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +            'use_eval_set': False,
Как будто эти параметры всегда будут false, если вручную не задать

2023-09-04 11:44 UTC, maypink requested changes

2023-09-04 11:44 UTC, maypink commented on fedot/core/data/data.py
> +    features_names: np.ndarray = None
типы в таком случае Optional[np.ndarray], как ниже

2023-09-04 11:44 UTC, maypink commented on fedot/core/operations/evaluation/boostings.py
> +        # 'xgboost': FedotXgboostBoostClassificationImplementation,
не забыть раскомментировать, если это для тестирования руками было сделано

2023-09-04 12:05 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +            'use_eval_set': False,
Так и подразумевается, `eval_set` будет скорее полезен при поисках оптимальных параметров

2023-09-04 12:19 UTC, aPovidlo commented on fedot/core/operations/evaluation/boostings.py
> +        operation_implementation = self.operation_impl(self.params_for_fit)
Тут делал аналогично тому как реализовано в [evaluation_strategy.py](https://github.com/aimclub/FEDOT/blob/b1f8bd63deedfe5d9428c16691967e2685fa9e58/fedot/core/operations/evaluation/evaluation_interfaces.py#L217)

2023-09-07 14:05 UTC, aPovidlo commented on fedot/core/pipelines/tuning/search_space.py
Да, точно. Совсем забыл для регрессии продублировать

2023-09-11 08:31 UTC, maypink requested changes

2023-09-11 08:31 UTC, maypink commented on fedot/core/data/data.py
> +                cat_features_names = self.features_names[self.categorical_features]
сходу непонятно, почему тут `self.features_names[self.categorical_features]`, а не `self.features_names[self.categorical_idx]`. ну и в таком случае стоит до конца проставить типы в 46-60 строках.

2023-09-11 08:31 UTC, maypink commented on fedot/core/data/data.py
> +            new_features_names = np.hstack(num_features_names, cat_features_names)
здесь точно одна пара скобок? по идее `np.hstack` принимает один аргумент

2023-09-11 09:10 UTC, maypink requested changes

2023-09-11 09:10 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/categorical_encoders.py
> +            self.encoded_ids = [i for i in range(non_categorical_features.shape[1], transformed_features.shape[1])]
range можно записать так же, как я писала выше

2023-09-11 09:10 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +        complete_params = {**default_params, **self.params.to_dict()}
что будет, если внутри переданных `params` будет лежать None?

2023-09-11 09:10 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +        self.params.update(**complete_params)
непонятно, зачем создается `complete_params` и потом им апдейтится `self.params`. вроде можно сделать `self.params = {**default_params, **self.params.to_dict()}` -- в таком случае просто значения, которые есть в переданных `params` перезапишут дефолтные

2023-09-11 12:00 UTC, aPovidlo commented on fedot/core/data/data.py
> +                cat_features_names = self.features_names[self.categorical_features]
Очепятка

2023-09-11 12:15 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +        complete_params = {**default_params, **self.params.to_dict()}
Если `None`, то они же далее в `ModelImplementation`  должны замениться на `OperationParameters()`.

2023-09-11 12:17 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +        self.params.update(**complete_params)
Делал аналогично тому, как сделано в [`FedotCNNImplementation`](https://github.com/aimclub/FEDOT/blob/7cd593e78d5ae8d216b52c6958c9aa5a45e1ba97/fedot/core/operations/evaluation/operation_implementations/models/keras.py#L158)

2023-09-11 12:18 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +        self.params.update(**complete_params)
Подумал, что стоит перенести default_params в json

2023-09-11 13:51 UTC, YamLyubov requested changes

2023-09-11 13:51 UTC, YamLyubov commented on fedot/core/repository/data/model_repository.json
> +        "tree", "non_linear"
Не совсем понимаю, почему здесь и в других случаях  нужно убирать тег `boosting`

2023-09-11 13:51 UTC, YamLyubov commented on fedot/core/operations/evaluation/boostings.py
> +        elif self.output_mode in ['probs', 'full_probs'] and predict_data.task:
А зачем нужна проверка на наличие `predict_data.task`?

2023-09-11 13:51 UTC, YamLyubov commented on fedot/core/operations/evaluation/boostings.py
> +            raise ValueError(f'Output model {self.output_mode} is not supported')
Кажется здесь опечатка model -> mode

2023-09-11 13:51 UTC, YamLyubov commented on fedot/core/operations/evaluation/boostings.py
> +        return operation_implementation
Можно сделать базовый класс `BoostingStrategy`, чтобы вынести в него этот код, так как он для обоих классов один и тот же вроде бы

2023-09-11 13:51 UTC, YamLyubov commented on fedot/core/data/visualisation.py
> +    if data.num_classes == 2 and prediction.predict.shape[1] != 2:
В каких случаях `prediction.predict.shape[1] == 2`?

2023-09-11 13:51 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +        self.params.update(**self.params.to_dict())
По-моему эта строчка не нужна - в базовом классе мы self.params и так присваиваем переданные параметры

2023-09-11 13:51 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +        if params['use_best_model'] or params['early_stopping_rounds'] and not params['use_eval_set']:
Здесь нужно работать именно с `OperationParameters`, так как этот класс записывает, какие параметры были изменены во время вычесления моделями. То есть нужно пользоваться  `OperationParameters.update`

2023-09-11 13:51 UTC, YamLyubov commented on fedot/core/pipelines/tuning/search_space.py
> +                    'hyperopt-dist': hp.loguniform,
Для дискретных значений не используется loguniform - лучше заменить на uniformint
http://hyperopt.github.io/hyperopt/getting-started/search_spaces/

2023-09-11 13:51 UTC, YamLyubov commented on fedot/core/pipelines/tuning/search_space.py
> +                    'hyperopt-dist': hp.loguniform,
Здесь так же стоит изменить распределение на дискретное

2023-09-11 13:51 UTC, YamLyubov commented on fedot/core/pipelines/tuning/search_space.py
> +                    'hyperopt-dist': hp.loguniform,
Не дискретное распределение

2023-09-11 13:58 UTC, aPovidlo commented on fedot/core/repository/data/model_repository.json
> +        "tree", "non_linear"
Текущий PR для CatBoost, два других фреймворка будут изменены в другое время. Сейчас этот тэг несет иную роль, чем прежде.  Они вернуться после добавления других бустинговых моделей.

2023-09-11 14:04 UTC, aPovidlo commented on fedot/core/operations/evaluation/boostings.py
> +        return operation_implementation
Да, думаю это будет разумно

2023-09-11 14:05 UTC, aPovidlo commented on fedot/core/data/visualisation.py
> +    if data.num_classes == 2 and prediction.predict.shape[1] != 2:
Когда модели возвращают np.array размерностью (n, 2). Например, CatBoost для задачи бинарной классификации выдает вероятности для каждого класса.

2023-09-11 14:07 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +        self.params.update(**self.params.to_dict())
В этой строке есть изменения

2023-09-19 13:26 UTC, YamLyubov requested changes

2023-09-25 12:07 UTC, aPovidlo commented on fedot/core/operations/evaluation/boostings.py
> +        elif self.output_mode in ['probs', 'full_probs'] and predict_data.task:
> Здесь в каких-то случаях может быть не 'classification'?

Делал аналогично какому-то реализованному методу, но думаю, что логично если этот метод и так для классификации, то можно и убрать.

2023-09-25 12:12 UTC, aPovidlo commented on fedot/core/data/data.py
> +                cat_features_names = self.features_names[self.categorical_features]
Исправил

2023-09-25 12:12 UTC, aPovidlo commented on fedot/core/data/data.py
> +            new_features_names = np.hstack(num_features_names, cat_features_names)
Исправил

2023-09-25 12:12 UTC, aPovidlo commented on fedot/core/data/data.py
> +            new_cat_idx = np.array([i for i in range(new_features.shape[1])])
Исправил

2023-09-25 12:13 UTC, aPovidlo commented on fedot/core/data/data.py
> +            new_num_idx = np.array([i for i in range(new_features.shape[1])])
И тут тоже исправил

2023-09-25 12:16 UTC, aPovidlo commented on fedot/core/data/data.py
> +    encoded_idx: np.ndarray = None
Добавил

2023-09-25 12:16 UTC, aPovidlo commented on test/integration/models/test_strategy.py
> +        print(metric)
Убрал

2023-09-25 12:55 UTC, MorrisNein commented on fedot/core/data/data.py
> +            new_cat_idx = np.array([i for i in range(new_features.shape[1])])
Тут вроде как даже можно обойтись `np.arange(new_features.shape[1])`

2023-09-26 08:35 UTC, nicl-nno commented on test/integration/models/test_strategy.py
> +def test_boosting_regression_operation():
А по времени этот тест норм работает? Синт. датасет не самый маленький.

2023-09-26 08:36 UTC, nicl-nno approved these changes

2023-10-05 12:37 UTC, maypink requested changes

2023-10-05 12:37 UTC, maypink commented on fedot/core/data/data.py
> +    categorical_features: Optional[np.ndarray] = None
в `OutputData` есть `encoded_idx`. Надо убрать, если они определены в самой `Data`

2023-10-05 12:37 UTC, maypink commented on fedot/core/data/data.py
> +    categorical_features: Optional[np.ndarray] = None
но, честно говоря, мне кажется, что с 46 по 49 строчку -- это должныть быть в `InputData`, тк `Data` здесь просто как базовый класс в который загружаются данные из файлов разного формата и никаких действимй с ними не выполняется.

2023-10-05 15:08 UTC, aPovidlo commented on test/integration/models/test_strategy.py
> +def test_boosting_regression_operation():
![image](https://github.com/aimclub/FEDOT/assets/22475542/faee3e5e-fe68-4235-924a-7f234976dbd9)

2023-10-05 15:08 UTC, aPovidlo commented on test/integration/models/test_strategy.py
> +def test_boosting_regression_operation():
Может быть увеличится с добавлением других бустинговых методов

2023-10-10 11:33 UTC, maypink approved these changes

2023-10-10 12:57 UTC, MorrisNein approved these changes

2023-10-13 09:51 UTC, YamLyubov approved these changes

2023-10-17 16:12 UTC, merged