Remove redundant metrics mapping
aimclub/FEDOT pull request #1167
Opened 2023-09-07 13:24 UTC by YamLyubov

WIP

2023-09-13 11:54 UTC, MorrisNein requested changes

2023-09-13 11:54 UTC, MorrisNein commented on fedot/api/api_utils/api_composer.py
>                   .with_iterations(DEFAULT_TUNING_ITERATIONS_NUMBER)
Почему тут только по первой из метрик? Возможно, индекс лишний?

2023-09-13 11:54 UTC, MorrisNein commented on fedot/api/main.py
> +        metric = ensure_wrapped_in_sequence(metric_name)[0] if metric_name else self.metrics[0]
Вот тут снова только первая из метрик используется. Интересно, почему такое дефолтное поведение.

Так или иначе `ensure_wrapped_in_sequence(metric_name)[0]` выглядит избыточным, если принимается только единичная `metric_name`

2023-09-13 11:54 UTC, MorrisNein commented on fedot/api/main.py
> +        metric_names = [str(metric) for metric in ensure_wrapped_in_sequence(metrics)]
В строке 511 избыточный `ensure_wrapped_in_sequence`, т.к. в `self.metrics` храним метрики списком

2023-09-13 11:54 UTC, MorrisNein commented on fedot/core/optimisers/objective/metrics_objective.py
> +            if isinstance(metric, Callable):
Такую проверку можно производить ключевым словом callable: `callable(metric)`

2023-09-13 11:54 UTC, MorrisNein commented on test/unit/pipelines/prediction_intervals/__init__.py
> +    pathlib.WindowsPath = pathlib.PosixPath
Это чтобы пути с прямым слэшем работали?

2023-09-14 09:28 UTC, YamLyubov commented on fedot/api/api_utils/api_composer.py
>                   .with_iterations(DEFAULT_TUNING_ITERATIONS_NUMBER)
Это нужно, так как у нас сейчас через api используется только `SimultaneousTuner`, а он работате только для однокритериальной оптимизации

2023-09-14 09:34 UTC, YamLyubov commented on test/unit/pipelines/prediction_intervals/__init__.py
> +    pathlib.WindowsPath = pathlib.PosixPath
Это нужно для тестов с предсказательными интервалами.

Данные тесты используют pkl файл `pred_ints_model_test.pickle`, который хранит инстанс `Fedot`. Так как я поменяла архитектуру федота, мне пришлось этот файл сгенерировать заново. Я работаю на windows -> в pickle записались виндовсовские пути. При загрузке этого пр тесты на github упали, так как они запускаются на linux.

2023-09-14 10:19 UTC, MorrisNein approved these changes

2023-09-14 10:19 UTC, MorrisNein commented on fedot/api/main.py
>                      :class:`~fedot.core.repository.quality_metrics_repository.ComplexityMetricsEnum`
Посмотри, пожалуйста, в результате изменений - эта докстринга актуальна?

2023-09-14 14:16 UTC, merged