Fix some bugs
aimclub/FEDOT pull request #1174
Opened 2023-09-25 09:11 UTC by kasyanovse

2023-09-25 09:12 UTC, pep8speaks commented
Hello @kasyanovse! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py`](https://github.com/aimclub/FEDOT/blob/f71b69082a0073647493b305b0062c7b8cf4fea8/fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py):

> [Line 116:9](https://github.com/aimclub/FEDOT/blob/f71b69082a0073647493b305b0062c7b8cf4fea8/fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py#L116): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'prefix' is assigned to but never used

* In the file [`test/integration/models/test_model.py`](https://github.com/aimclub/FEDOT/blob/f71b69082a0073647493b305b0062c7b8cf4fea8/test/integration/models/test_model.py):

> [Line 29:1](https://github.com/aimclub/FEDOT/blob/f71b69082a0073647493b305b0062c7b8cf4fea8/test/integration/models/test_model.py#L29): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.repository.operation_types_repository.AVAILABLE_REPO_NAMES' imported but unused

2023-09-28 13:31 UTC, valer1435 requested changes

2023-09-28 13:42 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        if self.window_size + forecast_length > len(time_series):
Кидать ошибку. Это некорректный случай.
Идея в том, чтобы убрать скрытое поведение. Если тюнер или композер хотят поставить некорректное значение окна, то пусть они узнают об этом.

2023-09-28 13:43 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        self.window_size_minimum = 4
Где-то в тестах ряд задан так, что не проходит с минимальным окном в 6. Раньше в этом тесте оно само подстраивалось.

2023-09-28 13:44 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +                                   for i in range(ts_target.shape[0] - forecast_length + 1)])
stack - это конкатенация, она медленнее, чем np.array.

2023-09-28 13:48 UTC, kasyanovse commented on fedot/utilities/ts_gapfilling.py
> +            if node.name == 'lagged':
Так это и есть внутри. Разве нет?

2023-09-28 13:51 UTC, kasyanovse commented on fedot/utilities/ts_gapfilling.py
> +                    node.parameters = {'window_size': data_length - forecast_length - 1}
Этот код срабатывает только тогда, когда данных почти что нет. Толку от лишнего сэмпла я бы не ожидал, потому что на 90% он будет состоять из тех же точек.
И возникает вопрос, сколько сэмплов брать? Опять же, нужно будет выбирать их количество с учетом того, что и окно, размером в 2 точки маловато может быть.
В общем, мне кажется, что взять максимальное окно и не париться - вполне рабочий вариант.

2023-09-28 13:52 UTC, kasyanovse commented on fedot/utilities/ts_gapfilling.py
> +                    node.parameters = {'window_size': data_length - forecast_length - 1}
К тому же, я рассчитываю на автоматический расчет окна в lagged в будущем)

2023-09-28 13:54 UTC, kasyanovse commented on test/integration/models/test_model.py
> +            for data_type in operation.input_types:
Для грубой оценки вполне можно.
Если есть идеи что еще можно прикрутить - я за))

2023-09-28 13:55 UTC, kasyanovse commented on test/unit/validation/test_time_series_cv.py
> +    ppl_ss = PipelineSearchSpace({'lagged': {'window_size': {'hyperopt-dist': hp.uniformint,
Да. Там очень небольшое количество тестовых данных, тюнер легко вылетает в область недопустимых окон и все падает, так как lagged выкидывает ошибку о недопустимости размера окна.

2023-09-28 14:15 UTC, kasyanovse commented on fedot/core/pipelines/prediction_intervals/solvers/mutation_of_best_pipeline.py
> +        for i, m in enumerate(range(len(first_pred_constraints))):
Пофиксил.

2023-09-29 07:39 UTC, valer1435 commented on fedot/utilities/ts_gapfilling.py
> +            if node.name == 'lagged':
Сейчас получается так, что, если у lagged преобразования длина окна слишком большая для конкретного ряда, то вываливается ошибка, которая нигде не обрабатывается. Это код только для замены пропусков, длина окна будет подбираться только для этой задачи, а в общем случае будет ошибка. То есть придется в любой код, в котором мы не хотим, чтобы вываливалась ошибка, писать подобные условия

2023-09-29 08:04 UTC, valer1435 requested changes

2023-09-29 08:04 UTC, valer1435 commented on test/integration/models/test_model.py
> +            for data_type in operation.input_types:
Мне кажется тут нужно смотреть разницу на больших рядах (допустим 1000 или больше). На маленьких рядах даже тяжелый алгоритм будет работать "быстро", что не показательно

2023-09-29 08:04 UTC, valer1435 commented on test/unit/validation/test_time_series_cv.py
> +    ppl_ss = PipelineSearchSpace({'lagged': {'window_size': {'hyperopt-dist': hp.uniformint,
А как сейчас эта ошибка вообще обрабатывается?

2023-09-29 08:17 UTC, kasyanovse commented on fedot/utilities/ts_gapfilling.py
> +                    node.parameters = {'window_size': data_length - forecast_length - 1}
Там же по умолчанию длина окна 10, разве нет? И проблема возникает только при малом количестве точек.

2023-09-29 08:20 UTC, kasyanovse commented on test/integration/models/test_model.py
> +            for data_type in operation.input_types:
Если тяжелый алгоритм работает быстро на малом количестве точек, то надо просто уставку занизить))
А вообще, у алгоритмов есть минимальное время работы, которое, по сути, здесь и проверятся, и время работы, зависящее от количества данных.

А какую уставку по времени для 1к и для 10к точек ты бы задал?

2023-09-29 08:20 UTC, kasyanovse commented on test/unit/validation/test_time_series_cv.py
> +    ppl_ss = PipelineSearchSpace({'lagged': {'window_size': {'hyperopt-dist': hp.uniformint,
Тюнером?

2023-09-29 08:23 UTC, kasyanovse commented on fedot/utilities/ts_gapfilling.py
> +            if node.name == 'lagged':
Все правильно, разве нет?
Если длина окна задана некорректно, то мы получаем ошибку. Это как с пайплайном. Сейчас некорректные начальные пайплайны вываливают ошибку, а не сами как-то корректируются.

2023-09-29 13:59 UTC, valer1435 commented on test/unit/validation/test_time_series_cv.py
> +    ppl_ss = PipelineSearchSpace({'lagged': {'window_size': {'hyperopt-dist': hp.uniformint,
Например. Или композером

2023-09-29 14:07 UTC, valer1435 commented on test/integration/models/test_model.py
> +            for data_type in operation.input_types:
Поэкспериментировать - посмотреть, для каких порогов, какие модели не проходят. Будет в том числе полезно понять, какое реальное время работы у тех или иных алгоритмов. А потом выбрать порог - чтобы все нужные модели проходили, возможно придется сделать несколько порогов, например, для пресетов fast_train и best_quality

2023-10-03 11:56 UTC, GrigoriJasnovidov approved these changes

2023-10-16 06:40 UTC, kasyanovse commented on test/integration/models/test_model.py
> +            for data_type in operation.input_types:
Я отталкивался от обратной мылси: принять какой-то условный порог и посмотреть какие модели не проходят, а не сначала выбрать модели, а потом под них подгонять порог.

Для моделей `best_quality` вообще порог не нужен, как мне кажется. Он имеет смысл только для `fast_train`, потому что сам критерий `fast_train` подразумевает скорость работы.

2023-10-16 07:25 UTC, kasyanovse commented on test/unit/validation/test_time_series_cv.py
> +    ppl_ss = PipelineSearchSpace({'lagged': {'window_size': {'hyperopt-dist': hp.uniformint,
С композером проблем нет, потому что оценка пайплайна обернута в `try-except`, пайплайн с некорректным окном получается некорректным. Тюнер вылетает. Теперь вот не знаю, откатить это изменение или скорректировать тюнер.

2023-10-17 07:31 UTC, valer1435 commented on test/unit/validation/test_time_series_cv.py
> +    ppl_ss = PipelineSearchSpace({'lagged': {'window_size': {'hyperopt-dist': hp.uniformint,
А можно ли тюнер обернуть в try except?

2023-10-17 07:44 UTC, kasyanovse commented on test/unit/validation/test_time_series_cv.py
> +    ppl_ss = PipelineSearchSpace({'lagged': {'window_size': {'hyperopt-dist': hp.uniformint,
Починю тюнер тогда.

2023-10-17 10:14 UTC, kasyanovse commented on test/unit/validation/test_time_series_cv.py
> +    ppl_ss = PipelineSearchSpace({'lagged': {'window_size': {'hyperopt-dist': hp.uniformint,
Тюнер в починке не нуждается. Он корректно отрабатывает ошибки.

2023-10-17 12:47 UTC, valer1435 approved these changes

2023-10-17 12:57 UTC, merged