Add desc to not implemented errors
aimclub/FEDOT pull request #1177
Opened 2023-09-28 13:21 UTC by valer1435

Closes https://github.com/aimclub/FEDOT/issues/259

2023-09-28 13:21 UTC, pep8speaks commented
Hello @valer1435! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`fedot/api/api_utils/assumptions/assumptions_builder.py`](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/api/api_utils/assumptions/assumptions_builder.py):

> [Line 127:21](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/api/api_utils/assumptions/assumptions_builder.py#L127): [E131](https://duckduckgo.com/?q=pep8%20E131) continuation line unaligned for hanging indent









* In the file [`fedot/core/composer/metrics.py`](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/core/composer/metrics.py):

> [Line 49:80](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/core/composer/metrics.py#L49): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'self'
> [Line 54:80](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/core/composer/metrics.py#L54): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'self'





















* In the file [`fedot/core/operations/operation.py`](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/core/operations/operation.py):

> [Line 124:9](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/core/operations/operation.py#L124): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)











* In the file [`fedot/preprocessing/base_preprocessing.py`](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/preprocessing/base_preprocessing.py):

> [Line 52:1](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/preprocessing/base_preprocessing.py#L52): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 60:9](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/preprocessing/base_preprocessing.py#L60): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 66:1](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/preprocessing/base_preprocessing.py#L66): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 74:9](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/preprocessing/base_preprocessing.py#L74): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 81:1](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/preprocessing/base_preprocessing.py#L81): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 89:9](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/preprocessing/base_preprocessing.py#L89): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 97:1](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/preprocessing/base_preprocessing.py#L97): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 133:1](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/preprocessing/base_preprocessing.py#L133): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 141:9](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/preprocessing/base_preprocessing.py#L141): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 156:9](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/preprocessing/base_preprocessing.py#L156): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 185:9](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/preprocessing/base_preprocessing.py#L185): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 188:1](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/preprocessing/base_preprocessing.py#L188): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 191:1](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/preprocessing/base_preprocessing.py#L191): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 223:1](https://github.com/aimclub/FEDOT/blob/404d79cae918abf2ed3268fa994eca1c2f8ec3fa/fedot/preprocessing/base_preprocessing.py#L223): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2023-09-28 13:23 UTC, valer1435 commented
работает примерно так 
![image](https://github.com/aimclub/FEDOT/assets/32017472/7b111b06-660b-45e8-a838-263a62786d53)

2023-09-28 13:45 UTC, kasyanovse requested changes

2023-09-28 13:45 UTC, kasyanovse commented on fedot/api/api_utils/assumptions/assumptions_builder.py
> +        raise NotImplementedError(f'Method {stack()[0][3]} not implemented in {self.__class__}')
Лучше писать что это абстрактный метод и его нельзя вызывать. Во всех наследниках этого класса этот метод будет реализован, никаких проблем с его отсутствием не будет. Абстрактный метод можно вызвать только через `super()`, так что по идее ошибка может быть только в попытке его вызвать.

2023-09-28 13:45 UTC, kasyanovse commented on fedot/api/api_utils/assumptions/assumptions_builder.py
> +        raise NotImplementedError(f'Method {stack()[0][3]} not implemented in {self.__class__}')
Лучше писать что это абстрактный метод и его нельзя вызывать. Во всех наследниках этого класса этот метод будет реализован, никаких проблем с его отсутствием не будет. Абстрактный метод можно вызвать только через `super()`, так что по идее ошибка может быть только в попытке его вызвать.

2023-09-28 13:45 UTC, kasyanovse commented on fedot/api/api_utils/assumptions/operations_filter.py
> +        raise NotImplementedError(f'Method {stack()[0][3]} not implemented in {self.__class__}')
Лучше писать что это абстрактный метод и его нельзя вызывать. Во всех наследниках этого класса этот метод будет реализован, никаких проблем с его отсутствием не будет. Абстрактный метод можно вызвать только через `super()`, так что по идее ошибка может быть только в попытке его вызвать.

2023-09-28 13:45 UTC, kasyanovse commented on fedot/api/api_utils/assumptions/task_assumptions.py
> +        raise NotImplementedError(f'Method {stack()[0][3]} not implemented in {self.__class__}')
Лучше писать что это абстрактный метод и его нельзя вызывать. Во всех наследниках этого класса этот метод будет реализован, никаких проблем с его отсутствием не будет. Абстрактный метод можно вызвать только через `super()`, так что по идее ошибка может быть только в попытке его вызвать.

2023-09-28 13:45 UTC, kasyanovse commented on fedot/api/api_utils/assumptions/task_assumptions.py
> +        raise NotImplementedError(f'Method {stack()[0][3]} not implemented in {self.__class__}')
Лучше писать что это абстрактный метод и его нельзя вызывать. Во всех наследниках этого класса этот метод будет реализован, никаких проблем с его отсутствием не будет. Абстрактный метод можно вызвать только через `super()`, так что по идее ошибка может быть только в попытке его вызвать.

2023-09-28 13:45 UTC, kasyanovse commented on fedot/api/api_utils/assumptions/task_assumptions.py
> +        raise NotImplementedError(f'Method {stack()[0][3]} not implemented in {self.__class__}')
Лучше писать что это абстрактный метод и его нельзя вызывать. Во всех наследниках этого класса этот метод будет реализован, никаких проблем с его отсутствием не будет. Абстрактный метод можно вызвать только через `super()`, так что по идее ошибка может быть только в попытке его вызвать.

2023-09-28 13:45 UTC, kasyanovse commented on fedot/core/composer/composer.py
> +        raise NotImplementedError(f'Method {stack()[0][3]} not implemented in {self.__class__}')
Лучше писать что это абстрактный метод и его нельзя вызывать. Во всех наследниках этого класса этот метод будет реализован, никаких проблем с его отсутствием не будет. Абстрактный метод можно вызвать только через `super()`, так что по идее ошибка может быть только в попытке его вызвать.

2023-09-28 13:45 UTC, kasyanovse commented on fedot/core/composer/metrics.py
> +        raise NotImplementedError(f'Method {stack()[0][3]} not implemented in {self.__class__}')
Лучше писать что это абстрактный метод и его нельзя вызывать. Во всех наследниках этого класса этот метод будет реализован, никаких проблем с его отсутствием не будет. Абстрактный метод можно вызвать только через `super()`, так что по идее ошибка может быть только в попытке его вызвать.

2023-09-28 13:45 UTC, kasyanovse commented on fedot/core/composer/metrics.py
> +        raise NotImplementedError(f'Method {stack()[0][3]} not implemented in {self.__class__}')
Лучше писать что это абстрактный метод и его нельзя вызывать. Во всех наследниках этого класса этот метод будет реализован, никаких проблем с его отсутствием не будет. Абстрактный метод можно вызвать только через `super()`, так что по идее ошибка может быть только в попытке его вызвать.

2023-09-28 13:45 UTC, kasyanovse commented on fedot/core/composer/metrics.py
> +        raise NotImplementedError(f'Method {stack()[0][3]} not implemented')
Лучше писать что это абстрактный метод и его нельзя вызывать. Во всех наследниках этого класса этот метод будет реализован, никаких проблем с его отсутствием не будет. Абстрактный метод можно вызвать только через `super()`, так что по идее ошибка может быть только в попытке его вызвать.

2023-09-28 13:45 UTC, kasyanovse commented on fedot/core/data/data_detection.py
> +        raise NotImplementedError(f'Method {stack()[0][3]} not implemented')
Лучше писать что это абстрактный метод и его нельзя вызывать. Во всех наследниках этого класса этот метод будет реализован, никаких проблем с его отсутствием не будет. Абстрактный метод можно вызвать только через `super()`, так что по идее ошибка может быть только в попытке его вызвать.

2023-09-28 13:45 UTC, kasyanovse commented on fedot/core/data/data_detection.py
> +        raise NotImplementedError(f'Method {stack()[0][3]} not implemented')
Лучше писать что это абстрактный метод и его нельзя вызывать. Во всех наследниках этого класса этот метод будет реализован, никаких проблем с его отсутствием не будет. Абстрактный метод можно вызвать только через `super()`, так что по идее ошибка может быть только в попытке его вызвать.

2023-09-28 13:45 UTC, kasyanovse commented on test/unit/pipelines/prediction_intervals/test_prediction_intervals.py
> -        pred_ints.plot()
Этот момент я у себя тоже пофиксил))
https://github.com/aimclub/FEDOT/pull/1174

2023-09-28 18:59 UTC, nicl-nno commented on fedot/api/api_utils/assumptions/task_assumptions.py
> +        raise NotImplementedError(f'Method {stack()[0][3]} is not implemented in {self.__class__}')
stack()[0][3] бы в какую-то служебную функцию вынести.

А конкретно для этого кейса - вообще целиком вся строка "raise NotImplementedError(f'Method {stack()[0][3]} is not implemented in {self.__class__}')" может быть вынесена.

2023-09-29 12:39 UTC, valer1435 commented on fedot/api/api_utils/assumptions/assumptions_builder.py
> +        raise NotImplementedError(f'Method {stack()[0][3]} not implemented in {self.__class__}')
Отпишу только здесь, тк по другим неактуально
 [Добавил ](https://github.com/aimclub/FEDOT/pull/1177/commits/ed8c38882396cd9085e656d313dd9695439fcd3c#diff-9ebd8b68b04b1906412707050e71cd320d13bc2db3d5963913b3c925de921a43R1)классы ошибок

2023-09-29 13:02 UTC, kasyanovse approved these changes

2023-10-02 07:36 UTC, merged