Integration tests fix v2
aimclub/FEDOT pull request #1183
Opened 2023-10-18 12:25 UTC by IIaKyJIuH

Rework of integration tests passing.

2023-10-18 14:39 UTC, nicl-nno commented on test/integration/real_applications/test_examples.py
> +    forecast = run_ts_forecasting_example(dataset='australia', timeout=1, with_tuning=with_tuning)
timeout=2 ломает тест?

2023-10-18 15:28 UTC, IIaKyJIuH commented on test/integration/real_applications/test_examples.py
> +    forecast = run_ts_forecasting_example(dataset='australia', timeout=1, with_tuning=with_tuning)
Видимо, да)

2023-10-18 15:55 UTC, nicl-nno commented on test/integration/real_applications/test_examples.py
> +    forecast = run_ts_forecasting_example(dataset='australia', timeout=1, with_tuning=with_tuning)
Как минимум пометь тогда жирным TODO с указанием на то, какую именно проблему вызывает другой таймаут.

2023-10-19 12:52 UTC, nicl-nno commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                  metric=['mase', 'mae', 'mape', 'rmse'],
Ну ниже они просто вычисляются, а тут они используются для оптимизации. Если не указать, то какой тест падает?

2023-11-09 13:25 UTC, aPovidlo requested changes

2023-11-09 13:25 UTC, aPovidlo commented on fedot/core/data/data.py
> +            raise ValueError('There is no features')
Может это лишнее. `get_not_encoded_data` возвращает данные, которые не содержат закодированные категориальные признаки. Если в данных нет численных признаков и нет категориальных, то поэтому и возвращаются такие же самые данные, которые были, условно говоря, на входе

2023-11-09 13:25 UTC, aPovidlo commented on fedot/core/operations/evaluation/boostings.py
> +        elif (self.output_mode in ['probs', 'full_probs', 'default'] and
А зачем это изменение?

2023-11-09 13:25 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +        self.classes_ = np.unique(np.array(input_data.target))
Не понятно, а зачем уточнять классы внутри?

2023-11-09 13:25 UTC, aPovidlo commented on test/integration/quality/test_quality_improvement.py
> +                           preset='fast_train',
А чем обусловлена замена пресета?

2023-11-09 13:25 UTC, aPovidlo commented on test/integration/real_applications/test_model_result_reproducing.py
> +    fedots = [get_fitted_fedot(forecast_length=len(test.idx),
Не совсем понимаю замену. Разве предыдущее не быстрее работает?

2023-11-09 13:26 UTC, aPovidlo commented on test/integration/quality/test_quality_improvement.py
> +                           preset='fast_train',
Также заметил, что и в других тоже есть замена на `'fast_train'`

2023-11-09 13:33 UTC, andreygetmanov requested changes

2023-11-09 13:33 UTC, andreygetmanov commented on fedot/utilities/ts_gapfilling.py
> +                    node.parameters = {'window_size': max(data_length - forecast_length - 10, 2)}
Здесь бы хорошо смотрелся небольшой комментарий, почему выбирается именно такой размер окна

2023-11-09 13:33 UTC, andreygetmanov commented on test/integration/pipelines/tuning/test_pipeline_tuning.py
> +        max_window = int(train_data.features.shape[0] / (folds + 1)) - (forecast_length * validation_blocks) - 1
Пояснишь комментарием этот кусок теста?

2023-11-09 13:58 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +        self.classes_ = np.unique(np.array(input_data.target))
Необходимо для корректной работы `ROC AUC`, для которой размер предикта зависит от количества классов. Если класс один, то это столбец, если больше, то это матрица с количеством столбцов, равным количеству классов.

2023-11-09 13:59 UTC, kasyanovse commented on test/integration/quality/test_quality_improvement.py
> +                           preset='fast_train',
Вопрос к @IIaKyJIuH

2023-11-09 14:02 UTC, kasyanovse commented on test/integration/real_applications/test_model_result_reproducing.py
> +    fedots = [get_fitted_fedot(forecast_length=len(test.idx),
Скорее всего в `test.idx` может лежать объект без свойства `shape`. Встречал похожую проблему в других местах.

2023-11-09 14:03 UTC, kasyanovse commented on fedot/core/operations/evaluation/boostings.py
> +        elif (self.output_mode in ['probs', 'full_probs', 'default'] and
Сделано в соответствии с `FedotClassificationStrategy`, потому что иначе не работают некоторые метрики.

2023-11-09 14:06 UTC, kasyanovse commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False, with_tuning=False, validation_blocks=2):
Тюнинг часто натыкается на несовместимые параметры у катбуста или некорректное окно у лаггед преобразования и вылетает с ошибкой. Чтобы уменьшить количество тестов, которые вылетают с этой проблемой, местами был отключен тюнинг.

2023-11-09 14:08 UTC, kasyanovse commented on fedot/api/api_utils/api_params_repository.py
> +            pass
Да, планируется починка отдельным PR. По факту мержа этого PR надо будет создать issue.

2023-11-09 14:10 UTC, kasyanovse commented on fedot/utilities/ts_gapfilling.py
> +                    node.parameters = {'window_size': max(data_length - forecast_length - 10, 2)}
Это кусок выпиленного алгоритма `LaggedImplementation`. Чтобы не нарушать работу `gapfilling`, этот код был перенесен сюда. Почему он такой я не знаю))

2023-11-09 14:12 UTC, kasyanovse commented on test/integration/quality/test_quality_improvement.py
> +                           preset='fast_train',
Кстати, возможно что проблема в катбусте. При `best_quality` он попадает в композицию и может вылетать с ошибкой при мутации параметров.

2023-11-09 14:35 UTC, andreygetmanov commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False, with_tuning=False, validation_blocks=2):
А можешь подробнее рассказать о несовместимых параметрах катбуста?
Я правильно понимаю, катбуст там может появиться после лаггед преобразования?
Почему нельзя в таком случае просто задать кастомное пространство поиска гиперпараметров или вообще убрать катбуст из списка возможных моделей?

2023-11-09 14:47 UTC, kasyanovse commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False, with_tuning=False, validation_blocks=2):
> А можешь подробнее рассказать о несовместимых параметрах катбуста?

Например: `min_data_in_leaf` может быть использовано только с `grow_policy in ['Lossguide', 'Depthwise']`. В остальных случаях использование этого параметра выдает ошибку.

> Я правильно понимаю, катбуст там может появиться после лаггед преобразования?

Да. В этом тесте проблема только с лаггед преобразованием, тут катбуст не используется в композиции.

> Почему нельзя в таком случае просто задать кастомное пространство поиска гиперпараметров или вообще убрать катбуст из списка возможных моделей?

1. Если задавать кастомное пространство поиска гиперпараметров:
    2. то его надо будет определить для всех параметров катбуста, учтя все возможные сочетания
    3. это нужно будет сделать везде, где он в теории может примениться
    4. нужно будет переписать функцию мутации параметров (скорее всего)
5. Если вариант исключить катбуст из тестирования прокатит, то я за, но он тогда не будет протестирован)) Вообще, катбусту очень не хватает юнит тестов. Ловить всякие ошибки и опечатки на интеграционниках очень сложно.

2023-11-10 07:37 UTC, kasyanovse commented on test/integration/pipelines/tuning/test_pipeline_tuning.py
> +        max_window = int(train_data.features.shape[0] / (folds + 1)) - (forecast_length * validation_blocks) - 1
Готово.

2023-11-10 07:42 UTC, kasyanovse commented on fedot/core/data/data.py
> +            raise ValueError('There is no features')
Этот метод много где приводил к ошибкам и часто выдавал `None` вместо признаков. Эта ошибка служит для удобства выявления такого поведения в дальнейшем, так как с усложнением класса `Data` все сложней и сложней отслеживать какие данные он в себе хранит, что возвращает, как оно внутри Федота преобразуется и т.д. В таком виде все работает, причин менять пока что не вижу, но подозреваю, что с текстовыми и графическими данными могут быть ошибки. Всплывут - будем править.

2023-11-10 10:25 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +        self.classes_ = np.unique(np.array(input_data.target))
А что делать с теми классами, которые не были в трейне, но появились в тесте или на валидации?

2023-11-10 10:30 UTC, aPovidlo commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False, with_tuning=False, validation_blocks=2):
@kasyanovse Встречал еще подобный параметр у катбуста и добавлял в имплементацию в федоте [такую проверку](https://github.com/aimclub/FEDOT/blob/70fc033921805b6b348844a87727d5c82bfe75c8/fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py#L50), чтобы она их исправляла. Может быть добавить еще одно такое правило, что если указан `min_data_in_leaf` и не используется нужное `grow_policy`, то исправлять эти параметры.

2023-11-10 10:33 UTC, aPovidlo commented on test/integration/quality/test_quality_improvement.py
> +                           preset='fast_train',
@kasyanovse [написал ниже комментарий](https://github.com/aimclub/FEDOT/pull/1183#discussion_r1389219964) по поводу катбуста. Стоит вынести эти проблемы и ошибки в отдельный ишью, чтобы разобраться с ними и полноценно использовать эту модель.

2023-11-10 10:36 UTC, aPovidlo commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False, with_tuning=False, validation_blocks=2):
@kasyanovse Тоже видимо нужно будет создать отдельный ишью для покрытия юнит тестами катбуста

2023-11-10 11:27 UTC, kasyanovse commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False, with_tuning=False, validation_blocks=2):
> добавлял в имплементацию в федоте [такую проверку](https://github.com/aimclub/FEDOT/blob/70fc033921805b6b348844a87727d5c82bfe75c8/fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py#L50)

Придется писать кучу правил проверки (параметров в катбусте ого-го), отлаживать эти проверки, актуализировать для каждой версии катбуста и делать все это не только для катбуста, но и для каждой сколь-нибудь сложной модели, у которой есть несовместимые параметры. Проще один раз разработать принципиальное решение.

2023-11-10 11:31 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +        self.classes_ = np.unique(np.array(input_data.target))
Эта проблема решена в `DataSourceSplitter`, где включена стратификация по умолчанию. Какие-то модели уже падали от подобного.

2023-11-10 11:32 UTC, kasyanovse commented on test/integration/quality/test_quality_improvement.py
> +                           preset='fast_train',
На полноценное использование модели это не влияет, потому что композер и тюнер выбрасывают ошибку в таком случае только в тестах.

2023-11-10 13:50 UTC, aPovidlo commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False, with_tuning=False, validation_blocks=2):
@kasyanovse кажется так поступают и другие. Их там не сильно много. Но что увеличивается поддержка этого кода, это да

2023-11-10 14:05 UTC, kasyanovse commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False, with_tuning=False, validation_blocks=2):
Странно, конечно, что это все только ради прохождения тестов.
Добавишь в этот PR?

2023-11-10 14:11 UTC, nicl-nno approved these changes

2023-11-10 14:39 UTC, kasyanovse commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False, with_tuning=False, validation_blocks=2):
Вообще, есть вариант просто убрать мутацию параметров в композере для тестов.

2023-11-10 14:40 UTC, aPovidlo commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False, with_tuning=False, validation_blocks=2):
> @aPovidlo Странно, конечно, что это все только ради прохождения тестов. Добавишь в этот PR?

Не совсем понял твой комментарий

2023-11-10 14:50 UTC, kasyanovse commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False, with_tuning=False, validation_blocks=2):
@aPovidlo 
Проблема актуальна только в тестах. Композер и тюнер игнорируют упавшие пайплайны в обычной работе.

2023-11-16 09:39 UTC, aPovidlo approved these changes

2023-11-17 11:03 UTC, andreygetmanov commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False, with_tuning=False, validation_blocks=2):
>     2. Если вариант исключить катбуст из тестирования прокатит, то я за, но он тогда не будет протестирован)) Вообще, катбусту очень не хватает юнит тестов. Ловить всякие ошибки и опечатки на интеграционниках очень сложно.

Насколько я знаю, катбуст относительно недавно добавили в модели
Я однозначно за отдельный PR с юнит-тестами для него. И я однозначно за интеграционники, которые покрывают катбуст, но их можно и отдельно сделать
Поэтому я за вариант убрать катбуст из этого теста
А только в этом тесте из-за него что-то падало?

И призываю @nicl-nno. Что думаешь? Какой вариант тебе кажется лучше?

2023-11-17 11:04 UTC, andreygetmanov commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False, with_tuning=False, validation_blocks=2):
> Вообще, есть вариант просто убрать мутацию параметров в композере для тестов.

Вот совсем против такой штуки
Мутация параметров в композере - это одна из базовых операций, есть риск очень многое поломать

2023-11-17 11:12 UTC, nicl-nno commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False, with_tuning=False, validation_blocks=2):
Если я правильно понимаю проблему - то вот такой вариант не поможет

![image](https://github.com/aimclub/FEDOT/assets/5711814/ace89fd9-d05a-4a41-9dd4-c5cbd0293d38)

?

2023-11-17 11:13 UTC, kasyanovse commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False, with_tuning=False, validation_blocks=2):
> Поэтому я за вариант убрать катбуст из этого теста

Кажется, что вместе с катбустом надо будет убрать вообще все `best-quality` модели.

> А только в этом тесте из-за него что-то падало?

Нет. У меня от 1 до 3 тестов падает с одной и той же ошибкой `_catboost.CatBoostError: max_leaves option works only with lossguide tree growing`. На сервере больше одного не падает.

PS. Вчера еще раз пустил тесты, появилась новая ошибка. Попробую отловить у себя.

> Мутация параметров в композере - это одна из базовых операций, есть риск очень многое поломать

Как временный вариант. Однострочная правка поможет избежать изменения нескольких тестов. Или можно отключить падение композера и тюнера в тестах с созданием issue на включение после решения проблем.

2023-11-17 11:16 UTC, kasyanovse commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False, with_tuning=False, validation_blocks=2):
> Если я правильно понимаю проблему - то вот такой вариант не поможет сейчас обойти её:

Должен сработать. Потестирую пока буду ловить новую ошибку.

2023-11-21 14:14 UTC, andreygetmanov approved these changes

2023-11-21 14:17 UTC, merged