add InputData from pd and numpy
aimclub/FEDOT pull request #1184
Opened 2023-10-18 16:54 UTC by ChrisLisbon

Add InputData.from_dataframe and InputData.from_numpy methods. From dataframe expects that user already opend his df, set indeces, removed columns. From numpy based on exicting function.

2023-10-18 18:14 UTC, valer1435 requested changes

2023-10-18 18:17 UTC, ChrisLisbon commented on fedot/core/data/data.py
> +                       df: pd.DataFrame,
ну тут идея как раз в том, что пользователь уже пооткрывал свои данные и подготовил датафрейм самостоятельно, специально из этого метода убрала всю автоматичность

2023-10-19 08:59 UTC, ChrisLisbon commented on fedot/core/data/data.py
> +                   data_type: Optional[DataTypesEnum] = None) -> InputData:
Да, по аналогии с from_csv прописала

2023-10-19 14:23 UTC, MorrisNein approved these changes
Отлично, так гораздо удобнее, чем импортировать отдельную функцию.

2023-10-19 14:23 UTC, MorrisNein commented on fedot/core/data/data.py
> +                       df: pd.DataFrame,
Про отдельные X и Y спорный момент. С одной стороны, мы идеологически предлагаем решение "из коробки" - вы просто читаете любой формат в DataFrame и засовываете в AutoML. С другой, если почти любая предобработка данных пользователем выдаст X и Y отдельно.

Я считаю, этот вопрос можно переформулировать так: мы рассчитываем на продвинутого пользователя или наоборот?

Судя по тому, что дело дошло до создания InputData вручную, скорее на продвинутого. Тогда, на мой взгляд, разумнее использовать вариант с отдельными параметрами для X и Y.

2023-10-19 16:14 UTC, ChrisLisbon commented on fedot/core/data/data.py
> +                       df: pd.DataFrame,
Принято, разделила from_dataframe на два входа features_df и target_df

2023-10-19 18:09 UTC, valer1435 commented on fedot/core/data/data.py
> +                               target_array: np.ndarray,
Было бы здорово сделать таргет по умолчанию None, И если он None, то features считаем равным таргет.

2023-10-19 18:09 UTC, valer1435 commented on fedot/core/data/data.py
> +                            target_array: numpy array with target.
Мне как возможному пользователю может быть непонятно, что в федоте чаще всего фичи = таргет в инпут дате для задач прогнозирования.

2023-10-20 08:50 UTC, ChrisLisbon commented on fedot/core/data/data.py
> +                               target_array: np.ndarray,
Добавила

2023-10-20 08:51 UTC, ChrisLisbon commented on fedot/core/data/data.py
> +                            target_array: numpy array with target.
Чаще всего, но не всегда. Добавила пояснение в докстринг

2023-10-21 09:08 UTC, MorrisNein requested changes

2023-10-21 09:08 UTC, MorrisNein commented on fedot/core/data/data.py
> +                       target_df: pd.DataFrame,
Предлагаю здесь разрешить приём как DataFrame, так и Series (в том числе для фич — временных рядов).

Просто занести в этот метод преобразование в DataFrame, если нам это необходимо.

2023-10-21 09:08 UTC, MorrisNein commented on test/unit/data/test_data.py
> +    actual_features_from_df = InputData.from_dataframe(features, target).features
В обоих случаях вроде должно работать без to_numpy?

2023-10-21 13:28 UTC, ChrisLisbon commented on test/unit/data/test_data.py
> +    actual_features_from_df = InputData.from_dataframe(features, target).features
Сделала по аналогии с [from_csv](https://github.com/aimclub/FEDOT/pull/1184/files#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eR175-R177), но без тоже работает, убрала в своей функции

2023-10-21 13:28 UTC, ChrisLisbon commented on fedot/core/data/data.py
> +                       target_df: pd.DataFrame,
Добавила

2023-10-22 11:45 UTC, valer1435 approved these changes

2023-10-23 12:38 UTC, MorrisNein approved these changes

2023-10-23 12:39 UTC, merged