Support for changes in GOLEM
aimclub/FEDOT pull request #1189
Opened 2023-10-26 10:53 UTC by kasyanovse

Support for changes in https://github.com/aimclub/GOLEM/pull/230

2023-10-26 10:54 UTC, pep8speaks commented
Hello @kasyanovse! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:











* In the file [`fedot/core/data/merge/data_merger.py`](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py):

> [Line 6:1](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L6): [F403](https://duckduckgo.com/?q=pep8%20F403) 'from fedot.core.data.array_utilities import *' used; unable to detect undefined names
> [Line 30:21](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L30): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 31:31](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L31): [F405](https://duckduckgo.com/?q=pep8%20F405) 'find_common_elements' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 33:30](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L33): [F541](https://duckduckgo.com/?q=pep8%20F541) f-string is missing placeholders
> [Line 60:72](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L60): [F405](https://duckduckgo.com/?q=pep8%20F405) 'Optional' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 81:32](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L81): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 89:44](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L89): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 108:50](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L108): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 108:69](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L108): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 110:25](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L110): [F405](https://duckduckgo.com/?q=pep8%20F405) 'atleast_2d' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 112:45](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L112): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 112:59](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L112): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 114:16](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L114): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 116:53](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L116): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 116:66](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L116): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 120:46](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L120): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 120:75](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L120): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 123:22](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L123): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 125:18](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L125): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 140:36](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L140): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 147:50](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L147): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 147:69](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L147): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 149:38](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L149): [F405](https://duckduckgo.com/?q=pep8%20F405) 'atleast_4d' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 162:53](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L162): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 162:66](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L162): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 164:16](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L164): [F405](https://duckduckgo.com/?q=pep8%20F405) 'flatten_extra_dim' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 169:45](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L169): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 169:59](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/merge/data_merger.py#L169): [F405](https://duckduckgo.com/?q=pep8%20F405) 'np' may be undefined, or defined from star imports: fedot.core.data.array_utilities
> [Line 176:26](https://github.com/aimclub/FEDOT/blob/c3b2ab44935905cf47d06dd75edf84860b44a035/fedot/core/data/ [...]

2023-10-31 15:01 UTC, YamLyubov requested changes
Возможно некоторые интеграционные тесты еще надо подправить (например, `test_dispatchers_with_faulty_objectives`)

2023-11-01 06:16 UTC, kasyanovse commented
> Возможно некоторые интеграционные тесты еще надо подправить (например, `test_dispatchers_with_faulty_objectives`)

Этот тест я поправил, но остальные интеграционники не смотрел, так как они правятся в соседней ветке.

2023-11-01 06:22 UTC, kasyanovse commented on test/unit/pipelines/prediction_intervals/test_mutations.py
> +#      it does not work due to old version of golem in .pickle file with fedot instance
`pickle` пересчитал.

2023-11-01 09:07 UTC, YamLyubov approved these changes

2023-11-01 09:14 UTC, merged