Add direct examples
aimclub/FEDOT pull request #1192
Opened 2023-11-02 13:45 UTC by valer1435

WIP

2023-12-06 12:41 UTC, kasyanovse requested changes

2023-12-06 12:41 UTC, kasyanovse commented on docs/source/examples/regression_example.rst
> +        * TaskTypesEnum.ts_forecasting
Дублирование того, что написано в `data.rst`. Возможно, лучше ссылку на `data.rst` сделать и ничего не расписывать.

2023-12-06 12:41 UTC, kasyanovse commented on docs/source/examples/regression_example.rst
> +and pass name of target column to ``target`` field. This method returns the best pipeline was obtained during optimization.
Не согласуется с подготовкой данных, реализованной выше.

2023-12-06 12:41 UTC, kasyanovse commented on docs/source/examples/regression_example.rst
> +    prediction = model.predict(features=test) # csv file should contains target column too for metric calculation
Не согласуется с подготовкой данных выше.

2023-12-06 12:41 UTC, kasyanovse commented on docs/source/examples/regression_example.rst
> +Thus by this example we learned how to solve regression task with Fedot.
Аналогично ранее сделанному комментарию, что лучше сделать ссылку на сохранение/загрузку пайплайнов, а подготовку инференса лучше построить вокруг финального пайплайна.

2023-12-06 12:41 UTC, kasyanovse commented on docs/source/examples/ts_forecasting.rst
> +        * TaskTypesEnum.ts_forecasting
Лучше просто ссылку на `data.rst`.

2023-12-06 12:41 UTC, kasyanovse commented on docs/source/examples/ts_forecasting.rst
> +Thus by this example we learned how to solve time series forecasting task with Fedot.
Аналогично ранее сделанному комментарию, что лучше сделать ссылку на сохранение/загрузку пайплайнов, а подготовку инференса лучше построить вокруг финального пайплайна.

2023-12-08 07:32 UTC, valer1435 commented on docs/source/examples/classification_example.rst
> +    test_data_path = 'path_to_test_file'
Обычно юзеры слишком ленивы, чтобы так делать) Поэтому дублирование не всегда плохо)

2023-12-08 07:35 UTC, valer1435 commented on docs/source/examples/classification_example.rst
> +and pass name of target column to ``target`` field. Method runs optimization and returns the best pipeline was obtained during optimization.
Идея в том, чтобы показать, что данные можно подгружать разными способами - через датафрейм или через инпут дату. И понятно, что такие примеры будут отличаться

2023-12-08 07:39 UTC, valer1435 commented on docs/source/examples/regression_example.rst
> +        * TaskTypesEnum.ts_forecasting
Отвечал про дублирование

2023-12-10 11:19 UTC, valer1435 commented on docs/source/examples/classification_example.rst
> +and pass name of target column to ``target`` field. Method runs optimization and returns the best pipeline was obtained during optimization.
Я тоже так думал, но к сожалению, в реальности у людей много разных типов данных, не только csv. Поэтому им иногда нужно сначала подгрузить данные в пандас, а потом уже прокидывать в федот. Я тоже за подход InputData-only, но у меня был опыт как у пользователя фреймворка с такой работой с данными. 
![image](https://github.com/aimclub/FEDOT/assets/32017472/e460453c-4131-463a-8c04-5b613128ac28)
Вот во что это превращалось) Думаю, что оптимальным тут будет дать ссылку на data.rst, чтобы если что нашли вариант по душе

2023-12-11 07:22 UTC, kasyanovse commented on docs/source/examples/classification_example.rst
> +and pass name of target column to ``target`` field. Method runs optimization and returns the best pipeline was obtained during optimization.
Так я про то же говорю.
Сделать одну базовую подготовку pd.DataFrame -> InputData в data.rst  и исходить из нее, а не показывать везде свои варианты загрузки данных и работу с показанным вариантом загрузки.

2023-12-11 11:34 UTC, valer1435 commented on docs/source/examples/classification_example.rst
> +You also can define metric parameter (ROC-AUC in this example), timeout in minutes (in this example we limit fedot for 5 minutes).
https://github.com/aimclub/FEDOT/issues/1223 Сделал ишшью, добавлять пустую доку пока не буду, так как не первостепенная задача

2023-12-11 13:55 UTC, valer1435 commented on docs/source/examples/classification_example.rst
> +    test_data_path = 'path_to_test_file'
https://github.com/aimclub/FEDOT/pull/1192/commits/30f7e0cecf2be313164e6a70f1a26d729dbda3b2#diff-277d5b174eedba3072394139feb5e4070e391c78dbbe6e3b88b1f383903c7e3fR21 поменял в целом метод загрузки в примере на более общий

2023-12-11 13:55 UTC, valer1435 commented on docs/source/examples/data.rst
> +     from fedot.core.repository.tasks import Task, TaskTypesEnum, TsForecastingParams
[вернул](https://github.com/aimclub/FEDOT/pull/1192/commits/30f7e0cecf2be313164e6a70f1a26d729dbda3b2#diff-662dc50fd963f0870ab1a6a6b34fa89fba214240f3e7250249be766aa52456ecR80)

2023-12-11 13:55 UTC, valer1435 commented on docs/source/examples/classification_example.rst
> +and pass name of target column to ``target`` field. Method runs optimization and returns the best pipeline was obtained during optimization.
Теперь не так актуально

2023-12-11 13:55 UTC, valer1435 commented on docs/source/examples/classification_example.rst
> +Since we want to calculate ROC-AUC metric for our test data we should use ``predict_proba()`` method.
Теперь не так актуально

2023-12-11 13:55 UTC, valer1435 commented on docs/source/examples/classification_example.rst
> +    prediction = model.predict_proba(features=test) # csv file should contains target column too for metric calculation
Теперь не так актуально

2023-12-11 13:56 UTC, valer1435 commented on docs/source/examples/classification_example.rst
> +     loaded_pipeline = Pipeline().load('path_to_save_and_load')
[Добавил ](https://github.com/aimclub/FEDOT/pull/1192/commits/30f7e0cecf2be313164e6a70f1a26d729dbda3b2#diff-f118768347d92884d93397ca7a26edbef5fa54cb61868205ff4dd6dd872e9d7eR136)такой текст в конец каждого примера

2023-12-11 13:56 UTC, valer1435 commented on docs/source/examples/classification_example.rst
> +Thus by this example we learned how to solve classification task with Fedot.
Выше ответил

2023-12-11 13:56 UTC, valer1435 commented on docs/source/examples/regression_example.rst
> +and pass name of target column to ``target`` field. This method returns the best pipeline was obtained during optimization.
Не актуально

2023-12-11 13:56 UTC, valer1435 commented on docs/source/examples/regression_example.rst
> +    prediction = model.predict(features=test) # csv file should contains target column too for metric calculation
Не актуально

2023-12-11 13:57 UTC, valer1435 commented on docs/source/examples/regression_example.rst
> +Thus by this example we learned how to solve regression task with Fedot.
Ответил выше

2023-12-11 14:07 UTC, kasyanovse commented on docs/source/examples/classification_example.rst
> +You also can define metric parameter (ROC-AUC in this example), timeout in minutes (in this example we limit fedot for 5 minutes).
А зачем это

```There are 3 possible values for TaskType:
    * TaskTypesEnum.classification
    * TaskTypesEnum.regression
    * TaskTypesEnum.ts_forecasting
```

в примере с классификацией?

2023-12-12 07:34 UTC, kasyanovse approved these changes
Мне кажется, что каждую страничку надо сделать меньше и проще. Главный принцип - дать тему в заголовке и кратко раскрыть только эту тему. Вопрос субъективный.

В остальном возражений нет, вливай.

2023-12-13 11:23 UTC, merged