Boosting method implementation (XGBoost)
aimclub/FEDOT pull request #1209
Opened 2023-11-27 15:54 UTC by RomanKharkovskoy

2023-11-27 18:47 UTC, nicl-nno commented
Выставлять на ревью PR-ы без описания и с PEP8-дефектами - плохая практика.

Изменения не покрыты тестами (нужны в случае если поведение чем-то отличается от предыдущей реализации xbg).

2024-01-31 12:29 UTC, RomanKharkovskoy commented
/fix-pep8

2024-02-07 15:22 UTC, andreygetmanov requested changes
Не совсем понял, как идёт сравнение с Федотом?
Берутся xgboost из коробки и федот с 1 моделью (xgboost)?
Тогда перед имплементацией стоит взять больше датасетов (хотя бы 10), запустить их минимум по 5 раз и усреднить
Возможно, @nicl-nno знаешь более оптимальные цифры или датасеты подскажешь?

2024-02-07 15:22 UTC, andreygetmanov commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +        self.model_params = {k: v for k, v in self.params.to_dict().items() if k not in self.__operation_params}
Стоит назвать переменные более явно

2024-02-07 15:22 UTC, andreygetmanov commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +    def fit(self, input_data: InputData):
pandas dataframe в сравнении с numpy array - крайне "дорогая" структура данных. Возможно, есть смысл брать элементы из InputData (фичи и таргет там хранятся в np.array, если правильно помню) и класть их в xgboost без дополнительной конвертации?

2024-02-07 15:22 UTC, andreygetmanov commented on fedot/core/pipelines/tuning/search_space.py
> +                'booster': {
Чем обусловлен выбор именно такого пространства поиска?
Желательно, чтобы ни одна из комбинаций параметров не давала модель с огромным временем обучения

2024-02-07 15:22 UTC, andreygetmanov commented on fedot/core/repository/data/default_operation_params.json
> +    "n_jobs": 1,
А n_jobs из FEDOT API замещает дефолтный?

2024-02-15 08:54 UTC, RomanKharkovskoy commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +        self.model_params = {k: v for k, v in self.params.to_dict().items() if k not in self.__operation_params}
k, v достаточно явные названия переменных в контексте иттерации по словарю (key: value)

2024-02-15 08:56 UTC, RomanKharkovskoy commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +    def fit(self, input_data: InputData):
Действительно крайне "дорогая" структура данных, однако XGBoost'у можно объяснить какие признаки категориальные, а это можно сделать только с Pandas DataFrame
https://xgboost.readthedocs.io/en/stable/tutorials/categorical.html

2024-02-15 09:04 UTC, RomanKharkovskoy commented on fedot/core/pipelines/tuning/search_space.py
> +                'booster': {
Такое пространство поиска выбрано исходя из изучения различных тетрадок с Kaggle, а также исхожя из интуитивных соображений (остальные гиперпараметры чересчур специфичные и настраиваются в редких случаях)
Верхняя граница пространства поиска для всех параметров была выбрана недостаточно большой, чтобы не появлялись комбинации с огромным временем обучения

2024-02-19 19:02 UTC, RomanKharkovskoy commented
> Не совсем понял, как идёт сравнение с Федотом? Берутся xgboost из коробки и федот с 1 моделью (xgboost)? Тогда перед имплементацией стоит взять больше датасетов (хотя бы 10), запустить их минимум по 5 раз и усреднить Возможно, @nicl-nno знаешь более оптимальные цифры или датасеты подскажешь?

Взял по 10 датасетов для классификации (заменил таблицу в шапке PR'а). XGBoost берётся из коробки + заполняются пропуски с помощью sklearn.SimpleInputer и кодируются категориальные признаки с помощью sklearn.OneHotEncoder. А для сравнения с FEDOT берётся predefined_model='xgboost'

2024-02-20 13:51 UTC, andreygetmanov commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +    def fit(self, input_data: InputData):
> Действительно крайне "дорогая" структура данных, однако XGBoost'у можно объяснить какие признаки категориальные, а это можно сделать только с Pandas DataFrame https://xgboost.readthedocs.io/en/stable/tutorials/categorical.html

"The easiest way to pass categorical data into XGBoost is using dataframe" - самый простой не значит самый быстрый

Дальше в документации нашёл ссылку на внутреннюю структуру xgboost.DMatrix, которая "optimized for both memory efficiency and training speed"

Вижу твой комментарий в начале PR:

> Интерфейс fit/predict не поддерживает работу с внутренним типом данных xgboost.DMatrix

А в чём там проблема? Почему нельзя преобразовать InputData в DMatrix?

2024-02-20 14:01 UTC, andreygetmanov commented
> > Не совсем понял, как идёт сравнение с Федотом? Берутся xgboost из коробки и федот с 1 моделью (xgboost)? Тогда перед имплементацией стоит взять больше датасетов (хотя бы 10), запустить их минимум по 5 раз и усреднить Возможно, @nicl-nno знаешь более оптимальные цифры или датасеты подскажешь?
> 
> Взял по 10 датасетов для классификации (заменил таблицу в шапке PR'а). XGBoost берётся из коробки + заполняются пропуски с помощью sklearn.SimpleInputer и кодируются категориальные признаки с помощью sklearn.OneHotEncoder. А для сравнения с FEDOT берётся predefined_model='xgboost'

А усреднение по скольки запускам считаешь?

2024-02-20 14:05 UTC, andreygetmanov requested changes

2024-03-05 17:40 UTC, RomanKharkovskoy commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +    def fit(self, input_data: InputData):
InputData можно преобразовать в DMatrix, но DMatrix можно использовать только внутри интерфейса train/predict, а train не создаёт отдельный экзмепляр класса XGBoostClassifier, т.е. он работает в таком ключе
xgboost.train(train_DMatrix)
pred = xgboost.predict(test_DMatrix)
А для создания модели всё-таки удобнее создавать отдельный объект вида
model = XGBoostClassifier(**model_params)
model.fit(X_train, y_train)
pred = model.predict(X_test)

2024-03-05 17:40 UTC, RomanKharkovskoy commented on test/unit/api/test_assumption_builder.py
> +    available_operations = ['linear', 'lagged']  # 'xgboost'
Изначальное оставлял для теста и забыл убрать

2024-07-24 15:44 UTC, aPovidlo commented on fedot/core/repository/data/default_operation_params.json
> +    "n_jobs": 1,
@andreygetmanov Да, должен. Добавили по аналогии с другими моделями описанными в этом json

2024-07-24 16:05 UTC, aPovidlo commented on test/unit/api/test_assumption_builder.py
> +    available_operations = ['linear', 'lagged']  # 'xgboost'
@andreygetmanov Тест покрывает случаи, когда в `available_operations` подается модели или операции, которые не подходят для задачи. В текущем кейсе была выбрана задача **классификации** и в доступные операции модели не совместимые с этой задачей `'linear', 'lagged'`. Скажешь, но ведь `xgboost` подходит для этой задачи и окажешься прав. Но есть, как говориться, нюанс, который достался нам из прошлого. До этого PR `xgboost` считался `not suitable` операцией (не знаю по какой причине). Сейчас возвращается его использование. Думаю, что можно заменить его на `xgboostreg` в этом и другом тесте чтобы сохранить логику теста.

2024-07-24 17:07 UTC, aPovidlo commented
/fix-pep8

2024-07-24 17:11 UTC, aPovidlo reviewed
-- wip --

2024-07-26 13:56 UTC, andreygetmanov commented on test/unit/api/test_assumption_builder.py
> +    available_operations = ['linear', 'lagged']  # 'xgboost'
> Сейчас возвращается его использование. 

Отлично!

>Думаю, что можно заменить его на `xgboostreg` в этом и другом тесте чтобы сохранить логику теста.

Да, давай так

2024-07-26 13:57 UTC, andreygetmanov approved these changes

2024-07-26 14:12 UTC, merged