1211-fix
aimclub/FEDOT pull request #1213
Opened 2023-11-29 12:14 UTC by kasyanovse

2023-12-01 09:58 UTC, MorrisNein requested changes

2023-12-01 09:58 UTC, MorrisNein commented on test/integration/models/test_atomized_model.py
> +        assert task_type == set(atomized_node.operation.metadata.task_type)
Тест покрывает то, что сломалось в issue? А что именно, и как удалось починить?

2023-12-01 09:58 UTC, MorrisNein commented on test/integration/models/test_atomized_model.py
> +        pipeline = atomized_node.operation.pipeline
Можно отправить этот список в pytest.mark.parametrize и сократить уровни вложенности теста. Будет проще понять, на какой модели сломался тест.

2023-12-01 09:58 UTC, MorrisNein commented on fedot/core/operations/atomized_model.py
> +        def extract_metadata_from_pipeline(attr_name: str, node_filter: Optional[Callable] = None):
Возможно, этот метод бы пригодился в классе `Pipeline`

2023-12-01 11:09 UTC, kasyanovse commented on fedot/core/operations/atomized_model.py
> +        def extract_metadata_from_pipeline(attr_name: str, node_filter: Optional[Callable] = None):
> Можно уточнить сигнатуру `node_filter` и возвращаемого значения

Это, конечно, правильно, но я просто не могу себе позволить написать целый класс (или протокол?) для определения сигнатуры функции, используемой один раз через пару строк после определения)) Слишком многословно))

> Возможно, этот метод бы пригодился в классе `Pipeline`

Возможно, но какой интерфейс для такой функции будет удобен и полезен? `node_filter`, на мой взгляд, для метода `Pipeline` не нужен. Плюс появляется вопрос как работать с множествами атрибутов узлов. Нужно находить их пересечение или объединение?

2023-12-01 11:23 UTC, kasyanovse commented on test/integration/models/test_atomized_model.py
> +        assert task_type == set(atomized_node.operation.metadata.task_type)
> Тест покрывает то, что сломалось в issue?

Да.

> А что именно, и как удалось починить?

Извлечение `metadata` из пайплайна. Проблема была в том, что метаданные извлекались с использованием старых методов и свойств, которых не было в актуальной версии федота. Поправил обращение к метаданным операций и немного изменил извлечение `input_types` и `output_types`.

2023-12-01 11:30 UTC, kasyanovse commented on fedot/core/operations/atomized_model.py
> +        def extract_metadata_from_pipeline(attr_name: str, node_filter: Optional[Callable] = None):
Добавил сигнатур в класс `AtomizedModel`.

2023-12-01 15:02 UTC, MorrisNein requested changes

2023-12-01 15:02 UTC, MorrisNein commented on fedot/core/operations/atomized_model.py
> +        def extract_metadata_from_pipeline(attr_name: str, node_filter: Optional[Callable] = None):
Да, прошу прощения, неясно выразился)
Я имел в виду написать `Callable[[NodeType], bool]` вместо `Callable`

2023-12-04 07:39 UTC, kasyanovse commented on fedot/core/operations/atomized_model.py
> +        def extract_metadata_from_pipeline(attr_name: str, node_filter: Optional[Callable] = None):
> ```Callable[[NodeType], bool]```

Я даже не подумал об этом))

2023-12-04 07:50 UTC, kasyanovse commented on fedot/core/operations/atomized_model.py
> +        def extract_metadata_from_pipeline(attr_name: str, node_filter: Optional[Callable] = None):
Также добавил аргумент в `extract_metadata_from_pipeline`.

2023-12-04 08:33 UTC, MorrisNein requested changes

2023-12-04 08:40 UTC, MorrisNein commented on test/integration/models/test_atomized_model.py
> +def test_atomized_model_metadata(atomized_node):
Кхм, невнимательно посмотрел на вложенность кода, извиняюсь

2023-12-04 10:05 UTC, merged