Metrics fixes, tests, refactoring, typing improvement
aimclub/FEDOT pull request #1214
Opened 2023-11-29 16:45 UTC by MorrisNein

Changes:

- Fix F1 & precision evaluation
- Remove flattening of target & predict values during metrics evaluation
- Unwrap the shape of prediction in `pipeline.predict()` from `(1, N)` to `(N)` for forecasting tasks
- Add duck typing for `MetricCallable` 
- Multiple inheritance fixes for the inheritors of `Metric` 
- Add unit tests for all supported metrics, tasks and data types

2023-11-29 16:45 UTC, pep8speaks commented
Hello @MorrisNein! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`test/unit/tasks/test_regression.py`](https://github.com/aimclub/FEDOT/blob/fcd46c75a305cd2b8d2df85d6e96ac44a9defcd3/test/unit/tasks/test_regression.py):

> [Line 104:52](https://github.com/aimclub/FEDOT/blob/fcd46c75a305cd2b8d2df85d6e96ac44a9defcd3/test/unit/tasks/test_regression.py#L104): [F811](https://duckduckgo.com/?q=pep8%20F811) redefinition of unused 'data_setup' from line 14

2023-11-29 19:15 UTC, MorrisNein commented on fedot/core/repository/quality_metrics_repository.py
> +    def __self__(self) -> Metric: ...
To-do: убрать

2023-11-29 19:21 UTC, MorrisNein commented on fedot/api/builder.py
> +            metric: Union[str, MetricCallable, MetricsEnum, List[Union[str, MetricCallable, MetricsEnum]]] = DEFAULT_VALUE,
To-do: использовать MetricType.
Переименовать в MetricInputType для наглядности

2023-11-30 10:09 UTC, kasyanovse requested changes

2023-11-30 10:09 UTC, kasyanovse commented on test/unit/composer/test_metrics.py
> +    actual_metric_value = round(actual_metric_value, 2)
А зачем здесь хардкодить ожидаемые значения? Если добавить в `ComplexityMetricsEnum` новую метрику, то тест перестанет проходить.

2023-11-30 10:09 UTC, kasyanovse commented on test/unit/composer/test_metrics.py
> +    assert metric_value != MetricsRepository.get_metric_class(metric).default_value
Кажется, что их можно сделать в виде одного теста.

2023-11-30 10:09 UTC, kasyanovse commented on test/unit/composer/test_metrics.py
Возможно, стоит добавить тест, который будет проверять, что значение метрики на идеальном предсказании не равно дефолтному.

2023-11-30 10:09 UTC, kasyanovse commented on fedot/core/composer/metrics.py
> -            results, reference_data = cls.flatten_convert(results, reference_data)
Почему убрана эта строка?

2023-11-30 12:15 UTC, MorrisNein commented on fedot/core/composer/metrics.py
>          """ Get metrics values based on pipeline and InputData for validation """
Думаю, достаточно будет добавить **kwargs и актуализировать докстрингу

2023-11-30 12:17 UTC, MorrisNein commented on fedot/core/composer/metrics.py
>  class QualityMetric:
Действительно. Странно, что не наследуется. Проглядел, спасибо.

2023-11-30 12:29 UTC, MorrisNein commented on fedot/core/repository/metrics_repository.py
> +class MetricsEnum(str, Enum): ...
Тут уже не актуально, вернул как было.

Но вообще изучил вопрос: я думал, что варианты равнозначны, но оказалось, что многоточие это константа наподобие None. Буду впредь использовать pass

В определениях MetricCallable тоже поправлю

2023-11-30 14:58 UTC, MorrisNein commented on fedot/core/repository/metrics_repository.py
> +class MetricsEnum(str, Enum): ...
Cделал

2023-11-30 18:40 UTC, valer1435 commented on fedot/core/composer/metrics.py
> +            additional_params = dict(average=F1.binary_averaging_mode, pos_label=pos_label)
> Аргументы против переопределения pos_label:
> 
> В таком случае метрика может вычисляться по разному для разных фолдов.
> Такой расчет может отличаться от расчета этой же метрики вне федота.
> Поиск самого редкого класса требует времени. Почему бы не взять первый попавшийся класс?

1. Да, это проблема, со стратификацией действительно может возникнуть путаница какой класс выбирать. Но, кажется, если классы близки к 50/50 разницы, по какому классу считать метрику не сильно важно
2. Подсчет f1 по редкому классу самый честный, поэтому я его и оставил
3. Потому что первый попавшийся класс может быть большинством и мы получим некорректные метрики

2023-12-02 09:18 UTC, valer1435 commented on fedot/core/composer/metrics.py
> +            additional_params = dict(average=F1.binary_averaging_mode, pos_label=pos_label)
btw для тестовых данных по идее стратификация не должна работать, потому что получим смещение относительно реальных данных

2023-12-02 10:12 UTC, MorrisNein commented on fedot/core/composer/metrics.py
> +            additional_params = dict(average=F1.binary_averaging_mode, pos_label=pos_label)
> btw для тестовых данных по идее стратификация не должна работать, потому что получим смещение относительно реальных данных

Не совсем понял, это требует какого-либо фикса?

2023-12-05 16:01 UTC, MorrisNein commented on test/unit/composer/test_metrics.py
Добавил

2023-12-05 16:01 UTC, MorrisNein commented on test/unit/composer/test_metrics.py
> +    assert metric_value != MetricsRepository.get_metric_class(metric).default_value
Объединил

2023-12-05 16:03 UTC, MorrisNein commented
@kasyanovse, вынес проблему с бинарной классификацией в отдельную [issue](https://github.com/aimclub/FEDOT/issues/1221). 

А пока что вынес этот случай в менее строгий тест.

2023-12-06 08:14 UTC, kasyanovse commented on fedot/core/composer/metrics.py
> -            results, reference_data = cls.flatten_convert(results, reference_data)
Потестировал. Все метрики толерантны к форме данных на входе.

2023-12-06 08:18 UTC, kasyanovse commented on test/unit/composer/test_metrics.py
1. Я добавил сид для теста метрик
2. Убрал автоматическую перезапись результатов расчета метрик
3. Перенес перезапись результатов расчета метрик после `assert`

У меня небольшая проблема возникла, что в результате теста переписываются все метрики для временных рядов. Пока посмотрю из-за чего, потом аппрувну, если все будет ок.

2023-12-06 11:55 UTC, merged