1035-docs
aimclub/FEDOT pull request #1222
Opened 2023-12-06 16:22 UTC by Lopa10ko

Add table of supported models and operations to the documentation. Also this list should be available in docstring of API parameter `available_operations`.

closes #1035

2023-12-07 06:10 UTC, kasyanovse requested changes

2023-12-07 06:10 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `scaling`,`ScalingImplementation`,Scaling,Feature Scaling,"`fast_train`, `ts`, `*tree`"
Большинство моделей вида `*Implementation` нужно расшифровать. Класс `*Implementation` часто всего лишь обертка. Для того же `ScalingImplementation` в классе можно найти использование `sklearn.preprocessing.StandardScaler`.

2023-12-07 06:10 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `exog_ts`,`ExogDataTransformationImplementation`,Exogeneus Tranformation,Timeseries Tranformation,""
Выше на этой же страничке есть разделы `Feature selection`, `Feature extraction`, `Feature expansion`. Нужно этот список рассортировать по этим разделам.

2023-12-07 06:10 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `cnn`,`FedotCNNImplementation`,Convolutional Neural Network,Classification,""
Перенести в раздел `Models used`.

2023-12-07 12:01 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `exog_ts`,`ExogDataTransformationImplementation`,Exogeneus Tranformation,Timeseries Tranformation,""
Пока пусть будет по старым категориям разбито.

2023-12-07 12:02 UTC, Lopa10ko commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `scaling`,`ScalingImplementation`,Scaling,Feature Scaling,"`fast_train`, `ts`, `*tree`"
как поступать с моделями, где не очень понятно, как выделить основную модель? например, в `CGRUImplementation` используется блоки различного вида и не очень понятно, как поступить: написать про наследование от `nn.Module` или просто перечислить `nn.Conv1d + nn.ReLU`,  `nn.LSTM`, `nn.Linear`

2023-12-11 10:54 UTC, Lopa10ko commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `exog_ts`,`ExogDataTransformationImplementation`,Exogeneus Tranformation,Timeseries Tranformation,""
d869967a56a1cee41ad25470aebd626775992fab

2023-12-11 15:26 UTC, pep8speaks commented
Hello @Lopa10ko! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`test/integration/models/test_model.py`](https://github.com/aimclub/FEDOT/blob/ba7bdbb6d591888025699374e7a5ef9645580af7/test/integration/models/test_model.py):

> [Line 508:1](https://github.com/aimclub/FEDOT/blob/ba7bdbb6d591888025699374e7a5ef9645580af7/test/integration/models/test_model.py#L508): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2023-12-12 07:13 UTC, kasyanovse commented on test/integration/models/test_model.py
> +                assert operation_found, f"Operation {operation.id} is not documented in {path_to_docs}"
Возможно, быстрее будет сначала считать весь файл в одну строку, а потом выполнять поиск по ней.

2023-12-12 09:50 UTC, Lopa10ko commented on test/integration/models/test_model.py
> +                assert operation_found, f"Operation {operation.id} is not documented in {path_to_docs}"
да, просто подумал, что файл может разрастись и было бы неприятно держать в памяти строку такого размера. вернулся к старому варианту (0a14859463a30640b47d801d748ca8d3f5461509)

2023-12-12 14:18 UTC, kasyanovse requested changes

2023-12-13 07:40 UTC, Lopa10ko commented on docs/source/introduction/fedot_features/automation_features.rst
[done](a24543c40b013b5bf397c8c9b558c20cb278de72)

2023-12-14 07:33 UTC, kasyanovse requested changes

2023-12-14 07:33 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `decompose`,`DecomposerRegImplementation`,Regression Decomposition
```suggestion
   `decompose`,`FEDOT model`,Set the difference between the prediction and the target as the new target
```

2023-12-14 07:33 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `class_decompose`,`DecomposerClassImplementation`,Classification Decomposition
```suggestion
   `class_decompose`,`FEDOT model`,Set the difference between the prediction and the target as the new target
```

2023-12-14 07:33 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `word2vec_pretrained`,`PretrainedEmbeddingsImplementation`,Word2Vec
```suggestion
   `word2vec_pretrained`,[Gensin-data model](https://github.com/piskvorky/gensim-data),Text vectorization
```

2023-12-14 07:33 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `lagged`,`LaggedTransformationImplementation`,Lagged timeseries tranformation
```suggestion
   `lagged`,FEDOT model,Lagged time series transformation/Time series to the Hankel matrix transformation
```

2023-12-14 07:33 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `sparse_lagged`,`SparseLaggedTransformationImplementation`,Sparse Lagged timeseries tranformation
```suggestion
   `sparse_lagged`,FEDOT model,As `lagged` but with sparsing
```

2023-12-14 07:33 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `smoothing`,`TsSmoothingImplementation`,Smoothing timeseries tranformation
```suggestion
   `smoothing`,FEDOT model,Moving average timeseries transformation
```

2023-12-14 07:33 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `gaussian_filter`,`GaussianFilterImplementation`,Gaussian Filter timeseries tranformation
```suggestion
   `gaussian_filter`,FEDOT model,Gaussian Filter timeseries tranformation
```

2023-12-14 07:33 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `diff_filter`,`NumericalDerivativeFilterImplementation`,Derivative Filter timeseries tranformation
```suggestion
   `diff_filter`,FEDOT model,Derivative Filter timeseries transformation
```

2023-12-14 07:33 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `cut`,`CutImplementation`,Cut timeseries tranformation
```suggestion
   `cut`,FEDOT model,Cut timeseries
```

2023-12-14 07:33 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `exog_ts`,`ExogDataTransformationImplementation`,Exogeneus timeseries tranformation
```suggestion
```

2023-12-14 07:33 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `resample`,`ResampleImplementation`,Resample features
```suggestion
   `resample`,FEDOT model,Imbalanced binary class transformation for
    classification task by using method from `sklearn.utils.resample`
```

2023-12-14 07:33 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `cnn`,`FedotCNNImplementation`,Convolutional Neural Network,Classification
```suggestion
   `cnn`,FEDOT model,Convolutional Neural Network,Classification
```

2023-12-14 07:33 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `cgru`,`CGRUImplementation`,Convolutional Gated Recurrent Unit,Forecasting
```suggestion
   `cgru`,FEDOT model,Convolutional Gated Recurrent Unit,Forecasting
```

2023-12-14 07:33 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `locf`,`RepeatLastValueImplementation`,Last Observation Carried Forward,Forecasting
```suggestion
   `locf`,FEDOT model,Last Observation Carried Forward,Forecasting
```

2023-12-14 07:33 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `polyfit`,`PolyfitImplementation`,Polynomial fitter,Forecasting
```suggestion
   `polyfit`,FEDOT model,Polynomial approximation,Forecasting
```

2023-12-14 07:33 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `ts_naive_average`,`NaiveAverageForecastImplementation`,Naive Average,Forecasting
```suggestion
   `ts_naive_average`,FEDOT model,Naive Average,Forecasting
```

2023-12-14 07:33 UTC, kasyanovse commented on docs/source/introduction/fedot_features/automation_features.rst
В Feature transformation operations нужно добавить тип задачи.

2023-12-15 09:37 UTC, kasyanovse approved these changes

2023-12-15 09:42 UTC, valer1435 commented
Думаю можно добавить в табличку информацию, в какой пресет какая операция попадает. А так очень полезная вещь - действительно был пробел в документации

2023-12-15 09:46 UTC, kasyanovse commented
> Думаю можно добавить в табличку информацию, в какой пресет какая операция попадает. А так очень полезная вещь - действительно был пробел в документации

@Lopa10ko Тогда надо будет еще добавить тест на проверку что все существующие пресеты упомянуты в таблицах.

2023-12-19 06:47 UTC, kasyanovse requested changes

2023-12-19 06:47 UTC, kasyanovse commented on test/integration/models/test_model.py
> +def test_all_presets_are_documented():
Этот тест перекрывает `test_all_operations_are_documented`. Следовательно `test_all_operations_are_documented` можно удалить.

2023-12-19 06:47 UTC, kasyanovse commented on test/integration/models/test_model.py
> +                    f"Operation {operation.id} presets {operation.presets} are not documented in {path_to_docs}"
Тут можно сделать через `for...else` и выброс ошибки. Кажется, что так будет читабельнее, но смотри сам.

2023-12-20 07:38 UTC, Lopa10ko commented on test/integration/models/test_model.py
> +                    f"Operation {operation.id} presets {operation.presets} are not documented in {path_to_docs}"
1e91c0c394e4bd830ca56981e7197f61a8edb7d6

2023-12-20 07:38 UTC, Lopa10ko commented on test/integration/models/test_model.py
> +def test_all_presets_are_documented():
1e91c0c394e4bd830ca56981e7197f61a8edb7d6

2023-12-20 07:40 UTC, Lopa10ko commented
- [x] get all operations in list, split into two groups: `preprocessing operations` and `models`
- [x] add the table with models/operations for class/regr/forecasting tasks
  - [x] determine the place for the table in the documentation
- [x] add `available_operations` list to `fedot.api.builder.FedotBuilder.setup_pipeline_structure` docstring (fd1db3dffabd2e9f328125c1b4b866bf27c29948)
- [x] add a test that checks whether operations are documented (ba7bdbb6d591888025699374e7a5ef9645580af7)

<details>
    <summary>Table of data processing operations</summary>

API name|Model used|Definition|Problem|Tags
----------|-------------|------------|---------|----
`scaling`|`ScalingImplementation`|Scaling|Feature Scaling|['`fast_train`', ' `ts`', ' `*tree`']
`normalization`|`NormalizationImplementation`|Normalization|Feature Scaling|['`fast_train`', ' `ts`', ' `*tree`']
`simple_imputation`|`ImputationImplementation`|Imputation|Feature Imputation|['`fast_train`', ' `*tree`']
`pca`|`PCAImplementation`|Principal Component Analysis|Feature Reduction|['`fast_train`', ' `ts`', ' `*tree`']
`kernel_pca`|`KernelPCAImplementation`|Kernel Principal Component Analysis|Feature Reduction|['`ts`', ' `*tree`']
`fast_ica`|`FastICAImplementation`|Independent Component Analysis|Feature Reduction|['`ts`', ' `*tree`']
`poly_features`|`PolyFeaturesImplementation`|Polynomial Features|Feature Engineering|['']
`one_hot_encoding`|`OneHotEncodingImplementation`|Ohe-Hot Encoder|Feature Encoding|['']
`label_encoding`|`LabelEncodingImplementation`|Label Encoder|Feature Encoding|['`fast_train`', ' `*tree`']
`rfe_lin_reg`|`LinearRegFSImplementation`|Linear Regression Recursive Feature Elimination|Feature Selection|['']
`rfe_non_lin_reg`|`NonLinearRegFSImplementation`|Decision Tree Recursive Feature Elimination|Feature Selection|['']
`rfe_lin_class`|`LinearClassFSImplementation`|Logistic Regression Recursive Feature Elimination|Feature Selection|['']
`rfe_non_lin_class`|`NonLinearClassFSImplementation`|Decision Tree Recursive Feature Elimination|Feature Selection|['']
`isolation_forest_reg`|`IsolationForestRegImplementation`|Regression Isolation Forest|Feature Filtering|['']
`isolation_forest_class`|`IsolationForestClassImplementation`|Classification Isolation Forest|Feature Filtering|['']
`decompose`|`DecomposerRegImplementation`|Regression Decomposition|Decomposition|['`fast_train`', ' `ts`', ' `*tree`']
`class_decompose`|`DecomposerClassImplementation`|Classification Decomposition|Decomposition|['`fast_train`', ' `*tree`']
`resample`|`ResampleImplementation`|Resample features|Resampling|['']
`ransac_lin_reg`|`LinearRegRANSACImplementation`|Regression Random Sample Consensus|Feature Filtering|['`fast_train`', ' `*tree`']
`ransac_non_lin_reg`|`NonLinearRegRANSACImplementation`|DecisionTreeRegressor Random Sample Consensus|Feature Filtering|['`fast_train`', ' `*tree`']
`cntvect`|`sklearn.feature_extraction.text.CountVectorizer`|Count Vectorizer|Text Processing|['']
`text_clean`|`TextCleanImplementation`|Lemmatization and Stemming|Text Processing|['']
`tfidf`|`sklearn.feature_extraction.text.TfidfVectorizer`|TF-IDF Vectorizer|Text Processing|['']
`word2vec_pretrained`|`PretrainedEmbeddingsImplementation`|Word2Vec|Text Processing|['']
`lagged`|`LaggedTransformationImplementation`|Lagged Tranformation|Timeseries Tranformation|['`fast_train`', ' `ts`']
`sparse_lagged`|`SparseLaggedTransformationImplementation`|Sparse Lagged Tranformation|Timeseries Tranformation|['`fast_train`', ' `ts`']
`smoothing`|`TsSmoothingImplementation`|Smoothing Tranformation|Timeseries Tranformation|['`fast_train`', ' `ts`']
`gaussian_filter`|`GaussianFilterImplementation`|Gaussian Filter Tranformation|Timeseries Tranformation|['`fast_train`', ' `ts`']
`diff_filter`|`NumericalDerivativeFilterImplementation`|Derivative Filter Tranformation|Timeseries Tranformation|['`fast_train`', ' `ts`']
`cut`|`CutImplementation`|Cut Tranformation|Timeseries Tranformation|['`fast_train`', ' `ts`']
`exog_ts`|`ExogDataTransformationImplementation`|Exogeneus Tranformation|Timeseries Tranformation|['']

</details>


<details>
    <summary>Table of operations that are models</summary>

API name|Model used|Definition|Problem|Tags
----------|-------------|------------|---------|----
`adareg`|`sklearn.ensemble.AdaBoostRegressor`|AdaBoost Regressor|Regression|['`fast_train`', ' `ts`', ' `*tree`']
`ar`|`AutoRegImplementation`|AutoRegression|Forecasting|['`fast_train`', ' `ts`']
`arima`|`ARIMAImplementation`|ARIMA|Forecasting|['`ts`']
`cgru`|`CGRUImplementation`|Convolutional Gated Recurrent Unit|Forecasting|['`ts`']
`bernb`|`sklearn.naive_bayes.BernoulliNB`|Naive Bayes Classifier (multivariate Bernoulli)|Classification|['`fast_train`']
`catboost`|`FedotCatBoostClassificationImplementation`|Catboost Classifier|Classification|['`*tree`']
`catboostreg`|`FedotCatBoostRegressionImplementation`|Catboost Regressor|Regression|['`*tree`']
`dt`|`sklearn.tree.DecisionTreeClassifier`|Decision Tree Classifier|Classification|['`fast_train`', ' `*tree`']
`dtreg`|`sklearn.tree.DecisionTreeRegressor`|Decision Tree Regressor|Regression|['`fast_train`', ' `ts`', ' `*tree`']
`gbr`|`sklearn.ensemble.GradientBoostingRegressor`|Gradient Boosting Regressor|Regression|['`*tree`']
`kmeans`|`sklearn.cluster.Kmeans`|K-Means clustering|Clustering|['`fast_train`']
`knn`|`FedotKnnClassImplementation`|K-nearest neighbors Classifier|Classification|['`fast_train`']
`knnreg`|`FedotKnnRegImplementation`|K-nearest neighbors Regressor|Regression|['`fast_train`', ' `ts`']
`lasso`|`sklearn.linear_model.Lasso`|Lasso Linear Regressor|Regression|['`fast_train`', ' `ts`']
`lda`|`LDAImplementation`|Linear Discriminant Analysis|Classification|['`fast_train`']
`lgbm`|`lightgbm.sklearn.LGBMClassifier`|Light Gradient Boosting Machine Classifier|Classification|['']
`lgbmreg`|`lightgbm.sklearn.LGBMRegressor`|Light Gradient Boosting Machine Regressor|Regression|['`*tree`']
`linear`|`sklearn.linear_model.LinearRegression`|Linear Regression Regressor|Regression|['`fast_train`', ' `ts`']
`logit`|`sklearn.linear_model.LogisticRegression`|Logistic Regression Classifier|Classification|['`fast_train`']
`mlp`|`sklearn.neural_network.MLPClassifier`|Multi-layer Perceptron Classifier|Classification|['']
`multinb`|`sklearn.naive_bayes.MultinomialNB`|Naive Bayes Classifier (multinomial)|Classification|['`fast_train`']
`qda`|`QDAImplementation`|Quadratic Discriminant Analysis|Classification|['`fast_train`']
`rf`|`sklearn.ensemble.RandomForestClassifier`|Random Forest Classifier|Classification|['`fast_train`', ' `*tree`']
`rfr`|`sklearn.ensemble.RandomForestRegressor`|Random Forest Regressor|Regression|['`fast_train`', ' `*tree`']
`ridge`|`sklearn.linear_model.Ridge`|Ridge Linear Regressor|Regression|['`fast_train`', ' `ts`']
`polyfit`|`PolyfitImplementation`|Polynomial fitter|Forecasting|['`fast_train`', ' `ts`']
`sgdr`|`sklearn.linear_model.SGDRegressor`|Stochastic Gradient Descent Regressor|Regression|['`fast_train`', ' `ts`']
`stl_arima`|`STLForecastARIMAImplementation`|STL Decomposition with ARIMA|Forecasting|['`ts`']
`glm`|`GLMImplementation`|Generalized Linear Models|Forecasting|['`fast_train`', ' `ts`']
`ets`|`ExpSmoothingImplementation`|Exponential Smoothing|Forecasting|['`fast_train`', ' `ts`']
`locf`|`RepeatLastValueImplementation`|Last Observation Carried Forward|Forecasting|['`fast_train`', ' `ts`']
`ts_naive_average`|`NaiveAverageForecastImplementation`|Naive Average|Forecasting|['`fast_train`', ' `ts`']
`svc`|`FedotSVCImplementation`|Support Vector Classifier|Classification|['']
`svr`|`sklearn.svm.LinearSVR`|Linear Support Vector Regressor|Regression|['']
`treg`|`sklearn.ensemble.ExtraTreesRegressor`|Extra Trees Regressor|Regression|['`*tree`']
`xgboost`|`xgboost.XGBClassifier`|Extreme Gradient Boosting Classifier|Classification|['`*tree`']
`xgbreg`|`xgboost.XGBRegressor`|Extreme Gradient Boosting Regressor|Regression|['`*tree`']
`cnn`|`FedotCNNImplementation`|Convolutional Neural Network|Classif [...]

2023-12-20 11:35 UTC, kasyanovse approved these changes

2023-12-25 13:57 UTC, nicl-nno approved these changes
Видимо можно мержить.

2023-12-25 15:15 UTC, merged