add window size selector
aimclub/FEDOT pull request #1237
Opened 2023-12-27 07:33 UTC by kasyanovse

wip

2023-12-27 07:33 UTC, pep8speaks commented
Hello @kasyanovse! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`fedot/utilities/window_size_selector.py`](https://github.com/aimclub/FEDOT/blob/619f64bfbf0023933284ef94ca99463850603597/fedot/utilities/window_size_selector.py):

> [Line 234:26](https://github.com/aimclub/FEDOT/blob/619f64bfbf0023933284ef94ca99463850603597/fedot/utilities/window_size_selector.py#L234): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2023-12-27 09:04 UTC, valer1435 reviewed
В теории ок, выглядит достаточно лаконично. Но есть вопросы:

1) Сейчас подбор окна происходит при каждом вызове transform. впринципе ок, думаю можно оставить подбор для каждого фолда, но не слишеом ли то долго?
2) Как-то можно посмотреть настоящую длину окна, а не параметр 0?
3) Как проверял эффективность? Действительно ли стало лучше?

2023-12-27 09:17 UTC, kasyanovse commented
> 1. Сейчас подбор окна происходит при каждом вызове transform. впринципе ок, думаю можно оставить подбор для каждого фолда, но не слишеом ли то долго?

Почему при каждом вызове? Я сейчас посмотрел, после тюнинга параметры сохраняются в узле.

> 2. Как-то можно посмотреть настоящую длину окна, а не параметр 0?

Да, в `lagged` хранится настоящая длина окна после обучения.

> 3. Как проверял эффективность? Действительно ли стало лучше?

https://github.com/aimclub/FEDOT/pull/1227 в описании PR есть таблички с оценкой изменения положения пайплайна внутри поколения после мутации.

2023-12-27 10:43 UTC, valer1435 commented
Кстати тюнер будет игнорировать длину окна или нет?

2023-12-27 11:25 UTC, kasyanovse commented
> Кстати тюнер будет игнорировать длину окна или нет?

Не будет. Он как раз и дотюнивает окно после композиции.

2023-12-28 10:11 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    def _check_and_correct_window_size(self, time_series: np.ndarray, forecast_length: int):
Окно подстраивается только если оно по дефолту не задано. Если задать его руками или изменить в процессе композиции/тюнинга, то оно не будет переопределяться.

2023-12-28 10:21 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    def _check_and_correct_window_size(self, time_series: np.ndarray, forecast_length: int):
То есть сейчас это работает так: 
1) Дефолтное значение длины окна 0.
2) Пусть у нас 3 фолда валидации
3) Заходим в первый фолд, подбираем длину окна
4) На следующих фолдах и при финальном обучении на всем ряду размер окна не подбираем?

2023-12-28 11:50 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    def _check_and_correct_window_size(self, time_series: np.ndarray, forecast_length: int):
Добавил тесты что при вычислении графа на фолдах и внутри тюнера окно не перенастраивается.

2023-12-28 12:28 UTC, valer1435 requested changes

2023-12-28 12:28 UTC, valer1435 commented on test/unit/data_operations/test_time_series_operations.py
> +    ts = get_timeseries(length=1000, random=True)
Не много данных для теста?

2023-12-28 12:31 UTC, kasyanovse commented on test/unit/data_operations/test_time_series_operations.py
> +    ts = get_timeseries(length=1000, random=True)
Чтобы автовыбор окна случайно не совпал с тюнером им нужна некоторая свобода выбора.

2023-12-28 14:44 UTC, valer1435 commented on test/unit/data_operations/test_time_series_operations.py
> +    ts = get_timeseries(length=1000, random=True)
А по времени сколько работает. Я апрувну, но если тест работает дольше 2-3 секунд, стоит урезать

2023-12-28 14:44 UTC, valer1435 approved these changes

2023-12-29 10:06 UTC, kasyanovse commented on test/unit/data_operations/test_time_series_operations.py
> +    ts = get_timeseries(length=1000, random=True)
`test_time_series_operations.py` у меня на компе за 1,5 секунды выполняется.

2024-01-04 07:42 UTC, kasyanovse commented on fedot/core/composer/gp_composer/specific_operators.py
> +            random() < node_mutation_probability):
```suggestion
        lagged = node.operation.metadata.id in ('lagged', 'sparse_lagged', 'exog_ts')
        do_mutation = random() < (node_mutation_probability * (0.5 if lagged else 1))
        if do_mutation:
```

2024-01-04 08:11 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
>              raise ValueError(f"Window size is to high ({self.window_size}) for provided data len {len(time_series)}")
```suggestion
        if self.window_size > max_allowed_window_size:
            new = int(random() * max_allowed_window_size)
            new = min(new, max_allowed_window_size)
            new = max(new, self.window_size_minimum)
            self.log.message((f"Window size of lagged transformation was changed from {self.params.get('window_size')} to {new}"))
            self.params.update(window_size=new)
```

2024-01-04 08:13 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        max_allowed_window_size = len(time_series) - forecast_length
```suggestion
        max_allowed_window_size = max(1, len(time_series) - forecast_length - 1)
```

2024-01-04 10:01 UTC, merged