Add topofeatures
aimclub/FEDOT pull request #1241
Opened 2023-12-28 11:27 UTC by valer1435

TopologicalFeaturesImplementation was added

2023-12-28 11:27 UTC, pep8speaks commented
Hello @valer1435! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`fedot/api/api_utils/assumptions/task_assumptions.py`](https://github.com/aimclub/FEDOT/blob/ecbed309d65039e5542fe2ce5e706c9861687f29/fedot/api/api_utils/assumptions/task_assumptions.py):

> [Line 57:21](https://github.com/aimclub/FEDOT/blob/ecbed309d65039e5542fe2ce5e706c9861687f29/fedot/api/api_utils/assumptions/task_assumptions.py#L57): [E131](https://duckduckgo.com/?q=pep8%20E131) continuation line unaligned for hanging indent
> [Line 129:62](https://github.com/aimclub/FEDOT/blob/ecbed309d65039e5542fe2ce5e706c9861687f29/fedot/api/api_utils/assumptions/task_assumptions.py#L129): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`fedot/core/operations/evaluation/common_preprocessing.py`](https://github.com/aimclub/FEDOT/blob/ecbed309d65039e5542fe2ce5e706c9861687f29/fedot/core/operations/evaluation/common_preprocessing.py):

> [Line 11:121](https://github.com/aimclub/FEDOT/blob/ecbed309d65039e5542fe2ce5e706c9861687f29/fedot/core/operations/evaluation/common_preprocessing.py#L11): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)



* In the file [`fedot/core/operations/evaluation/operation_implementations/data_operations/topological/point_cloud.py`](https://github.com/aimclub/FEDOT/blob/ecbed309d65039e5542fe2ce5e706c9861687f29/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/point_cloud.py):

> [Line 55:9](https://github.com/aimclub/FEDOT/blob/ecbed309d65039e5542fe2ce5e706c9861687f29/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/point_cloud.py#L55): [E741](https://duckduckgo.com/?q=pep8%20E741) ambiguous variable name 'I'
> [Line 60:9](https://github.com/aimclub/FEDOT/blob/ecbed309d65039e5542fe2ce5e706c9861687f29/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/point_cloud.py#L60): [E741](https://duckduckgo.com/?q=pep8%20E741) ambiguous variable name 'I'
> [Line 72:9](https://github.com/aimclub/FEDOT/blob/ecbed309d65039e5542fe2ce5e706c9861687f29/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/point_cloud.py#L72): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'xs' is assigned to but never used



* In the file [`fedot/core/operations/evaluation/operation_implementations/data_operations/topological/topological_extractor.py`](https://github.com/aimclub/FEDOT/blob/ecbed309d65039e5542fe2ce5e706c9861687f29/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/topological_extractor.py):

> [Line 13:121](https://github.com/aimclub/FEDOT/blob/ecbed309d65039e5542fe2ce5e706c9861687f29/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/topological_extractor.py#L13): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)

2023-12-28 13:19 UTC, kasyanovse requested changes
До конца не досмотрел. Давай сначала найденные моменты уточним.
Вообще, кажется, что местами итерирование по спискам можно заменить на работу с `np.ndarray`, что значительно ускорит топологические признаки.
И смущает полное отсутствие тестов для всех новых объектов. Мне кажется, что нужно покрыть все объекты и основные методы.

2023-12-28 13:19 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/topological.py
> +            if np.equal(lifetime, self.ratio_ * max_lifetimes[index]):
Почему через `np.equal`?

2023-12-28 13:19 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/topological.py
> +        persistence_entropy = PersistenceEntropy(n_jobs=-1)
По умолчанию все ноды в FEDOT работают в один поток, т.к. распараллеливание осуществляется на уровне пайплайнов.

2023-12-31 07:42 UTC, valer1435 commented on fedot/core/operations/evaluation/common_preprocessing.py
> +        'topological_features': TopologicalFeaturesImplementation
Вход табличка (лаг таблица), на выходе таблица (в теории можно запустить и для табличных данных, но думаю пока нецелесообразно)

2023-12-31 07:44 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/hankel_matrix.py
> +class HankelMatrix:
На самом деле ни в чем) Не было времени реализовать с момощью нашего лаг преобразования

2024-01-01 09:36 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/point_cloud.py
> +            [np.array([dg for dg in diag if np.isfinite(dg).all()]).max() for diag in diagrams if diag.shape[0] > 0])
Это скорее всего что-то старое и неиспользуемое) Удалил

2024-01-01 09:36 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/point_cloud.py
> +                     ]).sum(axis=0).tolist()
Аналогично

2024-01-01 09:36 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/point_cloud.py
> +                    [np.array(((epsilon_range >= point[0]) & (epsilon_range <= point[1])).astype(int))
Аналогично

2024-01-01 09:36 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/topological.py
> +            return x_transformed
Убрал здесь параллелизм вообще

2024-01-01 10:06 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/topological.py
> +        persistence_entropy = PersistenceEntropy(n_jobs=-1)
Да, мне тоже неприятно, но иначе это работает неприлично долго. Я пока не заметил серьезных проблем из-за этого. Главная проблема у нас из-за распараллеливания была с памятью - тут ее много не надо. Предлагаю пока оставить, но держать в голове, что может когда-то выстрелить

2024-01-02 17:40 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/topological.py
> +        persistence_entropy = PersistenceEntropy(n_jobs=-1)
Может быть попробовать оптимизировать? Накладные расходы на работу с огромным количеством потоков (в пределе это `n_cpu ** n_cpu`) никто не отменял.

2024-01-09 09:04 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/topological.py
> +        persistence_entropy = PersistenceEntropy(n_jobs=-1)
Боюсь, что оптимизация не сильно поможет, так как алгоритмы сами по себе нелинейные. Но это лучше спросить у Ильи

2024-01-09 09:10 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/topological.py
> +        persistence_entropy = PersistenceEntropy(n_jobs=-1)
Посмотрел. Операции извлечения фич в основном линейные. Но проблема в том, что в процессе их генерации мы каждый лаг матрицы преобразуем в еще одну матрицу и работаем со второй матрицей, то есть сложность уже ближе к квадратичной (но не квадрат, поменьше)

2024-01-09 10:14 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/topological.py
> +        persistence_entropy = PersistenceEntropy(n_jobs=-1)
Если каждый лаг матрицы - матрица, то не проще создать n-мерную матрицу и работать с ней векторно?
Я в свое время сталкивался с подобной проблемой и таким образом смог ускорится в десятки раз.

2024-01-09 10:42 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/topological.py
> +        persistence_entropy = PersistenceEntropy(n_jobs=-1)
Не выйдет, так как не все операции векторизуются в контексте оптимизации времени. np.vectorise не ускоряет выполнение

2024-01-09 10:46 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/topological.py
> +        persistence_entropy = PersistenceEntropy(n_jobs=-1)
Я имел ввиду векторизацию в виде использования чистых `numpy` функций над одним многомерным `np.ndarray`.
Но тут надо разбираться как это можно реализовать.

2024-01-09 11:01 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/topological.py
> +        persistence_entropy = PersistenceEntropy(n_jobs=-1)
Тем более код не мой, я скорее его адаптирую для федота

2024-01-12 12:31 UTC, valer1435 commented
/fix-pep8

2024-01-13 08:26 UTC, kasyanovse commented on examples/simple/time_series_forecasting/api_forecasting.py
> +        label = random.choice(np.unique(time_series['label']))
Поставь ограничение на длину датасета, пожалуйста. Если он слишком короткий, то там много проблем с композицией пайплайнов возникает, которые корректно отрабатываются в проде, но падают на тесте. Я бы поставил длину ряда в районе 1000 точек - с ней все хорошо. С длиной до 400 очень часто падает.

2024-01-15 10:42 UTC, valer1435 commented on examples/simple/time_series_forecasting/api_forecasting.py
> +        label = random.choice(np.unique(time_series['label']))
В тестах используются старые датасеты (beer, salaries и тд)

2024-01-15 10:44 UTC, valer1435 commented
/fix-pep8

2024-01-15 10:46 UTC, kasyanovse approved these changes

2024-01-15 11:29 UTC, valer1435 commented
/fix-pep8

2024-01-15 16:48 UTC, valer1435 commented
/fix-pep8

2024-01-15 19:35 UTC, merged