Fast topological features
aimclub/FEDOT pull request #1252
Opened 2024-01-19 15:21 UTC by kasyanovse

This is a 🙋 feature or enhancement.

## Summary

Ускоренная версия топологических фич (в 30 раз). От обычных топологических фич отличаются достаточно сильно:
1. Скинул весь код в один класс.
2. Отказался от использования [giotto-tda](https://github.com/giotto-ai/giotto-tda) в пользу [giotto-ph](https://github.com/giotto-ai/giotto-ph).
3. Изменил расчет фич из топологических фич для максимального ускорения.

## Context

Inspired by https://github.com/aimclub/FEDOT/pull/1241.

2024-01-19 15:21 UTC, pep8speaks commented
Hello @kasyanovse! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`fedot/core/operations/evaluation/common_preprocessing.py`](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/common_preprocessing.py):

> [Line 11:121](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/common_preprocessing.py#L11): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (127 > 120 characters)

* In the file [`fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py`](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py):

> [Line 1:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) 'math' imported but unused
> [Line 2:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L2): [F401](https://duckduckgo.com/?q=pep8%20F401) 'sys' imported but unused
> [Line 3:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L3): [F401](https://duckduckgo.com/?q=pep8%20F401) 'itertools.chain' imported but unused
> [Line 4:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L4): [F401](https://duckduckgo.com/?q=pep8%20F401) 'multiprocessing.cpu_count' imported but unused
> [Line 8:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L8): [F401](https://duckduckgo.com/?q=pep8%20F401) 'scipy.stats.entropy' imported but unused
> [Line 12:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L12): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.operations.evaluation.operation_implementations.data_operations.topological.point_cloud.TopologicalTransformation' imported but unused
> [Line 14:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.operations.evaluation.operation_implementations.data_operations.topological.topological.HolesNumberFeature' imported but unused
> [Line 14:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.operations.evaluation.operation_implementations.data_operations.topological.topological.MaxHoleLifeTimeFeature' imported but unused
> [Line 14:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.operations.evaluation.operation_implementations.data_operations.topological.topological.RelevantHolesNumber' imported but unused
> [Line 14:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.operations.evaluation.operation_implementations.data_operations.topological.topological.AverageHoleLifetimeFeature' imported but unused
> [Line 14:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.operations.evaluation.operation_implementations.data_operations.topological.topological.SumHoleLifetimeFeature' imported but unused
> [Line 14:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.operations.evaluation.operation_implementations.data_operations.topological.topological.PersistenceEntropyFeature' imported but unused
> [Line 14:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.operations.evaluation.operation_implementations.data_operations.topological.topological.SimultaneousAliveHolesFeature' imported but unused
> [Line 14:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.operations.evaluation.operation_implementations.data_operations.topological.topological.AveragePersistenceLandscapeFeature' imported but unused
> [Line 14:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.operations.evaluation.operation_implementations.data_operations.topological.topological.BettiNumbersSumFeature' imported but unused
> [Line 14:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.operations.evaluation.operation_implementations.data_operations.topological.topological.RadiusAtMaxBNFeature' imported but unused
> [Line 14:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.operations.evaluation.operation_implementations.data_operations.topological.topological.PersistenceDiagramsExtractor' imported but unused
> [Line 14:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.operations.evaluation.operation_implementations.data_operations.topological.topological.TopologicalFeaturesExtractor' imported but unused
> [Line 22:1](https://github.com/aimclub/FEDOT/blob/2388af252d9c7744bdb330213760a904861a7e32/fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py#L22): [F401](https://duckduckgo.com/?q=pep8%20F401)  [...]

2024-01-19 15:45 UTC, kasyanovse commented
/fix-pep8

2024-01-22 14:46 UTC, Lopa10ko requested changes

2024-01-22 14:46 UTC, Lopa10ko commented on fedot/api/api_utils/assumptions/task_assumptions.py
> +                                                             'fast_ica', 'ridge'),
неконсистентность в переносах строк
```suggestion
            'topo_ica_ridge':
                PipelineBuilder()
            .add_sequence('lagged', 'fast_topological_features', 'fast_ica', 'ridge'),
```

2024-01-22 14:46 UTC, Lopa10ko commented on fedot/core/repository/data/data_operation_repository.json
> +    "fast_topological_features": {
нужно ли добавлять это сразу в таблицу доступных операций в доках? и в список api параметра `available_operations`

2024-01-22 14:52 UTC, Lopa10ko commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py
> +        self.shape = sum(map(len, [fun(np.zeros((10, ))) for fun in self.feature_funs]))
непонятно, почему `self.shape` вычисляется именно так, если `self.feature_funs` определяется в конструкторе

2024-01-22 16:20 UTC, kasyanovse commented on fedot/api/api_utils/assumptions/task_assumptions.py
> +                                                             'fast_ica', 'ridge'),
Почему? Вроде бы все ок.

2024-01-22 16:20 UTC, kasyanovse commented on fedot/core/repository/data/data_operation_repository.json
> +    "fast_topological_features": {
Ага, добавлю.

2024-01-22 16:27 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py
> +        self.shape = sum(map(len, [fun(np.zeros((10, ))) for fun in self.feature_funs]))
https://github.com/aimclub/FEDOT/pull/1252/commits/18815b83cc186ec859e8c552451057492ef60e40

2024-01-22 16:27 UTC, kasyanovse commented on fedot/core/repository/data/data_operation_repository.json
> +    "fast_topological_features": {
https://github.com/aimclub/FEDOT/pull/1252/commits/328b4b30adaf7b14f91e65d368cfc8fa2cafe9c1

2024-01-22 16:30 UTC, Lopa10ko commented on fedot/api/api_utils/assumptions/task_assumptions.py
> +                                                             'fast_ica', 'ridge'),
ну просто некоторые записи в словаре с переносом `PipelineBuilder()` на новую строку и дальнейшим переносом шагов билдера, а некоторые нет

2024-01-22 16:33 UTC, Lopa10ko commented on fedot/core/repository/data/data_operation_repository.json
> +    "fast_topological_features": {
если не сложно, то вот сюда еще `fedot/api/builder.py`
в список `available_operations`

2024-01-22 16:48 UTC, Lopa10ko commented on fedot/core/repository/data/data_operation_repository.json
> +    "fast_topological_features": {
> [328b4b3](https://github.com/aimclub/FEDOT/commit/328b4b30adaf7b14f91e65d368cfc8fa2cafe9c1)

в этом списке только три колонки с разделителем в запятую.
если запустить сфинкс, то в таком случае отрисуется странная табличка.
в 72-73 строчках можно заменить:
`, only for time series,Data transformation` на `,Time series transformation`

2024-01-24 08:39 UTC, valer1435 commented
Хотелось бы тест на то, что фичи получаются +- те же, что и в обычном

2024-01-24 08:46 UTC, v1docq commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py
> +        result = list()
Неплохо бы вынести хотя бы метрику, n_threads, и размерность гомологий в гиперпараметры. Очень сильно будут влиять на итоговые диаграммы

2024-01-24 08:48 UTC, v1docq commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py
> +        self.shape = None
.Поинт клауд реализовался через абстракцию траекторной матрицы что связывало с собой эти классы и позволяло реализовывать над ними алгебру (складывать, вычитать, делить) для федота это офк лишнее, но просто имей ввиду. Человеку который никогда не видел фильтрацию виетори рипса и персистентных диаграмм
сходу придется учить giotta. Поэтому отказ от собственных абстрактных классов в пользу решений из коробки не всегда самое очевидное решение

2024-01-24 18:15 UTC, kasyanovse commented on fedot/api/api_utils/assumptions/task_assumptions.py
> +                                                             'fast_ica', 'ridge'),
[3972d10](https://github.com/aimclub/FEDOT/pull/1252/commits/3972d10106bbc4f3fdf65b9e35e3c7ee5ba98e0b)

Сразу пофиксил и для другой модели в том же месте.

2024-01-24 18:16 UTC, kasyanovse commented on fedot/core/repository/data/data_operation_repository.json
> +    "fast_topological_features": {
[7f742a4](https://github.com/aimclub/FEDOT/pull/1252/commits/7f742a4ecc6a24dbcdf37585b7dd91b495609fce)
Докстринг билдера.

[e2b0249](https://github.com/aimclub/FEDOT/pull/1252/commits/e2b02497adac08867be0af01db8a0ba924de58f9)
Доки.

2024-01-24 18:17 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py
> +        result = list()
[a749678](https://github.com/aimclub/FEDOT/pull/1252/commits/a74967823cc380a66baf89a019e1741b09d09b77)
[b2c5f3e](https://github.com/aimclub/FEDOT/pull/1252/commits/b2c5f3e319f8429023bc8481e6dc39fc0486b1ed)

Вынес. Распараллеливание сделал на уровне `transform` метода.

2024-01-24 18:18 UTC, kasyanovse commented on fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py
> +        self.shape = None
Согласен, код обычных топо фич читается лучше, но, надеюсь, в этот код мало кому придется лазить)

2024-01-24 18:26 UTC, kasyanovse commented
> Хотелось бы тест на то, что фичи получаются +- те же, что и в обычном

Здесь из топологии генерируются другие фичи, поэтому смысла в этом нет. Сравнение предсказаний для `lagged`-`topo`-`ridge` на картинке. Я бы не сказал, что есть принципиальные отличия, надо тестить в `pytsbe`.

![image](https://github.com/aimclub/FEDOT/assets/25120268/bc228d4a-5fb7-4756-82ca-873aa67bb3bb)


<details>
  <summary>Код для генерации картинки</summary>
  
  ```import logging
from time import perf_counter
import pickle

import numpy as np
from matplotlib import pyplot as plt

from fedot.core.pipelines.node import PipelineNode
from fedot.core.pipelines.pipeline import Pipeline
from fedot.core.repository.tasks import Task, TaskTypesEnum, TsForecastingParams
from fedot.api.main import Fedot
from fedot.core.data.data import InputData
from fedot.core.repository.dataset_types import DataTypesEnum
from fedot.core.data.data_split import train_test_data_setup


RANDOM_SEED = 100


def get_data(data_length=500, test_length=100):
    garmonics = [(0.1, 0.9), (0.1, 1), (0.1, 1.1), (0.05, 2), (0.05, 5), (1, 0.02)]
    time = np.linspace(0, 100, data_length)
    data = time * 0
    for g in garmonics:
        data += g[0] * np.sin(g[1] * 2 * np.pi / time[-1] * 25 * time)

    data = InputData(idx=np.arange(0, data.shape[0]),
                     features=data,
                     target=data,
                     task=Task(TaskTypesEnum.ts_forecasting,
                               TsForecastingParams(forecast_length=test_length)),
                     data_type=DataTypesEnum.ts)
    return train_test_data_setup(data,
                                 validation_blocks=1,
                                 split_ratio=(data_length - test_length) / ((data_length - test_length) + test_length))


def plot_ppl(ppls, train, test, labels):
    _, ax = plt.subplots()
    limits = len(test.target)
    ax.plot(train.idx[-limits:], train.target[-limits:], label='train')
    ax.plot(test.idx, test.target, label='test')
    for label, ppl in zip(labels, ppls):
        predict = ppl.predict(test).predict
        ax.plot(test.idx[-len(predict):], predict, label=label)
    ax.legend()


if __name__ == '__main__':
    train, test = get_data()
    node = PipelineNode('lagged')
    node = PipelineNode('fast_topological_features', nodes_from=[node])
    node = PipelineNode('ridge', nodes_from=[node])
    ppl1 = Pipeline(node)
    t0 = perf_counter()
    ppl1.fit(train)
    ppl1.predict(test)
    print(perf_counter() - t0)

    train, test = get_data()
    node = PipelineNode('lagged')
    node = PipelineNode('topological_features', nodes_from=[node])
    node = PipelineNode('ridge', nodes_from=[node])
    ppl2 = Pipeline(node)
    t0 = perf_counter()
    ppl2.fit(train)
    ppl2.predict(test)
    print(perf_counter() - t0)

    plot_ppl([ppl1, ppl2], train, test, ('fast_topo', 'topo'))

  ```
  
</details>

2024-01-24 18:36 UTC, Lopa10ko approved these changes
lgtm :)
я все nit-pick'и исчерпал

2024-01-26 10:36 UTC, v1docq approved these changes

2024-01-26 12:39 UTC, valer1435 approved these changes

2024-01-27 19:54 UTC, merged