Boosting method implementation (LightGBM)
aimclub/FEDOT pull request #1264
Opened 2024-03-05 17:46 UTC by RomanKharkovskoy

2024-03-07 10:11 UTC, valer1435 commented
@open-code-helper run

2024-03-07 10:14 UTC, valer1435 commented
@open-code-helper run fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py

2024-03-07 11:41 UTC, valer1435 commented
@open-code-helper run

2024-03-07 11:49 UTC, valer1435 commented
@open-code-helper run

2024-03-07 13:48 UTC, valer1435 commented
@open-code-helper run

2024-03-07 13:51 UTC, valer1435 commented
@open-code-helper run

2024-03-07 13:56 UTC, valer1435 commented
@open-code-helper run

2024-03-07 13:59 UTC, valer1435 commented
@open-code-helper run

2024-03-07 14:01 UTC, valer1435 commented
@open-code-helper run

2024-03-07 14:04 UTC, valer1435 commented
@open-code-helper run

2024-03-07 14:05 UTC, valer1435 commented
@open-code-helper run

2024-03-07 14:06 UTC, valer1435 commented
@open-code-helper run

2024-03-07 14:08 UTC, valer1435 commented
@open-code-helper run

2024-03-07 14:23 UTC, valer1435 commented
@open-code-helper run

2024-03-07 14:24 UTC, valer1435 commented
@open-code-helper run

2024-03-07 14:24 UTC, valer1435 commented
@open-code-helper run

2024-03-07 14:29 UTC, valer1435 commented
@open-code-helper run

2024-03-07 14:36 UTC, valer1435 commented
@open-code-helper run

2024-07-30 12:08 UTC, andreygetmanov requested changes

2024-07-30 12:08 UTC, andreygetmanov commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +    def set_eval_metric(n_classes):
Не уверен в надёжности метода. Получается, если нет классов, задача определяется как регрессия. Классы могут случайно появиться в задаче регрессии? Какая метрика используется в задаче регрессии?

Можно сделать так (например): определять задачу через task, а потом уже (если классификация) смотреть на число классов

2024-07-30 13:50 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +    def set_eval_metric(n_classes):
@andreygetmanov Нет, не могут. Они подсчитываются только [для классификации](https://github.com/aimclub/FEDOT/blob/fd3786d2169fa81ba5fcdfbab6cc4a18c87d3c22/fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py#L254), а для регрессии это будет всегда `None`.  В зависимости какой внутренний параметр `objective` в `LGBMRegressor` будет взят. Если оставить пустым, то он автоматически подберет дефолтные метрики. Вот [тут](https://lightgbm.readthedocs.io/en/latest/Parameters.html#objective) можно ознакомиться.

2024-07-30 13:51 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
> +    def set_eval_metric(n_classes):
Решил для регрессии `objective` расширить для тюнинга и добавил их некоторое количество в search_space.

2024-07-30 14:06 UTC, andreygetmanov approved these changes

2024-07-30 14:11 UTC, merged