Jupiter docker added, docker folder created, docker files moved to that folder, readme created
aimclub/FEDOT pull request #1271
Opened 2024-03-11 17:53 UTC by glad4enkonm

This is a 🙋 feature or enhancement.
This is a 🔦 documentation change.

## Summary

As discussed in the Telegram chat here is a PR for Jupiter dockerfile

2024-03-11 18:26 UTC, nicl-nno commented on docker/README.rst
> +Running FEDOT in Docker
Можно на эти файлы ещё дать ссылки в README разделе Installation.

2024-03-11 20:08 UTC, glad4enkonm commented on docker/README.rst
> +Running FEDOT in Docker
Хорошо, добавлю

2024-03-12 09:22 UTC, DRMPN requested changes

2024-03-12 09:22 UTC, DRMPN commented on docker/README.rst
> +- **docker run -p 8888:8888 -v $(pwd):/home/jovyan/work jupyter-with-fedot** запускаем, будет доступен по URL http://[YOUR_IP]:8888, храним все файлы в текущей папке
Указан флаг -v с локальным путем `/home/jovyan/work`

Название образа при запуске отличается от указанного:
Образ:  `jupyter-fedot-tst`
Запуск контейнера:  `jupyter-with-fedot`

2024-03-12 09:22 UTC, DRMPN commented on docker/README.rst
> +Jupiter
Вобще, можно создать docker compose, чтобы пользователь не вводил все эти команды самостоятельно

2024-03-12 09:22 UTC, DRMPN commented on docker/README_en.rst
> +- **cd docker** navigat to the docker folder
ошибка в слове

2024-03-12 09:29 UTC, glad4enkonm commented on docker/README.rst
> +=========
хорошо

2024-03-12 09:29 UTC, glad4enkonm commented on docker/README.rst
> +- **git clone** получаем файлы из git
хорошо

2024-03-12 09:30 UTC, glad4enkonm commented on docker/README.rst
> +- **docker run -p 8888:8888 -v $(pwd):/home/jovyan/work jupyter-with-fedot** запускаем, будет доступен по URL http://[YOUR_IP]:8888, храним все файлы в текущей папке
/home/jovyan/work это правильно, путь внутри контейнера
названия поправлю

2024-03-12 09:31 UTC, glad4enkonm commented on docker/README.rst
> +Jupiter
хорошо

2024-03-12 09:32 UTC, glad4enkonm commented on docker/README_en.rst
> +- **cd docker** navigat to the docker folder
хорошо

2024-03-12 12:41 UTC, nicl-nno approved these changes

2024-03-12 12:44 UTC, DRMPN commented on docker/README.rst
> +- **Проверте наличе docker (docker-compose)** docker (docker-compose) должен быть установлен
Можно указать команду для проверку наличия докера: `docker info`, но это по желанию

2024-03-12 12:44 UTC, DRMPN commented on docker/README.rst
> +============
Заголовки лучше выделять одинаковым количеством символов, как по документации
https://sphinx-tutorial.readthedocs.io/step-1/#sections

2024-03-12 12:49 UTC, DRMPN approved these changes

2024-03-12 13:11 UTC, glad4enkonm commented
Сборка падает, посмотрел сообщения не похоже чтобы причина была в моих изменениях, так?

2024-03-12 14:58 UTC, glad4enkonm commented
> > Сборка падает, посмотрел сообщения не похоже чтобы причина была в моих изменениях, так?
> 
> Проверки можно перезапускать

это не ответ на мой вопрос

2024-03-12 15:00 UTC, glad4enkonm commented
> > Сборка падает, посмотрел сообщения не похоже чтобы причина была в моих изменениях, так?
> 
> Проверки можно перезапускать

можно, так перезапускайте, я тоже могу изъясняться туманными фразами, странно у нас происходит общение

2024-03-12 15:18 UTC, nicl-nno commented
>Сборка падает, посмотрел сообщения не похоже чтобы причина была в моих изменениях, так?

Всё ок, линтер не отрабатывает из-за того что это форк, скорее всего.

Я нажму merge от себя как закончите. Спасибо за PR!

2024-03-12 15:27 UTC, glad4enkonm commented
> > Сборка падает, посмотрел сообщения не похоже чтобы причина была в моих изменениях, так?
> 
> Всё ок, линтер не отрабатывает из-за того что это форк, скорее всего.
> 
> Я нажму merge от себя как закончите. Спасибо за PR!

Спасибо за ответ, на сколько я понимаю, здесь всё сделано с моей стороны

2024-03-12 15:38 UTC, glad4enkonm commented on docker/README.rst
> +============
Впервые работаю с этим форматом, не знал что это важно, поправил

2024-03-12 16:02 UTC, merged