Fix multitarget stratification
aimclub/FEDOT pull request #1308
Opened 2024-06-30 20:03 UTC by DRMPN

This is a 🐛 bug fix. 

## Summary

Disable multitarget stratification when classes are unbalanced.
Add test for this specific scenario.

## Context

Fixes #1307

2024-06-30 20:03 UTC, pep8speaks commented
Hello @DRMPN! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`fedot/core/data/data_split.py`](https://github.com/aimclub/FEDOT/blob/9ff7126650a6f5d245e54f91d759a7e8b86c5cb7/fedot/core/data/data_split.py):

> [Line 148:1](https://github.com/aimclub/FEDOT/blob/9ff7126650a6f5d245e54f91d759a7e8b86c5cb7/fedot/core/data/data_split.py#L148): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

* In the file [`test/unit/data/test_data_split.py`](https://github.com/aimclub/FEDOT/blob/9ff7126650a6f5d245e54f91d759a7e8b86c5cb7/test/unit/data/test_data_split.py):

> [Line 152:121](https://github.com/aimclub/FEDOT/blob/9ff7126650a6f5d245e54f91d759a7e8b86c5cb7/test/unit/data/test_data_split.py#L152): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)

2024-06-30 20:13 UTC, DRMPN commented
Метод внутри пакета sklearn в `train_test_split()` выполняет one hot encode и превращает изначальные 7 классов в 11: 

![image](https://github.com/aimclub/FEDOT/assets/61294398/85ee3ec9-ab3e-4f05-a76d-a7b680465230)

Вследствие появления "новых" классов, их количества не хватает для стратификации, из-за чего появляется ошибка. Предлагаю превентивно производить проверку и отключать стратификацию.

2024-06-30 20:13 UTC, DRMPN commented
/fix-pep8

2024-07-01 10:02 UTC, Lopa10ko requested changes
выглядит валидно, если действительно спасает от ошибки деления со стратификацией, как показано на скрине.

2024-07-01 15:08 UTC, DRMPN commented on test/unit/data/test_data_split.py
> +        "test/data/multitarget_classification.csv",
В тестах видел другую констркцию:

#### **`FEDOT/test/unit/data/test_data.py`** 
``` python
test_file_path = str(os.path.dirname(__file__))
file = '../../data/simple_classification.csv'

file_data = InputData.from_csv(
os.path.join(test_file_path, file))
 ```

Какую лучше использовать?

2024-07-01 15:15 UTC, Lopa10ko commented on test/unit/data/test_data_split.py
> +        "test/data/multitarget_classification.csv",
кажется, лучше через fedot_project_root - с точки зрения путей до файлов ничего не изменяется, но в коде более читаемо

2024-07-02 08:44 UTC, Lopa10ko commented
/fix-pep8

2024-07-02 08:45 UTC, Lopa10ko approved these changes

2024-07-02 09:00 UTC, merged