fix: bring back cgru integration tests
aimclub/FEDOT pull request #1313
Opened 2024-07-23 10:08 UTC by Lopa10ko

This is a 🙋 feature or enhancement.

## Summary

- [x] parametrize tests by models (04d9a15)
- [x] restore the integration tests for the CGRU (a7c4022)
- [ ] restore the integration test scenarios with CGRU model

## Context

fixes #1240

2024-07-27 14:26 UTC, andreygetmanov approved these changes

2024-07-29 12:25 UTC, aPovidlo requested changes

2024-07-29 12:25 UTC, aPovidlo commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `xgboostreg`,`FEDOT model`,`*tree`
Тут все-таки лучше оставить как было

2024-07-29 12:25 UTC, aPovidlo commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `xgboost`,`FEDOT model`,`*tree`
И тут

2024-07-29 12:25 UTC, aPovidlo commented on test/integration/models/test_model.py
> +    to_skip = {'custom', 'arima', 'catboost', 'catboostreg', 'cgru', 'lda', 'decompose', 'class_decompose'}
А почему такая замена с `list` на `dict`?

2024-07-29 12:25 UTC, aPovidlo commented on test/integration/models/test_model.py
> +@pytest.mark.parametrize('operation', OperationTypesRepository('all')._repo, ids=lambda x: x.id)
Планируются другие какие-то параметры?

2024-07-29 12:25 UTC, aPovidlo commented on test/integration/models/test_model.py
> +                try:
Зачем `try`?

2024-07-29 12:25 UTC, aPovidlo commented on test/integration/real_applications/test_heavy_models.py
> -@pytest.mark.skip(reason="Fails due to the https://github.com/aimclub/FEDOT/issues/1240")
Правильно ли я понимаю, что ты тут объединил два теста?

2024-07-29 12:28 UTC, Lopa10ko commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `xgboostreg`,`FEDOT model`,`*tree`
почему? есть тест, который проверяет, есть ли упоминание всех доступных операций в доках.
или имеется в виду `xgboost.XGBRegressor` вместо `FEDOT model`?

2024-07-29 12:30 UTC, Lopa10ko commented on test/integration/real_applications/test_heavy_models.py
> -@pytest.mark.skip(reason="Fails due to the https://github.com/aimclub/FEDOT/issues/1240")
да, все верно, просто параметризованный тест для двух пайплайнов (если что-то из них упадет, можно будет все равно понять, какой пайплайн был проблемным)

2024-07-29 12:32 UTC, Lopa10ko commented on test/integration/models/test_model.py
> +                try:
не могу ответить точно, так как не я писал тест.
видимо, имелось в виду прохождение теста для всех зарегистрированных операций (учитывая случаи, когда для операции нет имплементации)

2024-07-29 12:34 UTC, aPovidlo commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `xgboostreg`,`FEDOT model`,`*tree`
@Lopa10ko второе

2024-07-29 12:35 UTC, Lopa10ko commented on test/integration/models/test_model.py
> +@pytest.mark.parametrize('operation', OperationTypesRepository('all')._repo, ids=lambda x: x.id)
нет

2024-07-29 12:36 UTC, aPovidlo commented on test/integration/models/test_model.py
> +@pytest.mark.parametrize('operation', OperationTypesRepository('all')._repo, ids=lambda x: x.id)
@Lopa10ko А зачем тогда выносить в parametrize?

2024-07-29 12:37 UTC, Lopa10ko commented on test/integration/models/test_model.py
> +    to_skip = {'custom', 'arima', 'catboost', 'catboostreg', 'cgru', 'lda', 'decompose', 'class_decompose'}
nitpick: если есть проверка на вхождение элемента (айдишника операции в этом случае), то look up в dict по сложности O(1) (а в списке за линию)

2024-07-29 12:40 UTC, Lopa10ko commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `xgboostreg`,`FEDOT model`,`*tree`
[e97e790](https://github.com/aimclub/FEDOT/pull/1313/commits/e97e790eb046976c43ec9c1ce94b2ca67d5d433d)

2024-07-29 12:40 UTC, Lopa10ko commented on docs/source/introduction/fedot_features/automation_features.rst
> +   `xgboost`,`FEDOT model`,`*tree`
[e97e790](https://github.com/aimclub/FEDOT/pull/1313/commits/e97e790eb046976c43ec9c1ce94b2ca67d5d433d)

2024-07-29 12:42 UTC, Lopa10ko commented on test/integration/models/test_model.py
> +@pytest.mark.parametrize('operation', OperationTypesRepository('all')._repo, ids=lambda x: x.id)
parametrize для тестов работает быстрее внутреннего цикла, тем более теперь сразу становится понятно, с какой операцией не прошел данный тест

2024-07-29 12:43 UTC, aPovidlo approved these changes

2024-07-29 12:49 UTC, merged