fix: do not launch composition for atomized model
aimclub/FEDOT pull request #1324
Opened 2024-08-23 11:05 UTC by DRMPN

This is a 🐛 bug fix.

## Summary

Quick Fix: prevent launch pipeline composition for Atomized model.

Example notebook with Atomized Model works as expected:
https://github.com/aimclub/FEDOT/blob/master/examples/advanced/additional_learning.py

## Context

Fixes #1317

2024-08-23 11:05 UTC, pep8speaks commented
Hello @DRMPN! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`fedot/api/api_utils/predefined_model.py`](https://github.com/aimclub/FEDOT/blob/114cae699fb660b610e9a0e85fd24151b87ff247/fedot/api/api_utils/predefined_model.py):

> [Line 35:12](https://github.com/aimclub/FEDOT/blob/114cae699fb660b610e9a0e85fd24151b87ff247/fedot/api/api_utils/predefined_model.py#L35): [E713](https://duckduckgo.com/?q=pep8%20E713) test for membership should be 'not in'

* In the file [`fedot/api/main.py`](https://github.com/aimclub/FEDOT/blob/114cae699fb660b610e9a0e85fd24151b87ff247/fedot/api/main.py):

> [Line 171:83](https://github.com/aimclub/FEDOT/blob/114cae699fb660b610e9a0e85fd24151b87ff247/fedot/api/main.py#L171): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2024-08-23 11:06 UTC, DRMPN commented
/fix-pep8

2024-08-23 11:17 UTC, Lopa10ko requested changes
не совсем понятна идея, почему для atomized пропускаем верификацию пайплайна и композицию

2024-08-23 11:17 UTC, Lopa10ko commented on fedot/api/api_utils/predefined_model.py
> +        # ISSUE #1317 Quick Fix: Skip pipeline verification for Atomized Model
лучше не оставлять такие артефакты в коде, всегда можно посмотреть потом по git blame причину изменений, коммит и PR

2024-08-23 11:17 UTC, Lopa10ko commented on fedot/api/api_utils/predefined_model.py
> +        if "atomized" not in pipelines.descriptive_id:
не смотрел подробно, но почему для atomized модельки нужно пропускать верификацию?

2024-08-23 11:17 UTC, Lopa10ko commented on fedot/api/main.py
> +        # ISSUE #1317 Quick Fix: Do not launch composition for Atomized Model
```suggestion
```

2024-08-23 11:17 UTC, Lopa10ko commented on fedot/api/api_utils/predefined_model.py
> +        # ISSUE #1317 Quick Fix: Skip pipeline verification for Atomized Model
```suggestion
```

2024-08-23 11:17 UTC, Lopa10ko commented on fedot/api/main.py
> +        if init_asm := self.params.data.get('initial_assumption'):
nit: моржовый оператор поддерживается с python 3.8, но все равно как-то не совсем хочется его использовать

2024-08-23 13:13 UTC, DRMPN commented
> не совсем понятна идея, почему для atomized пропускаем верификацию пайплайна и композицию

atomized функциональность на данный момент не приоритетная. Реализация будет написана позже.
Пока можно пропустить композицию. 
При верификации тип модели проверяется для Голема, там Atomized Model нет, поэтому код падает.

2024-08-23 13:53 UTC, Lopa10ko commented
> > не совсем понятна идея, почему для atomized пропускаем верификацию пайплайна и композицию
> 
> atomized функциональность на данный момент не приоритетная. Реализация будет написана позже. Пока можно пропустить композицию. При верификации тип модели проверяется для Голема, там Atomized Model нет, поэтому код падает.

понятно, нужно будет в таком случае создать дополнительно 2 issue:
- в продолжение #1227, чтобы наконец убрать `AtomizedModel`
- в поддержку новой `Atomized` для GOLEM

2024-08-24 20:10 UTC, DRMPN commented
> * в продолжение [Atomized model operation #1227](https://github.com/aimclub/FEDOT/pull/1227), чтобы наконец убрать `AtomizedModel`
> * в поддержку новой `Atomized` для GOLEM

Фича с `AtomizedModel` в текущем виде вообще не нужна?

2024-08-24 20:11 UTC, DRMPN commented
/fix-pep8

2024-08-24 20:15 UTC, Lopa10ko commented
> Фича с `AtomizedModel` в текущем виде вообще не нужна?

нужна, пусть и не работает. имел в виду, что после реализации `Atomized` нужно будет почистить упоминания `AtomizedModel`

2024-08-26 01:37 UTC, DRMPN commented
Интеграционные: https://github.com/aimclub/FEDOT/actions/runs/10551401207

2024-08-26 12:00 UTC, nicl-nno commented on fedot/api/main.py
> +        if (predefined_model is None):
Тут скобки лишние.

2024-08-26 12:00 UTC, nicl-nno commented
Как временный воркэраунд норм, но нужно все эти хаки пометить TODO и сообщением для пользователя.
Т,к. сейчас довольно неочевидное поведение возникает.

2024-08-26 21:28 UTC, nicl-nno approved these changes

2024-08-26 22:17 UTC, merged