Fix integration tests
aimclub/FEDOT pull request #764
Opened 2022-07-07 13:08 UTC by valer1435

Integration tests are fixed https://github.com/nccr-itmo/FEDOT/issues/752

2022-07-11 12:43 UTC, IIaKyJIuH requested changes

2022-07-11 12:43 UTC, IIaKyJIuH commented on examples/advanced/multiobj_optimisation.py
> +def run_classification_multiobj_example(with_plot=False, timeout=None):
Как я понял, внизу этого файла нужно ещё поставить запуск функции с включённой визуализацией

2022-07-11 12:43 UTC, IIaKyJIuH commented on fedot/core/repository/operation_types_repository.py
> +        OperationTypesRepository.__repository_dict__[self.operation_type]['initialized_repo'] = None
Ранее с этим полем были проблемы при завершении контекста?

2022-07-11 12:43 UTC, IIaKyJIuH commented on fedot/utilities/profiler/fedot_memory_profiler.py
> +except ImportError as e:
Это после дебаггинга осталось?

2022-07-11 12:43 UTC, IIaKyJIuH commented on examples/simple/pipeline_log.py
> -    release_log(logger=log)
Почему эта функция больше не нужна?

2022-07-11 12:43 UTC, IIaKyJIuH commented on test/integration/quality/test_quality_improvement.py
> +    auto_model = Fedot(problem=problem, timeout=timeout, seed=42, verbose_level=4,
Почему именно 4?

2022-07-11 12:43 UTC, IIaKyJIuH commented on test/integration/quality/test_synthetic_tasks.py
>      auto_model.current_pipeline.fit(train_data)
Точно ли нужно фитить тут сам пайплайн?

2022-07-11 12:43 UTC, IIaKyJIuH commented on test/integration/real_applications/test_examples.py
> +        lines_after = len(f.readlines())
Перепиши, плз, для единообразия с остальными местами на `pathlib.Path`

2022-07-11 12:43 UTC, IIaKyJIuH commented on test/integration/real_applications/test_examples.py
> +#     assert result > 0
Что будем делать с этим?

2022-07-11 12:43 UTC, IIaKyJIuH commented on test/integration/real_applications/test_real_cases.py
> +#     run_multi_modal_case('cases/data/mm_imdb', is_visualise=True, timeout=timedelta(minutes=1))
А с этим?

2022-07-11 13:01 UTC, valer1435 commented on examples/simple/pipeline_log.py
> -    release_log(logger=log)
`release_log` удаляет файл лога. Раньше тест предполагал, что мы пишем лог в отдельный файл. Но теперь лог - синглтон и он пишет в тот файл, который ему указали ранее (дефолтный путь к логу). И проверяется в тесте, что кол-во строк в логе изменилось после теста.

2022-07-12 06:33 UTC, IIaKyJIuH commented on fedot/core/repository/operation_types_repository.py
> +        OperationTypesRepository.__repository_dict__[self.operation_type]['initialized_repo'] = None
Понял

2022-07-13 08:17 UTC, valer1435 commented on fedot/core/pipelines/verification_rules.py
> +        print(type(root_node.operation))
[Не надо](https://github.com/nccr-itmo/FEDOT/pull/764/commits/2d1c619de5cbec2dec0efdebe9936b7b8166256b#diff-626f6b72c51c57024482629cd3ec367c301efd52b2e8883b75c2c6ce394c74eaR41-R44)

2022-07-13 08:18 UTC, nicl-nno approved these changes

2022-07-14 15:36 UTC, andreygetmanov commented on test/integration/api_params/test_main_api_params.py
> +        test_answer=lambda hist: len(hist.individuals) == 2
Не уверен, что понял эти изменения. Можешь объяснить чуть подробнее?

2022-07-15 14:42 UTC, andreygetmanov commented on test/integration/real_applications/test_examples.py
> +#     assert result > 0
> Ждать, пока @andreygetmanov пофиксит баг с сохранением tf-моделей

Дождались!

2022-07-15 16:21 UTC, andreygetmanov requested changes

2022-07-15 16:21 UTC, andreygetmanov commented on cases/multi_modal_genre_prediction.py
> +        .with_cache(OperationsCache())
Этот пример дублирует multi_modal_pipeline example, поэтому было принято решение удалить его

2022-08-03 13:19 UTC, pep8speaks commented
Hello @valer1435! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

































* In the file [`test/integration/real_applications/test_examples.py`](https://github.com/nccr-itmo/FEDOT/blob/fad0b83e5310f117162bada2f26aa12c9244f551/test/integration/real_applications/test_examples.py):

> [Line 115:1](https://github.com/nccr-itmo/FEDOT/blob/fad0b83e5310f117162bada2f26aa12c9244f551/test/integration/real_applications/test_examples.py#L115): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2022-08-03 13:32 UTC, valer1435 commented on test/integration/real_applications/test_examples.py
> +#     assert result > 0
[Добавил новый пример](https://github.com/nccr-itmo/FEDOT/pull/764/commits/fad0b83e5310f117162bada2f26aa12c9244f551#diff-56d68e52bb127113b66fad1ca9ba32e98deac9c953281d3d2d4d6106d983bf7fR112-R115)

2022-08-03 13:32 UTC, valer1435 commented on test/integration/real_applications/test_real_cases.py
> +#     run_multi_modal_case('cases/data/mm_imdb', is_visualise=True, timeout=timedelta(minutes=1))
[Удалил](https://github.com/nccr-itmo/FEDOT/pull/764/commits/fad0b83e5310f117162bada2f26aa12c9244f551#diff-571789f7547e3712aa692be242afe1efa3c73dd846af9a03007112404515e172R96-R97), так как дублируется функциональность

2022-08-03 14:46 UTC, gkirgizov requested changes

2022-08-03 14:46 UTC, gkirgizov commented on examples/advanced/fedot_profiler_example.py
> +from fedot.utilities.profiler.fedot_memory_profiler import MemoryProfiler
а зачем, если у нас и так любой путь начинается с `fedot. ...`?

2022-08-03 14:46 UTC, gkirgizov commented on fedot/core/repository/operation_types_repository.py
> +        OperationTypesRepository.__repository_dict__[self.operation_type]['initialized_repo'] = None
При такой логике легко нарваться на ошибку из-за такой деинициализации: 
```
self.repo = OperationTypesRepository()
with self.repo:
    # какая-то логика
    pass
# ... где-то ниже снова:
with self.repo:
    # тут репозиторий в невалидном состоянии
```
Более того, его нельзя заново проициниализировать из-за декоратора `@run_once`. Получается, что репозиторий у нас вообще неиспользуемый после `__exit__`.
Если такая функциональность правда требуется, то стоит сделать возможно деинициализировать и заново инициализировать. В `__enter__` тогда нужно либо давать ошибку если репозиторий в неициниализированном состоянии, либо проводить дефолтную инициализацию. Еще в класс добавить бы проперти `is_initialized`.

2022-08-04 05:30 UTC, IIaKyJIuH requested changes

2022-08-04 05:30 UTC, IIaKyJIuH commented on test/integration/real_applications/test_examples.py
> +        lines_after = len(f.readlines())
Можно всецело использовать pathlib:
```python
pth = Path(default_fedot_data_dir(), 'log.log')
with pth.open() as f:
    lines_before = len(f.readlines())
run_log_example(pth.name)
with pth.open() as f:
    lines_after = len(f.readlines())
```

2022-08-05 07:59 UTC, valer1435 commented on examples/advanced/fedot_profiler_example.py
> +from fedot.utilities.profiler.fedot_memory_profiler import MemoryProfiler
Возникал конфликт с пакетом memory_profiler. Надо было назвать как-то по-другому

2022-08-05 08:06 UTC, valer1435 commented on fedot/core/repository/operation_types_repository.py
> +        OperationTypesRepository.__repository_dict__[self.operation_type]['initialized_repo'] = None
Вообще сама функциональность с контекстом очень специфичная и сейчас используется только для запуска сторонних automl решений (h2o и TPOT). Вообще говоря их спокойно можно вставить в пайплайн на равне с другими моделями. У нас получается, что при инициализации репозитория, он "вечно" висит в открытом состоянии. А в случае с автомлем, хочется, чтобы мы могли его открыть, сделать то, что нам надо и закрыть, чтобы у нас не прокидывались модели h2o в FEDOT. 

Это нужно сейчас буквально в одном месте в тестах. Пока не вижу идей, зачем это можно использовать несколько раз

2022-08-05 12:23 UTC, andreygetmanov approved these changes

2022-08-05 14:28 UTC, gkirgizov commented on fedot/core/repository/operation_types_repository.py
> +        OperationTypesRepository.__repository_dict__[self.operation_type]['initialized_repo'] = None
В общих чертах понял, о чем ты. Но я скорее о том, что вне завиимости от того, как используется класс, сам по себе он с такой функциональностью реализован некорректно. Так его оставлять нельзя, это рецепт для незаметных багов в будущем. Нужно это как-то решить. Либо явно запретить использовать после закрытия. Либо реализовать до конца функциональность многократного открытия-закрытия.

2022-08-05 14:46 UTC, nicl-nno commented on fedot/core/repository/operation_types_repository.py
> +        OperationTypesRepository.__repository_dict__[self.operation_type]['initialized_repo'] = None
Контекст ещё для GPU используется. Но это тоже пока сильно второстепенный кейс

2022-08-05 14:47 UTC, nicl-nno commented on examples/advanced/fedot_profiler_example.py
> +from fedot.utilities.profiler.fedot_memory_profiler import MemoryProfiler
Что избежать тавтологии, можно назвать automl_memory_profiler

2022-08-08 13:03 UTC, valer1435 commented on fedot/core/repository/operation_types_repository.py
> +        OperationTypesRepository.__repository_dict__[self.operation_type]['initialized_repo'] = None
[Убрал ](https://github.com/nccr-itmo/FEDOT/pull/764/commits/36983162e5b1963141d13e3551a329df43589f2c) `@run_once`. Это оказалось самым простым решением. Когда писал этот метод, делал по образу и подобию `init_default_repositories`. Но поразмыслив сейчас, подумал, что run_once выглядит бессмысленным

2022-08-08 13:03 UTC, valer1435 commented on examples/advanced/fedot_profiler_example.py
> +from fedot.utilities.profiler.fedot_memory_profiler import MemoryProfiler
[Переименовал](https://github.com/nccr-itmo/FEDOT/pull/764/commits/d51d237ed841b2bd7d85e9532af389fb1ce456b0)

2022-08-08 13:04 UTC, valer1435 commented on test/integration/real_applications/test_examples.py
> +        lines_after = len(f.readlines())
[Переделал](https://github.com/nccr-itmo/FEDOT/pull/764/commits/f2ee7364ab95aeb6b3df0327f5b58786ab415c11#diff-56d68e52bb127113b66fad1ca9ba32e98deac9c953281d3d2d4d6106d983bf7fR69)

2022-08-10 12:51 UTC, IIaKyJIuH commented on fedot/core/repository/operation_types_repository.py
> +        OperationTypesRepository.__repository_dict__[self.operation_type]['initialized_repo'] = None
Почему `@run_once` бессмысленен?

2022-08-10 12:52 UTC, IIaKyJIuH commented on test/integration/real_applications/test_examples.py
> +        lines_after = len(f.readlines())
Почему нельзя использовать все операции только над одним объектом `pathlib.Path`?

2022-08-12 09:51 UTC, valer1435 commented on fedot/core/repository/operation_types_repository.py
> +        OperationTypesRepository.__repository_dict__[self.operation_type]['initialized_repo'] = None
В контексте automl репозитория - подразумевается, что он вызывается именно через with. Если дефолтные репозитории действительно стоит объявить один раз, то здесь такая логика излишняя. 

Тогда почему бы не дать возможность запускать несколько раз через with

2022-08-29 09:20 UTC, gkirgizov approved these changes

2022-11-01 10:18 UTC, IIaKyJIuH requested changes

2022-11-01 11:41 UTC, valer1435 commented on examples/advanced/automl/h2o_example.py
> +        h2o_ts_pipeline_evaluation(visualize=True)
Да, когда запускаем пример отдельно - мы хотим посмотреть на результаты. Когда запускаем тесты - нужно просто удостоверится, что ничего не упало

2022-11-01 11:42 UTC, valer1435 commented on test/integration/real_applications/test_examples.py
> +        print(key)
https://github.com/nccr-itmo/FEDOT/pull/764/commits/ffb9538f2cd7db77f6aeab72ea4f9ac3472ffd93#diff-56d68e52bb127113b66fad1ca9ba32e98deac9c953281d3d2d4d6106d983bf7fR35-R37 убрал

2022-11-01 12:03 UTC, valer1435 commented on examples/advanced/automl/h2o_example.py
> +        h2o_ts_pipeline_evaluation(visualize=True)
[Изменил](https://github.com/nccr-itmo/FEDOT/pull/764/commits/ffb9538f2cd7db77f6aeab72ea4f9ac3472ffd93#diff-56d68e52bb127113b66fad1ca9ba32e98deac9c953281d3d2d4d6106d983bf7fR35-R37)

2022-11-01 13:29 UTC, IIaKyJIuH requested changes

2022-11-01 13:29 UTC, IIaKyJIuH commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False):
Стоит внизу файла сделать тогда включение визуализации

2022-11-01 13:29 UTC, IIaKyJIuH commented on examples/simple/interpretable/pipeline_explain.py
> +    explainer = explain_pipeline(pipeline, data=train_data, method='surrogate_dt', visualization=False)
Точно не надо прокидывать в метод `run_pipeline_explain` параметр визуализации?

2022-11-01 13:29 UTC, IIaKyJIuH commented on examples/simple/interpretable/api_explain.py
> +def run_api_explain_example(visualization=True, timeout=None):
Тут тогда `False` должен быть? А внизу тогда нужно указать явно, чтобы визуализация использовалась как раз

2022-11-01 13:29 UTC, IIaKyJIuH commented on examples/simple/classification/api_classification.py
> +def run_classification_example(timeout: float = None, visualise=False):
В файле внизу тоже тогда нужно указать, чтобы использовалась визуализация

2022-11-01 13:29 UTC, IIaKyJIuH commented on examples/advanced/time_series_forecasting/nemo_multiple.py
>  def run_prediction_examples(mode='single'):
А сюда не стоит прокидывать параметр визуализации?

2022-11-01 13:29 UTC, IIaKyJIuH commented on examples/advanced/multimodal_text_num_example.py
> +def run_multi_modal_example(file_path: str, visualization=True) -> float:
Здесь тоже по умолчанию `False` же нужен, м?

2022-11-01 13:29 UTC, IIaKyJIuH commented on examples/advanced/multi_modal_pipeline.py
> +def run_multi_modal_pipeline(files_path: str, visualization=True) -> float:
И тут `False` по умолчанию, не?

2022-11-01 13:29 UTC, IIaKyJIuH commented on fedot/explainability/surrogate_explainer.py
> +    def explain(self, data: InputData, visualization: bool = True, **kwargs):
Тут тоже не `False` ли по умолчанию?

2022-11-01 13:29 UTC, IIaKyJIuH commented on fedot/sensitivity/sa_requirements.py
> +                 visualization: bool = True,
Тут тоже не `False`?

2022-11-01 13:29 UTC, IIaKyJIuH commented on test/integration/real_applications/test_examples.py
> +    forecast = run_ts_forecasting_example(dataset='australia', timeout=1, visualization=False)
параметр визуализации тогда вообще не нужно указывать, раз он и так `False`

2022-11-01 13:29 UTC, IIaKyJIuH commented on test/integration/real_applications/test_examples.py
> +    explainer = run_api_explain_example(visualization=False, timeout=1)
Как и тут, но метод ещё надо изменить, чтобы по умолчанию ставил `False`

2022-11-03 15:41 UTC, valer1435 commented on test/integration/real_applications/test_examples.py
> +    explainer = run_api_explain_example(visualization=False, timeout=1)
[Изменил](https://github.com/aimclub/FEDOT/pull/764/commits/f782d4ca746a39783a799cfd4eb99fc51ee4efb4)

2022-11-03 15:42 UTC, valer1435 commented on test/integration/real_applications/test_examples.py
> +    forecast = run_ts_forecasting_example(dataset='australia', timeout=1, visualization=False)
[Изменил](https://github.com/aimclub/FEDOT/pull/764/commits/d6095e8de3c9d4ad09f2d71ecaeb1b0cd9590689#diff-56d68e52bb127113b66fad1ca9ba32e98deac9c953281d3d2d4d6106d983bf7fR89)

2022-11-03 15:43 UTC, valer1435 commented on fedot/sensitivity/sa_requirements.py
> +                 visualization: bool = True,
Тут True, потому что он много где используется и чаще нужен все-таки True

2022-11-03 15:44 UTC, valer1435 commented on examples/advanced/multi_modal_pipeline.py
> +def run_multi_modal_pipeline(files_path: str, visualization=True) -> float:
[Изменил](https://github.com/aimclub/FEDOT/pull/764/commits/d6095e8de3c9d4ad09f2d71ecaeb1b0cd9590689#diff-56d68e52bb127113b66fad1ca9ba32e98deac9c953281d3d2d4d6106d983bf7fR89)

2022-11-03 15:47 UTC, valer1435 commented on examples/advanced/time_series_forecasting/nemo_multiple.py
>  def run_prediction_examples(mode='single'):
[Добавил](https://github.com/aimclub/FEDOT/pull/764/commits/d6095e8de3c9d4ad09f2d71ecaeb1b0cd9590689#diff-dd5f7c8bea778fdecd2a92b41441696c8ab8224d9b7d8ae3e2b5d6132e6c87ceR319)

2022-11-03 15:47 UTC, valer1435 commented on examples/simple/classification/api_classification.py
> +def run_classification_example(timeout: float = None, visualise=False):
[Добавил](https://github.com/aimclub/FEDOT/pull/764/commits/d6095e8de3c9d4ad09f2d71ecaeb1b0cd9590689#diff-b42069019862f2fa94d0428f6eae68669c539a219c75684c54c01c3778af65dcR27)

2022-11-03 15:47 UTC, valer1435 commented on examples/simple/interpretable/pipeline_explain.py
> +    explainer = explain_pipeline(pipeline, data=train_data, method='surrogate_dt', visualization=False)
[Нужно](https://github.com/aimclub/FEDOT/pull/764/commits/d6095e8de3c9d4ad09f2d71ecaeb1b0cd9590689#diff-85ad0ad01975b2a9518824ab3ece9255e7fdde6893033f57648d2b55164924e9R32)

2022-11-03 15:48 UTC, valer1435 commented on examples/simple/time_series_forecasting/api_forecasting.py
> +                               visualization=False):
[Добавил](https://github.com/aimclub/FEDOT/pull/764/commits/d6095e8de3c9d4ad09f2d71ecaeb1b0cd9590689#diff-61d9c62b97ba3e153b9fb93d8340113be9aeebf42be709a8b91dc56fa2c04ab9R65)

2022-11-03 16:36 UTC, aPovidlo approved these changes

2022-11-03 16:36 UTC, aPovidlo commented on test/integration/real_applications/test_real_cases.py
> -def test_multi_modal_case():
А почему данный тест был удален?

2022-11-03 18:26 UTC, valer1435 commented on test/integration/real_applications/test_real_cases.py
> -def test_multi_modal_case():
Пример был удален

2022-11-07 11:20 UTC, IIaKyJIuH requested changes

2022-11-07 11:20 UTC, IIaKyJIuH commented on examples/advanced/time_series_forecasting/exogenous.py
> +                             visualisation=False) -> None:
давай всё же `visualiZation`. И в докстринге, плз

2022-11-07 11:20 UTC, IIaKyJIuH commented on fedot/api/main.py
> +                method: str = 'surrogate_dt', visualization: bool = True, **kwargs) -> 'Explainer':
Здесь тоже остаётся по умолчанию `True`, т.к. часто используется?

2022-11-07 15:35 UTC, valer1435 commented on fedot/api/main.py
> +                method: str = 'surrogate_dt', visualization: bool = True, **kwargs) -> 'Explainer':
Да, так как это не пример, а метод апи. Основная функциональность здесь - показать какие-то картинки для анализа. Поэтому true

2022-11-07 16:18 UTC, valer1435 commented on examples/advanced/time_series_forecasting/exogenous.py
> +                             visualisation=False) -> None:
[Поменял](https://github.com/aimclub/FEDOT/pull/764/commits/525205250f007872013987d5ee77a5c03385f6de#diff-5c1b6605a571a773098220e5a52e069659dfc2cc44f673ab8759f7dea4314c6dR62)

2022-11-07 16:19 UTC, valer1435 commented on examples/advanced/time_series_forecasting/nemo_multiple.py
> +def run_single_example(len_forecast=40, visualization=True):
[поправил](https://github.com/aimclub/FEDOT/pull/764/commits/525205250f007872013987d5ee77a5c03385f6de#diff-dd5f7c8bea778fdecd2a92b41441696c8ab8224d9b7d8ae3e2b5d6132e6c87ceR248)

2022-11-08 08:47 UTC, IIaKyJIuH approved these changes

2022-11-08 12:17 UTC, merged