Implement custom class for generations
aimclub/FEDOT pull request #913
Opened 2022-09-28 12:41 UTC by MorrisNein

This PR is addressed to solve the following issues:

- #901 (including the inner #896 & #900) 
- #846 

Also makes a step towards #866 (labeled generations are planned, possible with custom values).

Work in progress:

- [ ] Move `OptHistory` and related objects to a separate module.
- [ ] Implement custom classes for individuals storage: `IndividualsList` & `Generation`.
- [ ] Make the new classes responsible for consistency of individuals during the optimization by implementing `individuals_pool` context variable.
- [ ] Wrap the optimization process into the new context, test resulting history consistency with & without multiprocessing.
- [ ] Set signatures of operators for working with `IndividualsList` or `Generation`.
- [ ] Include ability for generations labeling & other metadata.

2022-11-03 12:22 UTC, gkirgizov requested changes

2022-11-03 12:22 UTC, gkirgizov commented on fedot/core/optimisers/opt_history_objects/opt_history.py
> +        self.individuals.append(generation)
А OptHistory может сам подсчитывать номер поколения `generation_number`?

2022-11-03 12:22 UTC, gkirgizov commented on fedot/core/optimisers/opt_history_objects/opt_history.py
> +        self.individuals.append(generation)
и, возможно, лэйбл Optional

2022-11-03 12:22 UTC, gkirgizov commented on fedot/core/optimisers/opt_history_objects/opt_history.py
> +                return gen
Мы хотим наружу светить этим классом? Или он внутренний, утилитарный?

2022-11-03 12:22 UTC, gkirgizov commented on fedot/core/optimisers/populational_optimizer.py
> +                self._update_population(new_population, f'evo_gen_{self.generations.generation_num}')
а нам нужен этот лейбл для чего-то?

2022-11-03 12:22 UTC, gkirgizov commented on fedot/core/optimisers/populational_optimizer.py
> +
немного смущает то что есть и best_graphs и best_individuals в публичном интерфейсе.
эта проперть где-то используется кроме как, собтсвенно, в best_graphs?

2022-11-03 12:22 UTC, gkirgizov commented on fedot/core/optimisers/opt_history_objects/generation.py
> +            individual.set_native_generation(self.generation_num)
Если у нас теперь номер поколения хранится в Generation, надо ли хранить его и в Individual? Напомни, где это  используется?

2022-11-03 12:59 UTC, MorrisNein commented on fedot/core/optimisers/opt_history_objects/parent_operator.py
> +            object.__setattr__(self, 'parent_individuals', IndividualParents(parent_individuals))
Потому что dataclass(frozen=True)

2022-11-03 13:00 UTC, MorrisNein commented on fedot/core/optimisers/opt_history_objects/parent_operator.py
> +    parent_individuals: Union[IndividualParents, Iterable[Individual], Individual] = field()
Ты как-то смог отревьювить старую версию. Этого класса уже нет. Там может быть только tuple, а Union сделал, чтобы подавать в init разные варианты, которые потом унифицируются

2022-11-03 13:08 UTC, MorrisNein commented on fedot/core/optimisers/populational_optimizer.py
> +                self._update_population(new_population, f'evo_gen_{self.generations.generation_num}')
Данный конкретный -- нет. Можно сделать эти поколения и без лейблов.

2022-11-03 13:09 UTC, MorrisNein commented on fedot/core/optimisers/populational_optimizer.py
> +
Там, где в историю добавляеются `final_choices`. Можем оставить что-то одно из этого.

2022-11-03 13:10 UTC, MorrisNein commented on fedot/core/optimisers/opt_history_objects/generation.py
> +            individual.set_native_generation(self.generation_num)
Индивид таким образом узнаёт о том, в каком моменте он был создан в истории. Это используется в механизме наследования. У нас могут быть индивиды без поколений в предках, которые воспринимаются как промежуточные.

2022-11-03 13:12 UTC, MorrisNein commented on fedot/core/optimisers/opt_history_objects/opt_history.py
> +                return gen
Я думаю, что это опционально. Можем ограничиться возвращением списка индивидов, конечно. Вообще для анализа истории в коде неплохо бы работать с поколениями, потому что там могут быть сведения, такие как лейблы, номера поколений и метаданные.

2022-11-03 13:33 UTC, gkirgizov commented on fedot/core/optimisers/opt_history_objects/parent_operator.py
> +    parent_individuals: Union[IndividualParents, Iterable[Individual], Individual] = field()
да, разрабатываю в параллельной ветке машину времени.
неактуально, действительно

2022-11-03 13:35 UTC, MorrisNein commented on fedot/core/optimisers/opt_history_objects/opt_history.py
> +        self.individuals.append(generation)
Подсчитывать наподобие `GenerationsKeeper`? У нас тогда будет 2 отдельных места, где ведётся подсчёт поколений. Выглядит не очень

2022-11-03 13:36 UTC, MorrisNein commented on fedot/core/optimisers/opt_history_objects/opt_history.py
> +        self.individuals.append(generation)
С необязательным лейблом согласен

2022-11-04 08:32 UTC, gkirgizov commented on fedot/core/optimisers/opt_history_objects/opt_history.py
> +        self.individuals.append(generation)
> Подсчитывать наподобие `GenerationsKeeper`? У нас тогда будет 2 отдельных места, где ведётся подсчёт поколений. Выглядит не очень

Тоже подумал об этом. Но тут у нас возникает tradeoff: вводить зависимость между классами или продублировать подсчет. С учетом того, что функциональность тривиальна, проще продублировать.
А то это как сходить постучаться к соседу, чтобы спросить, который час.

2022-11-04 08:54 UTC, gkirgizov commented on fedot/core/optimisers/populational_optimizer.py
> +                self._update_population(new_population, f'evo_gen_{self.generations.generation_num}')
давай тогда эту строчку оставим без лейбла, а то возникает впеачтение, будто это нужно обязательно указаывать для апдейта поколения

2022-11-04 08:58 UTC, gkirgizov commented on fedot/core/optimisers/populational_optimizer.py
> +
да, давай что-то одно оставим

2022-11-08 11:06 UTC, MorrisNein commented on fedot/core/optimisers/populational_optimizer.py
> +
[Accomplished](https://github.com/aimclub/FEDOT/pull/913/commits/af4055d67e2edbd866644bcdbb0cd5261da51161)

2022-11-09 15:27 UTC, nicl-nno approved these changes
Нет ли смысла сразу и результат работы тюнера сохранять в историю?

2022-11-09 15:27 UTC, nicl-nno commented on test/unit/composer/test_history.py
> +    assert history.final_choices
Тут бы проверить, что их нужное количество.

2022-11-10 08:12 UTC, gkirgizov requested changes

2022-11-10 08:12 UTC, gkirgizov commented on fedot/core/optimisers/populational_optimizer.py
>              individual.set_native_generation(self.current_generation_num)
А нам сейчас нужны эти строки?

2022-11-10 08:12 UTC, gkirgizov commented on fedot/core/optimisers/opt_history_objects/generation.py
> +        return copy(self)
зачем отдельный метод, если есть `copy()`?

2022-11-10 08:19 UTC, MorrisNein commented on fedot/core/optimisers/opt_history_objects/generation.py
> +        return copy(self)
Переопределил метод класса-родителя, чтобы он работал без ошибки

2022-11-10 08:23 UTC, MorrisNein commented on fedot/core/optimisers/populational_optimizer.py
>              individual.set_native_generation(self.current_generation_num)
Действительно, не нужны. Я их уже убирал, потом, видимо, ненароком откатил

2022-11-10 08:23 UTC, MorrisNein commented on fedot/core/optimisers/populational_optimizer.py
>              individual.set_native_generation(self.current_generation_num)
Действительно, не нужны. Я их уже убирал, потом, видимо, ненароком откатил

2022-11-10 10:40 UTC, gkirgizov approved these changes

2022-11-10 15:04 UTC, aPovidlo approved these changes

2022-11-10 16:32 UTC, MorrisNein commented on test/unit/composer/test_history.py
> +    assert history.final_choices
[Теперь проверяем](https://github.com/aimclub/FEDOT/pull/913/commits/63e59b5364becbe89beed97f85ed3ab1b0f800dc)

2022-11-10 16:33 UTC, MorrisNein commented
> Нет ли смысла сразу и результат работы тюнера сохранять в историю?

Добавил в API такую возможность

https://github.com/aimclub/FEDOT/pull/913/commits/d4d8a074f8036252e7bd96dd518e8832b873aed7

2022-11-10 17:09 UTC, merged