Docs & diagrams for architecture & adapter subsystem (#886)
aimclub/FEDOT pull request #937
Opened 2022-10-17 18:52 UTC by gkirgizov

Resolves #886

Added 2 diagrams:
- One is an high-level view of framework architecture (UML component diagram)
- Another is a conceptual scheme of what is Adapter, why it's needed and how to use it

If diagrams or passages ain't straightforward, pls let me know. 
Comments & propositions are welcome, as always.

2022-10-17 21:56 UTC, nicl-nno commented on docs/source/advanced/adapter.rst
> +Problem domains usually work with their own graph representations that are suitable for specific needs. For example, in the case of AutoML problem (as in Fedot framework) this is a pipeline of ML ope
FEDOT лучше капсом. Вместо GEFEST лучше к BAMT отослаться и баесовским сетям, соответсвенно. Или NAS-у. Это будет более понятно, как примеры графовых моделей.

2022-10-17 21:59 UTC, nicl-nno commented on docs/source/advanced/architecture.rst
> +* Final optimal graph can be used for predictions.
Ну тут по факту архитектура оптимизатора описана, а не фреймворка в целом. Стоит добавить пару пунктов по остальным модулям (Pipeline, Data, etc).

2022-10-18 09:45 UTC, gkirgizov commented on docs/source/advanced/architecture.rst
> +* Final optimal graph can be used for predictions.
да, пожалуй. добавлю

2022-10-18 12:17 UTC, YamLyubov commented on docs/source/api/adapter.rst
> +   :no-undoc-members:
В сгенерированном файле не отображаются пункты в разделах Important notions и Adaptation registry usage and behavior. Нужно между  списком и заголовком добавить пустую строку.

2022-10-18 12:18 UTC, YamLyubov commented on docs/source/advanced/architecture.rst
> +* Final optimal graph can be used for predictions.
Возможно стоит добавить еще про тюнинг и про то, где задаются модели, операции и их параметры, исспользуемые при композоровании.

2022-10-25 07:43 UTC, YamLyubov requested changes

2022-10-25 07:43 UTC, YamLyubov commented on docs/source/api/adapter.rst
> +   :no-undoc-members:
Здесь пока-что так же 
![image](https://user-images.githubusercontent.com/43475193/197712283-13f03c52-14e9-471c-8a3c-0e97d6214d8c.png)

2022-10-25 07:51 UTC, gkirgizov commented on docs/source/api/adapter.rst
> +   :no-undoc-members:
Да, не заметил. [Поправил](https://github.com/nccr-itmo/FEDOT/pull/937/commits/a66cdb7ff12d92fd6fc0ea6e3b7a4463b14054f0)

2022-10-25 08:01 UTC, gkirgizov commented on docs/source/api/adapter.rst
> +   :no-undoc-members:
[добавил](https://github.com/nccr-itmo/FEDOT/pull/937/commits/a66cdb7ff12d92fd6fc0ea6e3b7a4463b14054f0)

2022-10-25 11:48 UTC, YamLyubov approved these changes

2022-11-08 09:37 UTC, nicl-nno approved these changes
Давайте вольем as ia.

2022-11-09 10:42 UTC, merged