Documentation for ts forecasting
aimclub/FEDOT pull request #960
Opened 2022-10-26 09:29 UTC by YamLyubov

Documentation for time-series forecasting are added. The actual page:

#883

2022-10-26 10:02 UTC, nicl-nno requested changes
Чего ещё не хватает: каких-то реальных примеров создания и визализации для in-sample предсказаний.

2022-10-26 10:02 UTC, nicl-nno commented on docs/source/basics/ts_forecasting.rst
> +   :width: 80%
Это всё уже детали реализации - важные, но могущие быть отправленными куда-то подальше от начала.

Нужно начать с какого-то максимально простого и лаконичного примера - с минимумом кода, кастомизации параметров и т.п. С пояснением - что и в каком формате на входе, что и в каком формате на выходе.

2022-10-26 10:28 UTC, YamLyubov commented on docs/source/basics/ts_forecasting.rst
> +- ``Fedot.forecast`` can be used to obtain out-of-sample forecast with custom forecast horizon.
Пока что его нет, поэтому решила не писать. Думала обновить, когда будет влито в мастер.

2022-10-26 10:30 UTC, YamLyubov commented on docs/source/basics/ts_forecasting.rst
> +                  available_operations=['lagged', 'smoothing', 'diff_filter', 'gaussian_filter',
Я столкнулась с тем, что если запускать на всех операциях, то fit падает с ошибкой. Постараюсь разобраться в чем проблема

2022-10-26 10:33 UTC, YamLyubov commented on docs/source/basics/ts_forecasting.rst
> +``split_ratio`` and ``shuffle_flag`` are ignored for time-series forecasting.
Написала, как это сейчас по факту происходит. Возможно стоит сделать это в отдельном pr.

2022-11-18 12:22 UTC, MorrisNein commented on docs/source/basics/ts_forecasting.rst
> +- ``Fedot.forecast`` can be used to obtain out-of-sample forecast with custom forecast horizon.
При беглом прочтении не понял разницу, только раза 3 перечитав. Предлагаю сформулировать описание для этих методов в одинаковых терминах и структуре, сконцентрировавшись на отличиях. Что-то вроде такого:

```
- ``Fedot.predict`` obtains forecast of future values with ``forecast_length`` predefined in the task parameters before learning.

- ``Fedot.forecast`` obtains parametrized forecast with custom ``pre_history`` and ``horizon``. Currently, only out-of-sample forecasting is supported.
```

2022-11-18 13:41 UTC, YamLyubov commented on docs/source/basics/ts_forecasting.rst
> +- ``Fedot.forecast`` can be used to obtain out-of-sample forecast with custom forecast horizon.
Это не совсем так. 
```Fedot.forecast``` поддерживает только out-of-sample и может получать итеративное предсказание, используя out-of-sample.

```Fedot.predict```сейчас перерабатывается, чтобы поддерживать итеративное in-sample предсказание https://github.com/aimclub/FEDOT/pull/930

2022-11-18 14:05 UTC, MorrisNein commented on docs/source/basics/ts_forecasting.rst
> +- ``Fedot.forecast`` can be used to obtain out-of-sample forecast with custom forecast horizon.
Ага, вот это как раз скорректировать, и должно стать понятнее

2022-11-28 16:07 UTC, YamLyubov commented on docs/source/basics/ts_forecasting.rst
> +Automated
[Добавила ](https://github.com/aimclub/FEDOT/pull/960/files#diff-081c74510a99d7346bfdbc2d3140fefa83d1caa2eddaa09d76bd910d60175c1fR21)

2022-11-28 16:08 UTC, YamLyubov commented on docs/source/basics/ts_forecasting.rst
> +    pipeline.show()
[Везде добавила](https://github.com/aimclub/FEDOT/pull/960/files#diff-081c74510a99d7346bfdbc2d3140fefa83d1caa2eddaa09d76bd910d60175c1fR59
)

2022-11-28 16:10 UTC, YamLyubov commented on docs/source/basics/ts_forecasting.rst
> +    {'rmse': 2.6591575431482206, 'mae': 2.1415227340013323, 'mape': 0.09970880013852462}
Добавило округление в доке и в [самой функции](https://github.com/aimclub/FEDOT/pull/960/files#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR382)

2022-11-28 16:12 UTC, YamLyubov commented on docs/source/basics/ts_forecasting.rst
> +        .to_pipeline()
Пояснения тоже [добавила](https://github.com/aimclub/FEDOT/pull/960/files#diff-081c74510a99d7346bfdbc2d3140fefa83d1caa2eddaa09d76bd910d60175c1fR140)

2022-11-28 16:14 UTC, YamLyubov commented on docs/source/basics/ts_forecasting.rst
> +- ``Fedot.forecast`` can be used to obtain out-of-sample forecast with custom forecast horizon.
[Изменила](https://github.com/aimclub/FEDOT/pull/960/files#diff-081c74510a99d7346bfdbc2d3140fefa83d1caa2eddaa09d76bd910d60175c1fR253) описание и довавиля примеры

2022-11-28 16:15 UTC, YamLyubov commented on docs/source/basics/ts_forecasting.rst
> +                  available_operations=['lagged', 'smoothing', 'diff_filter', 'gaussian_filter',
[Убрала](https://github.com/aimclub/FEDOT/pull/960/files#diff-081c74510a99d7346bfdbc2d3140fefa83d1caa2eddaa09d76bd910d60175c1fR468)

2022-11-28 16:16 UTC, YamLyubov commented on docs/source/basics/ts_forecasting.rst
> +                  available_operations=['lagged', 'smoothing', 'diff_filter', 'gaussian_filter',
Для раздела с многомерными рядами мне нужна помощь, чтобы различия multi ts и multimodal описать

2022-11-28 16:16 UTC, YamLyubov commented on docs/source/basics/ts_forecasting.rst
> +   :width: 80%
[Перенесла в конец](https://github.com/aimclub/FEDOT/pull/960/files#diff-081c74510a99d7346bfdbc2d3140fefa83d1caa2eddaa09d76bd910d60175c1fR601)

2022-11-30 10:42 UTC, nicl-nno approved these changes

2022-11-30 10:54 UTC, YamLyubov commented on docs/source/basics/ts_forecasting.rst
> +                  available_operations=['lagged', 'smoothing', 'diff_filter', 'gaussian_filter',
@ChrisLisbon 
Спасибо!
Посмотри пожалуйста этот раздел и проверь корректность описания file:///C:/Users/admin/Documents/fedot%20docs/basics/ts_forecasting.html#multivariate-time-series-forecasting

2022-11-30 12:53 UTC, nicl-nno commented on docs/source/basics/ts_forecasting.rst
> +                  available_operations=['lagged', 'smoothing', 'diff_filter', 'gaussian_filter',
Ссылка не та)

2022-11-30 15:28 UTC, MorrisNein requested changes
Пожалуйста, обнови networkx и перерисуй картинки пайплайнов. Они должны выглядеть чуть получше

2022-12-01 08:36 UTC, MorrisNein approved these changes

2022-12-01 10:13 UTC, merged