Documentation for tabular data
aimclub/FEDOT pull request #964
Opened 2022-10-31 12:15 UTC by aPovidlo

Resolve: #882 

Documentation of tabular data in classification and regression task are added.

The actual page:

2022-10-31 15:13 UTC, nicl-nno commented on docs/source/basics/tabular_data.rst
> +    prediction = model.predict(features=test)
Тут же про predict_proba стоит сказать.

2022-10-31 15:15 UTC, nicl-nno commented on docs/source/basics/tabular_data.rst
> +Tabular Data Prediction
Не очень понятно звучит. 

Мб Tabular Classification and Regression

2022-11-01 08:21 UTC, gkirgizov requested changes

2022-11-01 08:21 UTC, gkirgizov commented on docs/source/basics/tabular_data.rst
> +problem.
множественное число?

2022-11-01 08:21 UTC, gkirgizov commented on docs/source/basics/tabular_data.rst
> +    Class ``Fedot()`` has more than two params, e.g., ``timeout`` for setting time limits or
если речь про какой-то класс, то лучше его имя без скобок писать. иначе речь будто про вызов init.
то же самое про DataFrame выше

2022-11-01 08:21 UTC, gkirgizov commented on docs/source/basics/tabular_data.rst
> +The ``.fit()`` method begins the optimization and returns the resulting composite pipeline.
методы лучше без точки, если только ты не хочешь полностью писать `Fedot.predict()`

2022-11-01 08:21 UTC, gkirgizov commented on docs/source/basics/tabular_data.rst
> +    The same way FEDOT can be used to ``regression`` problem. Only it is required to change params according the problem
Порядок слов. 
*It is only required...*

2022-11-01 08:21 UTC, gkirgizov commented on docs/source/basics/tabular_data.rst
> +    Class ``Fedot()`` has more than two params, e.g., ``timeout`` for setting time limits or
e.g. пишется без запятой после

2022-11-01 08:21 UTC, gkirgizov commented on docs/source/basics/tabular_data.rst
> +    ``n_jobs`` for parallelization. For more details, see the `FEDOT API <https://fedot.readthedocs.io/en/latest/api/api.html>`_ section in our documentation.
Внутренние ссылки лучше оформлять средствами sphinx, а то со временем они меняются и такие http-style  оказываются сломанны.
Кажется, [вот так правильно ](https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html#the-doc-role)

2022-11-01 08:21 UTC, gkirgizov commented on docs/source/basics/tabular_data.rst
> +
Лучше бы добавиьт вводное предложение перед перечилением, чтобы быть более human-friendly, а-ля "больше деталей вы можете найти в примерах"

2022-11-01 09:32 UTC, aPovidlo commented on docs/source/basics/tabular_data.rst
> +    Class ``Fedot()`` has more than two params, e.g., ``timeout`` for setting time limits or
> если речь про какой-то класс, то лучше его имя без скобок писать. иначе речь будто про вызов init. то же самое про DataFrame выше

Так речь именно про параметры передаваемые во время инициализации

2022-11-01 09:33 UTC, aPovidlo commented on docs/source/basics/tabular_data.rst
> +The ``.fit()`` method begins the optimization and returns the resulting composite pipeline.
> методы лучше без точки, если только ты не хочешь полностью писать `Fedot.predict()`

Хорошо, уберу точки

2022-11-02 09:02 UTC, gkirgizov commented on docs/source/basics/tabular_data.rst
> +    Class ``Fedot()`` has more than two params, e.g., ``timeout`` for setting time limits or
Но ты начинаешь предложение со слова `Class` , а пустые скобки мало смысла писать для имени класса

2022-11-02 09:04 UTC, gkirgizov approved these changes

2022-11-02 09:08 UTC, aPovidlo commented on docs/source/basics/tabular_data.rst
> +    Class ``Fedot()`` has more than two params, e.g., ``timeout`` for setting time limits or
@gkirgizov А как тогда лучше написать? Object?

2022-11-02 12:21 UTC, aPovidlo commented on docs/source/basics/tabular_data.rst
> +    prediction = model.predict(features=test)
@nicl-nno указал в блоке `hint`

2022-11-02 12:55 UTC, nicl-nno approved these changes
Можно ещё добавить пример визуализации какого-то интересного пайплайна и сохранения его в json. Раз этот раздел первый по порядку - то читателей может быть не в курсе, как они выглядят.

2022-11-03 16:47 UTC, aPovidlo commented
> Можно ещё добавить пример визуализации какого-то интересного пайплайна и сохранения его в json. Раз этот раздел первый по порядку - то читателей может быть не в курсе, как они выглядят.

Может это сделать как отдельную страницу, а не заталкивать все в Tabular data?

2022-11-03 16:49 UTC, aPovidlo commented
> > Можно ещё добавить пример визуализации какого-то интересного пайплайна и сохранения его в json. Раз этот раздел первый по порядку - то читателей может быть не в курсе, как они выглядят.
> 
> Может это сделать как отдельную страницу в Basics, а не заталкивать все в Tabular data?

Сохранение в json есть в раздел Advanced usage

2022-11-03 17:27 UTC, nicl-nno commented
>Может это сделать как отдельную страницу в Basics, а не заталкивать все в Tabular data?

Ну кажется это две строчки кода. Можешь и отдельно оформить, но показать структуру пайплайна для классификации в примере по классификацию точно будет не лишним. Аналогично про регрессию.

2022-11-04 09:05 UTC, gkirgizov commented on docs/source/basics/tabular_data.rst
> +    Class ``Fedot()`` has more than two params, e.g., ``timeout`` for setting time limits or
ну можно просто `Fedot.__init__()`, если хочешь подчеркнуть что это про init

2022-11-07 14:52 UTC, gkirgizov approved these changes

2022-11-08 14:29 UTC, nicl-nno approved these changes

2022-11-09 11:18 UTC, merged