Make Objective more general & fix adaptive pop size scheme
aimclub/FEDOT pull request #966
Opened 2022-11-01 16:22 UTC by gkirgizov

- Abstract Objective from MetricsEnum for GOLEM (it doesn't yet need these Metrics, as they are specific for FEDOT)
- Modify GenerationKeeper to allow improvement watching & adaptive scheme for custom quality & complexity metrics (Resolves #959)

2022-11-01 23:13 UTC, nicl-nno commented
Общее соображение - а не отказаться ли нам от MetricsEnum вообще? Кажется, они себя не очень оправдали.

2022-11-02 09:13 UTC, gkirgizov commented
> Общее соображение - а не отказаться ли нам от MetricsEnum вообще? Кажется, они себя не очень оправдали.

В целом, они много функциональность не несут. 
Я вижу 2 плюса:
- удобный список того что доступно
- читаемые имена (metrics enum удобно где-нибудь в логах печатать) 

И то и другое можно каким-то словариком поддержать. Да и вроде эти словарики уже есть. Так что metricsenum дублирует существующие словарики и иерархию Metrics. Я, пожалуй, против такого дублирования. 
Можно будет убрать потом. Нужно будет много использований переиначить.

Кстати, в голем я их все равно пока не планировал переносить, так как метрики завязаны на InputData, а это на данный момент специфичный для Федота класс.

2022-11-02 15:48 UTC, YamLyubov requested changes

2022-11-02 15:48 UTC, YamLyubov commented on fedot/api/api_utils/api_composer.py
>          if isinstance(metric, (str, Callable)):
Здесь не хватает проверки на ``MetricEnum``. Или просто заменить на ``not isinstance(metric, Sequance)``

2022-11-08 12:58 UTC, YamLyubov approved these changes

2022-11-08 14:03 UTC, merged