Documentation for `Examples and notebooks`
aimclub/FEDOT pull request #968
Opened 2022-11-02 11:58 UTC by aPovidlo

Resolve: #882

Documentation in [Examples and notebooks](https://fedot.readthedocs.io/en/latest/examples/index.html) section.

The actual page: https://fedot--964.org.readthedocs.build/en/964/basics/tabular_data.html

2022-11-02 14:33 UTC, nicl-nno requested changes
Хорошо бы сделать ещё секцию Examples со ссылками на примеры из cases и (возможно) репозиотории хакатонов.

2022-11-02 14:33 UTC, nicl-nno commented on docs/source/examples/index.rst
> +FEDOT is covered with examples materials for both novice and advanced machine learners and data scientists.
beginners and experienced ... 
будет лучше.

2022-11-07 16:39 UTC, MorrisNein requested changes

2022-11-07 16:39 UTC, MorrisNein commented on docs/source/examples/index.rst
> +In this section you can find notebooks and useful pipelines structure for various problems:
Тут правильнее `pipeline structures`

2022-11-07 16:39 UTC, MorrisNein commented on docs/source/examples/index.rst
> +FEDOT is covered with examples materials for both beginners and experienced machine learners and data scientists.
Имхо, `machine learners` звучит странно. Предлагаю такой вариант:

`... for both beginners and experienced data scientists and machine learning professionals.`

2022-11-07 16:39 UTC, MorrisNein commented on docs/source/examples/notebooks.rst
> +In this repository you can find following notebooks:
`you can find` часто повторяется. Предлагаю заменить тут на

 `This repository contains following notebooks:`

2022-11-07 16:39 UTC, MorrisNein commented on docs/source/examples/notebooks.rst
> +you can find notebooks, where presented work of framework in JupyterLab with MLflow:
```The `repository<https://github.com/stockblog/webinar_automl_fedot>`_ contains examples of usage with JupiterLab & MLflow:```

2022-11-08 12:28 UTC, nicl-nno approved these changes

2022-11-08 17:21 UTC, MorrisNein approved these changes
Всё супер!

2022-11-08 17:21 UTC, MorrisNein commented on docs/source/examples/notebooks.rst
> +Fedot can be used in cloud services, e.g. `VK Cloud's ML Platform <https://mcs.mail.ru/>`_. This `repository <https://github.com/stockblog/webinar_automl_fedot>`_
И последнее, что не заметил, тут Федота капсом обзови

2022-11-09 11:46 UTC, merged