Early stopping criteria
aimclub/FEDOT pull request #973
Opened 2022-11-08 22:56 UTC by maypink

WIP

2022-11-10 10:57 UTC, gkirgizov requested changes

2022-11-10 10:57 UTC, gkirgizov commented on fedot/api/api_utils/params.py
> +                    depending_on_timeout if depending_on_timeout > 5 else 5
В чем тут идея? Мб пояснить комментом?

2022-11-10 10:57 UTC, gkirgizov commented on fedot/core/optimisers/archive/generation_keeper.py
> +    def stagnation_time_duration(self) -> float:
Пожалуй, стоит добавить этот метод в интерфейс ImpovementWatche

2022-11-10 10:57 UTC, gkirgizov commented on fedot/core/optimisers/archive/generation_keeper.py
> +        self._stagnation_start_time = datetime.datetime.now()
Может, инициализировать таймер не сразу, а только после добавления первого поколения?

2022-11-10 14:47 UTC, maypink commented on fedot/api/api_utils/params.py
> +                    depending_on_timeout if depending_on_timeout > 5 else 5
[done](https://github.com/aimclub/FEDOT/pull/973/commits/1d4d2bfb9e74b810c1b3f1f35d8da7c1b2ec6528#diff-35c9039b23102036436d1536f49036a1cdfa7214c697fbd184e84071246dead8R98)

2022-11-10 14:47 UTC, maypink commented on fedot/core/optimisers/archive/generation_keeper.py
> +    def stagnation_iter_amount(self) -> int:
[ага, хотела к `stagnation_time` amount дописать и перепутала](https://github.com/aimclub/FEDOT/pull/973/commits/1d4d2bfb9e74b810c1b3f1f35d8da7c1b2ec6528#diff-767655307973b076485acf6a71ca3a0511d135ef6054f786fd6fe612d5239610R18)

2022-11-10 14:48 UTC, maypink commented on fedot/core/optimisers/archive/generation_keeper.py
> +    def stagnation_time_duration(self) -> float:
[done](https://github.com/aimclub/FEDOT/pull/973/commits/1d4d2bfb9e74b810c1b3f1f35d8da7c1b2ec6528#diff-767655307973b076485acf6a71ca3a0511d135ef6054f786fd6fe612d5239610R22)

2022-11-10 14:48 UTC, maypink commented on fedot/core/optimisers/archive/generation_keeper.py
> +        self._stagnation_start_time = datetime.datetime.now()
[done](https://github.com/aimclub/FEDOT/pull/973/commits/1d4d2bfb9e74b810c1b3f1f35d8da7c1b2ec6528#diff-e0e12ff0999ee0e0e70460dd64c32a5997512319c5c55c48c1ec8827632265c2R91)

2022-11-11 07:48 UTC, gkirgizov approved these changes

2022-11-11 07:50 UTC, gkirgizov requested changes

2022-11-11 07:50 UTC, gkirgizov commented on fedot/core/optimisers/populational_optimizer.py
> +            self.generations.stagnation_start_time = datetime.datetime.now()
думаю, инициализироватья он может сам при получении первого поколения?
это легко забыть сделать извне, пусть он сам

2022-11-14 12:05 UTC, maypink commented on fedot/core/optimisers/populational_optimizer.py
> +            self.generations.stagnation_start_time = datetime.datetime.now()
[done](https://github.com/aimclub/FEDOT/pull/973/commits/2de77559bce1e34de67f579abff641f0e78be5f3)

2022-11-14 15:53 UTC, maypink commented on fedot/core/optimisers/archive/generation_keeper.py
> +        self._stagnation_start_time = stagnation_start_time
[;.......)](https://github.com/aimclub/FEDOT/pull/973/commits/8671f3b64492a24dbef7831c4478962061727f78)

2022-11-15 07:02 UTC, gkirgizov approved these changes

2022-11-15 11:37 UTC, merged