Refactor visuals for golem [WIP]
aimclub/FEDOT pull request #980
Opened 2022-11-10 14:31 UTC by MorrisNein

Isolates visualizations from `Pipeline`-specific usage, parametrizing such cases.

2022-11-11 07:46 UTC, gkirgizov requested changes

2022-11-11 07:46 UTC, gkirgizov commented on fedot/core/visualisation/pipeline_specific_utils.py
> +
На сейчас пойдет, но это больше похоже на хак :)
Будет полезно для ясности назвать фунцию очевиднее (вроде `set_default_tags_map`, а то он ничего не чекает, чтобы быть чекером).
И поясни комментом, зачем нужно проставлять этот аргумент для пайплайна.

Также я бы избавился от этого алиаса `PipelineArgConstraintWrapper`, а то могут возникнуть вопросы в будущем. Я понимаю, что это для читаемости, но это неочевидно. Лучше сделать функцию, которая будет проставлять этот constraint и явно ее вызывать где-то в очевидном месте.

2022-11-11 12:29 UTC, MorrisNein commented on fedot/core/visualisation/pipeline_specific_utils.py
> +
Я тебя правильно понял?

https://github.com/aimclub/FEDOT/pull/980/commits/61adb09a363f368605be8a270c3f08ff1b49de42

2022-11-14 14:38 UTC, MorrisNein commented on fedot/core/visualisation/pipeline_specific_utils.py
> +
> Только я бы эт функцию `set_default_values_for_pipeline` не на уровне модуля вызывал, желательно. И где-нибудь в файле, связанном с Pipeline.

На данный момент не могу предсказать, какая функция, связанная с пайплайнами, будет вызвана до того, как мы захотим посмотреть историю с пайплайнами

2022-11-14 15:16 UTC, gkirgizov requested changes

2022-11-14 15:16 UTC, gkirgizov commented on fedot/core/visualisation/opt_history/arg_constraint_wrapper.py
> +
Этот файл пойдет в Голем, насколько я понимаю. Тогда сюда нельзя импортировать пайплайновые штуки. Нужно где-то на стороне федота эту настройку производить

2022-11-14 15:16 UTC, gkirgizov commented on fedot/core/visualisation/opt_history/operations_animated_bar.py
> +        # tags_all = [*tags_model, *tags_data]
зачем закомментированный код?

2022-11-14 15:21 UTC, gkirgizov commented
Вообще, текущая проблема выглядит просто как необходимость передавать какие-то аргументы (palette) а init HistoryVizualization и/или OptHistoryVizualizer.
И при необходимости кастомизации во фреймовруах -- вызывать этот класс напрямую, а не через OptHistory.show, ведь он принципиально не может знать чего-либо о тех, кто его использует (Федот)

2022-11-14 16:06 UTC, MorrisNein commented on fedot/core/visualisation/opt_history/operations_animated_bar.py
> +        # tags_all = [*tags_model, *tags_data]
прибрал за собой

2022-11-14 16:06 UTC, MorrisNein commented on fedot/core/visualisation/opt_history/arg_constraint_wrapper.py
> +
Унёс

2022-11-16 16:44 UTC, gkirgizov approved these changes

2022-11-16 16:44 UTC, gkirgizov commented on fedot/core/pipelines/pipeline.py
> +    @copy_doc(GraphDelegate)
@copy_doc(Graph) лучше

2022-11-17 14:58 UTC, merged