Fix getting suitable operations for multi ts
aimclub/FEDOT pull request #981
Opened 2022-11-11 13:29 UTC by YamLyubov

Previously data_type was not used while getting suitable operations during model composition. That was causing problems described [here](https://github.com/aimclub/FEDOT/issues/974)
Changes:
- available_operations are defined during fit strage to take ```input_data.data_type``` into account
- new method ```ApiParams.update_available_operations_by_preset``` were created
- filterring operations by data_type in ```OperationTypesRepository.suitable_operations``` was fixed to not filter out to many operations

2022-11-14 09:57 UTC, ChrisLisbon requested changes
У нас есть два примера с multi_ts ([один](https://github.com/aimclub/FEDOT/blob/master/examples/advanced/time_series_forecasting/multi_ts_arctic_forecasting.py), [второй](https://github.com/aimclub/FEDOT/blob/master/cases/multi_ts_level_forecasting.py)).

Второй использует API и там указан список совместимых операций, я так понимаю цель этого pr'а, чтобы автоматически подхватывать допустимые операции для каждого типа данных, но если я убираю вручную заданный список операций стабильно выпадает такое оповещение 

`Generations:   5%|▌         | 1/20 [00:00<?, ?gen/s]2022-11-14 12:50:11,674 - ApiComposer - Initial pipeline was fitted in 0.5 sec.

2022-11-14 12:50:11,678 - ApiComposer - AutoML configured. Parameters tuning: True Time limit: 2 min Set of candidate models: ['adareg', 'dtreg', 'gbr', 'lasso', 'lgbmreg', 'linear', 'rfr', 'ridge', 'sgdr', 'svr', 'treg', 'lagged', 'sparse_lagged', 'smoothing', 'gaussian_filter', 'diff_filter', 'cut', 'exog_ts']

2022-11-14 12:50:11,679 - ApiComposer - Pipeline composition started.

Metric evaluation error: If using all scalar values, you must pass an index

Metric evaluation error: If using all scalar values, you must pass an index

Metric evaluation error: If using all scalar values, you must pass an index

Metric evaluation error: If using all scalar values, you must pass an index

Generations:   5%|▌         | 1/20 [02:50<?, ?gen/s]` 

Не уверена, что это нормально, но если да может есть идеи из-за какой операции такое происходит?

2022-11-24 12:07 UTC, YamLyubov commented
Ошибки возникали, потому что ```.transform``` для sparse-lagged не работал для multi-ts.  Я его [адаптировала](https://github.com/aimclub/FEDOT/pull/981/files#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412R272), но не уверена, что корретктно

2022-11-24 16:13 UTC, ChrisLisbon commented
> Ошибки возникали, потому что `.transform` для sparse-lagged не работал для multi-ts. Я его [адаптировала](https://github.com/aimclub/FEDOT/pull/981/files#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412R272), но не уверена, что корретктно

А можешь описать в чем конкретно была проблема?
Прогнала дебагером, вроде предыдущую логику такой фикс не нарушает, но все равно можно еще попросить добавить тест к sparse-lagged с multi_ts по аналогии с [вот этим тестом](https://github.com/aimclub/FEDOT/blob/master/test/unit/data_operations/test_data_operations_implementations.py#L530-L562)

2022-11-25 09:04 UTC, YamLyubov commented
> А можешь описать в чем конкретно была проблема? Прогнала дебагером, вроде предыдущую логику такой фикс не нарушает, но все равно можно еще попросить добавить тест к sparse-lagged с multi_ts по аналогии с [вот этим тестом](https://github.com/aimclub/FEDOT/blob/master/test/unit/data_operations/test_data_operations_implementations.py#L530-L562)

Для преобразования данных на этапе fit (```.transform_for_fit```, основная логика которого вынесена в метод [```_apply_transformation_for_fit```](https://github.com/aimclub/FEDOT/blob/master/fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py#L146))  все работало как надо. В случае многомерного ряда, каждый ряд обрабатывался в цикле и для обычного и для sparse lagged.
 
Для на этапе predict ([```_apply_transformation_for_predict```](https://github.com/aimclub/FEDOT/blob/master/fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py#L272)) в случае sparse  метод вне зависимости от размерности пытался обработать ряд одинаково, и падал, если ряд был многомерным.  Чтобы это исправить, я засунула обработку ряда для sparse в цикл, где каждый ряд последовательно обрабатывается)

2022-11-25 13:49 UTC, ChrisLisbon approved these changes

2022-11-25 14:13 UTC, merged