Add strict to tests
aimclub/FEDOT pull request #987
Opened 2022-11-18 10:37 UTC by valer1435

Solve for issue https://github.com/aimclub/FEDOT/issues/970

PS problem with ts connection will be solved in other PR

2022-11-18 15:40 UTC, ChrisLisbon requested changes

2022-11-18 15:40 UTC, ChrisLisbon commented on test/integration/real_applications/test_examples.py
?

2022-11-18 15:40 UTC, ChrisLisbon commented on test/unit/optimizer/test_data_objective_eval.py
> +        objective_eval(pipeline)
assert кажется потерялся

2022-11-18 15:45 UTC, ChrisLisbon commented
У меня есть глобальный вопрос к вот этому тезису:

# data source, exog_ts and custom models moving is useless

Если они используются в связке то да, но если предлагает поменять местами только два датасорса или экзогенных ряда, то кажется запрещать им это делать нет причин. А в текущей реализации, если мы видим их как кандидата на кроссовер или мутацию то сразу запрещаем?

2022-11-19 16:37 UTC, valer1435 commented on fedot/core/pipelines/verification_rules.py
> +                         'stl_arima': ['lagged', 'sparse_lagged', 'exog_ts'],
Потому что он преобразует ряд в матрицу, а эти операции работают с одномерным рядом

2022-11-19 16:39 UTC, valer1435 commented on test/integration/api_params/test_main_api_params.py
> +        test_answer=lambda hist: len(hist.individuals) == 3
Как я понял, теперь лучший (а могут ли быть лучшие) в отдельное поколение. По-крайней мере там такое название у этого последнего поколения. Мб @MorrisNein лучше подскажет

2022-11-19 16:40 UTC, valer1435 commented on test/unit/data/test_data_split.py
>  TEXT_SIMPLE = {'train_features_size': (8,), 'test_features_size': (2,), 'test_idx': (8, 9)}
Нет. Здесь специально увеличил ряд, тк нехватало данных для разбиения

2022-11-19 16:40 UTC, valer1435 commented on test/unit/data/test_data_split.py
Оно уходило в SingleFold

2022-11-19 16:41 UTC, valer1435 commented on test/unit/optimizer/test_data_objective_eval.py
> +        objective_eval(pipeline)
`with pytest.raises(ValueError):` предполагает возникновении тут ошибки, поэтому assert в конце - лишний

2022-11-19 17:16 UTC, MorrisNein commented on test/integration/api_params/test_main_api_params.py
> +        test_answer=lambda hist: len(hist.individuals) == 3
Верно, теперь конечный выбор оптимизатора попадает в последнее поколение с пометкой final_choices

2022-11-20 08:35 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            return count <= 1
Вообще предполагается, что метод вызывается, когда хотя бы один datasource есть. Но для верности учел вариант с 0 (<=1)

2022-11-20 08:37 UTC, valer1435 commented on fedot/utilities/debug.py
> +    # return 'PYTEST_CURRENT_TEST' in os.environ
Это переменная среды, которая появляется, если мы запускаемся через тесты. Пока сделал, чтобы всегда возвращалось True, для отладки

2022-11-20 08:43 UTC, valer1435 commented on fedot/utilities/debug.py
> +    # return 'PYTEST_CURRENT_TEST' in os.environ
> У меня есть глобальный вопрос к вот этому тезису:
> 
> # data source, exog_ts and custom models moving is useless
> Если они используются в связке то да, но если предлагает поменять местами только два датасорса или экзогенных ряда, то кажется запрещать им это делать нет причин. А в текущей реализации, если мы видим их как кандидата на кроссовер или мутацию то сразу запрещаем?

Согласен, выглядит очень громоздко. Вообще, при неудачных мутациях федот не упадет, работая в обычном режиме, но тесты теперь предполагают полное отсутствие таких ошибок.

2022-11-20 08:44 UTC, valer1435 commented
> У меня есть глобальный вопрос к вот этому тезису:
> 
> # data source, exog_ts and custom models moving is useless
> Если они используются в связке то да, но если предлагает поменять местами только два датасорса или экзогенных ряда, то кажется запрещать им это делать нет причин. А в текущей реализации, если мы видим их как кандидата на кроссовер или мутацию то сразу запрещаем?

Согласен, выглядит очень громоздко. Вообще, при неудачных мутациях федот не упадет, работая в обычном режиме, но тесты теперь предполагают полное отсутствие таких ошибок.

2022-11-20 08:47 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/implementation_interfaces.py
> +                print(0)
[да](https://github.com/aimclub/FEDOT/pull/987/commits/61d5b7d09d3ec0754d1d540f6c7cfa15fbdd31dc#diff-53579048c8b22a05e52c5f7ee8b4779da341929a2be7ac10d431e85a071c34deR91)

2022-11-20 08:47 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/operators/crossover.py
> +        if 'exog_ts' == operation_id or 'custom' in operation_id:
[Поменял](https://github.com/aimclub/FEDOT/pull/987/commits/61d5b7d09d3ec0754d1d540f6c7cfa15fbdd31dc#diff-2b5f3f03a740803202f4cd9b4bc5da3b6219f5f062ee654a7bc8812a894b3084R139)

2022-11-20 08:48 UTC, valer1435 commented on fedot/core/pipelines/node.py
> +                print(0)
[да](https://github.com/aimclub/FEDOT/pull/987/commits/61d5b7d09d3ec0754d1d540f6c7cfa15fbdd31dc#diff-f8b54747977d30964212d81746ebb50494c660385b62e2819bb23b83c156f20dR476-R477)

2022-11-20 08:48 UTC, valer1435 commented on fedot/core/pipelines/pipeline_advisor.py
> +            'exog_ts' == operation_id or 'custom' in operation_id):
[Ок](https://github.com/aimclub/FEDOT/pull/987/commits/61d5b7d09d3ec0754d1d540f6c7cfa15fbdd31dc#diff-484b268a2c7fb8480482943eef8471e399d41bf8a87ca48fce47a28cf488f0f6R16)

2022-11-20 08:48 UTC, valer1435 commented on test/integration/real_applications/test_examples.py
[Осталось от отладки](https://github.com/aimclub/FEDOT/pull/987/commits/61d5b7d09d3ec0754d1d540f6c7cfa15fbdd31dc#diff-56d68e52bb127113b66fad1ca9ba32e98deac9c953281d3d2d4d6106d983bf7fR85)

2022-11-20 09:00 UTC, valer1435 commented on examples/simple/time_series_forecasting/api_forecasting.py
> -    run_ts_forecasting_example(dataset='beer', horizon=10, timeout=3, visualization=True)
[Осталось от отладки](https://github.com/aimclub/FEDOT/pull/987/commits/61d5b7d09d3ec0754d1d540f6c7cfa15fbdd31dc#diff-61d9c62b97ba3e153b9fb93d8340113be9aeebf42be709a8b91dc56fa2c04ab9R77)

2022-11-21 08:03 UTC, ChrisLisbon commented on fedot/utilities/debug.py
> +    # return 'PYTEST_CURRENT_TEST' in os.environ
Да я поняла, ты после отладки то приберись)

2022-11-21 08:07 UTC, ChrisLisbon commented on fedot/core/pipelines/verification_rules.py
> +                         'stl_arima': ['lagged', 'sparse_lagged', 'exog_ts'],
То есть в exog_ts уже встроен lagged внутрь?

2022-11-21 08:21 UTC, ChrisLisbon commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            return count <= 1
Думаю стоит оставить строгое равенство раз уж предполагается единственный датасорс, чтобы если вдруг их 0 сразу можно было заметить и разобраться в чем дело

2022-11-22 10:52 UTC, nicl-nno commented on examples/simple/time_series_forecasting/api_forecasting.py
> +    return Pipeline(final)
А он где-то используется?

2022-11-26 12:50 UTC, valer1435 commented on examples/simple/time_series_forecasting/api_forecasting.py
> +    return Pipeline(final)
[нет](https://github.com/aimclub/FEDOT/pull/987/commits/404fa3a629fdd229a4f9f7d6de984a3e5fc04c4a#diff-61d9c62b97ba3e153b9fb93d8340113be9aeebf42be709a8b91dc56fa2c04ab9R23-R24)

2022-11-26 12:50 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +                count += 1
[Сделал ](https://github.com/aimclub/FEDOT/pull/987/commits/404fa3a629fdd229a4f9f7d6de984a3e5fc04c4a#diff-adb53d31d35223b4209ffceadddd7fd47842a77c22c853a98a0df0de267d4325R408)более строгое равенство

2022-11-26 12:51 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            return count <= 1
[Сделал ](https://github.com/aimclub/FEDOT/pull/987/commits/404fa3a629fdd229a4f9f7d6de984a3e5fc04c4a#diff-adb53d31d35223b4209ffceadddd7fd47842a77c22c853a98a0df0de267d4325R408)более строгое равенство

2022-11-29 13:54 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +                count += 1
Сделал ранний [выход ](https://github.com/aimclub/FEDOT/pull/987/commits/5b957ecdeab8314b568481155337f5e2a6bef31f#diff-adb53d31d35223b4209ffceadddd7fd47842a77c22c853a98a0df0de267d4325R407)

2022-11-29 13:56 UTC, valer1435 commented on fedot/core/pipelines/verification_rules.py
> +                         'stl_arima': ['lagged', 'sparse_lagged', 'exog_ts'],
Оно имеет тэг ts_to_table
![image](https://user-images.githubusercontent.com/32017472/204547847-6fdfe164-c453-49b4-b956-07adcbb760ef.png)

2022-11-29 14:07 UTC, valer1435 commented on fedot/utilities/debug.py
> +    # return 'PYTEST_CURRENT_TEST' in os.environ
https://github.com/aimclub/FEDOT/pull/987/commits/86ee9cae9b5edfa8acd521d2183dfd82f599cfee

2022-11-29 14:08 UTC, ChrisLisbon commented on fedot/core/pipelines/verification_rules.py
> +                         'stl_arima': ['lagged', 'sparse_lagged', 'exog_ts'],
Действительно встроенная трансформация. [Вот тут](https://github.com/aimclub/FEDOT/blob/7fa7b4a2df59e8ace8aac20370f6ba5e97023abc/fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py#L415) можно было глянуть

2022-11-29 14:14 UTC, ChrisLisbon approved these changes

2022-11-29 15:55 UTC, nicl-nno approved these changes

2022-11-29 18:49 UTC, merged

2022-12-01 11:26 UTC, gkirgizov reviewed
Так что нужно придумать другое решение, без этих функций в мутации и кроссовере. В ближайшее время, желательно в течение недели

2022-12-01 11:26 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/crossover.py
> +    if is_crossover_correct(graph_first, graph_second):
Данное решение не сработает после PR с Големом, потому что эти файлы (mutation, crossover) уйдут туда. Что-либо знать об операциях в Pipeline они не могут. Так что нужен какой-то другой механизм. Например  через правила верификации.

2022-12-01 11:26 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/crossover.py
> +    if is_crossover_correct(graph_first, graph_second):
Да и в любом случае, даже если бы эти файлы оставались в Федоте, такой подход нарушает уровни изоляции (операторы не должны ничего знать о конкретном содержании нод). В долгосрочном плане это усложняет независимые изменения в модули

2022-12-01 11:26 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +        if check_for_specific_operations(operation_id):
same

2022-12-01 11:47 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/operators/crossover.py
> +    if is_crossover_correct(graph_first, graph_second):
Подумаю, что можно сделать. Впринципе эти вещи не критичные и их можно спокойно проигнорировать. Думаю, что новые правила верификации пайплайнов для временных рядов помогут побороть это