API improvements
aimclub/FEDOT pull request #990
Opened 2022-11-21 17:15 UTC by MorrisNein

Closes #906.

2022-11-25 14:57 UTC, nicl-nno commented on fedot/core/data/data.py
> +POSSIBLE_IDX_KEYWORDS = ['idx', 'index', 'id', 'datatime', 'date', 'unnamed: 0']
time наверное тоже можно добавить.

А нет смысла разбить стоблцы по TS и табличным данным?

2022-11-25 14:58 UTC, nicl-nno commented on fedot/core/data/data.py
> +
Строка лишняя.

2022-11-25 15:00 UTC, nicl-nno commented on fedot/core/data/data.py
> +            index_col = first_column
Тут возможно стоит печатать выбранный стоблец через logger.message, чтобы было прозрачнее.

2022-11-25 15:41 UTC, MorrisNein commented on fedot/core/data/data.py
> +POSSIBLE_IDX_KEYWORDS = ['idx', 'index', 'id', 'datatime', 'date', 'unnamed: 0']
Для временных рядов вообще есть отдельно реализованные `from_csv_time_series`, `from_csv_multi_time_series`. Это для меня вопрос "на подумать", как их теперь правильно унифицировать.

2022-11-25 17:19 UTC, nicl-nno commented on fedot/core/data/data.py
> +POSSIBLE_IDX_KEYWORDS = ['idx', 'index', 'id', 'datatime', 'date', 'unnamed: 0']
Можно тогда из POSSIBLE_IDX_KEYWORDS сделать словарь списков.

2022-12-09 11:36 UTC, MorrisNein commented on fedot/core/data/data.py
> +
Убрал, но почему-то на гитхабе не обновился этот фрагмент

2022-12-09 11:37 UTC, MorrisNein commented on fedot/core/data/data.py
> +            index_col = first_column
Сделал

2022-12-09 11:37 UTC, MorrisNein commented on fedot/core/data/data.py
> +POSSIBLE_IDX_KEYWORDS = ['idx', 'index', 'id', 'datatime', 'date', 'unnamed: 0']
Сделал отдельными константами, чтобы было проще документировать

2022-12-14 12:48 UTC, andreygetmanov requested changes
Очень здорово! Код стал лаконичнее и читабельнее. 
Мне кажется, стоит обновить соответствующие тесты (добавить проверку на правильное определение колонок и пр.). Они лежат в `test_data.py`, например

2022-12-14 12:48 UTC, andreygetmanov commented on fedot/api/main.py
> +                With any value specified, the method does not perform composing. In case of ``"auto"``,
Я бы ещё дополнил, что method does not perform composing **and tuning**

2022-12-14 12:48 UTC, andreygetmanov commented on fedot/core/data/data.py
> +POSSIBLE_TS_IDX_KEYWORDS = ['datatime', 'date', 'time', 'unnamed: 0']
*`datetime`

2022-12-14 12:48 UTC, andreygetmanov commented on fedot/core/data/data.py
> +    columns = list(pd.read_csv(file_path, sep=delimiter, index_col=False, nrows=1))
Здесь чуть читабельнее будет так: `pd.read_csv(file_path, sep=delimiter, index_col=False, nrows=1).columns`

2022-12-14 12:48 UTC, andreygetmanov commented on test/unit/api/test_main_api.py
> +    df = pd.read_csv(fedot_project_root().joinpath('test/data/simple_sea_level.csv'))
А юзеру тоже придётся добавлять `fedot_project_root` к пути при загрузке данных?

2022-12-14 22:25 UTC, nicl-nno approved these changes

2022-12-21 09:51 UTC, MorrisNein commented on test/unit/api/test_main_api.py
> +    df = pd.read_csv(fedot_project_root().joinpath('test/data/simple_sea_level.csv'))
Не-а, подойдёт и относительный путь от current working directory

2022-12-21 09:52 UTC, MorrisNein commented on fedot/api/api_utils/data_definition.py
> +        if ml_task.task_type is TaskTypesEnum.ts_forecasting:
Согласен, переименовал

2022-12-21 09:52 UTC, MorrisNein commented on fedot/api/main.py
> +                With any value specified, the method does not perform composing. In case of ``"auto"``,
Готово

2022-12-21 09:53 UTC, MorrisNein commented on fedot/core/data/data.py
> +    columns = list(pd.read_csv(file_path, sep=delimiter, index_col=False, nrows=1))
Верно, сделал

2023-01-26 15:50 UTC, MorrisNein commented
@andreygetmanov, добавил тесты для определения индекса колонок

https://github.com/aimclub/FEDOT/pull/990/commits/51d09504fca05c2e34cac3c47ce34ae963a815e0

2023-01-30 11:55 UTC, aPovidlo requested changes

2023-01-30 11:55 UTC, aPovidlo commented on fedot/core/data/data.py
> +    def from_csv(cls,
Аргумент `cls` неописан в докстринге метода. В других подобных местах тоже отсутствует описание.

2023-01-30 11:55 UTC, aPovidlo commented on fedot/core/data/multi_modal.py
> +            possible_idx_keywords: lowercase keys to find. If the first data column contains one of the keys,
Не понимаю, а зачем нужен этот парамметр. В каких случаях пользователь будет его заполнять? Как мне кажется, он дублирует функциональность парамметра `index_col`.

2023-01-30 11:55 UTC, aPovidlo commented on fedot/core/data/data.py
> +    def define_index_column(candidate_columns: List[str]) -> Optional[str]:
А зачем потребовалось делать один метод в другом?

2023-01-30 11:55 UTC, aPovidlo commented on fedot/core/data/data.py
> +    columns_to_drop = copy(columns_to_drop) or []
А зачем их копировать?

2023-01-30 11:55 UTC, aPovidlo commented on fedot/api/api_utils/data_definition.py
> +                      PathLike: CsvStrategy,
А может сделать какой-то выбор? Хотелось бы чтобы по пути не только `csv` умело открывать, но и numpy массивы. Мб выбирать стратегию от формата файла в конце пути?

2023-01-30 12:53 UTC, MorrisNein commented on fedot/core/data/data.py
> +    def from_csv(cls,
Это как self, но у методов класса)

2023-01-30 12:56 UTC, aPovidlo commented on fedot/core/data/data.py
> +    def from_csv(cls,
Ой, не заметил `@classmethod`

2023-01-30 12:56 UTC, MorrisNein commented on fedot/core/data/data.py
> +    def define_index_column(candidate_columns: List[str]) -> Optional[str]:
Исключительно для организации кода. Внутренняя функция не используется нигде больше, она максимально "локальная", сокрыта от внешнего контекста

2023-01-30 12:58 UTC, MorrisNein commented on fedot/core/data/data.py
> +    columns_to_drop = copy(columns_to_drop) or []
Чтобы не изменять список, переданный извне входным аргументом

2023-01-30 13:02 UTC, andreygetmanov approved these changes

2023-01-30 13:03 UTC, MorrisNein commented on fedot/api/api_utils/data_definition.py
> +                      PathLike: CsvStrategy,
Не знаком с форматом сохранения  numpy-массивов на диск. Это часто используется?

2023-01-30 13:10 UTC, MorrisNein commented on fedot/core/data/multi_modal.py
> +            possible_idx_keywords: lowercase keys to find. If the first data column contains one of the keys,
Вынести во внешний API было идеей @nicl-nno. Основная задумка в том, что при загрузке нескольких файлов пользователь мог бы один раз указать, какие индексы в них используются.

Сейчас, спустя время, думается, что лучше бы пользователь самостоятельно указывал индекс для каждого конкретного файла, чтобы не перегружать внешний интерфейс. Логика параметра не выглядит явной для внешнего пользователя. @nicl-nno, что думаешь?

2023-01-30 13:13 UTC, aPovidlo commented on fedot/core/data/data.py
> +    columns_to_drop = copy(columns_to_drop) or []
Так в области функции он же не должен менять переменные, которые находятся вне её? Еще копируешь через `copy()`, а она копирует только сылки на объект, находящиеся в оригинале. При этом копируешь в туже самую переменную. `columns_to_drop` в функции ты никак не изменяешь далее в функции.

2023-01-30 13:16 UTC, aPovidlo commented on fedot/api/api_utils/data_definition.py
> +                      PathLike: CsvStrategy,
Формат файла `.npy`. В некоторых экспериментах для одной компании, частично данные хранятся в таких файлах

2023-01-30 13:17 UTC, MorrisNein commented on fedot/core/data/data.py
> +    columns_to_drop = copy(columns_to_drop) or []
В питоне мутабельные ссылки передаются по значению. Т.е. списки вполне изменяются функцией.

За внутренние объекты списка мы тут не беспокоимся, это немутабельные строки или инты.

2023-01-30 13:22 UTC, MorrisNein commented on fedot/core/data/data.py
> +    columns_to_drop = copy(columns_to_drop) or []
Да, действительно, `columns_to_drop` не изменяю, сделал по аналогии с `columns_to_use` из-за строки

`columns_to_use.append(index_col)`

2023-01-30 13:49 UTC, MorrisNein commented on fedot/api/api_utils/data_definition.py
> +                      PathLike: CsvStrategy,
Под такую фичу хорошо бы отдельный PR сделать

2023-01-30 14:00 UTC, aPovidlo approved these changes

2023-01-30 14:35 UTC, nicl-nno commented on fedot/core/data/multi_modal.py
> +            possible_idx_keywords: lowercase keys to find. If the first data column contains one of the keys,
Смысл параметра был в том, что когда мы автоматизированно обрабатываем кучу разнородных файлов - то нам удобно указать набор возможных названий индекса. Наверное, можно это объединить с index_col, но давайте уже в следующих PR про это подумает.

2023-01-30 18:58 UTC, merged