Release fixes for multi-objective optimization
aimclub/FEDOT pull request #996
Opened 2022-12-01 18:23 UTC by gkirgizov

These fixes came from experiments with abstract graph optimization (synthtic task) that seems necessary for the release.

2022-12-01 19:37 UTC, nicl-nno commented
>Apparently, Multi-Objective optimization was broken.

Может это каким-то высокоуровневым тестом заодно проверить? Например, для пары целевых функций, где одна - число узлов в графе со знаком плюс, а другая - со знаком минус. Тогда оптимизатор должен найти полный набор.

2022-12-01 19:37 UTC, nicl-nno commented on fedot/core/optimisers/archive/generation_keeper.py
> +            self.archive = ParetoFront(maxsize=keep_n_best * 10, similar=similar)
Может 10 вынести в какую-то константу?

2022-12-01 19:38 UTC, nicl-nno commented on fedot/core/optimisers/archive/generation_keeper.py
> +                 similar: Callable = _individuals_same):
Мб similarity_criteria или как-то так?

2022-12-02 10:29 UTC, YamLyubov requested changes

2022-12-02 10:29 UTC, YamLyubov commented on fedot/core/optimisers/archive/generation_keeper.py
> +                      ind1.graph.length == ind2.graph.length)
А здесь не получится использовать равенство графов ```ind1.graph == ind2.graph```? По идее же в индивиде лежит некоторая реализация графа, для которой ```__eq__``` определен. Вроде как при текущем условии равными могут считаться разничные индивиды.

2022-12-02 10:29 UTC, YamLyubov commented on fedot/core/optimisers/archive/generation_keeper.py
> +         tells the Pareto front whether or not two individuals are similar, optional.
Тут очепятка: два раза tells

2022-12-02 10:41 UTC, gkirgizov commented on fedot/core/optimisers/archive/generation_keeper.py
> +                      ind1.graph.length == ind2.graph.length)
Тут смысл в том, чтбы вероятно одинаковых индивидовне добавлять. Если у них совпадае фитнесс, то даже и не страшно, что мы выкинем одного из них. На практике это редко должно возникать

2022-12-02 17:46 UTC, gkirgizov commented
> > Apparently, Multi-Objective optimization was broken.
> 
> Может это каким-то высокоуровневым тестом заодно проверить? Например, для пары целевых функций, где одна - число узлов в графе со знаком плюс, а другая - со знаком минус. Тогда оптимизатор должен найти полный набор.

Добавил интеграционный тест в https://github.com/aimclub/FEDOT/pull/996/commits/fcfee615243010528f523faaf14e98a28b8ace71

2022-12-02 23:31 UTC, nicl-nno commented on fedot/core/optimisers/archive/generation_keeper.py
> +                      ind1.graph.length == ind2.graph.length)
Для обобщенного случая все-таки выглядит не слишком надежно - могут быть варианты моделей, где уникальных фитнесов мало, а структуры не различаются по глубине и ширине.

Да и вычисление depth разве не тянет за собой по факту обход (чтобы найти самый длинный путь)?

2022-12-08 21:52 UTC, nicl-nno approved these changes

2022-12-09 10:36 UTC, YamLyubov approved these changes

2022-12-12 17:08 UTC, merged